### ISSUE TITLE
Minor documentation issue: tibble shows unprintable characters in vignette

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#1085]
On my computer, the tibble in the second code block seems to show some ASCII coloring characters:

https://mrgsolve.org/docs/articles/extra/time-after-dose.html#tad-calculated-as-runtime-argument

I think that it's happening here, but I'm not sure why it's happening:

https://github.com/metrumresearchgroup/mrgsolve/blob/2a1ed8afac8cd54983ccf76977cb741f5735b292/vignettes/extra/time-after-dose.Rmd#L34-L46

**Comment by kylebaron** [comment]
Thanks, @billdenney ; looks like some other text / code that I wanted output isn't showing up. I'll look into it; maybe some tweak needed to whatever is supporting pkgdown?

**Comment by kyleam** [comment]
Perhaps the crayon ANSI codes getting through is due to the lack of a `#` prefix: https://github.com/r-lib/pkgdown/issues/1965

If that's the case, the vignettes could be changed to either

 * use a comment prefix for the output
 * disable crayon highlighting `options(crayon.enabled = FALSE)`

**Comment by billdenney** [comment]
That looks like the culprit.

**Comment by kylebaron** [comment]
The special comment character was reverted to the default.
