### ISSUE TITLE
question on implementing zero-order absorption

### ISSUE THREAD

**Issue by shihao94** [metrumresearchgroup/mrgsolve#1089]
Hi, thanks for the nice package! 

I want to implement a zero-order absorption one compartmental linear elimination model, but have an issue. I refer to the code in [issue #317](https://github.com/metrumresearchgroup/mrgsolve/issues/317) and write the the code below. But when I read the model, it shows "Error: reserved symbols in model names: D_CENT". I want to use D_CENT to indicate the duration of absorption. Please let me know if you have any suggestions. Thanks! 
 

`$PLUGIN autodec 
  
$PROB YETI PK simulation, zero-order
  
[PARAM]
TVD_CENT = 8 // absorption duration, h
TVV = 100 // L
TVCL = 1.0 // L/h
WTKG = 70 //kg

[MAIN]
double D_CENT=TVD_CENT*exp(ED1);
double V=TVV*(WTKG/70)*exp(EV);
double CL=TVCL*pow(WTKG/70, 0.75)*exp(ECL);

$OMEGA @labels ED1 EV ECL 
  0.2 0.2 0.2

[CMT] 
CENT
  
[ODE]
dxdt_CENT = - CL*CENT/V;

[TABLE]
capture Cp = CENT*1000/V;`

**Comment by shihao94** [comment]
After I take out "double" within [MAIN], the code works fine

**Comment by kylebaron** [comment]
@shihao94  - that's right.

And since you are using `$PLUGIN autodec` just don't use `double` anywhere and you'll be fine.

Kyle
