### ISSUE TITLE
Recover Model Files After Updating mrgsolve

### ISSUE THREAD

**Issue by joh10068** [metrumresearchgroup/mrgsolve#1093]
Hello,

I stupidly updated many R packages the other day, and to my surprise the mrgsolve package directory was completely overwritten with a fresh install, deleting all my model files!

Anyone know of any way to recover these files?

**Comment by kylebaron** [comment]
Hi @joh10068  - 

Were your model files getting saved into the package directory?

Kyle

**Comment by joh10068** [comment]
Yes that is correct, I was able to locate the majority of the model files (minus the parameter information) which was saved by the compiler. 

Not perfect, but much better than losing everything, and will now save all files in a separate directory!

**Comment by kylebaron** [comment]
Ok; good idea to check those-pre-compile  files; didn't think of that.
