### ISSUE TITLE
Documentation of license through Github?

### ISSUE THREAD

**Issue by Andy00000000000** [metrumresearchgroup/mrgsolve#1181]
Banner of README lists GPL V2. If that is correct, maybe consider adding license to GitHub repo directly?

Insights tab of mrgsolve repo >> Community Standards >> License

**Comment by kylebaron** [comment]
Hi @Andy00000000000  - 

Thanks for the question:

> Banner of README lists GPL V2. If that is correct

The license is stated in the [DESCRIPTION](https://github.com/metrumresearchgroup/mrgsolve/blob/main/DESCRIPTION#L35) file and R provides a copy of that license. 

You can get this information programmatically

```r
> packageDescription("mrgsolve", fields="License")
[1] "GPL (>= 2)"
```

and you can have R show you that license

```r
RShowDoc("GPL-2")
```

So it should be clear from there what the license is. 

I did add a `LICENSE.md` file so GitHub can understand the license; but I think the one that matters is `DESCRIPTION`. 

Kyle
