### ISSUE TITLE
Deprecate table(name) = value; macro in $TABLE

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#120]
It's time to do it.  Depending on the problem, it can be a bad bottleneck (https://github.com/mrgsolve/examples/blob/master/misc_demo/capture.md). 

Any thoughts / preferences on how to do it?  Just let a warning appear for a while?  Or yank it out with instructions on what to do instead?

### Need to replace `table(name) = value;`
- `inst/models`
- User guide
- Rd (already checked and gone)

**Comment by dpastoor** [comment]
Do you have any idea of the # of users actively using mrgsolve? Given the active pace of development and changing API I would say a 2 week - 1 month deprecation warning is reasonable then rip it out.

You could also still add a check for table() and error out with an informative error message for a while longer to help catch anyone migrating from older code.

**Comment by kylebmetrum** [comment]
Not sure how many are actively keeping up with development versus using a version back from last winter.  I wonder about a release notice on NMUSERS; not everyone is on that list, but maybe a lot are.



It would be easy and unobtrusive to leave in the check and error message.  Right now, the warning is:

```r
> mod <- mcode("table_macro", code1)
Compiling table_macro ... done.
Warning message:
In handle_spec_block.specTABLE(X[[i]], ...) :
  The table(name) = value; macro will be deprecated soon.
Save your output to double and pass to $CAPTURE instead:
   $TABLE double name = value;
   $CAPTURE name

```

I hope it's enough text to get the attention and bother so that people actually make the change.

The other thing is that `$TABLE` is so ill-named right now.  We can easily add an alias that makes more sense.  But I don't know what to call it.  The functions are really:

```c 
$BEFORE_SOLVING_ODES
double CL = TVCL*ETCL;

$SOLVING_ODES
dxdt_CENT = -(CL/VC)*CENT;

$AFTER_SOLVING_ODES
double CP = CENT/VC;
```

etc

**Comment by dpastoor** [comment]
my votes would be for either `$POST` (preferred) or maybe `$RES`

**Comment by kylebmetrum** [comment]
I like `$POST`.  I'm not a big fan of `$MAIN` either ... would be nice to find a matching name.

**Comment by kylebmetrum** [comment]
@vjd

I have all of the changes implemented to be done with `table()`.  Changes in `dev` branch will get merged next week.  Users will see a very detailed error message of we find `table(` in `$TABLE`.
