### ISSUE TITLE
ERROR Cannot load model (mod =mread fails)

### ISSUE THREAD

**Issue by jeslo328** [metrumresearchgroup/mrgsolve#1200]
Hi
I'm a beginner to mrgsolve. I have some code that i have been using and running well till now. I am trying to load a model but giving me error as below. I tried re-installing the mrgsolve even. Please help.

library(dplyr)
library(tidyr)
library(mrgsolve)
library(ggplot2)
library(scales)
mod = mread("pkpd-human-tgfb1")

#---------------------------------------#
> mod = mread("pkpd-human-tgfb1")
Building pkpd-human-tgfb1 ... error.

---:: stderr ::---------------------------------------------
Error in system(paste(MAKE, p1(paste("-f", shQuote(makefiles))), "compilers"),  : 
  'make' not found
Calls: <Anonymous> -> .shlib_internal -> system
Execution halted
------------------------------------------------------------
Error: the model build step failed.

**Comment by kylebaron** [comment]
Hi @jeslo328  - I'm thinking that R can't find the tools required to compile your model. 

1. Are you running this on windows?
2. If so, could you install the `pkgbuild` R package and verify this

```r
pkgbuild::hss_rtools(debug = TRUE)
```

**Comment by jeslo328** [comment]
Hi Baron,
Yes i am

**Comment by jeslo328** [comment]
Hi Baron

unable to
> pkgbuild::hss_rtools(debug = TRUE)
Error: 'hss_rtools' is not an exported object from 'namespace:pkgbuild'
> library(pkgbuild)
> pkgbuild::hss_rtools(debug = TRUE)
Error: 'hss_rtools' is not an exported object from 'namespace:pkgbuild'

**Comment by kylebaron** [comment]
@jeslo328  - 

Sorry about that ... can you try

```r
pkgbuild::has_rtools(debug = TRUE)
```

**Comment by jeslo328** [comment]
what is the difference ?

I am already using pkgbuild::has_rtools(debug = TRUE)

**Comment by kylebaron** [comment]
Hi @jeslo328  - 

There was a typo in the command previously; what you posted previously just showed that the correct command wasn't entered correctly

<img width="591" alt="Screenshot 2024-06-08 at 07 52 53" src="https://github.com/metrumresearchgroup/mrgsolve/assets/16908301/5f1488e7-4ae4-4fa2-9646-ec4cd5998449">


Can you please try this command and report back the result?

```r
pkgbuild::has_rtools(debug = TRUE)
```

Thanks,
Kyle

**Comment by kylebaron** [comment]
Hi @jeslo328  - following up on your issue. Any progress to report? If not, we can close this. 

Kyle

**Comment by kylebaron** [comment]
Closing this. Could you please open a new issue if you would still like help with this? Thanks!
