### ISSUE TITLE
[F] Annotated OMEGA and SIGMA

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#121]
Current:
```r
$OMEGA labels=s(ECL,EVC,EKA), block=TRUE

1
0.1 2
0.1 0.1 3
```

becomes

```r
$OMEGA >> annotated=TRUE, block = TRUE

ECL: ETA on Clearance
EVC: ETA on Volume
EKA: ETA on KA
1
0.1 2
0.1 0.1 3
```

or 

```r
$OMEGA >> annotated = TRUE

ECL : 1         : ETA on Clearance
EVC : 0.1 2     : ETA on Volume
EKA : 0.1 0.1 3 : ETA on KA 
```

**Comment by kylebmetrum** [comment]
```r
$PARAM >> annotated=TRUE
CL: 1.2 : Clearance (L/hr)
VC: 22.2 : Volume (L)
KA : 0.89 : Absorption rate constant (1/hr)

$OMEGA >> annotated=TRUE, block=TRUE
ETACL: 0.10 : ETA on CL [ADD]
ETAVC: 0.03 0.06 : ETA on Vd [PROP]
ETAKA: 0.04 0.03 0.05 : ETA on KA

$SIGMA >> annotated=TRUE
ADD : 1  : Additive error
PROP: 2  : Proportional error

> mod <- mcode("anmat", code,warn=FALSE)
Compiling anmat ... done.
> 
> mrgsolve:::details(mod)
  block  name                    descr unit options
1 PARAM    CL                Clearance L/hr       .
2 PARAM    VC                   Volume    L       .
3 PARAM    KA Absorption rate constant 1/hr       .
4 OMEGA ETACL                ETA on CL    .     ADD
5 OMEGA ETAVC                ETA on Vd    .    PROP
6 OMEGA ETAKA                ETA on KA    .       .
7 SIGMA   ADD           Additive error    .       .
8 SIGMA  PROP       Proportional error    .       .
> 
> revar(mod)
$omega
$...
        [,1] [,2] [,3]
ETACL:  0.10 0.03 0.04
ETAVC:  0.03 0.06 0.03
ETAKA:  0.04 0.03 0.05


$sigma
$...
       [,1] [,2]
ADD:      1    0
PROP:     0    2


> param(mod)

 Model parameters (N=3):
 name value . name value
 CL   1.2   | VC   22.2 
 KA   0.89  | .    .    
```

**Comment by kylebmetrum** [comment]
A couple of options for specifying the annotations: linked and unlinked ....

```r
#linked
$OMEGA >> annotated=TRUE, block=TRUE
ECL: 1 : ETA on CL
EVC: 0.001 1: Eta on VC

#unlinked
$OMEGA >> annotated=TRUE, block = TRUE
EKIN:  ETA on KIN
EEC50: ETA on EC50

1 
0.001
3
```

`mrgsolve` will figure out what you are doing and error if there is ambiguity.

``` r
code <- '
$OMEGA >> annotated=TRUE, block=TRUE
ECL: 1 : ETA on CL
EVC: 0.001 1: Eta on VC

$OMEGA >> annotated=TRUE, block = TRUE
EKIN:  ETA on KIN
EEC50: ETA on EC50

1 
0.001
3

'
```

```R
mod <- mcode("mat",code,warn=FALSE)

mrgsolve:::details(mod)

   block  name       descr unit options
 1 OMEGA   ECL   ETA on CL    .       .
 2 OMEGA   EVC   Eta on VC    .       .
 3 OMEGA  EKIN  ETA on KIN    .       .
 4 OMEGA EEC50 ETA on EC50    .       .

```

``` r
revar(mod)

$omega
$...
        [,1]  [,2]
 ECL:  1.000 0.001
 EVC:  0.001 1.000
 
 $...
          [,1]  [,2]
 EKIN:   1.000 0.001
 EEC50:  0.001 3.000
 
 
 $sigma
 No matrices found
```

### PROBLEM
``` r
code <- '
$OMEGA >> annotated=TRUE, block=TRUE
ECL: 1 : ETA on CL
EVC: 0.001 1: Eta on VC
EKIN : ETA on KIN
EKOUT : ETA on KOUT
1 0.001 3
'

print(try(mod <- mcode("mat2",code, warn=FALSE)))

[1] "Error : Ambigious or mixed annotations in $OMEGA\n"
 attr(,"class")
 [1] "try-error"
 attr(,"condition")
 <simpleError: Ambigious or mixed annotations in $OMEGA>
```

I think this unlinked specification may be needed when you have large matrix
and you want to carry a lot of digits along.   Say 8x8 omega matrix; the lines might 
start to get long or it might be more handy to just dump a bunch of numbers
into `$OMEGA` and add the annotations above or below that.

**Comment by dpastoor** [comment]
unlinked seems tricky to manage as is. I see the usefulness, but I would be concerned on trying to keep track of what is where, or if needing to add/remove/rearrange.

Have you considered an intermediate where the key/annotation is above, while still key'ing the omega block. It would remove (some) potential ambiguity at the expense of retaining some verbosity, but it should keep line lengths down at least


```
#unlinked
$OMEGA >> annotated=TRUE, block = TRUE
EKIN:  ETA on KIN
EEC50: ETA on EC50

EKIN: 1 
EEC50: 0.001 3
```

**Comment by kylebmetrum** [comment]
@dpastoor  Thanks for the feedback.

I've been kicking this around for a couple of weeks trying to find an intermediate that is easy to understand and is doable in terms of space.  I definitely prefer `linked` and want to promote that. Only wanted to offer `unlinked` in case it was really needed.  The cases I had in mind required ability to just dump numbers into the block without requiring any formatting.  So I'd tend to keep that one around just for the flexibility (even if it was harder to understand).  

One thing that I struggled with was whether or not to add a block option that declares what format to look for.  I was originally heading for that, but didn't want to (seems hard to explain the option name and what it means).  I ended up detecting the different format  ... it easier to implement than I expected and not a lot of code to maintain.

Re ambiguity:

The `unlinked` format isn't much different than

```r
$OMEGA 
>> block=TRUE
>> labels="ECL,EVC,EKIN,EKOUT"

1
2 3
4 5 6
7 8 9 10
```

which might also be

```r
$OMEGA 
>> block=TRUE,
>> labels="ECL,EVC,EKIN,EKOUT"

1 2  3 4 
5 6 7 8 9 10
```
depending on how you got the values.  The only difference is a different `labels` specification.  I probably should have done this from the start, but didn't have the infrastructure in the package to easily implement it like this.


User still has to get the length of `labels` to match the number of rows.  Obviously, we usually type this in as lower triangle as an aid to make sure we have it right.  If user can
do that, they can just use `linked` format.  If not, the values are going to be without format anyway and we can still allow them to annotate with `unlinked`.  

I want to offer the annotated `$MATRIX` blocks, but part of me thinks the value is much less than other blocks.  `ETA on CL` doesn't say much more than `ETA_CL` or `ECL`.  Specifying the functional form (`additive` or `exponential`) might be the most useful piece of information.  But if we use names like we usually do, they'll naturally link up with one of the parameters and it should be easy to figure out, even programatically.  You could put a tag in the `options` (need to change that name ... it doesn't fit) to join them up, but I'd leave that up to the user.

**Comment by dpastoor** [comment]
yeah it is a tricky question - I think actually a little rstudio add-on could help mitigate some ambiguity regarding proper matrix notation. I've never felt like a 'clean' solution has presented itself in nonmem-land either for annotating mod files. I don't like completely separating comments/annotations and 'data' spatially, as it they are more likely to get out of sync and I've run into too many model problems when annotations were 'lying' because thetas were changed, the blocks were updated, but comments were not.

At the risk of starting a snowball of expanding possibilities, another way would be to have 3 'tiers'

1) wild west - no annotations/labels, user has to manage themselves, but they can just 'dump' numbers in quickly

2) existing linked proposal, using full inline annotations --> *just annotated=T*

3) *NEW * - annotated=T, linked=T
linking would allow for references to annotated values to be combined into a numeric values in the matrix

```
$OMEGA >> annotated=TRUE, block = TRUE
ECL: 1 : ETA on CL
EVC: 1: Eta on VC

ECL
0.001 EVC
```

this would also allow non-annotated values to be added diagonally if the user really wanted (though I don't know if this would break the annotation parser?

```
$OMEGA >> annotated=TRUE, block = TRUE
ECL: 1 : ETA on CL
EVC: 1 : Eta on VC

ECL
0.001 EVC
0.001 0.001 0.1
```

but more importantly, it could be used to control off-diagonals more easily too

```
$OMEGA >> annotated=TRUE, block = TRUE
ECL: 1 : ETA on CL
EVC: 0.1 : Eta on VC


*ECL
0.001 *EVC
```

this could give an end-user the ability to set off-diagonal values more easily by name

```
mod %>% replace_by_name(ECLEVC = 0.03, EKA = 0.) ....
```

if different correlation structures were to be explored.

3b) same, but adding a reference-like syntax in the block if that would be easier for parsing/differentiation

```
$OMEGA >> annotated=TRUE, block = TRUE
ECL: 1 : ETA on CL
EVC: 0.001 1: Eta on VC


ECL
ECLEVC EVC
0.001 0.001 EKA
```

**Comment by kylebmetrum** [comment]
Third tier:  I was imagining something like that (diagonals in an annotated block, off diagonals in a separate chunk) but I sort of thought it was the hardest one to wrap my head around. 

Replace-by-name (and just generally handling off diagonal names): I want to handle that totally internally;  once you set the labels of the diagonals, the off diagonals are determined.  We should be able to compute the the locations and do that replacement or yank those values as you showed but it would be:

```r
mod %>% replace_by_name(ECL-EVC = 0.03, EKA = 0.2) ...
```
or something that won't make R complain.

It seems like the most used will be wild-west + labels or the linked/annotated setup.  Labels are important and should always be used since they make sure user doesn't go out of bounds on the `ETA` vector and maybe a little faster since they use `ETA[n]` rather than `ETA.at(n)` (I wish this totally sped thing up, but just small improvement).  I'm going to be revising examples to always use labels and want to encourage it.

**Comment by dpastoor** [comment]
cd4e9e6 is awesome! referencing here with the commit details

```
New proposal:

>> marks likes with name1=value1, name2=value2 as it is now
@ marks lines with boolean indicators
So these are equivalent:

$PARAM 
>> annot = TRUE
$PARAM 
@annot
which is the same as

$PARAM @annot
And put them on separate lines if you wish

$OMEGA
@annot
@block
@cor
Or not

$OMEGA
@ annot cor block
```
