### ISSUE TITLE
Old/New System Issue - can't find 'make'

### ISSUE THREAD

**Issue by AndrewHeitmanSagerRx** [metrumresearchgroup/mrgsolve#1226]
Running R v4.4 - I get the following error when I try to compile the code for simulation:

 ---:: stderr ::---------------------------------------------
Error in system(paste(MAKE, p1(paste("-f", shQuote(makefiles))), "compilers"),  : 
  'make' not found
Calls: <Anonymous> -> .shlib_internal -> system
Execution halted
------------------------------------------------------------
Error: the model build step failed.

I have tried previous suggestions and getting the PATH redone, and it doesn't seem to work with the RTools fix.

**Comment by AndrewHeitmanSagerRx** [comment]
Hi Kyle,

I installed pkgbuild and ran the code. I get the output:

[1] TRUE

-A


________________________________

**Comment by kylebaron** [comment]
Thanks; I wonder if that's just telling us that the tools are there (we know that already). But I think the problem is really path-related. 

If you want to start back and forth to try to figure this out, I'd be happy to do it with you. Stuff like 

```r
Sys.getenv("PATH")
Sys.which("make")
```

That sort of thing; if we surface enough info might be able to figure it out.

**Comment by AndrewHeitmanSagerRx** [comment]
That would be great.

Sys.getenv("PATH") looks like its pointed at my rtools44 directory.

But Im not sure this is right:

> Sys.which("make")
make
  ""


***@***.***



Andrew Heitman, Ph.D.

Associate Director, Clinical Pharmacology

o: (617) 500-7212

215 First Street, Suite 220, Cambridge, MA 02142

(He/Him)



www.sagerx.com<http://www.sagerx.com/>







________________________________

**Comment by AndrewHeitmanSagerRx** [comment]
"c:/rtools44/x86_64-w64-mingw32.static.posix/bin;c:/rtools44/usr/bin;..."

Is this enough?


***@***.***



Andrew Heitman, Ph.D.

Associate Director, Clinical Pharmacology

o: (617) 500-7212

215 First Street, Suite 220, Cambridge, MA 02142

(He/Him)



www.sagerx.com<http://www.sagerx.com/>







________________________________

**Comment by kylebaron** [comment]
Yeah; as far as I can tell, the tools should be in `c:/rtools44/usr/bin`; if `make.exe` is in that folder (along with gcc etc) I think that should be correct. 

This is from an older Rtools version, but it seems like the PATH information should still be valid. 
https://cloud.r-project.org/bin/windows/Rtools/rtools40.html

And `Sys.which("make")` should be an mrgsolve-independent way of checking R and the toolchain. 

<img width="665" alt="Screenshot 2024-08-29 at 14 29 50" src="https://github.com/user-attachments/assets/2dfe56c9-182a-4715-a29f-62ff0488c167">


I think if `make.exe` is under `rtools44/usr/bin` then you have to start looking into why R isn't finding that.

**Comment by AndrewHeitmanSagerRx** [comment]
Hey Kyle,

The RTools appears to  be in the correct directory - I created a textfile (.Renviron) per the screenshot. MRGsolve still isnt finding the "make" comman.










________________________________

**Comment by kylebaron** [comment]
Thanks for following up, @AndrewHeitmanSagerRx. Glad you got it working. 

For future reference: mrgsolve doesn't need to find `make` or anything else in that toolchain. mrgsolve calls `R CMD SHLIB` and _R_ needs to find that stuff. So what we need to do in this case is connect R and the toolchain. None of this runs through mrgsolve. None.
