### ISSUE TITLE
Problem creating shiny app with mrgsolve

### ISSUE THREAD

**Issue by MarioGS** [metrumresearchgroup/mrgsolve#123]
Hi,

I am creating a shiny app that runs perfectly ok locally. However, when I try to upload the app in shinyapp.io using deployApp() I get the following error:
Error: Unable to retrieve package records for the following packages:
- "mrgsolve"

If I run packrat::init() I get:
Initializing packrat project in directory:
- "C:/Projects/Mario/R/Shiny/DrugX_1C_BOLUS_MRGSOLVE"
Error: Unable to retrieve package records for the following packages:
- "mrgsolve"
In addition: Warning message:
In FUN(X[[i]], ...) :
  Failed to infer source for package 'mrgsolve'; using latest available version on CRAN instead

I am able to deply the same app using pkmodel() from mlxR package and sim_ode() from PKPDsim package. Thus, I am wondering... 

1) is it possible to use mrgsolve for shiny apps?

2) any ideas about how to solve this problem? 

Thanks in advance,

Mario

**Comment by kylebmetrum** [comment]
Hi @MarioGS - 

Yes, you can use `mrgsolve` with shiny apps, both locally and on a Shiny server.

This my first time with `deployApp()` ... but I was running into the same `Error: Unable to retrieve package records for the following packages:` error that you were seeing.   

Looking at the [`shinyapps.io` documentation](http://shiny.rstudio.com/articles/shinyapps.html):

> Important note on GitHub packages

> Only packages installed from GitHub with devtools::install_github in version 1.4 (or later) of devtools are supported. Packages installed with an earlier version of devtools must be reinstalled before you can deploy your application. If you get an error such as “PackageSourceError” when you attempt to deploy, check that you have installed any package from Github with devtools 1.4 or later.
 

When I installed `mrgsolve` with `install_github` (on my laptop), I was able to deploy the app and it looks it is working [https://mrgsolve.shinyapps.io/house/](https://mrgsolve.shinyapps.io/house/).  I had to also install `assertthat` with `install_github` to get around that error message as well.  And to use the `plot` method for `mrgsims` objects, I had to explicitly load `lattice` in the app, apparently to get that deployed. 

It seems like `rsconnect` tries to figure out what packages you need to run the app and bundles that up when you deploy.  For some reason, it is able to do this when you `install_github`.  I have no idea why this works but I'd say give it a try.

Can you give that a try and let me know if it works?

Kyle

**Comment by kylebmetrum** [comment]
`ui.R`

```r
library(shiny)
library(rsconnect)
shinyUI(plotOutput("plot"))
```

`server.R`

```r
library(mrgsolve)
library(lattice)

mod <- mread("pk1cmt", modlib())

shinyServer(function(input,output,session) {
  output$plot <- renderPlot({
    mod %>% ev(amt=100) %>% mrgsim %>% plot
  })
})
```

**Comment by MarioGS** [comment]
Hi Kyle,
Thank you so much! That solved the problem :)
Best,

Mario González SalesPharm.D, M.Sc.Stats, Ph.D in PharmacometricsMobile: (+34) 722279993Email: mario_g_s@hotmail.esCallSend SMSAdd to SkypeYou'll need Skype CreditFree via SkypeCallSend SMSCall from mobileAdd to SkypeYou'll need Skype CreditFree via SkypeCallSend SMSCall from mobileAdd to SkypeYou'll need Skype CreditFree via Skype

Date: Mon, 12 Sep 2016 22:02:49 -0700

**Comment by kylebmetrum** [comment]
@MarioGS Np.  Thanks for the report and for getting me into shinyapps.io.

**Comment by dpastoor** [comment]
If I remember correctly (this was over a year ago when I was digging) part of the issue comes from how rsconnect determines the _likely_ dependencies needed to be bundled into a project for deployment on shinyapps.io, and they made the decision that including the packages only under 'suggests' massively expanded there dependency tree in a lot of situations, so by default they ignore those packages. Hence, by explicitly requiring lattice you are signalling you need the package, and it is pulled into the project bundle, resolving the error.

The underlying mechanism I'm almost positive is packrat for bundling, which recursively searches for library() invocations, as well as the Imports for all required packages to determine what to bundle, so if you run into issues, check how your usage might clash with packrat and that should shed the needed light to get fixes.
