### ISSUE TITLE
Cumulative AUC

### ISSUE THREAD

**Issue by klam16** [metrumresearchgroup/mrgsolve#1255]
Hello,

This might be a simple question, but I'm not sure if my mrgsolve model will give the correct output. I would like to calculate the AUC in the central compartment without assuming steady-state where at any timepoint ti, AUC will be cumulative AUC from time 0 to ti. How would this be done?

```
$PARAM
C0 = 0

$CMT 
GUT CENT PERIPH AUC

$NMEXT
path = ...
root = 'cppfile'

$MAIN
F_CENT = F;
CENT_0 = C0 * S2;  
double CL = exp(THETA1 + ETA(1));
double V2 = exp(THETA2);
double V3 = exp(THETA3);
double Q = exp(THETA4);
double KA = exp(THETA5);
double F = 1/(1 + exp(-THETA6));
double k10 = CL/V2;
double k12 = Q/V2;
double k21 = Q/V3;

double S2 = V2/1000; 

$ODE
dxdt_GUT = -KA*GUT;
dxdt_CENT = KA*GUT - k12*CENT - k10*CENT + k21*PERIPH;
dxdt_PERIPH = k12*CENT - k21*PERIPH;
dxdt_AUC = CENT/S2;

if(SS_ADVANCE) dxdt_AUC = 0;

$TABLE
double IPRED = CENT/S2;
double Y = IPRED * (1 + EPS(1)) + EPS(2);

while(Y < 0) {
  simeps();
  Y = IPRED*(1 + EPS(1)) + EPS(2);
}

$CAPTURE
IPRED Y CL V2 V3 Q 
``` 

Thank you,
Kevin

**Comment by kylebaron** [comment]
Hi @klam16  - 

The AUC part looks right to me.  Is the simulation giving you a reasonable result?

Kyle

**Comment by klam16** [comment]
Hi Kyle,

The simulated AUC seems to be reasonable. Thanks!

Kevin

**Comment by kylebaron** [comment]
Great! Let me know if you have other questions, @klam16 .
