### ISSUE TITLE
[F] option in $SET to write NONMEM-like compartment definitions

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#126]
Barrier when translating nonmem models:
`mrgsolve` uses `GUT`, `CENT`, `dxdt_CENT` etc.  `nonmem` uses `A(1)`, `A(2)`, `DADT(1)` etc.

First thought was to allow users to write `A(n)` as well to help with translation, but  danger in case the user goes out of bounds (using the pre-processor directives protects this).  

Maybe `A_2` or `DADT_2` so that compile error will happen (variable not defined) in case someone writes `A_10000`.

``` r
$SET nm_defs=TRUE
```

**Comment by kylebmetrum** [comment]
Better to add as a block option.

**Comment by kylebaron** [comment]
See https://github.com/metrumresearchgroup/mrgsolve/issues/904
