### ISSUE TITLE
change annotation syntax to be more 'macro-like'

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/mrgsolve#127]
in typing out #121 discussions, I realized, given we (potentially) have a number of settings that are either TRUE/FALSE, those boolean values could be handled in a more macro/decorator-like syntax

instead of

```
$OMEGA 
annotated = TRUE 
...
```

any booleans could be proceeded by `@`

```
$OMEGA 
@annotated 
...
```

```
$OMEGA
@annotated 
@block
...
```

I would presume it would also actually be easier to parse too, since you don't have to handle full expressions just look for what `@` macros were present

**Comment by kylebmetrum** [comment]
This was in cd4e9e6.  In the commit, `@` macros are only found in designated option lines (starting with `>>`).  We could look elsewhere in the block, but I'd like to migrate away from bare options in a block.  It's not that we couldn't parse it out ... just seems like more work / code to have to check anywhere in a block for the options.

```r
$OMEGA >> @annotated, @block
ECL: 1 : ETA on CL
EVC: 0.001 1: Eta on VC

$OMEGA >> @annotated, @block
EKIN:  ETA on KIN
EEC50: ETA on EC50

1  0.001 3
```

**Comment by dpastoor** [comment]
ah - i was thinking just make them more explicit in there location to reduce headaches - namely they just be right below the $<block> statement

**Comment by kylebmetrum** [comment]
Any objection to insisting on the `>>` tag for options?  

We're already picking that out and I feel like we can make this even more robust if we can first look for `>>` and then dice that up.  

Right now you can still do this
```r
$OMEGA
block = TRUE
1 2 3 4
```

This goes back a long time ago.  Basically we grep out `=` and take the whole line as comma-separated options.  We can't do that for `$PARAM` or other blocks where the data is `name=value`.  So I came up with `>>`.   I didn't really like `>>` at first but it's grown on me and seems more natural now when you put options right after the block name.  I'd like to get to the point where we phase out any option that is not preceded by `>>`.  I feel like we'll be able to do more with those options.  In the end, it will be less to look for.

**Comment by dpastoor** [comment]
I don't have a problem with it, the 'confusing' thing is `>>` a per line thing

```
$OMEGA
>> @annotate
>> @block
```

or just at the beginning of annotations. Also, does it need to be on the same line as `$statement` or can it be separated?


For example, my personal styling is 1 per line, this makes it easy to diff things by line

```
$OMEGA
>> @annotate
>> @block
```

to 

```
$OMEGA
>> @annotate
>> @inline 
>> @block
```

will produce a cleaner diff, to keep track of what is changing, than

```
$OMEGA >> @annotate,@block
```

to 

```
$OMEGA >> @annotate, @inline, @block
```

I don't have a problem adding `>>` anywhere, just seems like the `@` indication is providing the same notation as `>>` so at that point I would just use `>>` instead of `@` if you are set on `>>`

so 

```
$OMEGA
>> block 
...
```

**Comment by kylebmetrum** [comment]
IC ....  We need to have `>> @annotated`  because of way the options are turned into a list.  `@block` expands to `block=TRUE` before creating the list.  

The hangup is that the list is created by: 
https://github.com/metrumresearchgroup/mrgsolve/blob/3e201421fa506ce6fc383443a36e0d7063146b1b/rdev/R/utils.R#L688


Except for the `@` substitution, I just leave the string alone and wrap it in `list()` and evaluate, letting the parser figure things out.  That's how we get evaluated parameter values and `labels=c("ECL", "EVC")` and stuff like that.  The way it is now, I can't just split on `,` because it won't be right.  Maybe the parser needs to get more robust but so far it has held together.

**Comment by dpastoor** [comment]
yeah I would say on the priority list of things to change this is low - I should probably pick your brain at ACoP or something to better understand the internals of the flow from Rcode down the line so I have a better mental model on how things are parsed and passed around.

Anyway - even with `>>` its a great step forward to keeping sane with documenting parameter info on these models

**Comment by kylebmetrum** [comment]
Ok ... thanks again for feedback and suggestions.  I'll keep thinking about R based solutions and as well as a more full on parser.  Agree about priority but `block=TRUE` seems a little clunky.  

Maybe:
```r
x <- "+annotated, a=2, -block"
```

Gets expanded to `list(annotated=TRUE,a=2, block=FALSE)`.  But note well it needs to be turned into the list because these just get passed as arguments to a function via `do.call`.  One nice side effect is that you can do partial matching for all of the options.

Yeah ... let's sit down at ACoP and look.

**Comment by kylebmetrum** [comment]
This commit:  cd4e9e6d208eae4252bc279f4be5369c46603fee

New proposal: 
- `>>` marks likes with `name1=value1, name2=value2` as it is now
- `@` marks lines with boolean  indicators

So these are equivalent:

```r
$PARAM 
>> annot = TRUE
```

```r
$PARAM 
@annot
```

which is the same as

```r
$PARAM @annot
```

And put them on separate lines if you wish
```r
$OMEGA
@annot
@block
@cor
```

Or not

```r
$OMEGA
@ annot cor block
```

**Comment by kylebmetrum** [comment]
``` r
code <- '
$OMEGA  @block cor
1 
0.67 2

'
```

``` r
omat(mcode("hey2", code,warn=FALSE))
```

    . Compiling hey2 ...

    . done.

    . $...
    .          [,1]      [,2]
    . 1:  1.0000000 0.9475231
    . 2:  0.9475231 2.0000000

**Comment by kylebmetrum** [comment]
``` r
code <- '
$OMEGA  
@block cor
>> labels= "ETACL ETAVC"
>> name  = "OMEG"
1 
0.67 2

'
```

``` r
omat(mcode("hey2", code,warn=FALSE))
```

    . Compiling hey2 ...

    . done.

    . $OMEG
    .              [,1]      [,2]
    . ETACL:  1.0000000 0.9475231
    . ETAVC:  0.9475231 2.0000000

**Comment by kylebmetrum** [comment]
It would be nice to use that `@` notation to set `name=value` too, like:

```r
$BLOCKNAME
@bool

@name1 this is the value associated with name1

@name2 the value associated with name2
```
These would have to be one-per-line I a la roxygen syntax.



but can't do that with last commit b/c multiple bools on same line look like
```r
$BLOCKNAME
@annot block cor
```

I was wondering about:
```r
$BLOCKNAME
@annot-block-cor
```

or

```r
$OMEGA
@block

@@ labels "ECL EVC EKA"

```

Is any of this easier to communicate to users or for users to learn than hanging on to:


```r
$OMEGA
@block

>> labels =  "ECL EVC EKA"

```

???

**Comment by kylebmetrum** [comment]
Sorry ... this https://github.com/metrumresearchgroup/mrgsolve/commit/36472b2d3294012666b04a0c78b1255459eac907 was commit with latest `@` implementation.   I forgot to tag the commit message and not going to amend.

**Comment by kylebmetrum** [comment]
This is it:

- `labels` is @  name value
- `bool` is just boolean
- All of this can be on the same line or multiple lines
- But the leading `@` on a line marks that entire line as block options

So if this all works, let's axe the `>>` indicator and use @ sign for all block options?

```r
code <- '

@labels ECL EVC EKA @bool

@foo 

@kyle 2 @zip 55378 @bar

@Character The quick brown fox

'
```

``` r
mrgsolve:::parse_ats(strsplit(code, "\n")[[1]])
```

    . $labels
    . [1] "ECL EVC EKA"
    . 
    . $kyle
    . [1] 2
    . 
    . $zip
    . [1] 55378
    . 
    . $Character
    . [1] "The quick brown fox"
    . 
    . $bool
    . [1] TRUE
    . 
    . $foo
    . [1] TRUE
    . 
    . $bar
    . [1] TRUE

**Comment by kylebmetrum** [comment]
``` r
code <- '
$PARAM @annota
CL : 1 : clearance
VC : 2 : volume

$OMEGA 
@block @cor
@labels ECL EVC EKA

1
0.3 0.3
0.1 0.7 0.2

'

mod <- mcode("test", code, warn=FALSE)
```

    ## Compiling test ...

    ## done.

``` r
omat(mod)
```

    . $...
    .             [,1]      [,2]       [,3]
    . ECL:  1.00000000 0.1643168 0.04472136
    . EVC:  0.16431677 0.3000000 0.17146428
    . EKA:  0.04472136 0.1714643 0.20000000

``` r
mrgsolve:::details(mod)
```

    .   block name     descr unit options
    . 1 PARAM   CL clearance    .       .
    . 2 PARAM   VC    volume    .       .
