### ISSUE TITLE
Descriptive aliases for F(n), D(n), R(n) and ALAG(n)

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#13]
For example
````r
$CMT CENT

$MAIN
F_CENT = 0.67;
ALAG_CENT = 0.56;
````

**Comment by vjd** [comment]
This would be really helpful

**Comment by kylebmetrum** [comment]
I was talking to Bill Denny about it.  It would be more than just a convenience ... could really help prevent mistakes.


We can implement this:
````r
$CMT CENT
$MAIN
F_CENT = 0.67;
````
Easily.  But there would have to be one alias for every compartment x 4 (for D,F,R,and ALAG).  Maybe it's not that big of a deal ... but it could start to be big number with the large models.

We can already do this
````r
$CMT CENT
$MAIN
F(N_CENT) = 0.67;
````

So ... `N_CENT` is the number of the `CENT` compartment; that's already in there ... you just have to ask for it.  Is isn't quite as clean as the first approach, but seems to be a little more sensible implementation (you could totally use `N_CENT` for a lot of things).

Either way, I think those leading underscores are getting dropped in the next version ... or at least we will put in extra definitions so that you can use `F(1)` or `_F(1)`; hopefully the `_F(1)` will go away with time.

**Comment by kylebmetrum** [comment]
I forgot to ask the question:
is `F(N_CENT)` so clunky that we should be brute forcing it with `F_GUT`, `F_CENT`, `F_PERIPH`, `F_RESPONSE`, etc... ?
