### ISSUE TITLE
[F] mrgsolve:::render development

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#132]
Taking discussion here based on https://github.com/metrumresearchgroup/mrgsolve/pull/131

`mrgsolve:::render` should be generic and have methods for `mrgmod` (model object already in hand and for `character`.  In the character version, the character is the model name and another argument for `project` directory.  The model will get read and parsed but not compiled (not needed) and then passed back to `mrgsolve:::render` this time going to the `mrgmod` method.

**Comment by dpastoor** [comment]
In regards to the render function, I think you could get away with just using a [parameterized report](http://rmarkdown.rstudio.com/developer_parameterized_reports.html) with a templated Rmd embedded in the package that gets called, with the model object and whatever else needed passed in.

Let me know if you'd need me to make a little example to work off of (I think i understand what you're going for but not 100% sure)

**Comment by kylebmetrum** [comment]
This is cool .... so we could totally simplify this by just passing in the model name and the project directory and then have then run the .Rmd read/parse the model and spit out the output.  Then pass everything in `...` to `rmarkdown::render` as you suggested.

**Comment by dpastoor** [comment]
yep yep

**Comment by kylebmetrum** [comment]
Methods with signature `character` and `mrgmod`.  I think we have enough control over this now to merge the parameter/initial values onto the details data frame to make a single integrated summary table.  


```r
> mrgsolve:::render("viral2", modlib(), output_format="md_document")


processing file: viral2.Rmd
  |......                                                           |   9%
  ordinary text without R code

  |............                                                     |  18%
label: unnamed-chunk-1 (with options) 
List of 1
 $ echo: logi FALSE

  |..................                                               |  27%
   inline R code fragments

  |.................................................................| 100%
  ordinary text without R code


  |........................                                         |  36%
label: unnamed-chunk-2
  |..............................                                   |  45%
  ordinary text without R code

  |...................................                              |  55%
label: unnamed-chunk-3
  |.........................................                        |  64%
  ordinary text without R code

  |...............................................                  |  73%
label: unnamed-chunk-4
  |.....................................................            |  82%
  ordinary text without R code

  |...........................................................      |  91%
label: unnamed-chunk-5
  |.................................................................| 100%
   inline R code fragments


output file: viral2.knit.md

/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS viral2.utf8.md --to markdown_strict --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output viral2.md --standalone 

Output created: viral2.md
```


```r
> 
> #+
> mod <- mrgsolve:::house()
> mrgsolve:::render(mod, output_format="md_document")


processing file: housemodel.Rmd
  |......                                                           |   9%
  ordinary text without R code

  |............                                                     |  18%
label: unnamed-chunk-1 (with options) 
List of 1
 $ echo: logi FALSE

  |..................                                               |  27%
   inline R code fragments

  |.................................................................| 100%
  ordinary text without R code


  |........................                                         |  36%
label: unnamed-chunk-2
  |..............................                                   |  45%
  ordinary text without R code

  |...................................                              |  55%
label: unnamed-chunk-3
  |.........................................                        |  64%
  ordinary text without R code

  |...............................................                  |  73%
label: unnamed-chunk-4
  |.....................................................            |  82%
  ordinary text without R code

  |...........................................................      |  91%
label: unnamed-chunk-5
  |.................................................................| 100%
   inline R code fragments


output file: housemodel.knit.md

/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS housemodel.utf8.md --to markdown_strict --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output housemodel.md --standalone 

Output created: housemodel.md
> cat(readLines("housemodel.md"),sep="\n")
```

`mrgsolve` housemodel
=====================

This model is compiled with `mrgsolve`.

-   Author: Metrum Research Group, LLC
-   Description: Generic indirect response PK/PD model
-   Covariates: Weight, female sex
-   Random effects: CL, VC, KA, KOUT
-   Error model: exponential

Model details
=============

       block  name                    descr     unit options
       PARAM    CL                Clearance     L/hr       .
       PARAM    VC   Volume of distribution        L       .
       PARAM    KA Absorption rate constant     1/hr       .
       PARAM    F1 Bioavailability fraction        .       .
       PARAM    WT                   Weight       kg       .
       PARAM   SEX     Covariate female sex        .       .
       PARAM  WTCL        Exponent WT on CL        .       .
       PARAM  WTVC        Exponent WT on VC        .       .
       PARAM SEXCL    Prop cov effect on CL        .       .
       PARAM SEXVC    Prop cov effect on VC        .       .
       PARAM   KIN  Resp prod rate constant     1/hr       .
       PARAM  KOUT  Resp elim rate constant     1/hr       .
       PARAM  IC50 Conc giving 50% max resp    ng/ml       .
         CMT   GUT       Dosing compartment       mg       .
         CMT  CENT      Central compartment       mg       .
         CMT  RESP                 Response unitless       .
     CAPTURE    DV       Dependent variable    ng/ml       .
     CAPTURE    CP     Plasma concentration    ng/ml       .

Parameter values
----------------


     Model parameters (N=13):
     name value . name  value
     CL   1     | SEXCL 0.7  
     F1   1     | SEXVC 0.85 
     IC50 10    | VC    20   
     KA   1.2   | WT    70   
     KIN  100   | WTCL  0.75 
     KOUT 2     | WTVC  1    
     SEX  0     | .     .    

Compartments and initial values
-------------------------------


     Model initial conditions (N=3):
     name       value . name       value
     CENT (2)   0     | RESP (3)   0    
     GUT (1)    0     | . ...      .    

Model code
==========


    Model file: housemodel.cpp 

    $SET
    end=120, delta=0.25

    $GLOBAL
    #define CP (CENT/VCi)
    #define INH (CP/(IC50+CP))
    typedef double localdouble;

    $MAIN
    F_GUT = F1;
    double CLi   = exp(log(CL)   + WTCL*log(WT/70) + log(SEXCL)*SEX + ECL);
    double VCi   = exp(log(VC)   + WTVC*log(WT/70) + log(SEXVC)*SEX + EVC);
    double KAi   = exp(log(KA)   + EKA);
    double KOUTi = exp(log(KOUT) + EKOUT);
    RESP_0 = KIN/KOUTi;

    $ODE
    dxdt_GUT = -KAi*GUT;
    dxdt_CENT = KAi*GUT - (CLi/VCi)*CENT;
    dxdt_RESP = KIN*(1-INH) - KOUTi*RESP;

    $TABLE
    double DV = CP*exp(EXPO);

`mrgsolve`
==========

-   Date: Thu Oct 6 00:04:09 2016
-   Version: 0.7.6.9018
