### ISSUE TITLE
Error Installing modmrg

### ISSUE THREAD

**Issue by krinaj** [metrumresearchgroup/mrgsolve#138]
Hello,

I was able to install mrgsolve; however, when I try to install modmrg, I am having error message. 

I tried with direct command and got below mentioned error message.

![image](https://cloud.githubusercontent.com/assets/21271517/19253452/023a8f8a-8f00-11e6-986e-1b09c3cb4ce2.png)

I tried downloading package from dpastoor/modmrg and then installing, and got below mentioned error message.

![image](https://cloud.githubusercontent.com/assets/21271517/19253477/2ef440ac-8f00-11e6-9f00-b8728504041a.png)

Is it no longer available? 

Thanks,
Krina

**Comment by dpastoor** [comment]
Hi Krina,

You can get to the same behavior now my `mread()`ing the file. I think the documentation that you referred to hasn't been updated against the latest versions. Thanks for the catch!

Eg.

```r
library(mrgsolve)
mrgsolve_example("pkExample")
model <- mread("pkExample.cpp")
```

**Comment by krinaj** [comment]
thanks, devin.

**Comment by kylebmetrum** [comment]
@krinaj @dpastoor I think that `mrgsolve_example` is going to be deprecated soon too (I thought it already was).  

For pre-coded examples, 

```r
mod <- mread("pk1cmt", modlib())
```

`modlib()` returns the location of a directory under the `mrgsolve` install location and the result is passed into `mread` as `project`.

You can get a list of the models that are there with:

```r
?modlib
```

All of the `modmrg` models are there now and eventually all of the other examples will be there.

I will demo this tomorrow at 12 EDT:
https://github.com/isop-phmx/studyGroup/issues/26

**Comment by krinaj** [comment]
thanks, Kyle.

**Comment by kylebmetrum** [comment]
Np.
