### ISSUE TITLE
Is it possible to perform the equivalent of MAX=0 in NONMEM using mrgsolve?

### ISSUE THREAD

**Issue by quagmirerules** [metrumresearchgroup/mrgsolve#140]
I have seen that it is possible to perform some Bayes estimation with mrgsolve. Is it also possible to perform the equivalent of MAXEVAL=0 in NONMEM? If so, how can I do it?

Thanks in advance,

Jason

**Comment by dpastoor** [comment]
Jason,

Are you trying to get map bayes estimates? Is this what you're after? https://github.com/metrumresearchgroup/mrgsolve/wiki/map_bayes

**Comment by quagmirerules** [comment]
Hi Devin,

It looks like it is what I am looking for but not sure about the
terminology. In NONMEM I can do MAP with foe example: $EST METHOD=IMPMAP
INTERACTION. This is not what I am looking for. What I want is simply $EST
METHOD=0 MAXEVAL=0. Basically, I want to use a PopPK model with IIV and RV
variability to estimate the individual parameters of a particular subject
based uniquely in the observed concentrations of the subject. Do you call
that map bayes estimates?

In summary:

1) I have a PopPK model.

2) I have plasma concentration from only 1 subject.

3) I want to estimate the individual parameters of this subject based on
the observed plasma concentration 2) and the PopPK model 1).

I have also checked there is a maximum likelihood estimation tutorial:
https://github.com/metrumresearchgroup/mrgsolve/wiki/simplefit However, it
says: "Don't use R + mrgsolve to fit PK models like this when you have an
alternative (like NONMEM)." Should I use NONMEM over R+mrgsolve for my
purpose? If so, what is the reason?

Thanks,

2016-10-11 14:01 GMT-04:00 Devin Pastoor <notifications@github.com>:

**Comment by kylebmetrum** [comment]
Hi @quagmirerules  - 

Use the link that @dpastoor referenced.  Getting the empirical Bayes estimates from a population model works well in `R` + `mrgsolve`.  Basically, you fix everything and just estimate the `ETA`s.  This is exactly what you are describing.

The note on on the simplefit vignette
https://github.com/metrumresearchgroup/mrgsolve/wiki/simplefit

is only to let you know that using `R` + `mrgsolve` to fit population models doesn't offer a lot of advantages over just doing it in NONMEM.  I have fit population models for client projects and published the results etc.  You definitely can do it.  But it's probably more hassle than it is worth.

But getting empirical Bayes estimates in `R` with `mrgsolve` makes sense: it's fast and flexible and gives you same result as NONMEM.

**Comment by quagmirerules** [comment]
Thanks a lot for the explanation :)

2016-10-11 14:51 GMT-04:00 Kyle Baron <notifications@github.com>:

**Comment by kylebmetrum** [comment]
@quagmirerules Np.  If you're at ACoP in a couple of weeks, stop by and say hi.
