### ISSUE TITLE
[Q] Re-org repository?

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#154]
Would it be a disaster to move package contents up from `rdev` directory? I had the package in `rdev` for a long time because there was always other stuff in the (then-`svn`) repository.  All that stuff has another home now that `mrgsolve` is on github.  I'd like to put the package in the base directory of the repository, but don't want to wreak havoc on peoples' work flow.  

I want to get to a place where we can install with `install_github("metrumresearchgroup/mrgsolve")` and drop the `subdir` argument.

@dpastoor @vjd

**Comment by vjd** [comment]
@kylebmetrum it is not a bad idea. Considering the diversity of the current users, it is safe to say that there are very few out there whose workflow will be hampered by the change in the organization. As long as the install process remains the same, no issues at all.

**Comment by kylebmetrum** [comment]
Thx, @vjd.  I think we'll head in that direction; need to get some stuff worked out on my end too.  The package has been in `rdev` for years.

**Comment by dpastoor** [comment]
I have from the get-go been an advocate of the re-org, I think it is definitely more idiomatic and plays nicer with a lot of the tooling that is growing around the expectation that a repo = a package. Wohoo!

**Comment by dpastoor** [comment]
wooooooo

**Comment by dpastoor** [comment]
confirming after reorg no problems re-installing on windows and mac machines

**Comment by kylebmetrum** [comment]
Thx for trying it out.
