### ISSUE TITLE
[Q] R install & path on Windows 10

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#155]
Did anyone get `R` properly installed under `c:/Program Files`?  I took that as the default install directory and got the `PATH` properly set.  I can run `Rscript` fine from anywhere (command prompt or from a `system` command in `R`), but every time I try to run `R.exe`, it comes back with this: 
http://stackoverflow.com/questions/26020334/running-r-from-cmd-in-windows

I can even be in the directory where `R.exe` lives and type the full command (with path and quoted) and I still get 

```r
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

Wondering if any `mrgsolve` users have seen this as well.  I ended up installing `R` in `c:/R` and everything works fine.  Searched high and low for some `R` documentation that says you can't install in `c:/Program Files` but couldn't come up with anything.  

I can't imagine this is the reality but seems to me like it is.

**Comment by kylebmetrum** [comment]
I guess this is it: http://stackoverflow.com/a/25897083  But as @bbolker notes, I just can't believe more people haven't been bitten by this before.  Maybe default installs are going to user directories with no spaces?

**Comment by vjd** [comment]
@dpastoor  had to change the default installation of R to `C:/R` and boom, there were no problems with installing. I think it is safe to ask folks to change their R installation to this directory instead.

**Comment by kylebmetrum** [comment]
I agree; and it seems like there is a mandate from `R` for this as well.  I will update the install guide to emphasize this and add it to the checklist when people are having problems installing on Windows.

**Comment by kylebmetrum** [comment]
Apologies to everyone who may have reported issues like this and I'm not picking up on it until now.

**Comment by AjChavan** [comment]
Tnx VJD and Kyle. It worked successfully.
