### ISSUE TITLE
[F] Getting R objects to use in the model

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#158]
Working on a model that requires linear interpolation; we coded a function in `Rcpp` that does what `stats::approx` does but clearly to make this convenient, we need a way to pass in `R` objects to work on if needed; otherwise, it is clumsy to get the standards into the problem.

As a general purpose solution, allow the user to get an environment and pull objects from there; whatever they want / need.  There is a `$ENV`code block already that will source some `R` code and save the result in an environment.  That is primarily for parsing.  Maybe use that one by default and let users pass in a new environment (with new objects) to change up the simulation.  For now, the example just lets users get an environment from global and use objects from that environment. 

At some point, we'd have to define the objects (and types?) that must be available to run the model; in the example if `div2fun` wasn't around, it would be trouble.

```r
    library(mrgsolve)

    ## mrgsolve: Community Edition

    ## www.github.com/metrumresearchgroup/mrgsolve

    code <- '
    $PLUGIN Rcpp
    $INCLUDE env.h

    $MAIN

    Rcpp::Environment e = get_env("myenv");

    Rcpp::Function div2fun = e["fun"];

    capture value = e["value"];

    capture div2 = Rcpp::as<double>(div2fun(value));

    '

    myenv <- new.env()
    myenv$value <- 1.234
    myenv$fun <- function(x) x/2

    mod <- mcode("ENV", code, project='.')

    ## Compiling ENV ...

    ## done.

    mod %>% mrgsim

    ## Model:  ENV.cpp 
    ## Dim:    25 x 4 
    ## Time:   0 to 24 
    ## ID:     1 
    ##      ID time value  div2
    ## [1,]  1    0 1.234 0.617
    ## [2,]  1    1 1.234 0.617
    ## [3,]  1    2 1.234 0.617
    ## [4,]  1    3 1.234 0.617
    ## [5,]  1    4 1.234 0.617
    ## [6,]  1    5 1.234 0.617
    ## [7,]  1    6 1.234 0.617
    ## [8,]  1    7 1.234 0.617

```

**Comment by kylebmetrum** [comment]
@dpastoor You could easily write your own reporter for debugging a model now as an `R` function defined in `$ENV`

 ```r  
   library(mrgsolve)

    ## mrgsolve: Community Edition

    ## www.github.com/metrumresearchgroup/mrgsolve

    code <- '
    $PARAM FLAG = 1

    $PLUGIN Rcpp mrgx

    $ENV
    hithere <- function(i) print(paste0("Hi there; time is ", i))
    x <- 55.66

    $GLOBAL
    namespace {
      Rcpp::Environment env;
    }

    $MAIN
    if(NEWIND==0) env = mrgx_get_envir();

    static Rcpp::Function hey = env["hithere"];
    if(FLAG) hey(TIME);

    capture x = env["x"];
    '

    mod <- mcode("hithere", code)

    ## Compiling hithere ...

    ## done.

    out <- mod %>% mrgsim

    ## [1] "Hi there; time is 0"
    ## [1] "Hi there; time is 0"
    ## [1] "Hi there; time is 1"
    ## [1] "Hi there; time is 2"
    ## [1] "Hi there; time is 3"
    ## [1] "Hi there; time is 4"
    ## [1] "Hi there; time is 5"
    ## [1] "Hi there; time is 6"
    ## [1] "Hi there; time is 7"
    ## [1] "Hi there; time is 8"
    ## [1] "Hi there; time is 9"
    ## [1] "Hi there; time is 10"
    ## [1] "Hi there; time is 11"
    ## [1] "Hi there; time is 12"
    ## [1] "Hi there; time is 13"
    ## [1] "Hi there; time is 14"
    ## [1] "Hi there; time is 15"
    ## [1] "Hi there; time is 16"
    ## [1] "Hi there; time is 17"
    ## [1] "Hi there; time is 18"
    ## [1] "Hi there; time is 19"
    ## [1] "Hi there; time is 20"
    ## [1] "Hi there; time is 21"
    ## [1] "Hi there; time is 22"
    ## [1] "Hi there; time is 23"
    ## [1] "Hi there; time is 24"

    out

    ## Model:  hithere.cpp 
    ## Dim:    25 x 3 
    ## Time:   0 to 24 
    ## ID:     1 
    ##      ID time     x
    ## [1,]  1    0 55.66
    ## [2,]  1    1 55.66
    ## [3,]  1    2 55.66
    ## [4,]  1    3 55.66
    ## [5,]  1    4 55.66
    ## [6,]  1    5 55.66
    ## [7,]  1    6 55.66
    ## [8,]  1    7 55.66

    mod@envir$x <- 123.456

    mod %>% param(FLAG=0) %>% mrgsim

    ## Model:  hithere.cpp 
    ## Dim:    25 x 3 
    ## Time:   0 to 24 
    ## ID:     1 
    ##      ID time     x
    ## [1,]  1    0 123.5
    ## [2,]  1    1 123.5
    ## [3,]  1    2 123.5
    ## [4,]  1    3 123.5
    ## [5,]  1    4 123.5
    ## [6,]  1    5 123.5
    ## [7,]  1    6 123.5
    ## [8,]  1    7 123.5
```

**Comment by dpastoor** [comment]
very sweet! Two questions:

is the overhead just on compilation, or is there a much of a ding in performance invoking R functions from Rcpp?

Are there limitations (that you know of)?

**Comment by kylebmetrum** [comment]
There is definitely a performance ding for calling an `R` function over and over again here.  @eddelbuettel discusses it here: http://gallery.rcpp.org/articles/r-function-from-c++/.  

We coded `Rcpp_approx` for a client project and it is faster (and obviously simpler) than `stats::approx`.  But we had no way to get the interpolation standards into the game (`x` and `y` arguments to `approx`).  So this whole business of passing `R` objects into your model was mainly a way to get data into the model.  We might just use `stats::approx` for simplicity, but I suspect the ding would be more than we'd tolerate and Dirk seems to discourage it.

And I'd also say that, before doing this, I tried to make sure there was no way to do this either before or after the simulation; I'd definitely go that route if at all possible for performance and also just to try to keep things simple.  

I don't know of limitations so far.  I was worried about people leaving required objects out of the environment;  taking objects from `$ENV` by default at least encourages people to link those objects in with the model specification.  If the user tries to get an object out of the environment that doesn't exist, it tends to fail pretty gracefully;  not informative, but not disaster.  I don't know how much work I want to do to try to prevent mistakes or inform what is going wrong.  If you really need to try this, you better know what you are doing for now.

**Comment by kylebmetrum** [comment]
This example probably isn't the right thing to benchmark, but for some perspective the ding  here is:

```r
                                 test replications elapsed relative
2 mrgsim(mod, param = list(FLAG = 0))         1000   4.828    1.000
1                         mrgsim(mod)         1000   6.217    1.288
```
