### ISSUE TITLE
mrgsim - simulate e.g. cmin

### ISSUE THREAD

**Issue by vjd** [metrumresearchgroup/mrgsolve#17]
I understand that you can provide `start`, `end`, `delta` in `mrgsim` to create a simulation data frame. 

I wonder how the solver functions if all I request is one-time point by passing in something like this below
```
mod  %>% data_set(data) %>% 
  mrgsim(Req="DV", start=11.9, end=11.9)
```

I am assuming that 11.9 is my time for `cmin` as I have the following event block

```
ev(ID=1, amt=1000, ii=12, addl=3,ss=1)
```

So, instead of creating an entire time grid till 36 or 48 hours, what if I just pick out the time vector of cmin (the time point just before the next dosing event). I know we can post process in dplyr using `filter`, but just checking if there would be any saving in time if I just use the same start and end value. 

If there is any other elegant solution to pick out cmin only (not as a post-processing step), I would like to check it out.

**Comment by kylebmetrum** [comment]
````r
mod %>% data_set(data) %>% obsonly %>% mrgsim(end=-1, add=11.9)
````

Setting `end` to -1 gets you out of the whole `start` to `end` sequence; `add` is just an arbitrary vector of times to get.  You'll need to use `obsonly` if you really only want that single time in the output.

**Comment by kylebmetrum** [comment]
You might also look at this too:

```` r
mod %>% ev(amt=1000,ii=12, addl=3) %>% obsonly %>% mrgsim(recsort=2, add=seq(0,48,12))

````

The `recsort=2` will put the doses at time 12,24,36,48, etc... __after__ the observation records so you can grab those times as the trough.  I *believe* NONMEM puts the dose before the observation (at the same time) so those end up peaks (I think).  But whatever NONMEM is doing, you can control how that stuff is sorted through `recsort`.  See `?mrgsim` then  `Additional arguments`.

**Comment by vjd** [comment]
Thanks. Does the simulation property change as we are requesting only one time point, i.e., does the `SOLVERTIME` still run from 0 to end of the last dose?

**Comment by kylebmetrum** [comment]
You get the same result regardless of how many output times you ask for.  The solver will at least go from dose to dose (that you specified in `addl` ... so there are discontinuities there that you don't ever see happening) and it will take as many time steps as it needs to get there. 

Try this:

````r
code <- '
$PARAM TVCL = 1, TVVC=30

$CMT CENT

$ODE
dxdt_CENT = -(TVCL/TVVC)*CENT;

report(SOLVERTIME,CENT);

'


mod <- mread("mycode", tempdir(),code, warn=FALSE)

mod %>% ev(amt=100,ii=12,addl=3) %>% mrgsim(end=-1, add=72)

````

**Comment by vjd** [comment]
Nice. Getting better and better. The `recsort` option is really useful and I can think of using it different scenarios. I will write up a small gallery entry to simulate only troughs with these three examples that are stated here!

**Comment by kylebmetrum** [comment]
Cool;  thanks, Vijay.  

One qualification on these sparse simulations:  you might have to increase `maxsteps` if you are asking the solver to integrate between two times that are very far apart.  

Also, for models that are highly non-linear or have several very different scales, you might have to reduce `hmax` (to 1 or 0.1 depending on what time scale you are working with).  This will slow down the computation but it will limit how big of a step to take (`SOLVERTIME`).  I wouldn't reduce `hmax` unless there was some evidence it was required (some error from the solver or instability in the simulation or some other discontinuity I wanted to make sure to capture).  The vast majority of the time run with the default `hmax`.
