### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by rspsbits** [metrumresearchgroup/mrgsolve#170]
I am trying to use mrgsolve but it keeps giving me compilation error. The model is directly taken from the user's guide. 

[mrgsolve error.txt](https://github.com/metrumresearchgroup/mrgsolve/files/653384/mrgsolve.error.txt)

<(pkpdexample.cpp)>

PARAM CL = 1, VC = 30, KA = 1.3

$CMT GUT CENT

$ODE

dxdt_GUT = -KA*GUT;
dxdt_CENT = KA*GUT - (CL/VC)*CENT;

$TABLE
double CP = CENT/VC;

$CAPTURE CP

**Comment by dpastoor** [comment]
Hi @rspsbits are you sure you copied directly? You seem to be missing the multiplication of the absorption component

```diff
-dxdt_GUT = -KAGUT;
+dxdt_GUT = -KA*GUT;
dxdt_CENT = KAGUT - (CL/VC)*CENT;
-dxdt_CENT = KAGUT - (CL/VC)*CENT;
+dxdt_CENT = KA*GUT - (CL/VC)*CENT;
```

**Comment by rspsbits** [comment]
Hi Davin,

In my model file, multiplication is present. I could not attach .cpp file
to the thread and it seems multiplication sign in copying and pasting.

$PARAM CL = 1, VC = 30, KA = 1.3

$CMT GUT CENT

$ODE

dxdt_GUT = -KA*GUT;
dxdt_CENT = KA*GUT - (CL/VC)*CENT;

$TABLE
double CP = CENT/VC;

$CAPTURE CP

Thanks,

Best regards,

Ravi

**Comment by kylebmetrum** [comment]
@rspsbits @dpastoor Changing `KAGUT` to `KA*GUT` will fix the model.  But looking at the attached file with the error message, it looks like something else might be going on??

1.  Can you send the output of `sessionInfo()`
2.  Can you try the test code shown here: https://github.com/metrumresearchgroup/mrgsolve/wiki/compilers-and-mrgsolve#test-your-c-compiler

Thanks.

**Comment by rspsbits** [comment]
Hi Kyle,

Below are the outputs. It seems the compiler is not working properly.

> library(mrgsolve)
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United
States.1252
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C

[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] mrgsolve_0.7.6.9029

loaded via a namespace (and not attached):
 [1] lazyeval_0.2.0            magrittr_1.5              R6_2.1.3

 [4] assertthat_0.1            DBI_0.5-1                 tools_3.3.1

 [7] RcppArmadillo_0.7.500.0.0 dplyr_0.5.0               tibble_1.2

[10] Rcpp_0.12.8
> ccode <- 'extern "C" {void test() {double x=2.1; x = x+1;}}\n'
> cat(file="R_Cpp_Test.cpp", ccode)
> system("R CMD SHLIB R_Cpp_Test.cpp")
C:/Users/singr161/DOCUME~1/R/R-33~1.1/etc/x64/Makeconf:203: warning:
overriding commands for target `.m.o'
C:/Users/singr161/DOCUME~1/R/R-33~1.1/etc/x64/Makeconf:196: warning:
ignoring old commands for target `.m.o'
c:/Rtools/mingw_64/bin/g++
 -I"C:/Users/singr161/DOCUME~1/R/R-33~1.1/include" -DNDEBUG
-I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c
R_Cpp_Test.cpp -o R_Cpp_Test.o
The system cannot find the path specified.
make: *** [R_Cpp_Test.o] Error 1
Warning message:
running command 'make -f
"C:/Users/singr161/DOCUME~1/R/R-33~1.1/etc/x64/Makeconf" -f
"C:/Users/singr161/DOCUME~1/R/R-33~1.1/share/make/winshlib.mk"
SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)'
SHLIB="R_Cpp_Test.dll" WIN=64 TCLBIN=64 OBJECTS="R_Cpp_Test.o"' had status
2
Warning message:
running command 'R CMD SHLIB R_Cpp_Test.cpp' had status 1
>
> fcode <- '
+       subroutine bar(n, x)
+ integer n
+ double precision x(n)
+ integer i
+ do 100 i = 1, n
+ x(i) = x(i) ** 2
+ 100 continue
+ end
+ '
> cat(file="R_FORTRAN_Test.f", fcode)
> system("R CMD SHLIB R_FORTRAN_Test.f")
C:/Users/singr161/DOCUME~1/R/R-33~1.1/etc/x64/Makeconf:203: warning:
overriding commands for target `.m.o'
C:/Users/singr161/DOCUME~1/R/R-33~1.1/etc/x64/Makeconf:196: warning:
ignoring old commands for target `.m.o'
c:/Rtools/mingw_64/bin/gfortran      -O2  -mtune=core2 -c R_FORTRAN_Test.f
-o R_FORTRAN_Test.o
process_begin: CreateProcess(NULL, c:/Rtools/mingw_64/bin/gfortran -O2
-mtune=core2 -c R_FORTRAN_Test.f -o R_FORTRAN_Test.o, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [R_FORTRAN_Test.o] Error 2
Warning message:
running command 'make -f
"C:/Users/singr161/DOCUME~1/R/R-33~1.1/etc/x64/Makeconf" -f
"C:/Users/singr161/DOCUME~1/R/R-33~1.1/share/make/winshlib.mk"
SHLIB="R_FORTRAN_Test.dll" SHLIB_LIBADD='$(FLIBS)' WIN=64 TCLBIN=64
OBJECTS="R_FORTRAN_Test.o"' had status 2
Warning message:
running command 'R CMD SHLIB R_FORTRAN_Test.f' had status 1
>

Thanks,

Best regards,

Ravi

-------------------------------------

*RAVI SINGH, PH.D.*

**Comment by kylebmetrum** [comment]
Thanks;  hrm .... trying to figure out where to go with this. 

`c:/Rtools/mingw_64/bin/g++` seems to indicate that it can find the right toolchain. 

I'm not sure what this 

`C:/Users/singr161/DOCUME~1/R/R-33~1.1/etc/x64/Makeconf:203: warning:
overriding commands for target `.m.o'` 

is ... but it keeps showing up no matter what is the source file name. 

Can you share `Sys.getenv("PATH")` too?

**Comment by rspsbits** [comment]
Hi Kyle,

Please see below.

> Sys.getenv("PATH")

[1]
"C:\\Users\\singr161\\Documents\\R\\R-3.3.1\\bin\\x64;C:\\Perl516\\site\\bin;C:\\Perl516\\bin;C:\\Program
Files (x86)\\gfortran\\bin;C:\\Program Files
(x86)\\gfortran\\libexec\\gcc\\i586-pc-mingw32\\4.5.0;C:\\Program Files
(x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS
Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program
Files (x86)\\QuickTime\\QTSystem\\;C:\\Program Files (x86)\\Enterprise
Vault\\EVClient\\;C:\\Program Files\\Intel\\Intel(R) Management Engine
Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine
Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine
Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine
Components\\IPT;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program
Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Pkpd\\Bin;C:\\Program
Files (x86)\\Sennheiser\\SoftphoneSDK\\;C:\\nm712\\run;C:\\Program Files
(x86)\\gfortran\\libexec\\gcc\\i586-pc-mingw32\\4.5.0;C:\\Program Files
(x86)\\gfortran\\bin"

Thanks,

Best regards,

Ravi

-------------------------------------

*RAVI SINGH, PH.D.*

**Comment by kylebmetrum** [comment]
@rspsbits This is a bit of a reach, but I think worth trying:

Please see the example path specification here:
https://gist.github.com/kylebmetrum/e43cba0a6f06084ecbb28d15864bbe45

You'll see two Rtools locations (lines 2 and 3).  Notice that for each Rtools locations, there are two directories (a `bin` directory and a `gcc-4.6.3\\bin` directory).   Can you take a look at where you installed Rtools on your system and put that on the front of your path.  There is example code in the gist to show how to do that.  After you update the path, keep R running and try compiling the example code again (note: the FORTRAN snippet might not compile properly ... there is some pickiness in the spacing for that code that may not happen right if you copy /paste from github.  Nevertheless, the C++ code should run as-is).

Kyle

**Comment by rspsbits** [comment]
Hi Kyle,

It did not fix the problem but the error code changed to 127 and I do not
know what it actually mean. For some reason when we call for system(), for
some reason it starts to look for g++.exe in
C:/Rtools/mingw_64/bin/gfortran whereas it is actually located under
C:/RBuildTools/3.3/mingw_64/bin. Setting the path does not seems to pass on
to system().


> Sys.getenv("PATH")
[1]
"C:\\RBuildTools\\3.3\\bin;C:\\RBuildTools\\3.3\\gcc-4.6.3\\bin;C:\\RBuildTools\\3.3\\bin;C:\\RBuildTools\\3.3\\gcc-4.6.3\\bin;C:\\RBuildTools\\3.3\\bin;C:\\RBuildTools\\3.3\\gcc-4.6.3\\bin;C:\\Users\\singr161\\Documents\\R\\R-3.3.1\\bin\\x64;C:\\Perl516\\site\\bin;C:\\Perl516\\bin;C:\\Program
Files (x86)\\gfortran\\bin;C:\\Program Files
(x86)\\gfortran\\libexec\\gcc\\i586-pc-mingw32\\4.5.0;C:\\Program Files
(x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS
Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program
Files (x86)\\QuickTime\\QTSystem\\;C:\\Program Files (x86)\\Enterprise
Vault\\EVClient\\;C:\\Program Files\\Intel\\Intel(R) Management Engine
Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine
Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine
Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine
Components\\IPT;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program
Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Pkpd\\Bin;C:\\Program
Files (x86)\\Sennheiser\\SoftphoneSDK\\;C:\\nm712\\run;C:\\Program Files
(x86)\\gfortran\\libexec\\gcc\\i586-pc-mingw32\\4.5.0;C:\\Program Files
(x86)\\gfortran\\bin"
> oldpath <- Sys.getenv("PATH")
> newpath <-
paste0("C:\\RBuildTools\\3.3\\bin;C:\\RBuildTools\\3.3\\gcc-4.6.3\\bin;",oldpath)
> Sys.setenv(PATH=newpath)
> system("g++ -v")
Using built-in specs.
COLLECT_GCC=C:\RBUILD~1\3.3\GCC-46~1.3\bin\G__~1.EXE
COLLECT_LTO_WRAPPER=c:/rbuild~1/3.3/gcc-46~1.3/bin/../libexec/gcc/i686-w64-mingw32/4.6.3/lto-wrapper.exe
Target: i686-w64-mingw32
Configured with: /data/gannet/ripley/Sources/mingw-test3/src/gcc/configure
--host=i686-w64-mingw32 --build=x86_64-linux-gnu --target=i686-w64-mingw32
--with-sysroot=/data/gannet/ripley/Sources/mingw-test3/mingw32mingw32/mingw32
--prefix=/data/gannet/ripley/Sources/mingw-test3/mingw32mingw32/mingw32
--with-gmp=/data/gannet/ripley/Sources/mingw-test3/mingw32mingw32/prereq_install
--with-mpfr=/data/gannet/ripley/Sources/mingw-test3/mingw32mingw32/prereq_install
--with-mpc=/data/gannet/ripley/Sources/mingw-test3/mingw32mingw32/prereq_install
--disable-shared --enable-static --enable-targets=all
--enable-languages=c,c++,fortran --enable-libgomp --enable-sjlj-exceptions
--enable-fully-dynamic-string --disable-nls --disable-werror
--enable-checking=release --disable-win32-registry --disable-rpath
--disable-werror CFLAGS='-O2 -mtune=core2 -fomit-frame-pointer' LDFLAGS=
Thread model: win32
gcc version 4.6.3 20111208 (prerelease) (GCC)
> ccode <- 'extern "C" {void test() {double x=2.1; x = x+1;}}\n'
> cat(file="R_Cpp_Test.cpp", ccode)
> system("R CMD SHLIB R_Cpp_Test.cpp")
c:/Rtools/mingw_64/bin/g++
 -I"C:/Users/singr161/DOCUME~1/R/R-33~1.1/include" -DNDEBUG
-I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c
R_Cpp_Test.cpp -o R_Cpp_Test.o
c:/Rtools/mingw_64/bin/g++: not found
make: *** [R_Cpp_Test.o] Error 127
Warning message:
running command 'make -f
"C:/Users/singr161/DOCUME~1/R/R-33~1.1/etc/x64/Makeconf" -f
"C:/Users/singr161/DOCUME~1/R/R-33~1.1/share/make/winshlib.mk"
SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)'
SHLIB="R_Cpp_Test.dll" WIN=64 TCLBIN=64 OBJECTS="R_Cpp_Test.o"' had status
2
Warning message:
running command 'R CMD SHLIB R_Cpp_Test.cpp' had status 1
> fcode <- '
+       subroutine bar(n, x)
+ integer n
+ double precision x(n)
+ integer i
+ do 100 i = 1, n
+ x(i) = x(i) ** 2
+ 100 continue
+ end
+ '
> cat(file="R_FORTRAN_Test.f", fcode)
> system("R CMD SHLIB R_FORTRAN_Test.f")
c:/Rtools/mingw_64/bin/gfortran      -O2  -mtune=core2 -c R_FORTRAN_Test.f
-o R_FORTRAN_Test.o
make: c:/Rtools/mingw_64/bin/gfortran: Command not found
make: *** [R_FORTRAN_Test.o] Error 127
Warning message:
running command 'make -f
"C:/Users/singr161/DOCUME~1/R/R-33~1.1/etc/x64/Makeconf" -f
"C:/Users/singr161/DOCUME~1/R/R-33~1.1/share/make/winshlib.mk"
SHLIB="R_FORTRAN_Test.dll" SHLIB_LIBADD='$(FLIBS)' WIN=64 TCLBIN=64
OBJECTS="R_FORTRAN_Test.o"' had status 2
Warning message:
running command 'R CMD SHLIB R_FORTRAN_Test.f' had status 1

Thanks,

Best regards,

Ravi

-------------------------------------

*RAVI SINGH, PH.D.*

**Comment by rspsbits** [comment]
Hi Kyle,

I manually created a folder Rtools in C: drive and pasted the content from C:/RBuildTools/3.3 to that folder. After this, I had to update the path and then the compiler seems to work properly. Thanks for helping me with this. 

> library(mrgsolve)
> ccode <- 'extern "C" {void test() {double x=2.1; x = x+1;}}\n'
> cat(file="R_Cpp_Test.cpp", ccode)
> system("R CMD SHLIB R_Cpp_Test.cpp")
C:/Users/singr161/DOCUME~1/R/R-33~1.1/etc/x64/Makeconf:203: warning: overriding commands for target `.m.o'
C:/Users/singr161/DOCUME~1/R/R-33~1.1/etc/x64/Makeconf:196: warning: ignoring old commands for target `.m.o'
c:/Rtools/mingw_64/bin/g++  -I"C:/Users/singr161/DOCUME~1/R/R-33~1.1/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c R_Cpp_Test.cpp -o R_Cpp_Test.o
process_begin: CreateProcess(NULL, basename R_Cpp_Test.dll .dll, ...) failed.
process_begin: CreateProcess(NULL, basename R_Cpp_Test.dll .dll, ...) failed.
process_begin: CreateProcess(NULL, basename R_Cpp_Test.dll .dll, ...) failed.
"zR_Cpp_Test.o" was unexpected at this time.
make: *** [R_Cpp_Test.dll] Error 255
Warning message:
running command 'make -f "C:/Users/singr161/DOCUME~1/R/R-33~1.1/etc/x64/Makeconf" -f "C:/Users/singr161/DOCUME~1/R/R-33~1.1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="R_Cpp_Test.dll" WIN=64 TCLBIN=64 OBJECTS="R_Cpp_Test.o"' had status 2 
Warning message:
running command 'R CMD SHLIB R_Cpp_Test.cpp' had status 1 
> Sys.getenv("PATH")
[1] "C:\\Users\\singr161\\Documents\\R\\R-3.3.1\\bin\\x64;C:\\Perl516\\site\\bin;C:\\Perl516\\bin;C:\\Program Files (x86)\\gfortran\\bin;C:\\Program Files (x86)\\gfortran\\libexec\\gcc\\i586-pc-mingw32\\4.5.0;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\QuickTime\\QTSystem\\;C:\\Program Files (x86)\\Enterprise Vault\\EVClient\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Pkpd\\Bin;C:\\Program Files (x86)\\Sennheiser\\SoftphoneSDK\\;C:\\nm712\\run;C:\\Program Files (x86)\\gfortran\\libexec\\gcc\\i586-pc-mingw32\\4.5.0;C:\\Program Files (x86)\\gfortran\\bin"
> oldpath <- Sys.getenv("PATH")
> newpath <- paste0("C:\\RBuildTools\\3.3\\bin;C:\\RBuildTools\\3.3\\gcc-4.6.3\\bin;",oldpath)
> Sys.setenv(PATH=newpath)
> system("g++ -v")
Using built-in specs.
COLLECT_GCC=C:\RBUILD~1\3.3\GCC-46~1.3\bin\G__~1.EXE
COLLECT_LTO_WRAPPER=c:/rbuild~1/3.3/gcc-46~1.3/bin/../libexec/gcc/i686-w64-mingw32/4.6.3/lto-wrapper.exe
Target: i686-w64-mingw32
Configured with: /data/gannet/ripley/Sources/mingw-test3/src/gcc/configure --host=i686-w64-mingw32 --build=x86_64-linux-gnu --target=i686-w64-mingw32 --with-sysroot=/data/gannet/ripley/Sources/mingw-test3/mingw32mingw32/mingw32 --prefix=/data/gannet/ripley/Sources/mingw-test3/mingw32mingw32/mingw32 --with-gmp=/data/gannet/ripley/Sources/mingw-test3/mingw32mingw32/prereq_install --with-mpfr=/data/gannet/ripley/Sources/mingw-test3/mingw32mingw32/prereq_install --with-mpc=/data/gannet/ripley/Sources/mingw-test3/mingw32mingw32/prereq_install --disable-shared --enable-static --enable-targets=all --enable-languages=c,c++,fortran --enable-libgomp --enable-sjlj-exceptions --enable-fully-dynamic-string --disable-nls --disable-werror --enable-checking=release --disable-win32-registry --disable-rpath --disable-werror CFLAGS='-O2 -mtune=core2 -fomit-frame-pointer' LDFLAGS=
Thread model: win32
gcc version 4.6.3 20111208 (prerelease) (GCC) 
> ccode <- 'extern "C" {void test() {double x=2.1; x = x+1;}}\n'
> cat(file="R_Cpp_Test.cpp", ccode)
> system("R CMD SHLIB R_Cpp_Test.cpp")
c:/Rtools/mingw_64/bin/g++  -I"C:/Users/singr161/DOCUME~1/R/R-33~1.1/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c R_Cpp_Test.cpp -o R_Cpp_Test.o
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o R_Cpp_Test.dll tmp.def R_Cpp_Test.o -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/Users/singr161/DOCUME~1/R/R-33~1.1/bin/x64 -lR
> > mod<-mread("pkpdexample")
Compiling pkpdexample ... done.
> out <- mod %>% init(GUT=1000) %>% mrgsim(delta=0.1,end=168)
> out
Model:  pkpdexample.cpp 
Dim:    1681 x 5 
Time:   0 to 168 
ID:     1 
     ID time    GUT  CENT     CP
[1,]  1  0.0 1000.0   0.0  0.000
[2,]  1  0.1  878.1 121.7  4.057
[3,]  1  0.2  771.1 228.2  7.605
[4,]  1  0.3  677.1 321.2 10.708
[5,]  1  0.4  594.5 402.6 13.419
[6,]  1  0.5  522.0 473.6 15.786
[7,]  1  0.6  458.4 535.5 17.851
[8,]  1  0.7  402.5 589.5 19.651
>

**Comment by dpastoor** [comment]
@kylebmetrum I had a feeling when ravi posted his path it was going to be this issue. It seems that during the 'great switch' to R 3.3 and the new compilers, Rtools (team?) decided not to blow away the previous Rtools and instead install it as Rbuildtools (I think) if Rtools was already detected. This was not always reflected in updating the path, especially if the windows user didn't check the little update path box.

The 'good' news is, when installing on a fresh version of windows, at least recently, it 'properly' sets up an Rtools folder.

**Comment by kylebmetrum** [comment]
@rspsbits  Ok; great.  Thanks for reporting back.  You might look at setting that `PATH` environment variable in `windows` itself for convenience ... however that might wreck your `NONMEM` too.  There are some more-convenient ways to get the `PATH` set up correctly for your `R` sessions that I can help you with if that becomes an issue.

**Comment by kylebmetrum** [comment]
@dpastoor OIC .... I was wondering where RBuildTools came from;  when I set up my Windows box, it showed up but I thought Rstudio had something to do with that (maybe that was wrong).  

But good idea going forward is to first figure out what `Sys.getenv("PATH")` is saying and then ask of it is `C:/Rtools` or `c:/Rbuildtools` (or somewhere else) that is in play.
