### ISSUE TITLE
[F] Connect data_set, idata_set, and ev with $ENV

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#173]
This was easy to implement and will probably stay as a way to package a data set or event with a model.  

The idea is that you can mention a data frame that exists in `$ENV` and use that for `data_set` or `idata_set`.  If you mention a function, the data frame comes from that function call.  You can also specify a `call` argument that is the name of a function in `$ENV` which accepts the data frame as an argument and let's you mess around with it.

``` r
knitr::opts_chunk$set(comment='.', message=FALSE)
```

``` r
library(dplyr)
library(mrgsolve)


code <- '

$ENV

idata <- data.frame(ID=1:5)

e1 <- ev(amt=200,ii=12, addl=3)
d1 <- as.data.frame(e1) %>% mutate(ID=1)

add_covs <- function(data,...) {
  data %>%
    dmutate(WT[0,]~ rnorm(55,20)|ID) %>%
    dmutate(SEX ~ binomial(0.5))
}

data1 <- function(nid,amt,ii,...) {
  expand.ev(ID=1:nid,amt=amt,ii=ii)
}

$PARAM CL=1,V=20
$CMT  CENT
$PKMODEL ncmt=1
'
```

``` r
mod <- mcode("test", code)
```

``` r
mod %>% idata_set(object="idata") %>% simargs
```

    . $idata
    .   ID
    . 1  1
    . 2  2
    . 3  3
    . 4  4
    . 5  5

``` r
mod %>% 
  idata_set(object="idata",call="add_covs") %>% 
  simargs
```

    . $idata
    .   ID       WT SEX
    . 1  1 60.12401   1
    . 2  2 56.61977   0
    . 3  3 28.64610   0
    . 4  4 35.59545   0
    . 5  5 61.05005   1

``` r
mod %>% 
  data_set(object="data1",nid=10,amt=c(50,100),ii=24) %>%  
  simargs 
```

    . $data
    .       ID amt ii evid cmt time ..zeros..
    .  [1,]  1  50 24    1   1    0         0
    .  [2,]  2  50 24    1   1    0         0
    .  [3,]  3  50 24    1   1    0         0
    .  [4,]  4  50 24    1   1    0         0
    .  [5,]  5  50 24    1   1    0         0
    .  [6,]  6  50 24    1   1    0         0
    .  [7,]  7  50 24    1   1    0         0
    .  [8,]  8  50 24    1   1    0         0
    .  [9,]  9  50 24    1   1    0         0
    . [10,] 10  50 24    1   1    0         0
    . [11,] 11 100 24    1   1    0         0
    . [12,] 12 100 24    1   1    0         0
    . [13,] 13 100 24    1   1    0         0
    . [14,] 14 100 24    1   1    0         0
    . [15,] 15 100 24    1   1    0         0
    . [16,] 16 100 24    1   1    0         0
    . [17,] 17 100 24    1   1    0         0
    . [18,] 18 100 24    1   1    0         0
    . [19,] 19 100 24    1   1    0         0
    . [20,] 20 100 24    1   1    0         0
    . attr(,"class")
    . [1] "mrgindata"

``` r
mod %>% ev(object="e1") %>% mrgsim
```

    . Model:  test.cpp 
    . Dim:    26 x 3 
    . Time:   0 to 24 
    . ID:     1 
    .      ID time  CENT
    . [1,]  1    0   0.0
    . [2,]  1    0 200.0
    . [3,]  1    1 190.2
    . [4,]  1    2 181.0
    . [5,]  1    3 172.1
    . [6,]  1    4 163.7
    . [7,]  1    5 155.8
    . [8,]  1    6 148.2

**Comment by kylebmetrum** [comment]
As follow up, do something like this:

```r
$ENV
wt <- WT[40,140] ~ rnorm(80,40)
flag <- SEX ~ binomial(0.5)

```
and

```r
mod %>% idata_set(mydata, formulae="wt,flag") %>% mrgsim
```

**Comment by dpastoor** [comment]
so by this example, is the default behavior to set _potential_ formulae, that you then have to activate in idata_set? 

how is precedence handled (eg what if I have a wt column in the dataset already?) error, override, warning? 

likewise - how is package management handled - I presume this is basically just executing the R code in a new environment? Is it a _brandnew_ environment separate from the original calling env?

Last, is there a way of setting a 'default' execution - eg if I am distributing this as an example, so want to set up dosing/sampling/param values in a $ENV, I'd like them to just be able to `mrgsim()` without having to know anything about objects or calls or otherwise.

Great concept!

**Comment by kylebmetrum** [comment]
Potential formulae .... right.  You have to active them and all it does it modify the data frame.  You can apply in either `data_set` or `idata_set`.  Obviously, depending on how the model is coded, it'll probably be one set.  But maybe a pediatric set and adult set?  You choose.  

If `WT` is already in a column, it is dumped and you take the new (simulated) weight.  What do you think?  Error or warning?  It's silent right now ... that should probably change.

Package management:  I fooled around with a "require" filed in `$SET` or something like that where I'd load the packages for you.  But I ended up thinking that we'd just have users `require(packagename)` in `$ENV` (or `requireNamespace` instead).   That should at least cause an error on compile if the package isn't available.  There is also a function to re-evaluate the code in `$ENV` that you could run after loading from cache just to make sure everything is still cool.  I'm hoping the code in `$ENV` would end up pretty simple so that packages wouldn't matter that much (but you already get `dplyr` and dendencies with `mrgsolve`). 

The environment is generated from `new.env()`.  I'm not sure what the parent environment is, but maybe I should double check to make sure it's `.GlobalEnv` or something not offensive?

**Comment by kylebmetrum** [comment]
@dpastoor @vjd

As of Version: 0.7.9.9003, to do a `dplyr::mutate` type operation in a `covset`, do:

```r
$PARAM
beta1 = 0.2, beta2 = 1, g = 9.8
mean_age = 50, sd_age = 20

$ENV

a <- AGE ~ rnorm(mean_age,sd_age)
b <- WT ~ mutate(AGE*beta1 + beta2)
c <- constant ~ mutate(12 + g)

cov1 <- covset(a,b,c)
```

So it really works like you would do with `dplyr::mutate` ... you can reference other columns in the data frame.  But since the parameters are in the evaluation environment, you can reference a param by name too. 


https://github.com/kylebmetrum/dmutate#create-a-formula-with-mutate-to-calculate-new-columns-in-the-dataframe-using-dplyrmutate

**Comment by kylebmetrum** [comment]
Is this worth having a $COVARIATE code block to do this:


``` r
knitr::opts_chunk$set(comment='.', message=FALSE)
```

``` r
library(dplyr)
library(mrgsolve)
library(rbenchmark)
library(ggplot2)


code <- '
$PARAM TVCL=1,TVV=30,KA=2,WT=70,SEX = 0

$PKMODEL cmt="GUT CENT", depot=TRUE

$COVARIATE @name cov1
WT[45,120] ~ rnorm(80,40) |ID
SEX ~ rbinomial(0.7) |ID

$COVARIATE @name cov2
WT ~ mutate(70) | ID
SEX ~ mutate(0) | ID

$MAIN
double CL = TVCL * pow(WT/70,0.75);
double V = TVV * (WT/70);
if(SEX==1) V = V*0.8;

$TABLE capture CP = CENT/V;

$CAPTURE WT SEX

'
```

``` r
mod <- mcode("foo", code)
```

``` r
data <- data.frame(ID=1:5)
```

``` r
mod %>% idata_set(data,covset="cov1") %>% 
  ev(amt=100, ii=24, addl=3) %>% mrgsim(end=240) 
```

    . Model:  foo.cpp 
    . Dim:    1210 x 7 
    . Time:   0 to 240 
    . ID:     5 
    .      ID time       GUT  CENT    WT SEX    CP
    . [1,]  1    0 0.000e+00  0.00 87.29   1 0.000
    . [2,]  1    0 1.000e+02  0.00 87.29   1 0.000
    . [3,]  1    1 1.353e+01 84.26 87.29   1 2.815
    . [4,]  1    2 1.832e+00 92.41 87.29   1 3.088
    . [5,]  1    3 2.479e-01 90.38 87.29   1 3.020
    . [6,]  1    4 3.355e-02 87.09 87.29   1 2.910
    . [7,]  1    5 4.540e-03 83.75 87.29   1 2.798
    . [8,]  1    6 6.144e-04 80.52 87.29   1 2.690

``` r
a <- mrgsolve:::get_covsets(get_env(mod))

#
a
```

    . $cov1
    . [[1]]
    . [1] "WT[45,120] ~ rnorm(80,40) |ID"
    . 
    . [[2]]
    . [1] "SEX ~ rbinomial(0.7) |ID"
    . 
    . attr(,"class")
    . [1] "covset"
    . 
    . $cov2
    . [[1]]
    . [1] "WT ~ mutate(70) | ID"
    . 
    . [[2]]
    . [1] "SEX ~ mutate(0) | ID"
    . 
    . attr(,"class")
    . [1] "covset"

``` r
data %>% mrgsolve:::mutate_random(a$cov1)
```

    .   ID        WT SEX
    . 1  1 105.51104   1
    . 2  2  85.22669   0
    . 3  3  93.19967   1
    . 4  4 108.61669   1
    . 5  5  67.69538   0

**Comment by kylebmetrum** [comment]
Renaming some things here: https://github.com/metrumresearchgroup/mrgsolve/commit/6b01cd50c2b0fa3442d1e463d8b8183776fbd452

```r
$COVSET @name cov1
logage ~ norm(log(50) 1)
age ~ expr(exp(logage))
```

**Comment by kylebmetrum** [comment]
The other issue is documentation of what's in `$ENV`.  It seems like the user could do this in `$PROB`.  I don't know if there really needs to be a formal structure to it, but maybe start encouraging that sort of documentation and a function to return the text in `$PROB`.  Obviously we could also render the model, but that might be too much to ask on a routine basis.
