### ISSUE TITLE
how to kill a simulation in progress?

### ISSUE THREAD

**Issue by vjd** [metrumresearchgroup/mrgsolve#18]
`ctrl + z, x, and c` did not work. 

multiple hits on `esc` seem to do the trick, but can't tell

Can you please confirm?

**Comment by kylebmetrum** [comment]
Are you in Rstudio?  Usually `esc` seems to work but I'm not sure why.  If you're parallelizing, that's hard to stop.  I usually have to kill the `R` processes myself from a bash prompt or just wait it out.

**Comment by vjd** [comment]
Esc definitely works, tested it again. Of course killing the R process is another option. 
Ran into this situation after I started a heavy simulation and realized one of my input parameters were mistyped.
