### ISSUE TITLE
explicit warning or error when data_set does not have evid

### ISSUE THREAD

**Issue by vjd** [metrumresearchgroup/mrgsolve#185]
`mrgsim` silently simulates from the model into the design of the data provided in `data_set`. If the data set passed into `data_set` does not have an `evid` set to `1`, then simulated dependent variables are zero as mrgsolve does not find a dosing record. It is better to throw out a warning or error out when simulation is requested but data set has no evid. 

note: `ev` automatically adds `evid` and sets it to `1`.

**Comment by kylebmetrum** [comment]
There is no requirement to have a data set with `evid=1`.  Here's the difference: the `ev` function creates an event or intervention so there should be some non-zero `evid` in there.  What you pass in to `data_set` is much more general.  Granted, most of the time there will be some `evid=1` records in there.  But for models that don't involve PK dosing, it would be totally natural to not have one in there.  We could make an optional check, but would have to decide which camp has to add that option (`dont_warn_about_missing_doses = TRUE`).
