### ISSUE TITLE
[D] Deprecate drop.re

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#201]
Either deprecate or make it an alias for `zero_re`.

**Comment by kylebmetrum** [comment]
This actually came in handy recently but the difference is confusing and 99.9% of the time people should use `zero_re`.  

1. Stop exporting the function
2. Add `drop` argument to `zero_re` that will just call `drop.re` instead

**Comment by dpastoor** [comment]
Both :-)

within drop.re add:

```
.Deprecated("zero_re")
```

This will give users a warning

```
Warning message:
'.Deprecated' is deprecated.
Use 'zero_re' instead.
```

then migrate the functionality to use zero_re if there can be a 1:1 mapping of functionality, eg using the drop arg proposed in option 2.


Remove in 6 months or so/when have a new big release with other breaking changes at once.
