### ISSUE TITLE
Where can I find more complete example

### ISSUE THREAD

**Issue by sibojan** [metrumresearchgroup/mrgsolve#204]
Hi ,
 
The user guide  (http://mrgsolve.github.io/user_guide/ ) provides a lot of examples on sub topics. It would be great if more complete examples are available.  For example, the complete simulation file, including from model building, dosing to plotting. 

Thank you,

Sibo

**Comment by kylebmetrum** [comment]
We do more of that in our training courses.  I'll link to some items below that might be a start.  

Look here for an end-to-end example:
https://github.com/mrgsolve/examples/tree/master/PrTS

Otherwise, if you want to propose more specifics about what you want to get done, I'll make the example as a blog post.   Don't provide every detail ... I just don't want to spend a lot of time working up something that isn't in the neighborhood of what you want to see.  For example:

- PK or PK/PD model
- Populations
  - Simulating multiple arms
  - Generating covariates
- Model features
   - Bioavailability
   - Lag time
   - Error model
   - Inter-occasion variability
- What kind of output or summary do you want to see

You might also look here:
http://mrgsolve.github.io/2017/01/01/generating-input-data-sets-for-mrgsolve/
https://github.com/mrgsolve/slides/blob/master/March12/simulation_examples.pdf
http://mrgsolve.github.io/topic/model-gallery/

**Comment by kylebmetrum** [comment]
There's some stuff on fitting model estimates:
https://github.com/mrgsolve/examples/tree/master/mtsinai_2016
http://mrgsolve.github.io/topic/map_bayes/

And a shiny app (just get started):
https://mrgsolve.shinyapps.io/house/

I'm working on getting all of this more centralized on https://mrgsolve.github.io

**Comment by sibojan** [comment]
Hi,

Thank you for your reply. I just found those example are in a narrative way. Are there any simple one/two comp  IV/oral examples including everything?  As a results, I can just copy, paste the whole code and run?   Then the plots come out automatically. 

Thank you,

**Comment by kylebmetrum** [comment]
I'll work on it for you this weekend.

**Comment by sibojan** [comment]
Thanks a lot.

**Comment by kylebmetrum** [comment]
Here's a simple example without the narrative.  It doesn't have "everything", but it illustrates a lot of features. 

- Code a model
  - Covariates & IIV
  - Bioavailability & lag time
  - Combined residual error model
  - Resimulate EPS until DV is positive
- Generate input data set with different doses and patient specific covariates
- Simulate with some customization of output
- Make some plots and summaries

Again this example is pretty basic example but it illustrates a complete example.  Even when the model gets complicated or we have more complicated tasks to do, it's not that much more than the types of steps you see here.

If this doesn't qualify as complete in your mind ... please get specific about what needs to be included to qualify as complete.  

```
##' ---
##' title: ""
##' date: ""
##' author: ""
##' ---

#+ message=FALSE, comment='.'
knitr::opts_chunk$set(comment='.', message=FALSE)
library(mrgsolve)
library(dplyr)
library(dmutate)
library(ggplot2)

#+
code <- '
$PARAM TVCL = 1, TVV = 35, TVKA = 1.3
F1 = 0.8, ALAG = 1.5
WT = 70, SEX = 0

$MAIN
double CL = TVCL*pow(WT/70,0.75)*exp(ECL);
double V  = TVV*(WT/70)*exp(EV);
double KA = TVKA*exp(EKA);

if(SEX==1) V = V*0.8;

F_GUT = F1;
ALAG_GUT = ALAG;

$PKMODEL cmt="GUT CENT", depot=TRUE

$OMEGA @labels ECL EV EKA
0.015 0.2 0.5

$SIGMA @labels PROP ADD
0.03 230

$TABLE
capture IPRED = CENT/(V/1000);
capture DV = IPRED*(1+PROP)+ADD;

while(DV < 0) {
  simeps();
  DV = IPRED*(1+PROP)+ADD;
}

$CAPTURE WT CL 
'

#+ message=FALSE
mod <- mcode_cache("demo", code)
#+
set.seed(33020)
idata <- 
  data_frame(ID=1:2000) %>% 
  mutate_random(WT[50,110] ~ rnorm(80,30)) %>% 
  mutate_random(SEX ~ rbinomial(0.7)) %>%
  mutate(dosegr = as.integer(WT > 90))

idata

ev1 <- ev(amt=100, ii=24, addl=9)
ev2 <- ev(amt=150, ii=24, addl=9)

data <- assign_ev(list(ev1,ev2),idata,"dosegr")

head(data)

set.seed(11009)

out <- 
  mod %>% 
  data_set(data) %>%
  idata_set(idata) %>%
  carry_out(dosegr) %>%
  mrgsim(delta=1, end=360,tad=TRUE)

##' \newpage
plot(out, IPRED+DV~., subset=ID==10)

##' \newpage
sims <- out %>% mutate(dosen = 1+(time-tad)/24)

tad <- filter(sims, ID <= 10 & time <= 240)

ggplot(tad, aes(tad,IPRED,group=dosen)) + 
  geom_line() + 
  facet_wrap(~ID)

##' \newpage
tr <- filter(sims, time==240)

ggplot(tr, aes(x=WT,y=DV)) + 
  geom_point() +  facet_wrap(~dosegr) +
  geom_smooth(method="loess")

##' \newpage
ggplot(tr,aes(x=DV,fill=factor(dosegr))) + 
  geom_density(alpha=0.5)
```

[sibo.pdf](https://github.com/metrumresearchgroup/mrgsolve/files/801023/sibo.pdf)

**Comment by sibojan** [comment]
Thank you so much. That is what I want, trying to get quick taste and overview of the power of the package.

**Comment by sibojan** [comment]
I ran into errors with the model.

![snap52](https://cloud.githubusercontent.com/assets/11802171/23331393/1d9592bc-fb33-11e6-9e3c-3e8775fc8a7b.jpg)

**Comment by kylebmetrum** [comment]
`127` usually means R can't find your compiler.  Check your path environment variable.

https://github.com/metrumresearchgroup/mrgsolve/wiki/Windows-Issues
https://github.com/metrumresearchgroup/mrgsolve/wiki/compilers-and-mrgsolve#windows-users
https://github.com/stan-dev/rstan/wiki/Install-Rtools-for-Windows

**Comment by kylebmetrum** [comment]
I'd recommend setting the `PATH` in your Windows system environment variables if you can.

**Comment by sibojan** [comment]
I have the path. 
![snap57](https://cloud.githubusercontent.com/assets/11802171/23332094/249b4738-fb41-11e6-9815-3493eeea2564.jpg)

There is no  gcc-4.6.3 subfolder under Rtools folder. Will try later.
Thank you Kyle for your unremitting support.

**Comment by kylebmetrum** [comment]
I would just re-install `Rtools`.  Get one that matches your `R` version number and never install a "non-frozen" version of `Rtools`.  Make sure you opt in to let the installer modify your `PATH`.

Here's the path on my Windows box; I have a couple of `Rtools` installs going on.  I think the most recent, `Rstudio`  (or `R`) installed into `RBuildTools`.  But you're on the right track: if no `gcc-4.6.3` directory, there will be an issue.  
```
> strsplit(Sys.getenv("PATH"),';')
[[1]]
 [1] "C:\\R\\R-3.3.1\\bin\\x64"                                                  
 [2] "c:\\R\\R-3.3.1\\bin\\x64"                                                  
 [3] "C:\\RBuildTools\\3.3\\bin"                                                 
 [4] "C:\\RBuildTools\\3.3\\gcc-4.6.3\\bin"                                      
 [5] "c:\\Rtools\\bin"                                                           
 [6] "c:\\Rtools\\gcc-4.6.3\\bin"  
```

**Comment by sibojan** [comment]
I see. Learn a lot overnight.
Will keep you update once I get a successful run.
I think that this is a common limitation for all the R packages depedent on
other compliers/packages.

**Comment by sibojan** [comment]
When I installed Rtools 3.4 yesterday night,  Rtools should have detected
my R version 3.0 and warned me of potential compatibility issues.   It is
kind of counter-intuitive that  Rtools is not backward compatible.

**Comment by kylebmetrum** [comment]
Yeah ... a lot of windows users encounter this issue.  Sometimes I'm surprised this can't be automated better by now.  But I also realize how much goes into picking the toolchain and making sure everything works together.  Once you get around the PATH issue, the system that R has put together for building shared objects is pretty amazing.  Thankfully, it's a hurdle that you get over once and don't have to bother with until you get a new computer.

Keep us posted.  I'm not a windows user, but always trying to learn where the problems are so we can better advise our users.

**Comment by sibojan** [comment]
Finally got it running. It seems that it is necessary to reboot or log out/in your computer after installing the Rtools.  Would like to see more complete examples, particularly differential equations based examples. With them in hands, we can do a quick simulation by modifying the template.  For example, a two compartment model sample code.

**Comment by sibojan** [comment]
I advise that the package installation process add a test run itself.

**Comment by kylebmetrum** [comment]
You can find more ODE models in the internal library: 
http://mrgsolve.github.io/2017/02/23/access-models-in-the-internal-library/

So ...
```r
mod <- mread("irm3", modlib())

see(mod)
mrgsolve:::code(mod)
```

**Comment by kylebmetrum** [comment]
> I advise that the package installation process add a test run itself.

Not sure what this means.

**Comment by sibojan** [comment]
Hi Kyle,

I mean:
Once the package is downloaded and installed successfully, why not to make it run a sample model automatically to make sure everything is in place?

 If it is not running, give the end user some suggestions on how to fix it.

**Comment by kylebmetrum** [comment]
I don't think there is really a mechanism for running something like that automatically.  We give lots of suggestions for how to fix things.  We also [encourage people to ask questions](https://github.com/metrumresearchgroup/mrgsolve#ask-a-question) and do our best to capture what we learn somewhere on the github site.

We have install instructions and advice here: 
https://github.com/metrumresearchgroup/mrgsolve/wiki/mrgsolve-Installation

Compiler info here:
https://github.com/metrumresearchgroup/mrgsolve/wiki/compilers-and-mrgsolve

with compiler test code here:
https://github.com/metrumresearchgroup/mrgsolve/wiki/compilers-and-mrgsolve#test-your-compilers

and some Windows-specific stuff here:
https://github.com/metrumresearchgroup/mrgsolve/wiki/Windows-issues

**Comment by sibojan** [comment]
I see. thanks.

**Comment by sibojan** [comment]
One more question:  Is it possible to convert  the formal class mrgsims type output object to a simple dataframe?  So that, other generic tools, e.g. ggplot can be used to plot the result.

**Comment by kylebmetrum** [comment]
Yes:
https://github.com/metrumresearchgroup/mrgsolve/wiki/howdoi#coerce-output-to-different-r-objects

That's in a [wiki page that I wrote a long time ago](https://github.com/metrumresearchgroup/mrgsolve/wiki/howdoi) that I need to transfer to `mrgsolve.github.io`.  IMO still pretty good showing how to start out.

If you want to dig into the model object:
```r
mod <- mrgsolve:::house()
 
# there is a lot of stuff here
x <- as.list(mod)
names(x)
str(x)

# More frequently, you want to just dig into the parameters 
as.list(param(mod))

# or better yet
mod$CL
```

**Comment by kylebmetrum** [comment]
More stuff on working with output:
http://mrgsolve.github.io/user_guide/simulated-output.html#coersion-methods

I do this sort of thing a lot:
http://mrgsolve.github.io/user_guide/simulated-output.html#methods-for-dplyr-verbs

Once you pipe to `filter` or `group_by` or `mutate` or something like that, you are out of `mrgsolve` land .... the data is just a `tibble` and you can do as you please.  

But it's a good question ... most of the time in the documented examples, I plot with the plot method for `mrgsims` because it is convenient.  In project work I almost always coerce to `data.frame` or `tibble` and plot / summarize as you suggest.

**Comment by sibojan** [comment]
Thank you for your advice.   It might be too early to say this, but a pdf manual with all those information complied into one place would be very handy. Apparently, pdf has its own limitations as well.  I understand that web page is more convenient to be updated than pdf.
