### ISSUE TITLE
Re-install compilers every time start R

### ISSUE THREAD

**Issue by WangdaZ** [metrumresearchgroup/mrgsolve#216]
Hello, 
I am a new user of mrgsolve and having a hard time keep the package running. With a company laptop, I don't have the admin right of my computer. The package was installed and working properly with code below:
~~~~~~~~~~~~~~~~~~~~~~~~~
library(installr)
.libPaths("C:\\R\\R-3.3.3\\library")
install.packages(c("Rcpp", "RcppArmadillo"), type="source")
library(mrgsolve)

path <- Sys.getenv("PATH")
path <- c("C:\\R\\R-3.3.3\\bin;C:\\R\\Rtools\\bin;C:\\R\\Rtools\\gcc-4.6.3\\bin", path)
path <- paste(path,collapse=";")
Sys.setenv(PATH=path)

code <- '
$PARAM CL = 1, VC = 30, KA = 1.3
$CMT GUT CENT
$ODE
dxdt_GUT = -KA*GUT;
dxdt_CENT = KA*GUT - (CL/VC)*CENT;
$TABLE
double CP = CENT/VC;
$CAPTURE CP
'
code
mod <- mcode("test", code)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
However, every time I restart R (rstudio), the mrgsovle package won't load with error:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> library(mrgsolve)
Error in library.dynam(lib, package, package.lib) : 
  DLL ‘Rcpp’ not found: maybe not installed for this architecture?
In addition: Warning message:
S3 methods ‘.DollarNames.C++Object’, ‘.DollarNames.Module’, ‘print.bytes’, ‘format.Rcpp_stack_trace’, ‘str.Rcpp_stack_trace’, ‘print.Rcpp_stack_trace’ were declared in NAMESPACE but not found 
Error: package or namespace load failed for ‘mrgsolve’
~~~~~~~~~~~~~~~~~~~

To me it seems the compilers are not working properly, I can solve this by re-installing the "Rcpp", "RcppArmadillo". However, I believe there is better solution for this. Can anyone provide any suggestions?

Thanks,
Wangda

**Comment by kylebmetrum** [comment]
The error is with the way `Rcpp` is installed or `R` not being able to find it.
```
Error in library.dynam(lib, package, package.lib) : 
  DLL ‘Rcpp’ not found: maybe not installed for this architecture?
```
I don't know exactly why this is blowing up, but this is what I would do:
1.  Re-install `Rcpp`, `RcppArmadillo`, and `mrgsolve` all from source; get `mrgsolve` from CRAN like you do for `Rcpp` and `RcppArmadillo`
1.  Whenever you re-start `R` set `.libPaths("C:\\R\\R-3.3.3\\library")` (that's assuming you installed everything in this location)
1.  Whenever you re-start `R` set your path again
1.  Did you really install `Rtools` here `C:\\R\\Rtools\\bin`?  I would at least double check this. 


Until you can restart `R` and get this to work
```
library(Rcpp)
```
don't bother with trying to load `mrgsolve`.  You need `Rcpp` in place and loadable to keep going.

Let me know what happens.

**Comment by WangdaZ** [comment]
Thanks for reply. I found the problem. As pointed out above #4. 
I did install the Rtools under the C:\R\ and that is the reason the compilers not working. It seems specify the paths did orient R to find compiler.
I installed another Rtools directly under C:\ and it solved the problem. 

~~~~~~~~~~~~~~~~~~~~~~~~~~~
.libPaths("C:\\R\\R-3.3.3\\library")
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
is still needed!

Thanks,
Wangda

**Comment by kylebmetrum** [comment]
Yeah ... you might always need to run that to point to the right package location.  

You should be able to put a file called `.Rprofile` in your `HOME` directory (see `Sys.getenv("HOME")`.  You put `R` code in that file and it gets run once every time you restart `R`.  You can put the `.libPaths()` stuff in there and it will be automatically run whenever you start `R`.   That is what I do ... It makes it a little more convenient.
