### ISSUE TITLE
Setting F(n) to 0 causes zero divide for infusion.

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#22]

**Comment by kylebmetrum** [comment]
F(n) must now have a positive value.

**Comment by vjd** [comment]
So there is no way to use F to shut off a dose in a cmpt. Is that correct?

**Comment by kylebmetrum** [comment]
Good point .... I think I figured out where the issue was with zero bioav.  It will be possible to say `F_CENT = 0;`  But (for now) there will be an error if `F_CMT` is zero and `ss=1`.

**Comment by vjd** [comment]
ok!
