### ISSUE TITLE
[F] @required in $PARAM

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/mrgsolve#220]
I'd like to propose the inclusion of `@required` as a macro to be included in a param block.

Though there are ways of 'faking' this by setting default values that do things like cause crashes (lol), there are times where we must be assured that the user is manually setting the parameter value.

A case in point - I was recently auditing a project in which the user was attempting to simulate the impact of changes in a couple different parameters under different dosing scenarios. During the setup process, an improper select statement caused one of the parameters to be dropped from the dataset that would be input to `data_set`. As there was a default value, mrgsolve obviously did not complain.

I consider such bugs to be by far the most dangerous and difficult to track down, hence, this would allow in-built capacity to force certain params to be provided each time. 

The other option I thought of was a set of validation functions that can allow more ad-hoc validation criteria - eg

```R
# ... create model above
model %>%
   data_set(validate_data(df, required = c("CL", "F_GUT"))) %>%
   mrgsim()
```

However, while such validators could provide checks for many more scenarios specific to a users analysis (and out of scope of even mrgsolve itself), these functions still do not securely protect at the model level, and would require more conscientious use.

**Comment by dpastoor** [comment]
To provide a 'test' mode, the `@required`  could also be overridden in mrgsim, as a named parameter

```R
model %>% 
mrgsim(.required = FALSE)
```

so a model could still be used flexibly, however the user would have to be very specific in order to override.

**Comment by kylebmetrum** [comment]
Thanks for report and suggestion.  I agree this is an issue and I will provide some functions to help with this.  A couple of thoughts:

1. A single requirement setting probably isn't enough since it could relate to parameter updates as well as parameters on a `data_set` and or parameters on and `idata_set`
1. I don't really see this as a property of the model.  I see the model as open by default (this is already the design) and restrictions established and enforced at simulation time.  I just rarely use a model with one specific, restrictive update pattern.  I would guess that most of the time you would end up having to force a parameter somewhere just to keep the parameter police happy.
1.  I suspect that having some audit of data input wrt parameters at run time would actually be clearer and more explicit in the end too.  
1.  I like the validator approach better too because I think that when the simulation gets big and complicated, there would probably be a chance to validate once up-front before the simulation gets fired off ... rather than having it be a part of the simulation sequence ... happening every time.

I'm working on a project now where I could do some validation.  I'll work out some code and bring into dev branch.

**Comment by dpastoor** [comment]
GeneralIy I agree, and for "built for purpose" models in a given project this makes sense. But if we consider a model almost as a 'function' that may be built for the purpose of others to consume, there are cases for sensible defaults, and cases where a model might 'only' make sense when provided non-zero value. 

That said, I definitely won't lose sleep over not having this functionality, as the external validation functions are a more extensible and powerful abstraction anyway. I guess the next question would be - should such a functionality be in the core package. This seems like a option ripe for a second package `mrgvalidate` or something.

**Comment by kylebmetrum** [comment]
> Though there are ways of 'faking' this by setting default values that do things like cause crashes (lol), there are times where we must be assured that the user is manually setting the parameter value.

I'm all for the validation functions ... but this isn't a bad idea and could be cheap to implement.  

It doesn't have to be as severe as a crash;  you can set a parameter to `NA` that would make sure the results are nonsense but avoiding crash.  I think the way the parser works, you'd have to set the parameter to `as.numeric(NA)` ... but we could have `.na() <- function() as.numeric(NA)` or whatever.

We could have an argument to `mread` that sets one or many or all parameters to `NA` and either let it return gibberish if the parameters don't get updated. 

Or if you were depending on some value in the parameter list that you want to be updated, `mrgsim` could stop if it finds missing values in the parameter list.

**Comment by dpastoor** [comment]
Yeah thats in line with what I was thinking. Just something simple, but 'enough' that you can have some control over model execution before needing to start reaching for actual validation functions. An NA/NULL value seems like a reasonable flag.

Regarding parsing, without having looked at the code of what you're doing, you could either what you said or just do a replace on na for the actual `NA_real_` "typed" value. 

I likewise have a project I'm working on, as well as one that finished up that definitely needed some extra care, so I can dump some validator ideas/prototype implemenations as I flesh them out.

**Comment by kylebmetrum** [comment]
`NA_real_` worked; I didn't know about it.  

This is basically what is happening:

```
x <- eval(parse(text="list(A=NA,B=1,C=NA_real_)"))
```

And the result is:

```
str(x)
List of 3
 $ A: logi NA
 $ B: num 1
 $ C: num NA
```

and `mrgsolve` chokes on this:

```
is.numeric(x$A)
[1] FALSE
```

**Comment by kylebmetrum** [comment]
But I like the idea of sabotaging the parameters right after the model is loaded (or right before you simulate) so you wouldn't have to recode to get a model with defaults.

**Comment by kylebmetrum** [comment]
- `inventory` lets you compare names in an R object (data.frame, list) with parameter names
- Notification is made if not all parameter names are found in the object (default) or if any 
in a list of user-provided parameter names (`need` argument) are not found in the R object
- Added `need` arguments to `data_set` and `idata_set`; if `need` is provided, `inventory` is called and error is generated if all required parameters are found in `data`
- `need` can be specified as `@all` ... which gets expanded to `names(param(mod))`
- An error is generated if anything in `need` is not found in the parameter list; need to make this error message more informative
- Planning on adding a `need` argument with call to `inventory` for `param(mod, ...)` too

**Comment by kylebmetrum** [comment]
I'd like to make the messaging more elegant.  Wondering too about printing or returning vector of missing names.  Or anything that is safe and helpful and flexible.  

Also ... this solely reports on __parameters__ that are __not__ in the `R` object being inventoried.  So maybe `inventory` isn't a good name.  We could go wild with reporting here, but I don't see any reason at this point to do any more than this basic task.  

```r
> code <- '
+ $PARAM CL = 1 , V2 = 3, KA = 4, VM = 5
+ 
+'
> 
> 
> mod <- mcode_cache("tst", code)
Loading model from cache.
> 
> idat <- data_frame(CL=1,V2=3)
> 
> dat <- mutate(idat,ID=1,time=0,evid=1,cmt=0)
> 
> try(mod %>% data_set(dat, need="CL VM"))
Error : object is missing required parameters
- VM
> 
> try(mod %>% data_set(dat, need="@all"))
Error : object is missing required parameters
- KA
- VM
> 
> inventory(mod,dat)
object is missing these parameters
 - KA
 - VM

```

**Comment by kylebmetrum** [comment]
I copied the source code for this into my project at work.  Not that the implementation is perfect or anything, but I thought it was so helpful.  I just called `inventory(mod,object)` once I got the model loaded and the data set worked out.  Nice to have that check.
