### ISSUE TITLE
steady-state superpositioning

### ISSUE THREAD

**Issue by mhismail** [metrumresearchgroup/mrgsolve#221]
Hi,

I would like to simulate complex steady-state dosing regimen (ie. 10 mg in the morning, 20 mg at night). NONMEM equivalent would be to use SS=2. I have been simulating the two regimens separately and then adding them together since drug follows linear kineitcs but was wondering if mrgsolve can support this functionality.

**Comment by kylebmetrum** [comment]
Hi @mhismail  - 

Thanks for the question.

Short answer is no, that functionality is not currently available in `mrgsolve`.  But got that same request a couple of months ago; I know it's an issue.  

We do have some `R` functionality that would help you code that (`?ev_days` ... but I'm not totally sure that would handle what you are doing).  But either way, you'd have to simulate that out to steady state on your own.  

I'll see what I can do about getting some SS=2 equivalent implemented.  I think it would be very useful.

Kyle

**Comment by kylebmetrum** [comment]
Just to correct my last comment: 10 mg QAM/20 mg QPM wouldn't require `ev_days` ... you'd just make two events, one starting at 8 am for 10 mg and one at 8pm for 20 mg (or however you want to work that out) and repeat each Q24h.  `ev_days` is more for `MWF` dosing or something like that.

**Comment by mhismail** [comment]
Thanks for the quick reply and the suggestion. Will keep an eye out for a SS=2 equivalent in future versions.

**Comment by kylebmetrum** [comment]
No problem.  After some reading, I learned that I didn't really understand what `SS=2` was doing :).  Now I don't think it will be too hard to implement.  

Can you test something for me  this weekend if I can get it into the dev branch?

Also ... could you post a minimal chunk of `NONMEM` data set that includes `SS=2` record?


`viii.pdf page 476` 
> MEANING: Steady-State (SS) data item for PREDPP CONTEXT: $INPUT record and NONMEM data set
USAGE:
$INPUT ... SS ...
DISCUSSION:
SS labels PREDPP’s steady-state (SS) data item. The steady-state data item is optional. It can take one of three values in any event record.
0 indicates that the dose is not a steady state dose.
1 indicates that the dose is a steady state dose, and that the compartment amounts are to be reset to the steady-state amounts resulting from the given dose. Compartment amounts resulting from prior dose event records are "zeroed out," and infusions in progress or pending additional doses are cancelled. The system is not totally reset: the on/off status of the compartments remains as it was at the time of the prior event record (if any), and the value of time must be greater than or equal to its value on the prior event record (if any).
2 indicates that the dose is a steady state dose and that the compartment amounts are to be set to the sum of the steady-state amounts resulting from the given dose plus whatever those amounts would have been at the event time were the steady-state dose not given. I.e., letting t be the time on the event record, then the amounts in the compartments are updated to amounts valid for time t, and next, these amounts are added to the steady-state amounts. This is meaningful when kinetics are linear and the superposition principle holds.
3 indicates that the dose is a steady state dose. SS = 3 is identical to SS = 1 with one exception: with Steady State routines SS6 and SS9, the existing state vector (com- partment amounts and eta derivatives) is used as the initial estimate in the computa- tion of the steady-state amounts. The user supplies the initial estimate with some combination of prior event records, e.g., reset, transient dose, and other-type event records.
When the SS data item is used, one or more of the data items AMT, RATE, and II must be present in the event record to specify the steady state dosing pattern.

**Comment by mhismail** [comment]
Great, and yes would be happy to give it a test this weekend.

Here is a nonmem dataset chunk using SS=2:
#ID, TIME, AMT, SS, II, MDV, DV, CMT
1,0,10,1,24,1,0,1
1,12,20,2,24,1,0,1
1,18,0,0,0,0,32,2

**Comment by kylebmetrum** [comment]
Got it.  Thx.

**Comment by kylebmetrum** [comment]
@mhismail Could you look at this please? 

1. The dose record at time 0 just advances to 10 mg Q24h steady state
1. Then the system advances to 12 hour dose record with `ss=2`
1. The compartment amounts are cached, the system advances to 20 mg Q24h steady state, and the cached compartment amounts are added to that new steady state value prior to continuing
1. After that ... continue

I'm not sure what inputs should be checked etc ... but for now, I'd like to just get the basic functionality right.  Thanks in advance for any feedback or correction.

You can install with 

```r
remotes::install_github("metrumresearchgroup/mrgsolve", ref="ss")
```


Test code
=========

``` r
knitr::opts_chunk$set(comment='.')
```

``` r
library(mrgsolve)
library(dplyr)
library(magrittr)

mod <- mread("pk2cmt", modlib()) %>% param(VC=3, VP=100)
mod %<>% update(req="CENT",digits=5)
```

With `ss`
---------

``` r
e1 <- ev(amt=10, ii=24, addl=99, ss=1, time=0,  cmt=2)
e2 <- ev(amt=20, ii=24, addl=99, ss=2, time=12, cmt=2)


out <- 
  mod %>% 
  obsonly %>% 
  ev(c(e1,e2)) %>%
  mrgsim(end=2400, recsort=3)
```

### Head

``` r
filter(out, time %in% seq(0,2364,12)) %>% head(n=6)
```

    . # A tibble: 6 × 4
    .      ID  time   CENT     CP
    .   <dbl> <dbl>  <dbl>  <dbl>
    . 1     1     0 10.779 3.5931
    . 2     1    12 22.402 7.4675
    . 3     1    24 12.466 4.1555
    . 4     1    36 22.402 7.4675
    . 5     1    48 12.466 4.1555
    . 6     1    60 22.402 7.4675

### Tail

``` r
filter(out, time %in% seq(0,2364,12)) %>% tail(n=6)
```

    . # A tibble: 6 × 4
    .      ID  time   CENT     CP
    .   <dbl> <dbl>  <dbl>  <dbl>
    . 1     1  2304 12.466 4.1555
    . 2     1  2316 22.402 7.4675
    . 3     1  2328 12.466 4.1555
    . 4     1  2340 22.402 7.4675
    . 5     1  2352 12.466 4.1555
    . 6     1  2364 22.402 7.4675

Without any `ss`
----------------

``` r
e1 <- ev(amt=10, ii=24, addl=99, time=0,  cmt=2)
e2 <- ev(amt=20, ii=24, addl=99, time=12, cmt=2)

out <- 
  mod %>% 
  obsonly %>% 
  ev(c(e1,e2)) %>%
  mrgsim(end=2400, recsort=3)
```

### Head

``` r
filter(out, time %in% seq(0,2388,12)) %>% head(n=6)
```

    . # A tibble: 6 × 4
    .      ID  time   CENT     CP
    .   <dbl> <dbl>  <dbl>  <dbl>
    . 1     1     0 10.000 3.3333
    . 2     1    12 20.123 6.7077
    . 3     1    24 10.360 3.4534
    . 4     1    36 20.456 6.8187
    . 5     1    48 10.668 3.5560
    . 6     1    60 20.740 6.9135

### Tail

``` r
filter(out, time %in% seq(0,2388,12)) %>% tail(n=6)
```

    . # A tibble: 6 × 4
    .      ID  time   CENT     CP
    .   <dbl> <dbl>  <dbl>  <dbl>
    . 1     1  2328 12.466 4.1555
    . 2     1  2340 22.402 7.4675
    . 3     1  2352 12.466 4.1555
    . 4     1  2364 22.402 7.4675
    . 5     1  2376 12.466 4.1555
    . 6     1  2388 22.402 7.4675

**Comment by mhismail** [comment]
@kylebmetrum This is great, thanks for implementing so quickly. I tried a few scenarios to check if ss=2 would function as expected and it checked out for all. 

# Test Code
```r 
library(mrgsolve)
library(dplyr)
library(magrittr)
```
## With `ss=2`
```r 
mod <- mread("pk2cmt", modlib()) %>% param(VC=3, VP=100)
mod %<>% update(req="CENT",digits=5)

e1 <- ev(amt=10, ii=24, addl=99, ss=1, time=0,  cmt=2)
e2 <- ev(amt=20, ii=24, addl=99, ss=2, time=12, cmt=2)


out <- 
  mod %>% 
  obsonly %>% 
  ev(e1+e2) %>%
  mrgsim(end=2400, recsort=3)

filter(out, time %in% seq(0,2364,12)) %>% head(n=6)
```
```
# A tibble: 6 × 4
ID  time   CENT     CP
<dbl> <dbl>  <dbl>  <dbl>
1     1     0 10.779 3.5931
2     1    12 22.402 7.4675
3     1    24 12.466 4.1555
4     1    36 22.402 7.4675
5     1    48 12.466 4.1555
6     1    60 22.402 7.4675
```

## Summing of multiple individual `SS=1` simulations
```r 
# Simulate 10mg (QAM) and 20 mg (QPM) seperately then combine -------------

out10 <-
  mod %>% 
  obsonly %>% 
  ev(e1) %>%
  mrgsim(end=2400, recsort=3)

filter(out10, time %in% seq(0,2364,12)) %>% head(n=6)


out20<-
  mod %>% 
  obsonly %>% 
  ev(e2) %>%
  mrgsim(end=2400, recsort=3)
filter(out20, time %in% seq(0,2364,12)) %>% head(n=6)


out10_20<- mutate(out10,CENT=CENT+out20$CENT,CP=CP+out20$CP)
filter(out10_20, time %in% seq(0,2364,12)) %>% head(n=6)
```

```
# A tibble: 6 × 4
ID  time     CENT      CP
<dbl> <dbl>    <dbl>   <dbl>
1     1     0 10.77900 3.59310
2     1    12 22.40251 7.46747
3     1    24 12.46600 4.15544
4     1    36 22.40251 7.46747
5     1    48 12.46600 4.15544
6     1    60 22.40251 7.46747
```

# Try resetting steady state `ss=1` after using `ss=2`
```r 
# Try resetting system (SS=1) and check output ----------------------------
e1 <- ev(amt=10, ii=24, addl=0, ss=1, time=0,  cmt=2)
e2 <- ev(amt=20, ii=24, addl=0, ss=2, time=12, cmt=2)
e3 <- ev(amt=10, ii=24, addl=0, ss=1, time=24, cmt=2)


out <- 
  mod %>% 
  obsonly %>% 
  ev(e1+e2+e3) %>%
  mrgsim(end=2400, recsort=3)

filter(out, time %in% seq(0,2364,12)) %>% head(n=6)
```
```
# A tibble: 6 × 4
ID  time     CENT      CP
<dbl> <dbl>    <dbl>   <dbl>
1     1     0 10.77900 3.59310
2     1    12 22.40200 7.46750
3     1    24 10.77900 3.59310
4     1    36  0.84351 0.28117
5     1    48  0.77944 0.25981
6     1    60  0.72027 0.24009

#CMT resets as expected
```
# Try adding a third daily dose to regimen
```r 
# Add a third daily dose time (20 mg midway between morning and ev --------

e1 <- ev(amt=10, ii=24, addl=99, ss=1, time=0,  cmt=2)
e2 <- ev(amt=20, ii=24, addl=99, ss=2, time=12, cmt=2)
e3 <- ev(amt=20, ii=24, addl=99, ss=2, time=6, cmt=2)


out <- 
  mod %>% 
  obsonly %>% 
  ev(e1+e2+e3) %>%
  mrgsim(end=2400, recsort=3)

filter(out, time %in% seq(0,2364,6)) %>% head(n=12)
```
```
# A tibble: 12 × 4
ID  time    CENT     CP
<dbl> <dbl>   <dbl>  <dbl>
1      1     0 10.7790 3.5931
2      1     6 22.4590 7.4863
3      1    12 24.2020 8.0674
4      1    18  4.2978 1.4326
5      1    24 14.0880 4.6960
6      1    30 24.0800 8.0268
7      1    36 24.2020 8.0674
8      1    42  4.2978 1.4326
9      1    48 14.0880 4.6960
10     1    54 24.0800 8.0268
11     1    60 24.2020 8.0674
12     1    66  4.2978 1.4326
```
```r
#Test against simulating each regimen seperately and summing
out1 <- 
  mod %>% 
  obsonly %>% 
  ev(e1) %>%
  mrgsim(end=2400, recsort=3)

out2 <- 
  mod %>% 
  obsonly %>% 
  ev(e2) %>%
  mrgsim(end=2400, recsort=3)

out3 <- 
  mod %>% 
  obsonly %>% 
  ev(e3) %>%
  mrgsim(end=2400, recsort=3)

out_all <- mutate(out1, CENT=CENT+out2$CENT+out3$CENT, CP=CP+out2$CP+out3$CP)
filter(out_all, time %in% seq(0,2364,6)) %>% head(n=12)
```
```
ID  time     CENT      CP
<dbl> <dbl>    <dbl>   <dbl>
1      1     0 10.77900 3.59310
2      1     6 22.45898 7.48629
3      1    12 24.20251 8.06745
4      1    18  4.29781 1.43259
5      1    24 14.08760 4.69598
6      1    30 24.08058 8.02683
7      1    36 24.20251 8.06745
8      1    42  4.29781 1.43259
9      1    48 14.08760 4.69598
10     1    54 24.08058 8.02683
11     1    60 24.20251 8.06745
12     1    66  4.29781 1.43259
#Results as expected
```
# Try adding single bolus dose on top of SS regimen

```
# Try adding single bolus dose (SS=0) midway between QAM and QPM dose --------
e1 <- ev(amt=10, ii=24, addl=99, ss=1, time=0,  cmt=2)
e2 <- ev(amt=20, ii=24, addl=99, ss=2, time=12, cmt=2)
e3 <- ev(amt=40, addl=0, ss=0, time=30, cmt=2)


out <- 
  mod %>% 
  obsonly %>% 
  ev(e1+e2+e3) %>%
  mrgsim(end=2400, recsort=3)

filter(out, time %in% seq(0,2364,12)) %>% head(n=6)
```
```
# A tibble: 6 × 4
ID  time   CENT     CP
<dbl> <dbl>  <dbl>  <dbl>
1     1     0 10.779 3.5931
2     1    12 22.402 7.4675
3     1    24 12.466 4.1555
4     1    36 23.005 7.6684
5     1    48 12.940 4.3134
6     1    60 22.840 7.6134
```
```
#Test against simulating each regimen seperately and summing
out1 <- 
  mod %>% 
  obsonly %>% 
  ev(e1) %>%
  mrgsim(end=2400, recsort=3)

out2 <- 
  mod %>% 
  obsonly %>% 
  ev(e2) %>%
  mrgsim(end=2400, recsort=3)

out3 <- 
  mod %>% 
  obsonly %>% 
  ev(e3) %>%
  mrgsim(end=2400, recsort=3)

out_all <- mutate(out1, CENT=CENT+out2$CENT+out3$CENT, CP=CP+out2$CP+out3$CP)
filter(out_all, time %in% seq(0,2364,12)) %>% head(n=6)
```
```
# A tibble: 6 × 4
ID  time     CENT      CP
<dbl> <dbl>    <dbl>   <dbl>
1     1     0 10.77900 3.59310
2     1    12 22.40251 7.46747
3     1    24 12.46600 4.15544
4     1    36 23.00535 7.66842
5     1    48 12.93967 4.31333
6     1    60 22.84023 7.61338

#All good
```

**Comment by kylebmetrum** [comment]
@mhismail Thanks for your help getting this going and especially for the rigorous tests posted last night to confirm the behavior.  Implementing this was pretty easy overall and my basic tests were ok.  But it's just a **huge** help to get all of these test and confirmation under different scenarios.  Big thanks!

This is now in the master branch so at least people who want it can get to it.  I'll make a separate todo to update the userguide and whatever else needs to get documented.  Maybe a blog post. And unit tests.

**Comment by mhismail** [comment]
@kylebmetrum Of course and thanks again for the quick response. Will let you know if I run into any bugs.
