### ISSUE TITLE
Negative concentrations with PROP error 

### ISSUE THREAD

**Issue by aalhadab** [metrumresearchgroup/mrgsolve#237]
I am simulating plasma concentrations with proportional residual error and I always get negative concentrations. Why is it that?

Here is my example 

code <- '
$PARAM
TVCL     = 15.7,
TVV2     = 150,
Q           = 87.7,
V3          = 592,
KA          = 0.777,
ALAG      = 0.536,
F             = 1.08,
FE           = 0.438,
OCC       = 0

$SET end=168, add=c(1,2,4,6,8,12,24,48,72,96,12,144,168)

$CMT GUT CENT PERI URINE 

$MAIN 
double  CL = TVCL * exp(ETA(1));
double  V2 = TVV2 * exp(ETA(2));

ALAG_GUT  = ALAG;
F_GUT     = 1;
if(OCC==1) F_GUT = F;

$ODE
dxdt_GUT     = -KA*GUT; 
dxdt_CENT    =  KA*GUT + Q/V3*PERI - Q/V2*CENT - CL/V2*CENT; 
dxdt_PERI    =  Q/V2*CENT - Q/V3*PERI;
dxdt_URINE   =  FE*CL/V2*CENT;

$OMEGA 
0.0151  0.0803

$SIGMA
0.0855

$TABLE
capture IPRED = CENT/V2;
double  CP    = IPRED + IPRED*EPS(1);

$CAPTURE CP
'
mod <- mcode("mod", code = code)

mod %>% ev(ID=1:100, amt=0.5) %>% mrgsim() %>% plot(log(CP)~time)

Warning message:
In log(CP) : NaNs produced

**Comment by kylebmetrum** [comment]
Some records had `EPS(1)` less than `-1`.  `CP` will be negative.  Use exponential error model or resimulate `EPS(1)` with `simeps()` to keep concentrations positive.  Or truncate some other way. 

```r
filter(out, EPS1 < -1)  %>% select(-GUT,-PERI,-URINE) %>% as.data.frame
  ID time        CENT            CP        IPRED      EPS1
1 29  145 0.002745241 -1.823884e-06 2.976411e-05 -1.061278
2 70   16 0.061711148 -4.012415e-05 4.154060e-04 -1.096590
3 84   98 0.014078550 -7.630040e-06 9.238314e-05 -1.082591
4 90  103 0.008978312 -7.342671e-07 6.256751e-05 -1.011736
```

**Comment by aalhadab** [comment]
Thanks Kyle
