### ISSUE TITLE
[F] Dynamic dosing in $MAIN

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#240]
I was thinking something simple like

```c
$MAIN
self.dose = 100;
```
 And if you have a dosing record with, say, `evid=27`, `mrgsolve` would just plug in that dose.

If you wanted to modify multiple doses I'd want to put the onus back on the model (I think this would work):
```c
$MAIN
if(self.cmt==1) {
  self.dose = 100;
}
if(self.cmt==2) {
  self.dose = 200;
}

```
Otherwise we'd have to pass another array into those functions and it doesn't seem worth it.  I don't think having one dose variable is an issue since it's totally dynamic.

or 
```c
$MAIN
if(self.cmt==1) {
  self.dose = 1.5*self.amt;
}
```
@dpastoor

**Comment by kylebmetrum** [comment]
@dinkorekic re-posted the original question in #241

**Comment by kylebmetrum** [comment]
@dpastoor Now that `Fn` is going back to being completely dynamic, I don't see why we'd need this.  While it might be more intuitive to just set the dose rather than the scaling the dose in the data set, I don't think it will be less work (you still need to set up the data set in a certain way and you still need to set something in the model control file).

**Comment by dpastoor** [comment]
yes, and to some extent the 'intuitiveness' of directly setting the dose may be offset by trying to explain to people the concept of `self` and its property accessors.

**Comment by kylebmetrum** [comment]
I have faith that people can understand it if we give them example.  There is already a bunch of stuff that you can only access through `self`.

**Comment by kylebmetrum** [comment]
Moving the conversation with myself here.  

# Bolus
- Bolus doses are easy: just read `F[n]` at the time the bolus is administered.  Nothing special needs to be done there.

# Infusion
- This is harder because, for doses scheduled out into the future, we don't know the duration of the infusion until the time the infusion starts. 
- No problem on the initial dose ... we start the infusion and schedule the end of the infusion whenever we come across that record in the data set (we already do that)
- The big change now is that we need to hold off on scheduling the end of the infusion until the time of the dose. 
- This will mean __a lot__ more pushing onto the record stack (or inserting) and sorting.  That must have been what we were doing before (but it's been a while).  Now, it must be more efficient b/c we schedule the start of every infusion as well as the end at one time and re-sort everything.
