### ISSUE TITLE
NEWIND behavior

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/mrgsolve#242]
From offline discussion, NEWIND == 1 is definitely the first record of each subject, per nonmem, however in mrgsolve for the first subject, this does not hold, therefore to get the behavior for all subjects must do

`if (NEWIND <= 1) ...`

In the nonmem manual it states:

```diff
NEWIND
    Same as the NEWIND argument passed by NONMEM to PREDPP.
    NEWIND=0:  First  record  of  the data set.  THETA value may differ
    from value at last call with this record.
    NEWIND=1: First record of the data set, THETA value does not differ
    from  value at last call with this record, and PRED is nonrecursive
+    (see I_REC), or,
+    First record of a subsequent individual record.
    NEWIND=2: Subsequent data record of an individual record.
```

I take this to mean that NEWIND == 1 should be applicable to all first records of any subject, even the first one?

Therefore 

if (NEWIND == 1) should be sufficient to initialize something at the beginning of each individual?

**Comment by kylebmetrum** [comment]
### NEW INDIVIDUAL INDICATOR: NEWIND
```
NEWIND
NEWIND is of interest only when ICALL=2, 4, 5, or 6. It is the same as the NEWIND argument passed by NONMEM to PREDPP (with the first data record of the current event record). Values are:
NEWIND=0: First event record of the data set.
NEWIND=1: First event record of the data set, THETA value does not differ from value at 
last call with this record, and PRED is nonrecursive (See Recur- sive PRED Indicator), or,
NEWIND=1: First event record of a subsequent individual record.
NEWIND=2: Subsequent event record of an individual record.
Location prior to NONMEM 7: procm1
```

There isn't really a concept of "THETA value does not differ from ... "  or "PRED is nonrecursive" in `mrgsolve` so I tend to cross that off the list.  

```
NEWIND=0: First event record of the data set.
NEWIND=1: First event record of a subsequent individual record.
NEWIND=2: Subsequent event record of an individual record.
```

 `NEWIND.LE.1` idiom is pretty standard in NONMEM code.
