### ISSUE TITLE
Error with preclean call

### ISSUE THREAD

**Issue by reejbee** [metrumresearchgroup/mrgsolve#252]
When building a model in a windows environment, the  mread call “preclean” causes this this error : “**modelname**-mread-source-win.def’: No such file or directory

**Comment by kylebmetrum** [comment]
@reejbee Can you reproduce the error with this code?

```r
foo <- mread("pk1cmt", modlib(), preclean=TRUE)
```

**Comment by reejbee** [comment]
@kylebmetrum, No. This works. 
It's the combination of soloc="../so", preclean=T that throws that win.def error. Sorry, this wasn't immediately clear to be before. 
foo <- mread("pk1cmt", modlib(), preclean=TRUE, soloc="../so") causes the same error.

**Comment by kylebmetrum** [comment]
Ok.  All of the formulations are working for me so far.  I'll keep looking for other explanations.

Can you share the `devtools::session_info()`?

```r
Packages -----------------------------------------------------------------------------------------
 package       * version     date       source                                       
 assertthat      0.1         2013-12-06 CRAN (R 3.3.1)                               
 bindr           0.1         2016-11-13 CRAN (R 3.4.1)                               
 bindrcpp      * 0.2         2017-06-17 CRAN (R 3.4.1)                               
 curl            2.2         2016-10-21 CRAN (R 3.3.1)                               
 devtools      * 1.12.0      2016-06-24 CRAN (R 3.3.1)                               
 digest          0.6.10      2016-08-02 CRAN (R 3.3.1)                               
 dplyr           0.7.2       2017-07-20 CRAN (R 3.3.2)                               
 git2r           0.15.0      2016-05-11 CRAN (R 3.3.1)                               
 glue            1.1.1       2017-06-21 CRAN (R 3.4.1)                               
 httr            1.2.1       2016-07-03 CRAN (R 3.3.1)                               
 lazyeval        0.2.0       2016-06-12 CRAN (R 3.3.1)                               
 magrittr        1.5         2014-11-22 CRAN (R 3.3.1)                               
 memoise         1.0.0       2016-01-29 CRAN (R 3.3.1)                               
 mrgsolve      * 0.8.6.9000  2017-07-26 Github (metrumresearchgroup/mrgsolve@3303bc8)
 pkgconfig       2.0.1       2017-03-21 CRAN (R 3.4.1)                               
 R6              2.2.0       2016-10-05 CRAN (R 3.3.1)                               
 Rcpp            0.12.12     2017-07-15 CRAN (R 3.3.2)                               
 RcppArmadillo   0.7.900.2.0 2017-06-04 CRAN (R 3.3.2)                               
 rlang           0.1.1       2017-05-18 CRAN (R 3.3.2)                               
 rstudioapi      0.6         2016-06-27 CRAN (R 3.3.1)                               
 tibble          1.3.3       2017-05-28 CRAN (R 3.4.1)                               
 withr           1.0.2       2016-06-20 CRAN (R 3.3.1)                          
```

**Comment by kylebmetrum** [comment]
@reejbee Can you also post the exact error text when you compile `pk1cmt` from `modlib()`?

**Comment by reejbee** [comment]
sessionInfo()

R version 3.3.2 (2016-10-31)
Packages ----------------------------------------------------------------------------------------------
 package         * version     date       source                                 
 assertthat        0.1         2013-12-06 CRAN (R 3.3.1)                         
 backports         1.0.4       2016-10-24 CRAN (R 3.3.2)                         
 codetools         0.2-15      2016-10-05 CRAN (R 3.3.1)                         
 colorspace        1.3-1       2016-11-18 CRAN (R 3.3.2)                         
 crayon            1.3.2       2016-06-28 CRAN (R 3.3.1)                         
 DBI               0.5-1       2016-09-10 CRAN (R 3.3.1)                         
 devtools          1.12.0      2016-06-24 CRAN (R 3.3.1)                         
 digest            0.6.12      2017-01-27 CRAN (R 3.3.3)                         
 dplyr             0.5.0       2016-06-24 CRAN (R 3.3.1)                         
 DT                0.2         2016-08-09 CRAN (R 3.3.1)                         
 evaluate          0.10        2016-10-11 CRAN (R 3.3.1)                         
 fda               2.4.4       2014-12-16 CRAN (R 3.3.3)                         
 gamlss.dist       5.0-2       2017-06-09 CRAN (R 3.3.3)                         
 ggplot2         * 2.2.1       2016-12-30 CRAN (R 3.3.3)                         
 gistr             0.4.0       2017-04-20 CRAN (R 3.3.3)                         
 growthstandards   0.1.0       2017-07-24 Github (HBGDki/growthstandards@31e2f9a)
 gtable            0.2.0       2016-02-26 CRAN (R 3.3.1)                         
 hbgd            * 0.3.8       2017-07-24 Github (HBGDki/hbgd@a2836b5)           
 hexbin            1.27.1      2015-08-19 CRAN (R 3.3.1)                         
 htmltools         0.3.6       2017-04-28 CRAN (R 3.3.3)                         
 htmlwidgets       0.9         2017-07-10 CRAN (R 3.3.3)                         
 httpuv            1.3.3       2015-08-04 CRAN (R 3.3.1)                         
 httr              1.2.1       2016-07-03 CRAN (R 3.3.1)                         
 jsonlite          1.5         2017-06-01 CRAN (R 3.3.3)                         
 knitr             1.16        2017-05-18 CRAN (R 3.3.2)                         
 labeling        * 0.3         2014-08-23 CRAN (R 3.3.1)                         
 lattice         * 0.20-34     2016-09-06 CRAN (R 3.3.1)                         
 lazyeval          0.2.0       2016-06-12 CRAN (R 3.3.1)                         
 lme4              1.1-13      2017-04-19 CRAN (R 3.3.3)                         
 magrittr        * 1.5         2014-11-22 CRAN (R 3.3.1)                         
 maps              3.2.0       2017-06-08 CRAN (R 3.3.3)                         
 MASS              7.3-45      2016-04-21 CRAN (R 3.3.1)                         
 Matrix            1.2-7.1     2016-09-01 CRAN (R 3.3.1)                         
 memoise           1.0.0       2016-01-29 CRAN (R 3.3.1)                         
 mgcv              1.8-16      2016-11-07 CRAN (R 3.3.2)                         
 mime              0.5         2016-07-07 CRAN (R 3.3.1)                         
 minqa             1.2.4       2014-10-09 CRAN (R 3.3.1)                         
 mrgsolve        * 0.8.6       2017-03-16 CRAN (R 3.3.3)                         
 munsell           0.4.3       2016-02-13 CRAN (R 3.3.1)                         
 nlme              3.1-128     2016-05-10 CRAN (R 3.3.1)                         
 nloptr            1.0.4       2014-08-04 CRAN (R 3.3.1)                         
 numDeriv          2016.8-1    2016-08-27 CRAN (R 3.3.2)                         
 plyr              1.8.4       2016-06-08 CRAN (R 3.3.1)                         
 prettyunits       1.0.2       2015-07-13 CRAN (R 3.3.2)                         
 progress          1.1.2       2016-12-14 CRAN (R 3.3.3)                         
 pryr              0.1.2       2015-06-20 CRAN (R 3.3.3)                         
 purrrlyr          0.0.2       2017-05-13 CRAN (R 3.3.3)                         
 R6                2.2.0       2016-10-05 CRAN (R 3.3.1)                         
 rbokeh            0.5.1       2017-07-24 Github (hafen/rbokeh@78e38a4)          
 Rcpp              0.12.8      2016-11-17 CRAN (R 3.3.2)                         
 RcppArmadillo     0.7.500.0.0 2016-10-22 CRAN (R 3.3.1)                         
 rmarkdown         1.5         2017-04-26 CRAN (R 3.3.3)                         
 rootSolve       * 1.7         2016-12-06 CRAN (R 3.3.2)                         
 rprojroot         1.1         2016-10-29 CRAN (R 3.3.2)                         
 rsconnect         0.8         2017-05-08 CRAN (R 3.3.3)                         
 scales            0.4.1       2016-11-09 CRAN (R 3.3.2)                         
 shiny           * 1.0.3       2017-04-26 CRAN (R 3.3.3)                         
 shinyAce        * 0.2.1       2016-03-14 CRAN (R 3.3.3)                         
 shinydashboard  * 0.6.0       2017-05-18 CRAN (R 3.3.3)                         
 sitar             1.0.9       2017-01-09 CRAN (R 3.3.3)                         
 stringdist        0.9.4.4     2016-12-16 CRAN (R 3.3.3)                         
 stringi           1.1.2       2016-10-01 CRAN (R 3.3.1)                         
 stringr           1.2.0       2017-02-18 CRAN (R 3.3.3)                         
 tibble            1.2         2016-08-26 CRAN (R 3.3.1)                         
 tidyr             0.6.3       2017-05-15 CRAN (R 3.3.3)                         
 withr             1.0.2       2016-06-20 CRAN (R 3.3.1)                         
 xtable            1.8-2       2016-02-05 CRAN (R 3.3.3)

Error: 

foo <- mread("pk1cmt", modlib(), preclean=TRUE, soloc="../so")
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'pk1cmt-mread-source-win.def': No such file or directory

**Comment by kylebmetrum** [comment]
@reejbee Thanks.  I can't reproduce after rolling back to version `0.8.6`.  I happen to be using `R 3.3.2` as well, so that is matching.  

I'll keep this open for a bit to see if we can get it reproduced on another platform.

**Comment by kylebmetrum** [comment]
@dpastoor Could you try this out for us if you're still on Windows?

```r
foo <- mread("pk1cmt", modlib(), preclean=TRUE, soloc="../so")
```

**Comment by dpastoor** [comment]
seems fine on my end, with the CRAN version

```
> foo <- mread("pk1cmt", modlib(), preclean=TRUE, soloc=".") # "../so" gives a soloc dir must exist error
Compiling pk1cmt ... done.
> packageVersion("mrgsolve")
[1] ‘0.8.6’
```

@reejbee after the error, can you please call `traceback()` so we can see a stack trace



```
> devtools::session_info()
Session info ------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 system   x86_64, mingw32             
 ui       RStudio (1.1.313)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2017-07-26                  

Packages ----------------------------------------------------------------------------
 package       * version     date       source                            
 assertthat      0.2.0       2017-04-11 CRAN (R 3.4.0)                    
 backports       1.1.0       2017-05-22 CRAN (R 3.4.0)                    
 base          * 3.4.0       2017-04-21 local                             
 bindr           0.1         2016-11-13 CRAN (R 3.4.0)                    
 bindrcpp      * 0.2         2017-06-17 CRAN (R 3.4.0)                    
 compiler        3.4.0       2017-04-21 local                             
 datasets      * 3.4.0       2017-04-21 local                             
 devtools        1.13.2      2017-06-02 CRAN (R 3.4.0)                    
 digest          0.6.12      2017-01-27 CRAN (R 3.4.0)                    
 dplyr           0.7.1       2017-06-22 CRAN (R 3.4.0)                    
 evaluate        0.10.1      2017-06-24 CRAN (R 3.4.1)                    
 glue            1.1.1       2017-06-21 CRAN (R 3.4.0)                    
 graphics      * 3.4.0       2017-04-21 local                             
 grDevices     * 3.4.0       2017-04-21 local                             
 htmltools       0.3.6       2017-04-28 CRAN (R 3.4.0)                    
 knitr           1.16        2017-05-18 CRAN (R 3.4.0)                    
 lazyeval        0.2.0       2016-06-12 CRAN (R 3.4.0)                    
 magrittr        1.5         2014-11-22 CRAN (R 3.4.0)                    
 memoise         1.1.0       2017-04-21 CRAN (R 3.4.0)                    
 methods       * 3.4.0       2017-04-21 local                             
 mrgsolve      * 0.8.6       2017-03-16 CRAN (R 3.4.0)                    
 pkgconfig       2.0.1       2017-03-21 CRAN (R 3.4.0)                    
 R6              2.2.2       2017-06-17 CRAN (R 3.4.0)                    
 Rcpp            0.12.11     2017-05-22 CRAN (R 3.4.0)                    
 RcppArmadillo   0.7.900.2.0 2017-06-04 CRAN (R 3.4.0)                    
 rlang           0.1.1       2017-05-18 CRAN (R 3.4.1)                    
 rmarkdown       1.6         2017-06-17 Github (rstudio/rmarkdown@ca634d7)
 rprojroot       1.2         2017-01-16 CRAN (R 3.4.0)                    
 stats         * 3.4.0       2017-04-21 local                             
 stringi         1.1.5       2017-04-07 CRAN (R 3.4.0)                    
 stringr         1.2.0       2017-02-18 CRAN (R 3.4.0)                    
 tibble          1.3.3       2017-05-28 CRAN (R 3.4.0)                    
 tools           3.4.0       2017-04-21 local                             
 utils         * 3.4.0       2017-04-21 local                             
 withr           1.0.2       2016-06-20 CRAN (R 3.4.0)                    
 yaml            2.1.14      2016-11-12 CRAN (R 3.4.0)   
```

**Comment by reejbee** [comment]
@kylebmetrum Thanks for trying it out. I'll tell Mike to keep leaving out the preclean call for now.

**Comment by reejbee** [comment]
@dpastoor, @kylebmetrum 

> foo <- mread("pk1cmt", modlib(), preclean=TRUE, soloc="../so")
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'pk1cmt-mread-source-win.def': No such file or directory
> traceback()
4: file(file, ifelse(append, "a", "w"))
3: cat(file = win_def_name(x), c("EXPORTS", paste0(" ", funs(x))), 
       sep = "\n")
2: write_win_def(x)
1: mread("pk1cmt", modlib(), preclean = TRUE, soloc = "../so")

**Comment by kylebmetrum** [comment]
@reejbee Does Mike need to build the model in `../so`?  If he can, I would leave `soloc` set to default `tempdir()`.  Maybe that would still let him run with `preclean=TRUE` ?

Obviously, it doesn't address the original issue ... apparently where `mrgsolve` doesn't have permission(?) to write that `-win.def` file.  Can't figure out how `preclean` figures into that.  

I wonder if any of this is happening on a Windows share or something like that ...

**Comment by dpastoor** [comment]
Now I'm really perplexed - just tried with R 3.3.2

```
> library(mrgsolve)
> setwd("C:/Users/devin/Documents/")
> mread("pk1cmt", modlib(), preclean=T, soloc="../so")
Compiling pk1cmt ... done.


-------- mrgsolve model object (windows) --------
  Project: C:/Users/devin/Documents/R/win-library/3.3/mrgsolve/models
  source:        pk1cmt.cpp
  shared object: pk1cmt-so-30b410797eab

  compile date:
  Time:          start: 0 end: 24 delta: 1
  >              add: <none>
  >              tscale: 1

  Compartments:  EV1 CENT EV2 [3]
  Parameters:    CL VC KA1 KA2 VMAX KM [6]
  Omega:         0x0
  Sigma:         0x0

  Solver:        atol: 1e-08 rtol: 1e-08
  >              maxsteps: 2000 hmin: 0 hmax: 0

Warning message:
package 'bindrcpp' was built under R version 3.3.3
```

I think you're right @kylebmetrum that its a permissions issue of some sort, but can't figure out how that plays into the `write_win_def` call.

**Comment by reejbee** [comment]
@kylebmetrum I think as long as wherever the shiny app is being served up has permissions to build the model in whatever tempdir it sits in, I don't think leaving soloc=tempdir() would pose a problem. We're about to meet with the GHAP-Shiny people so I can ask them about permissions. 

It doesn't surprise me that this would be a permissions issue. I have similar issues on the GHAP platform (installing packages, ect) all the time.  

Thanks again both of you.
