### ISSUE TITLE
accessing CMT and AMT in control file

### ISSUE THREAD

**Issue by justinpenz** [metrumresearchgroup/mrgsolve#253]
I am implementing a flexible transit model, and dosing to multiple compartments.  I would like to implement something like `$MAIN if(EVID==1 && CMT == 2) TOD = TIME;`.  How do I call CMT? 

It would also be helpful to access AMT in $MAIN or $ODE. 

Thanks!

**Comment by kylebmetrum** [comment]
Please look here: http://mrgsolve.github.io/user_guide/model-specification.html#variables-and-macros

Only very limited selection of data are accessible in `$ODE` (parameters, cmt amounts, initial conditions, and ... obviously ... global C++ variables).  So keep working in `$MAIN` for this.  If you do need to use in `$ODE` copy the values into variables:

```r
$MAIN
double amt = self.amt;

$ODE
// work with amt, not self.amt here
```

**Comment by justinpenz** [comment]
Thank you!
