### ISSUE TITLE
FORTRAN compiler verification (Windows 7)

### ISSUE THREAD

**Issue by JSC67** [metrumresearchgroup/mrgsolve#254]
From the output below, it looks as if there is a gfortran compiler but the test on https://github.com/metrumresearchgroup/mrgsolve/wiki/compilers-and-mrgsolve didn't work:

> fcode <- ' +       subroutine bar(n, x) + integer n + double precision x(n) + integer i + do 100 i = 1, n + x(i) = x(i) ** 2  + 100 continue + end + ' > cat(file="R_FORTRAN_Test.f", fcode) >  > system("R CMD SHLIB R_FORTRAN_Test.f") C:/RBuildTools/3.4/mingw_64/bin/gfortran      -O2  -mtune=core2 -c R_FORTRAN_Test.f -o R_FORTRAN_Test.o R_FORTRAN_Test.f:3.1:  integer n                                                                 1 Error: Non-numeric character in statement label at (1) R_FORTRAN_Test.f:3.1:  integer n                                                                 1 Error: Unclassifiable statement at (1) R_FORTRAN_Test.f:4.1:  double precision x(n)                                                     1 Error: Non-numeric character in statement label at (1) R_FORTRAN_Test.f:4.1:  double precision x(n)                                                     1 Error: Unclassifiable statement at (1) R_FORTRAN_Test.f:5.1:  integer i                                                                 1 Error: Non-numeric character in statement label at (1) R_FORTRAN_Test.f:5.1:  integer i                                                                 1 Error: Unclassifiable statement at (1) R_FORTRAN_Test.f:6.1:  do 100 i = 1, n                                                           1 Error: Non-numeric character in statement label at (1) R_FORTRAN_Test.f:6.1:  do 100 i = 1, n                                                           1 Error: Unclassifiable statement at (1) R_FORTRAN_Test.f:7.1:  x(i) = x(i) ** 2                                                          1 Error: Non-numeric character in statement label at (1) R_FORTRAN_Test.f:7.1:  x(i) = x(i) ** 2                                                          1 Error: Unclassifiable statement at (1) R_FORTRAN_Test.f:8.5:  100 continue                                                                  1 Error: Non-numeric character in statement label at (1) R_FORTRAN_Test.f:8.5:  100 continue                                                                  1 Error: Unclassifiable statement at (1) R_FORTRAN_Test.f:9.1:  end                                                                       1 Error: Non-numeric character in statement label at (1) R_FORTRAN_Test.f:9.1:  end                                                                       1 Error: Unclassifiable statement at (1) Error: Unexpected end of file in 'R_FORTRAN_Test.f' make: *** [R_FORTRAN_Test.o] Error 1 Warning message: running command 'make -f "C:/PROGRA~1/R/R-34~1.1/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-34~1.1/share/make/winshlib.mk" SHLIB="R_FORTRAN_Test.dll" SHLIB_LIBADD='$(FLIBS)' WIN=64 TCLBIN=64 OBJECTS="R_FORTRAN_Test.o"' had status 2  Warning message: running command 'R CMD SHLIB R_FORTRAN_Test.f' had status 1
--
 
> | >
>

**Comment by kylebmetrum** [comment]
Maybe the spacing got mixed up.  

There needs to be 6 spaces at the start of every line, except the `100  continue` line ...  the `c` in `continue` starts in column 7 and put the `100` in the first 3 columns.  

Example file attached.

[fcode.R.txt](https://github.com/metrumresearchgroup/mrgsolve/files/1174873/fcode.R.txt)

**Comment by JSC67** [comment]
Kyle, thank-you.  Apparently pasting the file text into the RStudio Console window causes the spaces to be removed.  I had to paste the lines in one at a time and then click the Home key and manually add the spaces back each time.  At the very end I used the Delete key since typing ' gave by default a pair of '.  The output is below (with line breaks inserted since pasting in the selected text got rid of them):


> fcode <- ' 
+       subroutine bar(n, x)
+       integer n
+       double precision x(n)
+       integer i 
+       do 100 i = 1, n 
+           x(i) = x(i) ** 2  
+   100 continue 
+       end + 
' > cat(file="R_FORTRAN_Test.f", fcode) 
> system("R CMD SHLIB R_FORTRAN_Test.f")
 C:/RBuildTools/3.4/mingw_64/bin/gfortran      -O2  -mtune=core2 -c R_FORTRAN_Test.f -o R_FORTRAN_Test.o C:/RBuildTools/3.4/mingw_64/bin/gcc -shared -s -static-libgcc -o R_FORTRAN_Test.dll tmp.def R_FORTRAN_Test.o -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -lgfortran -lm -lquadmath -LC:/PROGRA~1/R/R-34~1.1/bin/x64 -lR
--
 
>
