### ISSUE TITLE
?modelspec

### ISSUE THREAD

**Issue by JSC67** [metrumresearchgroup/mrgsolve#255]
https://github.com/metrumresearchgroup/mrgsolve/wiki/howdoi#about-the-model-specification-file says this:

About the model specification file

For more information, see ?modelspec. A brief overview is included below.

Well, here's what I got (after successful installation):

> ?modelspec
No documentation for ‘modelspec’ in specified packages and libraries:
you could try ‘??modelspec’
>

**Comment by kylebmetrum** [comment]
@JSC67 Thanks.  I removed that `R` help topic when we published the [user guide](http://mrgsolve.github.io/user_guide/).  

You can find the same content here:
http://mrgsolve.github.io/user_guide/model-specification.html

Specifically in these two sections:
http://mrgsolve.github.io/user_guide/model-specification.html#code-blocks
http://mrgsolve.github.io/user_guide/model-specification.html#variables-and-macros

And I updated the wiki page accordingly:
https://github.com/metrumresearchgroup/mrgsolve/wiki/howdoi#about-the-model-specification-file

Kyle

**Comment by JSC67** [comment]
> Thank-you, Kyle.
