### ISSUE TITLE
how to parallelize by variable in a dataset

### ISSUE THREAD

**Issue by vjd** [metrumresearchgroup/mrgsolve#26]
In the simulation examples from the March 12 handouts, there is an example to use mclapply to perform "n" simulations based on a dosing dataframe using  one set of posteriors for each of the "n" simulations

```
￼out <- mclapply(1:20, function(i) { mod %>%
param(slice(post,i)) %>% data_set(data) %>%
drop.re %>%
Req(CP) %>% carry.out(dose,EGFR) %>% mrgsim(end=240,delta=0.25) %>% mutate(irep=i)
}) %>% bind_rows
```

I have a dataset with a "rep" column where each "rep" has "m" individuals sampled from a unique combination of omega and sigma distribution for their parameter vectors. Since this dataset is created pre-mrgsim, I am using `data_set` to set the dataset that has to be used for simulation. Can I now perform a parallel simulation using `rep` as the variable, considering each `rep` has about 1000 subjects? I have about 100 reps. 

let me know if I am not clear enough.

**Comment by kylebmetrum** [comment]
I think this is what you are asking about ...
````
# Function to simulate one replicate
sim_rep <- function(this_rep) {
    mod %>% 
       data_set(this_rep) %>% 
       carry.out(rep) %>% 
       mrgsim %>% 
       as.tbl
}

reps <- data %>% split(.$rep)
out <- mclapply(reps, sim_rep) %>% bind_rows
````

Obviously untested code.  And maybe different / better ways to split it up(?).  But I think most of the time when there's 100 reps each with 1000 subjects, I'd parallelize on `rep` like you are suggesting.

**Comment by vjd** [comment]
Thanks, Kyle. I performed a microbenchmark on this to compare with and without the split. For a test dataset with only 10 reps and 10 subjects per rep, there is enough gain. I will give it a shot with the fill dataset and update you.

Without mclapply
```
Unit: seconds
      min       lq     mean   median       uq      max neval
 2.228971 2.286222 2.428616 2.339666 2.515087 2.952982   100
```

With mclapply on rep

```
Unit: milliseconds
      min       lq     mean   median       uq      max neval
814.6958 863.9214 877.7842 878.2451 895.1839 975.6802   100
```

**Comment by kylebmetrum** [comment]
How many cores available?

**Comment by vjd** [comment]
i used 4 cores.. not sure how many can i specify in a new MBP. any suggestions

**Comment by kylebmetrum** [comment]
I think it uses everything any / all resources you have by default ... probably 4.
