### ISSUE TITLE
Steady state (ss=1) with lagtime

### ISSUE THREAD

**Issue by edahmane** [metrumresearchgroup/mrgsolve#264]
@kylebmetrum @dpastoor  I am using mrgsolve CRAN version 0.8.9 and I have the following error message when I run a model with ss=1 and ALAG_GUT : `Error: ss dosing records with lag time are not currently supported`. I thought this bug was fixed in previous releases (https://github.com/metrumresearchgroup/mrgsolve/blob/master/NEWS.md). I have the same error message with the dev version 0.8.9.9000. Was this fix reverted ?
below is a reproducible example:
```
code <- '
$PARAM
SEX=0,
//SEX is 0 for male and 1 for female
TT=0,
//MDR1 C3435T polymorphism, TT=1 for homozygous variant TT and TT=0 if wild-type CC or CT.

TVK20=0.09, TVV2=172.7, TVK23=0.32, TVK32=0.1, TVKA=3.15, TVALAG1=0.21,

ETA1=0, ETA2=0, ETA3=0, ETA4=0,
EPS1=0

$SET delta=0.25, end=24

$CMT GUT CENT PERIPH

$MAIN
ALAG_GUT = ALAG1i;

double K20i = TVK20*exp(ETA1+ETA(1));
double V2i = TVV2*pow((1-0.17),TT)*exp(ETA2+ETA(2));
double KAi = TVKA*exp(ETA3+ETA(3));
double ALAG1i = TVALAG1*pow((1-0.43),SEX)*exp(ETA4+ETA(4));
double K23i = TVK23;
double K32i = TVK32;


$ODE 
double CLi = K20i*V2i;
double Qi = K23i*V2i;
double V3i = Qi/K32i;
double CP = CENT/V2i;

dxdt_GUT = -KAi*GUT;
dxdt_CENT = KAi*GUT + K32i*PERIPH - K23i*CENT - K20i*CENT;
dxdt_PERIPH = K23i*CENT - K32i*PERIPH;

$OMEGA name="bsv"
0//0.028 0.022 0.543 0.075

$SIGMA name="wsv"
0//0.032

$TABLE
double DV = CP*exp(EPS1+EPS(1));

$CAPTURE 
DV CP CLi Qi V3i
'

mod <- mcode("DIGO", code)

data <- expand.ev(ID=1, amt=375, ii=24, ss=1)

sim <- mod %>% 
  data_set(data) %>%  
  #carry_out(evid) %>% 
  mrgsim(Req="DV, CP") %>% 
  as.data.frame()
```

**Comment by kylebmetrum** [comment]
@edahmane Yes, PR #248 disabled that advance.   I still think it was probably working ok for bolus doses, but was absolutely failing for infusions (more complicated to manage the duration, especially when it could be dynamic through dynamic F).  I felt like getting the dynamic F right was higher priority until I can get SS with lag time worked out for bolus and infusion.  

Let's keep this open and I'll see what I can do about finding an organic  / maintainable way to make this happen.  I'm sorry if your code is broken in the meantime.

Kyle

**Comment by kylebmetrum** [comment]
@edahmane If you have some time, could you install from `dev` branch and (see PR #273) and play around with this?   I still need to check against NONMEM output, but so far I'm feeling good about this.  

I had to include some restrictions on what you can do (you'll get an error message).  But I think they would rarely be in play for 99% of the models we do. 

Thanks.

**Comment by kylebmetrum** [comment]
@edahmane Some tests to compare and confirm behavior against `nonmem`
https://github.com/mrgsolve/nmtests/blob/master/nmtest2.pdf

All of this should be in `master` branch now. Any testing or feedback from a real-world user would be appreciated.

**Comment by edahmane** [comment]
@kylebmetrum<https://github.com/kylebmetrum>. Thank you for working on this. I will try on the few models I have and I will compare with nonmem output and get back to you.
