### ISSUE TITLE
Defining Bioavailability in mrgsolve model

### ISSUE THREAD

**Issue by krinaj** [metrumresearchgroup/mrgsolve#265]
Hi Karl, Devin, and others,

I am doing simple 2 comp oral (parallel linear and non-linear elimination) simulations. I tried two different methods to incorporate bioavailability and getting different results. In method 1, I am defining bioavailability in $MAIN and I believe mrgsolve maps it automatically. In method 2, I included bioavailability in ODE. But simulated concentrations between these two methods show some difference.

I am wondering where am I making a mistake? 

Thanks,
Krina

**Method 1:**

```
$PARAM 
F = 0.771
KA= 0.404         //# 1/day
CL = 0.111       //# L/day 
Vmax = 11.9     //# mg/day 
Km = 33.9      //# mg/L 
Vc = 2.91     //# L 
Q = 0.445    //# L/day 
Vp = 3.06   //# L 

$CMT
DEPOT
CENTRAL
PERIPH
  
$MAIN
F_DEPOT = F; 
double Kel = CL/Vc;
double K12 = Q/Vc;
double K21 = Q/Vp;

$ODE
dxdt_DEPOT = -KA*DEPOT;
dxdt_CENTRAL = KA*DEPOT - Kel*CENTRAL - Vmax*CENTRAL/(Km+CENTRAL) - K12*CENTRAL + K21*PERIPH;
dxdt_PERIPH = K12*CENTRAL - K21*PERIPH;

$TABLE
capture Ccentral= (CENTRAL/Vc);
```
**Method 2:**

```
$PARAM 
F = 0.771
KA= 0.404         //# 1/day
CL = 0.111       //# L/day 
Vmax = 11.9     //# mg/day 
Km = 33.9      //# mg/L 
Vc = 2.91     //# L 
Q = 0.445    //# L/day 
Vp = 3.06   //# L 

$CMT
DEPOT
CENTRAL
PERIPH
  
$MAIN
double Kel = CL/Vc;
double K12 = Q/Vc;
double K21 = Q/Vp;

$ODE
dxdt_DEPOT = -F*KA*DEPOT;
dxdt_CENTRAL = F*KA*DEPOT - Kel*CENTRAL - Vmax*CENTRAL/(Km+CENTRAL) - K12*CENTRAL + K21*PERIPH;
dxdt_PERIPH = K12*CENTRAL - K21*PERIPH;


$TABLE
capture Ccentral= (CENTRAL/Vc);

```

**Comment by vjd** [comment]
@krinaj  `F_DEPOT` in your first method implicitly scales your dose going into the body. This is the correct way of using the term. However, I'd like to know why did you try the second method, more out of curiosity?

**Comment by krinaj** [comment]
Thanks, Vijay.

I am trying to actually simulate with mrgsolve and estimate back with
nlmixr to evaluate nlmixr performance. I do not find in-built option in
nlmixr for including bioavail, so I have to include it in ODE.

I am wondering rather than using method 1, can $INIT be used to scale dose
with bioavail? If I use $INIT, how would I scale multiple doses going in
depot compartment?

thanks,
Krina

**Comment by kylebmetrum** [comment]
@krinaj `$INIT` won't help for this; it just says where the compartments are started at the beginning of the problem.

You can verify the bioavailability behavior in `mrgsolve` by looking at what happens to the dose:
``` r
library(mrgsolve)
mod <- mcode("reprex", "$CMT DEPOT \n$MAIN F_DEPOT = 0.5;")
. Compiling reprex ...
. done.
mod %>% ev(amt = 100) %>% mrgsim(end = 0)
. Model:  reprex.cpp 
. Dim:    2 x 3 
. Time:   0 to 0 
. ID:     1 
.      ID time DEPOT
. [1,]  1    0     0
. [2,]  1    0    50
see(mod)
. 
. Model file:  reprex.cpp 
.  $CMT DEPOT 
.  $MAIN F_DEPOT = 0.5;
```

<details><summary>Session info</summary>

``` r
devtools::session_info()
. Session info -------------------------------------------------------------
.  setting  value                       
.  version  R version 3.4.1 (2017-06-30)
.  system   x86_64, darwin15.6.0        
.  ui       X11                         
.  language (EN)                        
.  collate  en_US.UTF-8                 
.  tz       America/Chicago             
.  date     2017-08-31
. Packages -----------------------------------------------------------------
.  package       * version     date       source        
.  assertthat      0.2.0       2017-04-11 CRAN (R 3.4.0)
.  backports       1.1.0       2017-05-22 CRAN (R 3.4.0)
.  base          * 3.4.1       2017-07-07 local         
.  bindr           0.1         2016-11-13 CRAN (R 3.4.0)
.  bindrcpp        0.2         2017-06-17 cran (@0.2)   
.  compiler        3.4.1       2017-07-07 local         
.  datasets      * 3.4.1       2017-07-07 local         
.  devtools        1.13.2      2017-06-02 CRAN (R 3.4.0)
.  digest          0.6.12      2017-01-27 CRAN (R 3.4.0)
.  dplyr           0.7.2       2017-07-20 CRAN (R 3.4.1)
.  evaluate        0.10.1      2017-06-24 CRAN (R 3.4.0)
.  formatR         1.5         2017-04-25 CRAN (R 3.4.0)
.  glue            1.1.1       2017-06-21 CRAN (R 3.4.0)
.  graphics      * 3.4.1       2017-07-07 local         
.  grDevices     * 3.4.1       2017-07-07 local         
.  htmltools       0.3.6       2017-04-28 CRAN (R 3.4.0)
.  knitr           1.16        2017-05-18 CRAN (R 3.4.0)
.  lazyeval        0.2.0       2016-06-12 CRAN (R 3.4.0)
.  magrittr        1.5         2014-11-22 CRAN (R 3.4.0)
.  memoise         1.1.0       2017-04-21 CRAN (R 3.4.0)
.  methods       * 3.4.1       2017-07-07 local         
.  mrgsolve      * 0.8.9       2017-08-28 CRAN (R 3.4.1)
.  pkgconfig       2.0.1       2017-03-21 CRAN (R 3.4.0)
.  R6              2.2.2       2017-06-17 CRAN (R 3.4.0)
.  Rcpp            0.12.12     2017-07-15 CRAN (R 3.4.0)
.  RcppArmadillo   0.7.900.2.0 2017-06-04 CRAN (R 3.4.0)
.  rlang           0.1.2       2017-08-09 CRAN (R 3.4.1)
.  rmarkdown       1.6         2017-06-15 CRAN (R 3.4.0)
.  rprojroot       1.2         2017-01-16 CRAN (R 3.4.0)
.  stats         * 3.4.1       2017-07-07 local         
.  stringi         1.1.5       2017-04-07 CRAN (R 3.4.0)
.  stringr         1.2.0       2017-02-18 CRAN (R 3.4.0)
.  tibble          1.3.4       2017-08-22 CRAN (R 3.4.1)
.  tools           3.4.1       2017-07-07 local         
.  utils         * 3.4.1       2017-07-07 local         
.  withr           2.0.0       2017-07-28 CRAN (R 3.4.1)
.  yaml            2.1.14      2016-11-12 CRAN (R 3.4.0)
```

</details>

<hr>

If you're doing bolus doses, that's all that should happen.  I can take a look at your code tonight but it looks like a valid approach that I see frequently in QSP modeling. 

BTW ... if you're looking at efficiency of simulation, `mrgsim` may or may not be the the most efficient for hooking in with `nlmixr` a la `RxODE`.  `qsim` may or may not be more efficient, depending on what you need out of the simulation.

Kyle

**Comment by kylebmetrum** [comment]
@krinaj 

Seems like you have to do something like this

```r

``` r
library(mrgsolve)
```

Two methods
-----------

``` r
mod1 <- mread("method1") %>% param(F1 = 1)
mod2 <- mread("method2") %>% param(F1 = 1)
```

### Modified method 2

``` r
blocks(mod2,ODE)
```

    . 
    . Model file: method2.cpp 
    . 
    . $ODE
    . double CP     = CENTRAL/Vc;
    . dxdt_DEPOT    =   -KA*DEPOT;
    . dxdt_CENTRAL  =   F1*KA*DEPOT - Kel*CENTRAL - Vmax*CP/(Km+CP) - K12*CENTRAL + K21*PERIPH;
    . dxdt_PERIPH   =   K12*CENTRAL - K21*PERIPH;

### Identical results when `F1==1`

``` r
out1 <- mrgsim(mod1,events=ev(amt=100))
out2 <- mrgsim(mod2,events=ev(amt=100))
identical(out1$Ccentral,out2$Ccentral)
```

    . [1] TRUE

Identical (pretty much) results when `F1==0.25`
-----------------------------------------------

``` r
mod12 <- update(mod1, param = list(F1 = 0.25))
mod22 <- update(mod2, param = list(F1 = 0.25))
out12 <- mrgsim(mod12,events=ev(amt=100))
out22 <- mrgsim(mod22,events=ev(amt=100))


out12
```

    . Model:  method1.cpp 
    . Dim:    26 x 6 
    . Time:   0 to 24 
    . ID:     1 
    .      ID time  DEPOT CENTRAL PERIPH Ccentral
    . [1,]  1    0  0.000   0.000 0.0000    0.000
    . [2,]  1    0 25.000   0.000 0.0000    0.000
    . [3,]  1    1 16.691   7.114 0.5824    2.445
    . [4,]  1    2 11.144  10.151 1.7722    3.488
    . [5,]  1    3  7.440  10.997 3.0570    3.779
    . [6,]  1    4  4.967  10.726 4.1975    3.686
    . [7,]  1    5  3.316   9.946 5.1027    3.418
    . [8,]  1    6  2.214   8.988 5.7585    3.089

``` r
out22
```

    . Model:  method2.cpp 
    . Dim:    26 x 6 
    . Time:   0 to 24 
    . ID:     1 
    .      ID time   DEPOT CENTRAL PERIPH Ccentral
    . [1,]  1    0   0.000   0.000 0.0000    0.000
    . [2,]  1    0 100.000   0.000 0.0000    0.000
    . [3,]  1    1  66.764   7.114 0.5824    2.445
    . [4,]  1    2  44.575  10.151 1.7722    3.488
    . [5,]  1    3  29.760  10.997 3.0570    3.779
    . [6,]  1    4  19.869  10.726 4.1975    3.686
    . [7,]  1    5  13.266   9.946 5.1027    3.418
    . [8,]  1    6   8.857   8.988 5.7585    3.089

``` r
identical(out12$Ccentral,out22$Ccentral)
```

    . [1] FALSE

``` r
summary(out12$Ccentral-out22$Ccentral)
```

    .       Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
    . -2.457e-09 -1.269e-09  0.000e+00 -5.286e-10  2.800e-11  4.700e-10
```

**Comment by kylebmetrum** [comment]
[Archive.zip](https://github.com/metrumresearchgroup/mrgsolve/files/1269074/Archive.zip)

**Comment by krinaj** [comment]
thanks so much, Kyle.

This approach works perfectly and produces identical results to built-in
bioavailability option.
