### ISSUE TITLE
Accounting for time-varying covariates

### ISSUE THREAD

**Issue by abuhelwa** [metrumresearchgroup/mrgsolve#276]
Below is a demo example of a simple 1 compartment first-order absorption model to illustrate the issue. The bioavailability in my model (F_GUT) is time-varying within the same subject and is calculated based on duration of treatment; DAY in the input dataset. However, mrgsolve is not doing the right thing here as it still assumes F_GUT=1 for the second dose while it should be 0.6065307 as per the example I attached (i.e. The amount in the GUT compartment at time=24 should be DOSE * 0.6065307 but it is not what mrgsolve is doing).

The clearance in my PK model is also time-varying (not in the example below). I am not sure if mrgsolve accounts for time-varying covariates at all? or coding F_GUT in the way presented is not right? How can we deal with such situations?

Thanks in advance!

Here is the demo code:

    #remove all current objects in the workspace
    rm(list=ls(all=TRUE))
    graphics.off()

    library(mrgsolve)
    library(dplyr)
    library(ggplot2)

    code <- '
        $GLOBAL
    #define KE (CL/VC)        //wherever KE is used in the model it will replaced by CL/V
    
    $SET delta=1
    
    $PARAM
    DAY = 1
    MULTIPLE = 0
    
    $CMT GUT CENT
    
    $THETA @annotated
    1   : POPCL
    30  : POPVC
    1.3 : POKA
    
    $MAIN
    double COVF = 1;    //single dose 
    if (MULTIPLE == 1 ) COVF = exp(-0.5*(DAY-1));  
    
    double FG = 1*COVF;
    F_GUT = FG;
    double CL = THETA1;
    double VC = THETA2;
    double KA = THETA3;
    
    $ODE
    dxdt_GUT = -KA*GUT*FG;
    dxdt_CENT = KA*GUT - KE*CENT;
    
    $TABLE
    double CP = CENT/VC;
    
    $CAPTURE F_GUT FG CP
    '
    
    mod <- mcode("demo", code)
    
    
    DOSE   <- 100 
    DAYS   <- 2 
    FREQ   <- 1 
    
    #calculate based on the inputs above
    ii   <- 24/FREQ    #tau
    addl <- DAYS*FREQ - 1    #additional doses
    tlast <- DAYS*24
    PKtimes <- sort(unique(c(seq(0,tlast,1))))
    MULTIPLE <- ifelse(DAYS > 1, 1, 0)
    
    #dosing record dataset
    data1 <- expand.ev(ID=1:1, time=0, amt=DOSE, ii=ii, addl=addl, cmt=1, evid=1, 
                       MULTIPLE = MULTIPLE)
    #PKtimes dataset
    data2 <- expand.grid(ID=1:1, time = PKtimes, amt=NA, ii=NA, addl=NA, cmt=2, evid=0,
                         MULTIPLE = MULTIPLE )  
    data <- rbind(data1, data2)
    data <- orderBy(~ID+time+amt, data=data)
    data$DAY <- floor(data$time/24) + 1 
    
    out <- mod %>%
        data_set(data) %>%
        mrgsim() 
    out <- as.data.frame(out)

**Comment by kylebmetrum** [comment]
Hi @abuhelwa  - 

The behavior that you are seeing has to do with the fact you have a dose scheduled for 24 hours (via `addl`) __AND__ you have an observation at that time.  Even though you coded all of the observations and doses into the data set, `mrgsolve` has to decide what to do first at 24 hours: the dose or the observation.  mrgsolve implements the dose first and that happens __before__ it makes it to the observation record where `DAY` starts to take on a new value.  

A couple of things you can try:

If you want to keep the model and data set coded as is, pass the argument `recsort = 2` to the `mrgsim` call.  This will put the `addl` dose at 24 hours after the data set record and you will see time time-varying F (you'll probably have to also get an observation at `24.001` or something like that to actually see something close to the actual F-adjusted dose in the compartment.  

You can make the `addl` doses explicit (in the data set) ...  there is a function called `realize_addl` that tries to help you with that.

If `DAY` is always `1+floor(TIME/24)`, you can drop that from the data set and calculate it inside `$MAIN` (maybe that's not what you want to happen).  

I tried all 3 of these and all seem to work to get that second dose to be `60.57` or so.

This is what I am using to test:

```r
other attached packages:
[1] bindrcpp_0.2        dplyr_0.7.2        
[3] mrgsolve_0.8.9.9002
```

**Comment by kylebmetrum** [comment]
@abuhelwa Also, note that `mrgsolve` handles time-verying covariates differently than nonmem.  When the system advances from record `n` to record `n+1`, `mrgsolve` uses the covariate on record `n`, not the covariate on record `n+1` to advance the system.

**Comment by abuhelwa** [comment]
Hi @kylebmetrum 

Thank you for your response.
I have put `DAY` inside the `$MAIN` and this solved the problem for the amount going into `GUT` compartment at `time=24` (this is now matching NONMEM output). However, as I mentioned earlier, I also have `CL` varying with time but looks like `mrgsolve` is not handling that in the way it handled  `F_GUT` at `time=24` (the simulated amount in `CENT` is not matching NONMEM output `A2`). To clarify this, I modified the demo code above to include time-varying covariate on CL and included the outputs for both. Not sure if this is a of NONMEM handling covariates as last observation carried backwards while mrgsolve as LOC forward? 
If that is the case, is there a way to handle `CL` the way we did for `F_GUT`? 
Also, how exactly you use the `realize_addl`?

Thank you!

NONMEM output

ID | TIME | A1 | A2 | F1 | DAY | CL
-- | -- | -- | -- | -- | -- | --
1 | 23 | 1.03E-11 | 47.67843 | 1 | 1 | 1
1 | 24 | 60.65307 | 46.39483 | 0.606531 | 2 | 0.818731

mrgsolve output

ID | time | GUT | CENT | F_GUT | DAY | CL
-- | -- | -- | -- | -- | -- | --
1 | 23 | 1.52E-09 | 47.67843 | 1 | 1 | 1
1 | 24 | 60.65307 | 46.21622 | 0.606531 | 2 | 0.818731


```
#remove all current objects in the workspace
rm(list=ls(all=TRUE))
graphics.off()

library(mrgsolve)
library(dplyr)
library(ggplot2)
library(doBy)

 code <- '
    $GLOBAL
    #define KE (CL/VC)        //wherever KE is used in the model it will replaced by CL/V
    
    $SET delta=1
    
    $PARAM

    MULTIPLE = 0
    
    $CMT GUT CENT
    
    $THETA @annotated
    1   : POPCL
    30  : POPVC
    1.3 : POKA
    
    $MAIN
    double DAY = floor(TIME/24)+1;
    double COVF = 1;    //single dose 
    if (MULTIPLE == 1 ) COVF = exp(-0.5*(DAY-1));  

    double COVCL = 1;    //single dose 
    if (MULTIPLE == 1 ) COVCL = exp(-0.2*(DAY-1)); 
    
    double FG = 1*COVF;
    F_GUT = FG;

    double CL = THETA1 * COVCL;
    double VC = THETA2;
    double KA = THETA3;
    
    $ODE
    dxdt_GUT = -KA*GUT*FG;
    dxdt_CENT = KA*GUT - KE*CENT;
    
    $TABLE
    double CP = CENT/VC;
    
    $CAPTURE F_GUT FG CP DAY CL
    '
    
    mod <- mcode("demo", code)
    
    
    DOSE   <- 100 
    DAYS   <- 2 
    FREQ   <- 1 
    
    #calculate based on the inputs above
    ii   <- 24/FREQ    #tau
    addl <- DAYS*FREQ - 1    #additional doses
    tlast <- DAYS*24
    PKtimes <- sort(unique(c(seq(0,tlast,1),24.00001)))
    MULTIPLE <- ifelse(DAYS > 1, 1, 0)
    
    #dosing record dataset
    data1 <- expand.ev(ID=1:1, time=0, amt=DOSE, ii=ii, addl=addl, cmt=1, evid=1, 
                       MULTIPLE = MULTIPLE)
    #PKtimes dataset
    data2 <- expand.grid(ID=1:1, time = PKtimes, amt=NA, ii=NA, addl=NA, cmt=2, evid=0,
                         MULTIPLE = MULTIPLE )  
    data <- rbind(data1, data2)
    data <- orderBy(~ID+time+amt, data=data)

    out <- mod %>%
        data_set(data) %>%
        mrgsim()
    out <- as.data.frame(out)
    
    head(out, 26)

```

**Comment by kylebmetrum** [comment]
@abuhelwa Guessing here, but it seems like maybe NONMEM is using analytical solution and you're using ODEs with limited tolerance in `mrgsolve`?  If you increase the relative tolerance to 1E-12 or so, the value at time 24 gets closer to NONMEM.  And when you use the analytical solution in `mrgsolve` it matches exactly (even the amount in GUT at the end of the dosing interval). 

Here is my code:
```r
#remove all current objects in the workspace
rm(list=ls(all=TRUE))
graphics.off()

library(mrgsolve)
library(dplyr)
library(ggplot2)
library(doBy)

code <- '
$GLOBAL
#define KE (CL/VC)        //wherever KE is used in the model it will replaced by CL/V

$SET delta=1

$PARAM

MULTIPLE = 0

$PKMODEL cmt = "GUT CENT", depot = TRUE

$THETA @annotated
1   : POPCL
30  : POPVC
1.3 : POKA

$MAIN
double DAY = floor((TIME)/24)+1;
double COVF = 1;    //single dose 
if (MULTIPLE == 1 ) COVF = exp(-0.5*(DAY-1));  

double COVCL = 1;    //single dose 
if (MULTIPLE == 1 ) COVCL = exp(-0.2*(DAY-1)); 

double FG = 1*COVF;
F_GUT = FG;

double CL = THETA1 * COVCL;
double V = THETA2;
double KA = THETA3;

$TABLE
double CP = CENT/V;

$CAPTURE F_GUT FG CP DAY CL
'

mod <- mcode("demo", code)


DOSE   <- 100 
DAYS   <- 2 
FREQ   <- 1 

#calculate based on the inputs above
ii   <- 24/FREQ    #tau
addl <- DAYS*FREQ - 1    #additional doses
tlast <- DAYS*24
PKtimes <- sort(unique(c(seq(0,tlast,1),24.00001)))
MULTIPLE <- ifelse(DAYS > 1, 1, 0)

#dosing record dataset
data1 <- expand.ev(ID=1:1, time=0, amt=DOSE, ii=ii, addl=addl, cmt=1, evid=1, 
                   MULTIPLE = MULTIPLE)
#PKtimes dataset
data2 <- expand.grid(ID=1:1, time = PKtimes, amt=NA, ii=NA, addl=NA, cmt=2, evid=0,
                     MULTIPLE = MULTIPLE )  
data <- rbind(data1, data2)
data <- dplyr::arrange(data, ID,time, amt)

out <- mod %>%
  data_set(data) %>%
  mrgsim(Req = "GUT,CENT,F_GUT,DAY,CL")
out <- as.data.frame(out)

#head(out, 26)
knitr::kable(filter(out, time %in% c(23,24)),digits = Inf)


```


And my result

| ID| time|          GUT|     CENT|     F_GUT| DAY|        CL|
|--:|----:|------------:|--------:|---------:|---:|---------:|
|  1|   23| 1.034177e-11| 47.67843| 1.0000000|   1| 1.0000000|
|  1|   24| 6.065307e+01| 46.39483| 0.6065307|   2| 0.8187308|


Your NONMEM result

ID | TIME | A1 | A2 | F1 | DAY | CL
-- | -- | -- | -- | -- | -- | --
1 | 23 | 1.03E-11 | 47.67843 | 1 | 1 | 1
1 | 24 | 60.65307 | 46.39483 | 0.606531 | 2 | 0.818731

**Comment by abuhelwa** [comment]
@kylebmetrum Thank you Kyle. I used ADVAN13 TOL=9 and $DES in NONMEM. I used the default tolerance in mrgsolve. The mrgsolve result is **closest** to NONMEM when `atol=1E-15` but yet never matches NONMEM output. The model I am using is a complex one and has to be coded in DES (the one I posted here is just for demonstration purposes).

**Comment by kylebmetrum** [comment]
@abuhelwa Here is exact match to nonmem output (with respect to CENT .... GUT needs more precision to get it to match) using the ODEs and the same tolerances. 

In this approach, we make the record at `time==23` and `evid==2` record;  this forces the solver to stop and reset, but otherwise like a an `evid==0` record.  This will slow down the simulation run

You can achieve a similar behavior by reducing `hmax` (the maximum step size for the solver) to `0.01` or something like this.  Then the solver takes smaller steps, less likely to overshoot by a lot and more like a solver reset right at the time where you want it to reset.  This will also slow down the simulation run. 


```r
#remove all current objects in the workspace
rm(list=ls(all=TRUE))
graphics.off()

library(mrgsolve)
library(dplyr)
library(ggplot2)
library(doBy)

code <- '
$GLOBAL
#define KE (CL/V)        //wherever KE is used in the model it will replaced by CL/V

$SET delta=1

$PARAM

MULTIPLE = 0

$CMT GUT CENT

$ODE
dxdt_GUT = -KA*GUT*FG;
dxdt_CENT = KA*GUT - KE*CENT;

$THETA @annotated
1   : POPCL
30  : POPVC
1.3 : POKA

$MAIN
double DAY = floor((TIME)/24)+1;
double COVF = 1;    //single dose 
if (MULTIPLE == 1 ) COVF = exp(-0.5*(DAY-1));  

double COVCL = 1;    //single dose 
if (MULTIPLE == 1 ) COVCL = exp(-0.2*(DAY-1)); 

double FG = 1*COVF;
F_GUT = FG;

double CL = THETA1 * COVCL;
double V = THETA2;
double KA = THETA3;

$TABLE
double CP = CENT/V;

$CAPTURE F_GUT FG CP DAY CL
'

mod <- mcode("demo", code)


DOSE   <- 100 
DAYS   <- 2 
FREQ   <- 1 

#calculate based on the inputs above
ii   <- 24/FREQ    #tau
addl <- DAYS*FREQ - 1    #additional doses
tlast <- DAYS*24
PKtimes <- sort(unique(c(seq(0,tlast,1),24.00001)))
MULTIPLE <- ifelse(DAYS > 1, 1, 0)

#dosing record dataset
data1 <- expand.ev(ID=1:1, time=0, amt=DOSE, ii=ii, addl=addl, cmt=1, evid=1, 
                   MULTIPLE = MULTIPLE)
#PKtimes dataset
data2 <- expand.grid(ID=1:1, time = PKtimes, amt=NA, ii=NA, addl=NA, cmt=2, evid=0,
                     MULTIPLE = MULTIPLE )  
data <- rbind(data1, data2)
data <- dplyr::arrange(data, ID,time, amt)

data <- mutate(data, evid = if_else(time %in% 23, 2, evid))

out <- mod %>%
  data_set(data) %>%
  mrgsim(Req = "GUT,CENT,F_GUT,DAY,CL", atol = 1E-9, rtol = 1E-9)

out <- as.data.frame(out)

#head(out, 26)
knitr::kable(filter(out, time %in% c(23,24)), digits = Inf)
```

The output

| ID| time|          GUT|     CENT|     F_GUT| DAY|        CL|
|--:|----:|------------:|--------:|---------:|---:|---------:|
|  1|   23| 4.198779e-11| 47.67843| 1.0000000|   1| 1.0000000|
|  1|   24| 6.065307e+01| 46.39483| 0.6065307|   2| 0.8187308|



If you want to fiddle with tolerances or other solver settings try something like 

```r
mrgsim(hmax = 0.01, rtol = 1E-12, atol = 1E-22)
```

**Comment by kylebmetrum** [comment]
@abuhelwa 

I hope the responses we have provided have been helpful to you.  We have given you many different options for working with the model to get the output that you want.  I think the differences between `mrgsolve` comes down to (known) differences in record processing and some differences in the solver settings between the two tools that are maybe less clear. 

If you want to use `mrgsolve` and want to match `nonmem` exactly, I think you really need to start getting more specific about solver settings etc.  But your original assertion that something is not right here seems to be unfounded.  We have demonstrated in several different setups that the the values match exactly.

If you are insisting on getting exact match to `nonmem` out to 8 digits, I would encourage you to always use the same inputs, tolerances, step sizes, digits, etc  for both the `nonmem` run and the `mrgsolve` run.  You also have to correct for differences in record processing (locf for` mrgsolve`) where appropriate.  There might be more that you need to do there, but I wouldn't do less.  I would also code the model in the exact same format / coding.  I don't know if you are currently doing that now or not.  

I would also think about the tool you are using.  If you want `nonmem`'s output to 8 digits, then why not just use `nonmem` for this project?  The output will be just as you like every time.

**Comment by abuhelwa** [comment]
@kylebmetrum 
Thanks Kyle. The responses have been helpful. `mrgsolve` is an amazing package and I would actually prefer it over `NONMEM` for doing simulations. This is my first time using the package and wanted to get deeper understanding of it by comparing against `NONMEM` output.
