### ISSUE TITLE
Time varying clearance and define time in model code

### ISSUE THREAD

**Issue by krinaj** [metrumresearchgroup/mrgsolve#277]
Hi Kyle and all,

My question might be related #276.

I am trying to incorporate a covariate that is dependent on number of doses. I tried adding NDose in dataset that looks like below and then calling out param(NDose=NDose) in R simulations call. But it says parameters has to be single number. It is not able to take list of the same covariate for the same ID.
![image](https://user-images.githubusercontent.com/21271517/31193974-7ecf1de4-a8fa-11e7-8fe0-7cb525420fdf.png)

So, I tried adding NDose in CPP file and code is as below, but it seems like it is not correlating time in cpp file and simulation times. I checked that by capturing NDOSE and printing out in sim output. All NDOSE used for simulations are 1.

Any suggestions as to how to describe time in model code? or how to read in covariate list in param()?

Many thanks,
Krina

```
$MAIN
double time;  
double NDOSE;  
  if(time==0) NDOSE=1; 
  else if(time>0 & time<=84) NDOSE=2; 
  else  if(time>84 & time<=168) NDOSE=3;
  else  if(time>168 & time<=252) NDOSE=4;
  else  if(time>252 & time<=336) NDOSE=5;
  else  if(time>336 & time<=588) NDOSE=6;
  else  if(time>588 & time<=756) NDOSE=7;
  else  if(time>756 & time<=924) NDOSE=8;
  else  if(time>924 & time<=1260) NDOSE=9;
  else  if(time>1260 & time<=1428) NDOSE=10;
  else  if(time>1428 & time<=1596) NDOSE=11;
  else  if(time>1596 & time<=1932) NDOSE=12;
  else  if(time>1392 & time<=2100) NDOSE=13;
  else  if(time>2100 & time<=2268) NDOSE=14;
  else  if(time>2268 & time<=2604) NDOSE=15;
  else  if(time>2604 & time<=2772) NDOSE=16;
  else  if(time>2772 & time<=2940) NDOSE=17;
  else  if(time>2940 & time<=3276) NDOSE=18;
  else  if(time>3276 & time<=3444) NDOSE=19;
  else  if(time>3444 & time<=3612) NDOSE=20;
  else  if(time>3216 & time<=3948) NDOSE=21;
  else  if(time>3948 & time<=4116) NDOSE=22;
  else  if(time>4116 & time<=4284) NDOSE=23;
  else  if(time>4284 & time<=4620) NDOSE=24;
  else  if(time>4620 & time<=4788) NDOSE=25;
  else  if(time>4788 & time<=4956) NDOSE=26;
  else  if(time>4956 & time<=5292) NDOSE=27;
  else  if(time>5292 & time<=5460) NDOSE=28;
  else  if(time>5460 & time<=5628) NDOSE=29;
  else  if(time>5628 & time<=5964) NDOSE=30;
  else  if(time>5964 & time<=6132) NDOSE=31;
  else  if(time>6132 & time<=6300) NDOSE=32;
  else  if(time>6300 & time<=6636) NDOSE=33;
  else  if(time>6636 & time<=6804) NDOSE=34;
  else  if(time>6804 & time<=6972) NDOSE=35;
  else NDOSE=0;  
  
double NDOSE1 = NDOSE;  
double COV1 = THETA9 * pow(1/THETA9, exp(-THETA10*(NDOSE1-1)));
double CL = THETA2 * COV1* pow(WT/75.5, THETA6) * exp(ETA(2));
```

**Comment by kylebmetrum** [comment]
Parameters are always single values.  If you want to access the current time in `$MAIN`, use `TIME`
http://mrgsolve.github.io/user_guide/model-specification.html#time

But you might also try something like this (not tested ... only to illustrate idea or approach).

```r
$GLOBAL 
double ndose;

$MAIN
if(NEWIND <= 1) ndose = 0;
if(EVID == 1) ndose++;
```

**Comment by krinaj** [comment]
great, TIME works perfectly.

Thanks so much for quick response.

**Comment by kylebmetrum** [comment]
@krinaj 

Ok.  I probably should have pointed this out from your code so you are aware going forward:

```r
$MAIN
double time;

if(time > 2) do something;
```

You declared a double precision variable, but didn't initialize it to anything.  This code will never do what you want and you always need to set a variable to something.  It doesn't have to be right away, but usually we do initialize stuff right away.  It's good practice.

If you need access to some internal variable (like `TIME`, or `EVID`) those variables show up automatically; you never declare them, but look into the documentation to know in which variable you should look for the information.

Kyle
