### ISSUE TITLE
Conditional assign_ev

### ISSUE THREAD

**Issue by AJABADI** [metrumresearchgroup/mrgsolve#278]
Hi Team mrgsolve,
My understanding is that when we assign an event in form:
`data <- assign_ev(list(ev1,ev2), idata,"SEX", join=TRUE),`
ev1 is assigned to the first value for "SEX" column, and ev2 to the next distinct "SEX" value. Since I generate SEX values randomly, how can I make sure ev1 is assigned to the value SEX==1?
Thanks in anticipation

**Comment by kylebmetrum** [comment]
Hi @AJABADI  - 

Thanks for the question.  You can try writing a little test to confirm the behavior (I posted one below).  That said, I regret that this is the behavior.  I think I was originally trying to get away from sorting anything, but ... hrm ... it seems like a bad decision now.  

We have similar function that lets you assign observation time grids to IDs or different levels of a covariate in the data set that I'm sure sorts the assignment variable prior to assigning.  So it is inconsistent behavior (across the program) at best.  

But anyway .... you can confirm what is going on with something like this:

```r
> library(mrgsolve)
> library(dplyr)
> 
> data <- expand.idata( SEX = c(1,0,1,0,0,1))
> 
> e1 <- ev(amt = 100) 
> e2 <- ev(amt = 200)
> 
> ev_assign(list(e1,e2),data, "SEX", join = TRUE)
  time cmt amt evid ID SEX
1    0   1 100    1  1   1
2    0   1 200    1  2   0
3    0   1 100    1  3   1
4    0   1 200    1  4   0
5    0   1 200    1  5   0
6    0   1 100    1  6   1
```

**Comment by kylebmetrum** [comment]
Ah ... @AJABADI I just caught the nuance in your question.  Right ... this makes it really clear that we need to sort the covariate prior to assignment. 

My only workaroud at this point would be to sort the data frame first: 

```r
> library(mrgsolve)
> library(dplyr)
> 
> data <- expand.idata( SEX = c(1,1,0,1,0,0,1))
> 
> e1 <- ev(amt = 100) 
> e2 <- ev(amt = 200)
> 
> data <- arrange(data, SEX)
> 
> ev_assign(list(e1,e2),data, "SEX", join = TRUE)
  time cmt amt evid ID SEX
1    0   1 100    1  3   0
2    0   1 100    1  5   0
3    0   1 100    1  6   0
4    0   1 200    1  1   1
5    0   1 200    1  2   1
6    0   1 200    1  4   1
7    0   1 200    1  7   1
```

I think we have to bite the bullet here and change this.  Thanks for bringing it to my attention.

**Comment by AJABADI** [comment]
Oh... That was easy! Nice and simple!

Thanks Kyle for your quick reply. Actually, this easy trick along with relevant definition of new data columns should be sufficient for most of the problems which need individualised dosing events  (in case you're wondering, I wasn't trying to adjust the dosing based on how frail the patients are, which can have more than 2 levels). The only penalty seems to be the loss of order of the ID's which isn't an issue as far as I know.

Thanks again.

**Comment by kylebmetrum** [comment]
@AJABADI  No problem.  You can always re-arrange the data frame if order is an issue.  But I think we just need to bite the bullet and change the behavior so you don't have to do any of this.

KTB

```r
> library(mrgsolve)
> library(dplyr)
> 
> data <- expand.idata( SEX = c(1,1,0,1,0,0,1))
> 
> e1 <- ev(amt = 100) 
> e2 <- ev(amt = 200)
> 
> data <- arrange(data, SEX)
> 
> 
> data <- ev_assign(list(e1,e2),data, "SEX", join = TRUE)
> 
> arrange(data, ID)
  time cmt amt evid ID SEX
1    0   1 200    1  1   1
2    0   1 200    1  2   1
3    0   1 100    1  3   0
4    0   1 200    1  4   1
5    0   1 100    1  5   0
6    0   1 100    1  6   0
7    0   1 200    1  7   1
```
