### ISSUE TITLE
Clean up the Makefile and makescripts/*

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#28]
Too much old stuff in there and stuff that will only work on your computer .

**Comment by kylebmetrum** [comment]
@dpastoor  Wondering if the Makefile works for you?  On Mac/Unix only ... 

````sh
make all
```
does the document, build, and install

````sh
make check 
````

Documents, builds, and checks. 

I'm pretty sure all of this can get turned into R code using devtools.  But I think you should be able to use it ... or at least give it a go.  And I'll work on making it fully R.

**Comment by dpastoor** [comment]
sure will give it a go tonight
