### ISSUE TITLE
Time-varying Covariates

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#289]
Opened this issue on RxODE:
https://github.com/nlmixrdevelopment/RxODE/issues/6

My testing against nonmem looks like, when using a fully specified input data set (both observations and doses), you do get the same answer.  I had to think about it for a while and go back to the simulation cycle.  The "current" record is the record we are advancing to; that is where we copy the covariates from and we copy __prior__ to advancing.  

I still want to make sure I haven't set up the test improperly, but I have been misspeaking when talking about NOCB versus LOCF for time-varying covariates.  It seems to be NOCB as well.  IT might be a more complicated or slightly different picture when simulating from input doses (without observations).

In the test, both mrgsim and nonmem are shown.  TVCL doesn't change until `time==21` (green line) but both mrgsim and nonmem use the TVCL at `time==21` when advancing from `time==20` to `time==21`.

<img width="948" alt="screen shot 2017-10-17 at 12 07 22 pm" src="https://user-images.githubusercontent.com/16908301/31676335-4aedc81e-b335-11e7-8f62-ccdf18f424eb.png">

**Comment by mattfidler** [comment]
I just saw your post.  So mrgsolve uses `NOCB`?

**Comment by kylebmetrum** [comment]
@mattfidler Yeah ... I was saying `locf` but it's `nocb`.   I've been thinking about this issue for a while and I'm sure did a test or two at one point.  But was just mistaken.  It's obvious to me now as I work through the simulation logic. 

I agree with [your assessment here](https://github.com/nlmixrdevelopment/RxODE/issues/6#issuecomment-337453214).  I added in toggle to pick between `nocb` and `locf` as well,  keeping `nocb` as default.  Thanks for thinking this through with me.

KTB

**Comment by mattfidler** [comment]
Thanks again.

**Comment by mattfidler** [comment]
I think you finished your project too

https://github.com/metrumresearchgroup/mrgsolve/projects/5
