### ISSUE TITLE
NSE-related? issue causing ev() to fail when column named amt

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/mrgsolve#29]
fails with error `Error: invalid subscript type 'double'`

```
ex_df <- data.frame(rate = 10, amt=10)
ev(time = 0, amt = 10, rate = ex_df$amt)
```

works

```
ev(time = 0, amt = 10, rate = 10)
```

works

```
ex_df <- data.frame(rate = 10)
ev(time = 0, amt = 10, rate = ex_df$rate)
```

But does not fail with other (possible) keywords, as this works

```
ex_df <- data.frame(rate = 10, amt=10, ss=10)
ev(time = 0, amt = 10, rate = ex_df$ss)
```

**Comment by dpastoor** [comment]
Occasion comes up when I want a 1 hr infusion so am setting rate = amt

**Comment by dpastoor** [comment]
Ok, looks like this isn't directly an mrgsolve issue, it is actually a [dplyr issue](https://github.com/hadley/dplyr/issues/1554)

The solution is to be careful about using $ in your commands (data[["amt"]] instead of data$amt)

I will keep the issue open now until @kylebmetrum decides whether this would be worthy of an additional note somewhere as I could see this occurance coming up again - maybe like a 'errors and solutions' document of sorts

**Comment by kylebmetrum** [comment]
I get that all the time with `dplyr` too.  I'll drop the NSE altogether.  It was an experiment and ended up not being that useful.
