### ISSUE TITLE
openMP

### ISSUE THREAD

**Issue by pitla1** [metrumresearchgroup/mrgsolve#291]
While installing mrgsolve, I get this warning.. 

/data/R/lib/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:474:96: note: #pragma message: WARNING: use of OpenMP disabled; this compiler doesn't support OpenMP 3.0+
   #pragma message ("WARNING: use of OpenMP disabled; this compiler doesn't support OpenMP 3.0+")
                                                                                                ^

Any suggestions regarding openMP.. would be highly appreciated. I get similar warnings with RxODE as well.

**Comment by kylebmetrum** [comment]
HI @pitla1 The warning is coming from `RcppArmadillo` headers.  You can try contacting that project if you want dig into it.  `mrgsolve` doesn't utilize OpenMP so there is no issue for us.

**Comment by mattfidler** [comment]
`RxODE` does not directly use OpenMP, either.  You have to use a supported linux distribution to make use of it;  

https://wbnicholson.wordpress.com/2014/07/10/parallelization-in-rcpp-via-openmp/

Then it would work in that Linux distribution (but not on windows or mac).  In theory it will make both `RxODE` and `mrgsolve` slightly faster when they use the `RcppArmadillo` routines.
