### ISSUE TITLE
question about evid=3 and compartment initialization

### ISSUE THREAD

**Issue by tonggne** [metrumresearchgroup/mrgsolve#297]
Hello Kyle,

I am working on a model that need EVID=3 to reset the system and reinitialize the compartments. The model include both the PK and PD compartments, and as expected EVID=3 will clear out the whole system. Since only the PD compartments need to be reset, I tent to re-initialize the PK compartments to the exact value before the reset. I did that in the $MAIN section. Also, the PD compartments were re-initialized depending on the model predicted values (G0, G1 or G2). I did the similar settings in NONMEM and it works as expected. However, I experienced some difficulties in mrgsolve. 

#########################################
$CMT GUT TOTAL UNBOUND PR0 PR1 PR23

$MAIN

if (NEWIND <=1) {
	    GUT_0=0;
	    TOTAL_0=0;
	    UNBOUND_0=0;
	    G0=1;
	    PR0_0=1;
	    PR1_0=0;
	    PR23_0=0;
}

if (EVID==3) {
	    GUT_0=GUT;
	    TOTAL_0=TOTAL;
	    UNBOUND_0=UNBOUND;
if(G0==1) {
	    PR0_0=1;
	    PR1_0=0;
	    PR23_0=0;
		}
if(G1==1) {
	    PR0_0=0;
	    PR1_0=1;
	    PR23_0=0;
		}
if(G2==1) {
	    PR0_0=0;
	    PR1_0=0;
	    PR23_0=1;
		}
}
##########################################

1) sounds like EVID=3 only works when it first appeared in the dataset, not later. I did some tests using the simple TOD code. 
First scenario: TOD stays at 1 all the time (does not change with TIME)
if (EVID==3) TOD = TIME;
e <- ev(time=1, amt=150, ii=1, addl=12*7, evid=3)
Second scenario: TOD matched with TIME perfectly
if (EVID==1) TOD = TIME;
e <- ev(time=1, amt=150, ii=1, addl=12*7, evid=1)

2) I was not able to assign the initial values the way I want through the $MAIN section. For example, the GUT_0 is always 0 no matter what values in the GUT. There should be something wrong but I have no idea how to fix

Thanks a lot!
Tong

**Comment by kylebmetrum** [comment]
Hi @tonggne - 

It might be that `evid==3` records are not currently getting scheduled out through the `addl` mechanism.  I can look into that.  I'm pretty sure there is a restrictive policy there.  But may need to be reconsidered.  Anyway, we made a  function that will address this ... `realize_addl` will make all of the `evid 3` records explicit in the data set.

It sounds like the implementations might be too different for your current project.  But if you could __share reproducible examples__ showing behavior for both `mrgsolve` and `NONMEM`, we could use that as a starting point to make some changes.  

Please also include your `sessionInfo` in the report.  

Thanks, 
Kyle

**Comment by tonggne** [comment]
Thanks Kyle. 

The "realize=TRUE" works for EVID=3 (all of the evid 3 records explicit in the data set). I will play with model more before I get back to you with more information

Best,
Tong

**Comment by kylebmetrum** [comment]
Thanks, @tonggne.  I'll start an issue to get `EVID==3` (and probably 4) recognized by the `addl` system.

KTB

**Comment by tonggne** [comment]
Hello Kyle,

Now the model works as expected!

I would need to first save the states of the PK compartments to couple of new variables in $TABLE, and then assign the new variables as initial values back to the PK compartments in the $MAIN if EVID==3. By doing so, the EVID==3 will not have any impact on the PK system.

$MAIN
if (EVID==3) {
GUT_0=A1;
TOTAL_0=A2;
UNBOUND_0=A3;
}

$TABLE 
double A1=GUT;
double A2=TOTAL;
double A3=UNBOUND;

Thanks!
Tong

**Comment by kylebmetrum** [comment]
@tonggne 

Just be careful with the variables `A1`, `A2` and `A3`.  I think it'll be ok as long as the `EVID 3` record isn't the first record in the data set (probably true).  Just make sure that you don't reference `A1`, `A2`, or `A3` before they get defined.  

It would be safer to just declare and initialize them before `$TABLE` so that the variables are always initialized.  Maybe in the `NEWIND <= 1` block?  This might be overkill but might head off some undefined values at some point down the road. 

KTB


```
$GLOBAL
double A1 = 0;
double A2 = 0;
double A2 = 0;

$MAIN
if(NEWIND <=1) {
  A1 = 0;
  A2 = 0; 
  A3 = 0;
}

$TABLE
A1=GUT;
A2=TOTAL;
A3=UNBOUND;
```


KTB

**Comment by tonggne** [comment]
Thanks Kyle for the suggestions!
