### ISSUE TITLE
Schedule doses with EVID %in% c(3,4) via addl

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#298]
As reported in #297

**Comment by kylebmetrum** [comment]
> DISCUSSION:
ADDL labels PREDPP’s additional dose (ADDL) data item. The additional dose data item is optional. In a dose or reset-dose event record it describes how many additional doses, exactly like the present ("initiating") dose, should be given. The interdose interval (II) data item gives the time between the additional doses (See ii).
When ADDL is 0, no additional doses are given.
For non-steady-state doses, ADDL should be a positive number if and only if the II data item is a positive number. II gives the time between additional doses.
For steady-state infusions, ADDL must be 0.
For other steady-state doses, ADDL is optional. If it is a positive number, it continues the pattern of implied doses beyond the steady-state dose. The additional doses of the pattern are non-steady state doses.
For observation, other-type and reset event records, ADDL should be zero.

**Comment by kylebmetrum** [comment]
Maybe this is something where we have to check behavior again.  But `viii.pdf` seems to say
that `ADDL` must be zero for reset events.

**Comment by billdenney** [comment]
Regardless of the contents of `viii.pdf`, I'd be confused if `EVID = 3` had an `ADDL` value since it should be reset-only.  (Is the desire to reset the data on a schedule?)

Perhaps giving an informative error message like "ADDL must be 0 when EVID = 3 or 4" would be the more helpful way to take care of this?  (That may already exist.)

**Comment by kylebmetrum** [comment]
@billdenney Thanks.  I was thinking `EVID 4` was more in the "dose" category rather than "reset" (as I understand it, it is "reset and dose").   I think mrgsolve `EVID 4` is "reset, dose, give additional doses if ADDL > 0`.  Maybe that isn't what should happen.  But it shouldn't be controversial with a NONMEM-compliant data set (where - maybe - ADDL would always be zero in that case).  I struggle with this a little ... it's nice to match NONMEM but sometimes, yeah, it'd be convenient to be able to schedule reset events every week or something like that, depending on what you were trying to do. 

`mrgsolve` has EVID 8 (replace the amount in a compartment) ... that's convenient to  to have addl-ability.  Same with EVID 2 (just to force the solver to make a hard stop and start over). 

KTB

**Comment by kylebmetrum** [comment]
And the EVID 3 with ADDL question came up b/c a user seemed to be using it in their code and was wondering why it wasn't matching NONMEM output.  I wonder if there was mis-match in how the model / data was coded up for that one.
