### ISSUE TITLE
[F] carry.out includes dplyr::select style renaming

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/mrgsolve#30]
example scenario, I am passing in a dataset with DV, and want to simulate against it, but also retain the original DV column to carry through. As of now, it will do so, however will result in 2 columns named DV 

![image](https://cloud.githubusercontent.com/assets/3196313/14645701/b613dc56-0624-11e6-9364-8fa661128d50.png)

```
model %>% 
idata_set(param_data) %>%
  data_set(my_data ) %>% 
  carry.out(evid, WT, RDV = DV) %>%
  mrgsim(end= max(my_data$time) + 12,delta=0.1,digits=4)
```

such that the column DV would be carried forward and renamed RDV

**Comment by kylebmetrum** [comment]
I think we'll be able to rename items in `Request()` by the same mechanism as well (change the name of a tabled item right after simulating and before returning from `mrgsim`).

**Comment by kylebmetrum** [comment]
Not committed yet.


``` r
see(ind_model)
```

    ## 
    ## Model file:  ind_model.cpp 
    ## 
    ## $PARAM CL= 1.2, VC=14.3
    ## $CMT GUT CENT
    ## $ADVAN2
    ## $MAIN
    ## pred_CL = CL;
    ## pred_V = VC;
    ## $TABLE table(DV) = CENT/pred_V; 
    ## 

``` r
out <- 
  ind_model %>%
  data_set(ex_id_data) %>% 
  carry.out(BAR = FOO, CMT = cmt, EVENT_ID = evid, addl) %>% 
  Req(CENTRAL = CENT, DV) %>%
  mrgsim(delta=0.1, digits=4) 

out
```

    ## Model:  ind_model.cpp 
    ## Dim:    244 x 8 
    ## Time:   0 to 24 
    ## ID:     1 
    ##      ID time CMT EVENT_ID addl BAR CENTRAL      DV
    ## [1,]  1  0.0   0        0    0   1  0.0000 0.00000
    ## [2,]  1  0.0   1        2    0   1  0.0000 0.00000
    ## [3,]  1  0.1   0        0    0   1  0.9958 0.06964
    ## [4,]  1  0.2   0        0    0   1  1.9830 0.13870
    ## [5,]  1  0.3   0        0    0   1  2.9630 0.20720
    ## [6,]  1  0.4   0        0    0   1  3.9340 0.27510
    ## [7,]  1  0.5   0        0    0   1  4.8970 0.34240
    ## [8,]  1  0.6   0        0    0   1  5.8510 0.40920

**Comment by dpastoor** [comment]
exactly what I had in mind!

**Comment by kylebmetrum** [comment]
Great.  If you have `DV` in both the sims (from `$TABLE`) and the `data_set`, you can pick new names for one, the other, or both. 

I've been doing battle with duplicate names in the output for a while now ... trying to prevent people from doing it.  Especially now, there should at least be a check and warning ... or error if we find duplicates?

**Comment by dpastoor** [comment]
hmm yes, I agree, we could make a check, the question is how aggressive to be. 

option 1) less aggressive: warning + either auto-renaming or just leave duplicate to their peril. In the past I've written a couple functions that would check then append a `_` but I don't like that approach as people generally ignore warnings, and if you have output spitting out later may not even see it.

option 2) (my preference) is a full check and a straight stop() with an error saying something like "the current settings will result in a duplicate column name `x`, please rename and try again"

**Comment by dpastoor** [comment]
option 3) control what keywords can be carried out/named for table statements, and don't let someone carry out/rename to certain reserved keywords. To me this is still better than option 1, it just forces people to rename their datasets before carrying them through, rather than making mrgsolve handling it

model %>% data_set(ex_data %>% rename(RDV = DV) %>% carry.out(RDV) ...

**Comment by kylebmetrum** [comment]
I was almost going to punt on the automated renaming ... and do something like your option 3)
````r
setMethod("data_set",c("mrgmod", "data.frame"), function(x,data,subset=TRUE,select=TRUE,...) {
    if(exists("data", x@args)) stop("data already has been set.")
    if(!missing(subset)) data <- filter_(data,.dots=lazy(subset))
    if(!missing(select)) data <- select_(data,.dots=lazy(select))
    if(nrow(data) ==0) stop("Zero rows in data after filtering.", call.=FALSE)
    data <- mrgindata(m=x,x=data,...)
    x@args <- merge(x@args,list(data=data), strict=FALSE)
    x
})

````
We could easily add a `rename` argument and call `dplyr::rename_` to make it a little more convenient. 

It wasn't super messy to get the renaming done as I posted earlier, but I ended up making a small S3 class to do it (figure out what the `to` and the `from` names are and a method to make the substitutions) and two more objects to keep track of in `mrgsim`.  But it's more code to maintain and another thing that could break.  

Also ... it would also be easy to make a `rename_.mrgsims` method so people can just rename stuff after the fact.  You would still have to rename stuff in the data set if it clashes with a compartment or other output variable, but if there wasn't a clash and you just wanted to rename something down the road it would be another pipe to `rename`.

**Comment by kylebmetrum** [comment]
This better replicates what the original issue was.  `conc` comes from the solver and `DV`  comes from `conc` in the `data_set`.

``` r
ind_code <- '
$PARAM CL= 1.2, VC=14.3
$CMT GUT CENT
$ADVAN2
$MAIN
pred_KA = 0.8;
pred_CL = CL;
pred_V = VC;
$TABLE table(conc) = CENT/pred_V; 
'

data(exTheoph)

head(exTheoph)
```

    ##   ID   WT Dose time  conc cmt  amt evid
    ## 1  1 79.6 4.02 0.00  0.00   1 4.02    1
    ## 2  1 79.6 4.02 0.25  2.84   0 0.00    0
    ## 3  1 79.6 4.02 0.57  6.57   0 0.00    0
    ## 4  1 79.6 4.02 1.12 10.50   0 0.00    0
    ## 5  1 79.6 4.02 2.02  9.66   0 0.00    0
    ## 6  1 79.6 4.02 3.82  8.58   0 0.00    0

``` r
ind_model <- mread(model="ind_model", code = ind_code)
```

    ## Using ADVAN2

    ## Compiling ind_model.cpp.cpp ...

    ## done.

    ## Loading: ind_modeld88832022e26.so

``` r
out <- 
  ind_model %>%
  data_set(exTheoph, ID == 3) %>% 
  carry.out(DV = conc) %>%
  mrgsim(delta=0.1, digits=4) 

out
```

    ## Model:  ind_model.cpp 
    ## Dim:    11 x 6 
    ## Time:   0 to 24.17 
    ## ID:     1 
    ##      ID time  DV     GUT   CENT    conc
    ## [1,]  3 0.00 0.0 4.53000 0.0000 0.00000
    ## [2,]  3 0.27 4.4 3.65000 0.8698 0.06082
    ## [3,]  3 0.58 6.9 2.84800 1.6380 0.11460
    ## [4,]  3 1.02 8.2 2.00300 2.4080 0.16840
    ## [5,]  3 2.02 7.8 0.90010 3.2660 0.22840
    ## [6,]  3 3.62 7.5 0.25030 3.4550 0.24160
    ## [7,]  3 5.08 6.2 0.07783 3.2170 0.22500
    ## [8,]  3 7.07 5.3 0.01584 2.7780 0.19430

**Comment by kylebmetrum** [comment]
I guess I'm not sure how to pass stuff to `dplyr::rename`

``` r
head(exTheoph)
```

    ##   ID   WT Dose time  conc cmt  amt evid
    ## 1  1 79.6 4.02 0.00  0.00   1 4.02    1
    ## 2  1 79.6 4.02 0.25  2.84   0 0.00    0
    ## 3  1 79.6 4.02 0.57  6.57   0 0.00    0
    ## 4  1 79.6 4.02 1.12 10.50   0 0.00    0
    ## 5  1 79.6 4.02 2.02  9.66   0 0.00    0
    ## 6  1 79.6 4.02 3.82  8.58   0 0.00    0

``` r
out <- 
  ind_model %>%
  data_set(exTheoph, subset=ID==3, DV=conc) %>% 
  carry.out(DV) %>%
  mrgsim(delta=0.1, digits=4) 

out
```

    ## Model:  ind_model.cpp 
    ## Dim:    11 x 6 
    ## Time:   0 to 24.17 
    ## ID:     1 
    ##      ID time  DV     GUT   CENT    conc
    ## [1,]  3 0.00 0.0 4.53000 0.0000 0.00000
    ## [2,]  3 0.27 4.4 3.65000 0.8698 0.06082
    ## [3,]  3 0.58 6.9 2.84800 1.6380 0.11460
    ## [4,]  3 1.02 8.2 2.00300 2.4080 0.16840
    ## [5,]  3 2.02 7.8 0.90010 3.2660 0.22840
    ## [6,]  3 3.62 7.5 0.25030 3.4550 0.24160
    ## [7,]  3 5.08 6.2 0.07783 3.2170 0.22500
    ## [8,]  3 7.07 5.3 0.01584 2.7780 0.19430



Best I can do is pass as dots:
````r
setMethod("data_set",c("mrgmod", "data.frame"), function(x,data,subset=TRUE,select=TRUE,...) {
    if(exists("data", x@args)) stop("data already has been set.")
    if(!missing(subset)) data <- dplyr::filter_(data,.dots=lazy(subset))
    if(!missing(select)) data <- dplyr::select_(data,.dots=lazy(select))
    data <- dplyr::rename_(data,.dots=lazy_dots(...))
    if(nrow(data) ==0) stop("Zero rows in data after filtering.", call.=FALSE)
    data <- mrgindata(m=x,x=data,...)
    x@args <- merge(x@args,list(data=data), strict=FALSE)
    x
})
````

Any ideas?

**Comment by dpastoor** [comment]
So you can do it via

rename_(data, "<newname>" = "<existing_name>") 

```
rename_(Theoph, "dv" = "conc")
```

but that is actually a bit cumbersome as in reality what we'd probably want is a more elegant way of passing in multiple options (barring usings dots to do this), so something like


We can probably just whip out good old base R, I will crank out a PR real quick so it will be easier to keep track of
```
df <- rename_cols(df ,c("newcol1" = "oldcol1", "newcol2" = "oldcol2", ...))
``

**Comment by kylebmetrum** [comment]
1.  Sorry for the hassle on build.  I use the makefile.  Part of the complication is that I need to use some of the package code to build that `house` model prior to actually building the package.  Part is that the make file is still sort of custom to my system.  On my todo list to make that useful and useable for everyone.  I'll post what target to use for everyday build.

2.  What about this?  It takes advantage of that rename code that I developed for `carry.out` and `Req`?  It retains the comma sep name=value setup but you have to put it in backticks.  Pro: it's fairly compact and still uses `dplyr::rename`.  Con: backticks?  Maybe it works as a quirky option.  As in your last people can always rename before getting into the chain of commands or right in `data_set` itself.  If they can stand the backticks they can use this too.  



``` r
out <- 
  ind_model %>%
  data_set(exTheoph, rename = `DV=conc,WEIGHT=WT`) %>% 
  carry.out(DV,WEIGHT) %>%
  mrgsim(delta=0.1, digits=4) 

out
```

    ## Model:  ind_model.cpp 
    ## Dim:    132 x 7 
    ## Time:   0 to 24.65 
    ## ID:     12 
    ##      ID time    DV WEIGHT     GUT   CENT    conc
    ## [1,]  1 0.00  0.00   79.6 4.02000 0.0000 0.00000
    ## [2,]  1 0.25  2.84   79.6 3.29100 0.7209 0.05041
    ## [3,]  1 0.57  6.57   79.6 2.54800 1.4350 0.10030
    ## [4,]  1 1.12 10.50   79.6 1.64100 2.2550 0.15770
    ## [5,]  1 2.02  9.66   79.6 0.79870 2.8980 0.20270
    ## [6,]  1 3.82  8.58   79.6 0.18920 3.0480 0.21310
    ## [7,]  1 5.10  8.36   79.6 0.06797 2.8510 0.19940
    ## [8,]  1 7.03  7.47   79.6 0.01451 2.4730 0.17300

**Comment by dpastoor** [comment]
That could definitely work, thoughthe biggest 'concern' I have with backticks is it is unintuitive and very few people (in my experience) even know the distinction. If they want that conciseness might as well directly use dplyr `data_set(exTheoph %>% rename(DV=conc,WEIGHT=WT))`

Personally, I would use the arguments to provide functionality not as easily given by the dplyr functionality - in this case, renaming from a vector of arguments would allow easier programmatic renaming.

```
to_rename <- c(...)


# somewhere in pipeline
...
data_set(my_data, rename=to_rename)
...
```

I guess the distinction in my mind is `carry.out` and `Req` need some renaming mechanism as the underlying data manipulation is abstracted away so we don't have direct access to rename data. Given that users _do_ have direct access in `data_set` I wonder if it even makes sense to provide such a thin wrapper that could be additional effort to maintain, vs actually give a different enough api to give them an option of how they would like to manage it, either more 'interactively' through nested dplyr pipes or using a more programmatic api mrgsolve could expose.

**Comment by kylebmetrum** [comment]
Agree. Agree. Agree. 

I included the access to `filter` and `select` mainly because it was easy to just utilize the `dplyr` functionality so easily.  It was a freebie.  The `filter` call is actually really useful and gets used. The `select` call ... I don't use it much.  But it's there.  Maybe the `rename` stuff is going too far when, as @dpastoor points out, it should be really easy for user to do it with other.

In terms of functionality, I realized this morning that you don't really need the backticks for `rename`.  You could / should use quotes.  Either way, it takes advantage of existing code that I already had in place to try to get more compact syntax (especially getting out of all the quotes when entering long character vectors).

So you could specify `rename` or `carry.out` this way:

``` r
out <- 
  ind_model %>%
  data_set(exTheoph, rename = "DV=conc,WEIGHT=WT") %>% 
  mrgsim(delta=0.1, digits=4,carry.out="DV,WEIGHT,evid", Req="DV,CENT") 

out
```

    ## Model:  ind_model.cpp 
    ## Dim:    132 x 6 
    ## Time:   0 to 24.65 
    ## ID:     12 
    ##      ID time evid    DV WEIGHT   CENT
    ## [1,]  1 0.00    1  0.00   79.6 0.0000
    ## [2,]  1 0.25    0  2.84   79.6 0.7209
    ## [3,]  1 0.57    0  6.57   79.6 1.4350
    ## [4,]  1 1.12    0 10.50   79.6 2.2550
    ## [5,]  1 2.02    0  9.66   79.6 2.8980
    ## [6,]  1 3.82    0  8.58   79.6 3.0480
    ## [7,]  1 5.10    0  8.36   79.6 2.8510
    ## [8,]  1 7.03    0  7.47   79.6 2.4730

But looking at this, it it doesn't provide much / any advantage over the nested pipe.  Sounds like it should get dropped.  

I think the filter piece sort of works because you don't need to name the argument and it's the only one that we tend to use.

**Comment by dpastoor** [comment]
👍
