### ISSUE TITLE
User guide + mrgsolve.github.io editorial comments

### ISSUE THREAD

**Issue by drexell0680** [metrumresearchgroup/mrgsolve#304]
The user guide is a great resource, thanks for putting it together.  Here's a small list of misspellings, render issues, etc...

**mrgsolve.github.io**

- "Site navagation" (sp)

**User guide**

- 2.5.1 ($MAIN function): looks like md bullets aren't rendering correctly
- 3.2.1: "Users are free to include bock (sp) code"
- 3.2.8: "... called once in two different settings 1. Immediately prior...  1. ..."(should be 2.)
- 3.2.9: "This construct will result in 4 additional columns in the simulated output with names A, B, C, and yes."  Move this statement to before the annotated example

**Comment by kylebmetrum** [comment]
Thanks again, @drexell0680
