### ISSUE TITLE
Extension of MAP Bayes example

### ISSUE THREAD

**Issue by JSC67** [metrumresearchgroup/mrgsolve#307]
Hi Kyle,

In the MAP Bayes tutorial (https://mrgsolve.github.io/2017/02/23/generate-map-bayes-parameter-estimates/) you wrote, "With some additional R coding, it could be expanded to consider multiple individuals in a single run." and at http://discuss.go-isop.org/t/mixed-effects-modeling-alternatives-in-r/552 you wrote, "I did some non-linear mixed effects modeling in R with plain old nlme + mrgsolve. The poster is here http://metrumrg.com/assets/pubs/asbmroct13.pdf but it has limited methodological details (presented to a more clinical audience)."  That link is now invalid, and I wonder if you could update it, and even better, provide more technical details.

I've revised the MAP Bayes tutorial for clarity (at least to me), and I also revised the mapbayes function itself.  With the revised mapbayes I was able to fit some richly sampled simulated data I made, but only for one individual at a time.  I think I could adapt it fairly straightforwardly for naive pooled fitting, fitting average, or for iterative 2-stage, but because the function as it is does nothing to change the THETA parameters, only update the ETA parameters, I could use some help in how to use mrgsolve together with newuoa (or whatever optimizer) to do actual nonlinear mixed effects.

I attach the revised mapbayes tutorial (lots of comments in it).  Finally, you also wrote at http://discuss.go-isop.org/t/mixed-effects-modeling-alternatives-in-r/552, "If I were to do it over today, I’d probably take the time to look at saemix (https://github.com/ecomets/saemix or https://cran.r-project.org/web/packages/saemix/index.html) first."  I'll take a look at that too, but if it's possible to use mrgsolve for actual NMLE fitting, I'd like to know how I could do it, if you've already done it.

Thank-you!
[generate-map-bayes-parameter-estimates4.R.txt](https://github.com/metrumresearchgroup/mrgsolve/files/1572177/generate-map-bayes-parameter-estimates4.R.txt)

James

**Comment by kylebmetrum** [comment]
Hi James - 

I hacked out an example for `nlme` that you should be able to run. 

Did you check out nlmixr yet?
https://github.com/nlmixrdevelopment/nlmixr
This looks like a nice solution for nlme in R.

Kyle

<hr>


nlme.R
================
kyleb
Tue Dec 19 23:34:14 2017

``` r
library(mrgsolve)
library(dplyr)
```

    ## 
    ## Attaching package: 'dplyr'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     filter, lag

    ## The following objects are masked from 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

``` r
library(nlme)
```

    ## 
    ## Attaching package: 'nlme'

    ## The following object is masked from 'package:dplyr':
    ## 
    ##     collapse

``` r
library(ggplot2)

data(exTheoph)

data <- exTheoph

mod <- mread_cache("pk1", modlib())
```

    ## Compiling pk1 ...

    ## done.

Pars will now be a data frame with same number of rows as `data` (see `nlme` call too)

Also, we return the predicted values here, not the objective function value

``` r
pred <- function(pars) {
  data <- bind_cols(data,exp(pars))
  out <- mrgsim(mod, data = data, obsonly = FALSE)
  out$CP
}
```

I'm going to set `conc` to `NA` for dosing records

``` r
data <- mutate(data, conc = if_else(evid==1, as.numeric(NA), conc))

head(data)
```

    ##   ID   WT Dose time  conc cmt  amt evid
    ## 1  1 79.6 4.02 0.00    NA   1 4.02    1
    ## 2  1 79.6 4.02 0.25  2.84   0 0.00    0
    ## 3  1 79.6 4.02 0.57  6.57   0 0.00    0
    ## 4  1 79.6 4.02 1.12 10.50   0 0.00    0
    ## 5  1 79.6 4.02 2.02  9.66   0 0.00    0
    ## 6  1 79.6 4.02 3.82  8.58   0 0.00    0

``` r
fit <- nlme(conc~pred(data_frame(CL = CL,V = V, KA = KA)),
            fixed = CL + V + KA ~ 1, 
            random =  CL + V  ~ 1|ID, 
            start = log(c(CL = 0.1, V = 0.11, KA = 0.1)),
            data = data, na.action = na.pass)

ebe <- exp(coef(fit)) %>% mutate(ID = unique(data$ID))

ebe
```

    ##            CL           V         KA ID
    ## 1  0.02782954 0.019685214 0.08588761  1
    ## 2  0.04010299 0.018948383 0.08588761  2
    ## 3  0.04076367 0.017759260 0.08588761  3
    ## 4  0.03721132 0.030864723 0.08588761  4
    ## 5  0.04267255 0.028607367 0.08588761  5
    ## 6  0.04607574 0.036458917 0.08588761  6
    ## 7  0.04656146 0.059600838 0.08588761  7
    ## 8  0.04418633 0.030989696 0.08588761  8
    ## 9  0.03244727 0.004982723 0.08588761  9
    ## 10 0.03564536 0.055025384 0.08588761 10
    ## 11 0.05089776 0.013596600 0.08588761 11
    ## 12 0.03765904 0.038548238 0.08588761 12

``` r
data <- left_join(data,ebe)
```

    ## Joining, by = "ID"

``` r
head(data)
```

    ##   ID   WT Dose time  conc cmt  amt evid         CL          V         KA
    ## 1  1 79.6 4.02 0.00    NA   1 4.02    1 0.02782954 0.01968521 0.08588761
    ## 2  1 79.6 4.02 0.25  2.84   0 0.00    0 0.02782954 0.01968521 0.08588761
    ## 3  1 79.6 4.02 0.57  6.57   0 0.00    0 0.02782954 0.01968521 0.08588761
    ## 4  1 79.6 4.02 1.12 10.50   0 0.00    0 0.02782954 0.01968521 0.08588761
    ## 5  1 79.6 4.02 2.02  9.66   0 0.00    0 0.02782954 0.01968521 0.08588761
    ## 6  1 79.6 4.02 3.82  8.58   0 0.00    0 0.02782954 0.01968521 0.08588761

``` r
PRED <- mrgsim(mod, data = data, carry.out = "conc") %>% as_data_frame

head(PRED)
```

    ## # A tibble: 6 x 6
    ##      ID  time  conc       EV       CENT        CP
    ##   <dbl> <dbl> <dbl>    <dbl>      <dbl>     <dbl>
    ## 1     1  0.00    NA 4.020000 0.00000000  0.000000
    ## 2     1  0.25  2.84 3.934603 0.07189182  3.652072
    ## 3     1  0.57  6.57 3.827937 0.13144229  6.677209
    ## 4     1  1.12 10.50 3.651316 0.18279744  9.286028
    ## 5     1  2.02  9.66 3.379707 0.20365192 10.345426
    ## 6     1  3.82  8.58 2.895597 0.18611961  9.454793

``` r
ggplot(data = PRED, aes(x = time)) + 
  geom_point(aes(y = conc)) + 
  geom_line(aes(y = CP), col = "firebrick") + 
  facet_wrap(~ID)
```

    ## Warning: Removed 12 rows containing missing values (geom_point).

![](nlme_files/figure-markdown_github-ascii_identifiers/unnamed-chunk-3-1.png)

![unnamed-chunk-1-1](https://user-images.githubusercontent.com/16908301/34192608-a8510776-e514-11e7-88f6-838ae361ee4a.png)

**Comment by mattfidler** [comment]
Thanks for the plug Kyle.

In nlmixr, there are some issues with nlme compared to something like SAEM.

I think this is true of any methods of ode solving using nlme, though I haven't tested it. 

Rik has a nice analysis about nlme performance

https://github.com/nlmixrdevelopment/nlmixr/issues/21#issuecomment-353329426

**Comment by kylebmetrum** [comment]
@mattfidler @JSC67 Yeah, I think when this topic came up on the isop discussion site, either nlmixr wasn't on my radar or maybe it wasn't super public yet.  Just seems like the obvious place to start for these problems.  

@JSC67 The link to the ASBMR poster is here:
http://metrumrg.com/wp-content/uploads/2017/10/Baron_ASBMR_2013.pdf

**Comment by mattfidler** [comment]
@kylebmetrum I understand about not being on the radar.  I didn't really know about what pharmacometric open source software was out there until recently.

**Comment by JSC67** [comment]
Hi Kyle, wow, thank-you for this example.  After I posted this issue, based on your words "If I were to do it over today, I’d probably take the time to look at saemix first." and also Rik Schoemaker's comment "I agree the documentation can be improved big time :-). " (both at http://discuss.go-isop.org/t/mixed-effects-modeling-alternatives-in-r/552), I looked into saemix first and am just now seeing your post.  Do you have any general impressions for one versus the other?  I'm not invested enough into saemix that I won't switch to nlmixr if you'd recommend it.

Thanks also for the updated poster link.

James

**Comment by kylebmetrum** [comment]
@JSC67 It all depends on what you need to accomplish, how much flexibility you need, what your other options are etc.  If you really need to be working in `R`, I'd look at `nlmixr` first.
