### ISSUE TITLE
[F] Change source file assumptions made by mread

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#308]
When calling `mread`, take a look at the `model` argument.  If we think it already includes a file extension (`\\.[[:alphanum:]]{1,3}`) don't tack on the `.cpp` suffix when looking for the model source code.  

### example
```r
mod <- mread("mymodel.txt")
```
will read from `mymodel.txt` file.

```r
mod <- mread("mymodel")
```
will read from `mymodel.cpp` file.

```r
mod <- mread("my.model")
```
will read from `my.model.cpp` file.

**Comment by billdenney** [comment]
Suggestion:  Maybe simplify this so that it first checks if "filename.cpp" exists (because there is a reasonable chance that both "filename" and "filename.cpp" will exist) then "filename", and if neither exists, then give an error.

**Comment by kylebmetrum** [comment]
@billdenney I will re-factor as you suggest.

**Comment by kylebmetrum** [comment]
This behaves as @billdenney suggested.
