### ISSUE TITLE
[bug] evid = 4 for row results in ignoring rate for infusion

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/mrgsolve#31]
example

```
ind_code <- '
$PARAM CL= 1.2, VC=14.3
$CMT GUT CENT
$ADVAN2
$MAIN
pred_CL = CL;
pred_V = VC;
$TABLE table(DV) = CENT/pred_V;
'

ind_model <- mread(model="ind_model", code = ind_code)
ex_id_data <- data.frame(ID = 1, time = c(0, 12, 24), evid = c(4, 1, 1), amt = 10, rate = 10, cmt = 2)

# causes problem with rate not being accepted for first dose only
ind_model %>%
  data_set(ex_id_data) %>% 
  carry.out(evid) %>%
  mrgsim(end= max(ex_id_data$time) + 12,delta=0.1,digits=4) %>% plot


```

![image](https://cloud.githubusercontent.com/assets/3196313/14647278/f8b38d80-062a-11e6-9c16-ac9cf09ab751.png)

```
# change all evid =1 and works fine
ind_model %>%
  data_set(ex_id_data %>% mutate(evid = 1) %>% 
  carry.out(evid) %>%
  mrgsim(end= max(ex_id_data$time) + 12,delta=0.1,digits=4) %>% plot
````

![image](https://cloud.githubusercontent.com/assets/3196313/14647242/d994745a-062a-11e6-8453-8d25ae93f81c.png)

Is this because evid = 4 is nonmem only, or am I misunderstanding how a reset event should behave regarding restarting the amt in the system, or just a bug?

**Comment by kylebmetrum** [comment]
It was a bug: when I went to do `evid==4`, it was doing a bolus after the reset.  In the fix, the reset is done, then `evid` is updated depending on the value of `rate` and the implement routine is called again.

I can't say I know exactly what NONMEM is doing with evid 4, but here is what mrgsolve is doing
1. All compartments are turned on
1. All infusions are stopped
1. All compartments are set to zero
1. The code in `$MAIN` is called again

I'm okay with this now .... except for "All compartments are set to zero".  This will not be correct if a compartment was initialized by hard-coded value in `$INIT` or if a compartment was initialized from `idata_set`.  We can do all of this, but it'll take some time to sit with it.  But it should work if the initial conditions are set in `$MAIN` (which is what I expect most are doing).

**Comment by dpastoor** [comment]
Great thanks - good to know. I think as is now is very reasonable. 

Regarding the idata_set, does that mean if param values were coded in columns for an individual and used in idata_set, if evid=4 is used at say a new occasion, it would clear out the reset param values as per set in idata_set? I presume this is NOT the case, but just want to confirm

Feeding back what you have said, it sounds like it is compartment initialization itself, say starting with some amt in a compartment, that would not be currently re-set and would instead be set to 0.

**Comment by kylebmetrum** [comment]
Just a sec ... https://github.com/metrumresearchgroup/mrgsolve/commit/21af50f028f9ef202c6b25694e95462a611c210b wasn't quite right.

**Comment by kylebmetrum** [comment]
This illustrates some of the options.  I'm not sure everything is totally square here, but I think it's better than I was thinking. 

https://github.com/metrumresearchgroup/mrgsolve/blob/master/demo/evid4.md

The reset event doesn't change any parameter - whether it's updated from `idata_set` or `data_set`.  

For the reset, the code in `$MAIN` gets called with the parameters as-is.  If you had an initial condition set with a parameter listed in `idata_set` (but not in `data_set`), that parameter is in effect for the entirety of that individual's simulation.  So the system (compartments) would get reset just as in that individual's first record.  If that parameter was in a column in `data_set`, that parameter gets updated as the problem goes along.  In that case, the call to `$MAIN` utilizes the value from the most recent update; so it could potentially be different than how the system was initialized at the first record.  

The other `idata_set` issue I was referring to is illustrated here:
https://github.com/metrumresearchgroup/mrgsolve/wiki/init#extra-bonus

If you have a compartment called `CMT` and column in `idata_set` called `CMT_0`, mrgsolve will initialize the compartment with that value ... when `NEWIND` is 0 or 1.  I didn't think this would work, but looking again at what I did ... it does.
