### ISSUE TITLE
realize_addl Requires time column to be lower case in a data.frame

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#314]
Both calls to `arrange_` at the bottom of `realize_addl.data.frame` should use `timecol` instead of `"time"`.

``` r
library(mrgsolve)
realize_addl(data.frame(ID = 1, AMT = 1, TIME = 0, II = 1, ADDL = 1))
#> Error in arrange_impl(.data, dots): cannot arrange column of class 'function' at position 2
realize_addl(data.frame(ID = 1, AMT = 1, time = 0, II = 1, ADDL = 1))
#>   ID AMT time II ADDL
#> 1  1   1    0  0    0
#> 2  1   1    1  0    0
```

**Comment by kylebmetrum** [comment]
@billdenney What version are you using?  This might be already fixed in master.

**Comment by billdenney** [comment]
I'm using 0.8.9.

**Comment by kylebmetrum** [comment]
Ok;  that is probably still an issue in `0.8.10` ... but I recently re-factored that function and it should be fixed in `master`.

**Comment by billdenney** [comment]
At a glance, the refactored code fixed this.

**Comment by kylebmetrum** [comment]
@billdenney BTW ... the function was originally meant for working on `ev` objects that presumably contained dosing information (only).   Come caution is required if using this on data sets where there is covariate information.  And I think the main issue is when there are time-varying covariates (or other time-varying data).  `realize_addl` by definition must add records to your data set at some future time from when they originated.  So if nothing else is time-varying, it won't be a big deal.  But it will if there is time-varying stuff.  Some assumption has to be made about what to do with those data.  In the refactor, I tried to acknowledge that and give some options.  Just take care.

**Comment by billdenney** [comment]
Thanks for the pointer.  I had assumed that it is stable to time invariant values on the same row and that if I needed to use time-variant values, I would need to do something else.

More simply, if it isn't ID, TIME, ADDL, or II (generalized to be upper or lower case), then it is copied to all new rows and maintained on the original row.
