### ISSUE TITLE
mixed order absorption model simulation issue

### ISSUE THREAD

**Issue by RajuKadam** [metrumresearchgroup/mrgsolve#317]
Hi,

I am trying to use the "mrgsolve" for simulation of mixed order absorption model following intramuscular injection.

In my Pop-PK model, I have two sequential absorption process (zero order absorption followed by first order absorption). 

Initially for 320 hours drug get absorbed by zero order absorption (immediate release fraction) then after that first order absorption process start (slow release fraction). Lag time for first order absorption process is 320 hours (Equals to duration for zero order absorption).

Fraction absorbed by zero order process is  0.2  and by first order process is 0.8.

I have a question on how to write the $ ODE  in .cpp file for this mixed order absorption process and how to code these 2 dosing events in "Event" object in R code.

Thanks in advance for your help and guidance.

Best Regards,
Raj

**Comment by kylebmetrum** [comment]
Not sure if this is what you're looking for ... but maybe it will help us get closer to the solution. 

This is a 100 mg dose that is given as a 20 mg portion via zero order infusion over 320 hours and then a 80 mg portion that is absorbed after the 320 hour infusion is finished. 

``` r
library(mrgsolve)
split_dose <- function(amt, frac = 0.2, cmt = c(2, 1), abs_time = 320, ...) {
  
  stopifnot(length(cmt) == 2)
  
  stopifnot(length(frac) == 1)
  
  immed <- ev(amt = amt * frac, cmt = cmt[1], rate = amt * frac/abs_time, 
    ...)
  slow <- ev(amt = amt * (1 - frac), cmt = cmt[2], time = abs_time, ...)
  
  c(immed, slow)
}

e <- split_dose(100, cmt = c("CENT", "DEPOT"))

e
#> Events:
#>   time   cmt amt   rate evid
#> 1    0  CENT  20 0.0625    1
#> 2  320 DEPOT  80 0.0000    1
```

**Comment by riggsmm** [comment]
Hi Raj, another option (general approach) vs actual code: set the full dose into CMTs 1 and 2 , then in $PARAM define F1 and F2 accordingly (e.g., F1 = frac, F2 = 1.0 - frac), frac = 0.2, D1 and ALAG2 = DUR1 (DUR1 = 320).  This would give flexibility in the model to varying fractions by each route and different durations for the 0 and 1st order inputs -- helpful in case those values are not fixed / are values that would be of interest to vary.

And while I was typing this, @kylebmetrum came up with actual code example (pasted below) !!
 
```
> code <- '
$PARAM CL = 1, VC = 20, KA = 1.1, FRAC = 0.2, DUR = 320
 
$CMT DEPOT CENT

$MAIN
F_DEPOT = 1-FRAC;
F_CENT = FRAC;
D_CENT = DUR;
ALAG_DEPOT = DUR;
 
$ODE
dxdt_DEPOT = -KA*DEPOT;
dxdt_CENT = KA*DEPOT - (CL/VC)*CENT;

$SET end = 360, delta = 0.1
 '
 
> library(mrgsolve)
> split_dose <- function(amt, cmt = c("CENT", "DEPOT"), ... ) {
 stopifnot(length(cmt)==2)
  immed <- ev(amt = amt, cmt = cmt[1], rate = -2, ...)
  slow <-  ev(amt = amt, cmt = cmt[2], ...)
  c(immed, slow)
}
 
> e <- split_dose(100)
 
> e
Events:
  time   cmt amt rate evid
1    0  CENT 100   -2    1
2    0 DEPOT 100    0    1
```

**Comment by RajuKadam** [comment]
Dear Kyle and Matthew,

Thanks a lot for your prompt reply.

I have used code sent by Matthew and able to simulate the desired PK
profiles for my Pop-PK model using "mrgsolve" package.

Best Regards,
Raj

**Comment by OliversLab** [comment]
Dear Kyle,

first I wanted to say thank you for this awesome package.

With regards to mixed absorption models, I think I found a bug (although not 100% sure if I overlooked something).
If the order of dosing events is reversed (first row is the DEPOT compartment) the steady state simulation is broken:

```
code <- '
$PARAM CL = 1, VC = 20, KA = 1.1, FRAC = 0.2, DUR = 0.5
 
$CMT DEPOT CENT

$MAIN
F_DEPOT = 1-FRAC;
F_CENT = FRAC;
D_CENT = DUR;
ALAG_DEPOT = DUR;
 
$ODE
dxdt_DEPOT = -KA*DEPOT;
dxdt_CENT = KA*DEPOT - (CL/VC)*CENT;

$SET end = 24, delta = 0.1
 '

library(mrgsolve)
library(dplyr)
split_dose <- function(amt, cmt = c("CENT", "DEPOT"), ... ) {
  stopifnot(length(cmt)==2)
  immed <- ev(amt = amt, cmt = cmt[1], rate = -2, ...)
  slow <-  ev(amt = amt, cmt = cmt[2], ...)
  c(immed, slow)
}

e <- split_dose(100)

mcode("mod", code) -> my_mod


my_mod %>% ev(e %>% mutate(ss=1, ii=24) ) %>% zero_re %>% 
  mrgsim(end=24, delta=0.1) %>% plot()



split_dose_inverse <- function(amt, cmt = c("CENT", "DEPOT"), ... ) {
  stopifnot(length(cmt)==2)
  immed <- ev(amt = amt, cmt = cmt[1], rate = -2, ...)
  slow <-  ev(amt = amt, cmt = cmt[2], ...)
  c(slow, immed)
}

e_inv <- split_dose_inverse(100)

my_mod %>% ev(e_inv %>% mutate(ss=1, ii=24) ) %>% zero_re %>% 
  mrgsim(end=24, delta=0.1) %>% plot()
```


This is not a big deal, unless you remember that the zero order compartment needs to be first in the order.

Cheers,
Oliver
