### ISSUE TITLE
Integration Issue

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#318]
When integrating what should be a relatively straight-forward model (the model is stiff; simulation occurs over months, and there is a ~1-4 hour window of time where there is a change from a biomarker decreasing to increasing), I get the following error:

```r
> simresult <-
+   model %>%
+   data_set(simdataset %>% filter(freq==4, DOSE==60)) %>%
+   mrgsim()
DLSODA-  At T (=R1) and step size H (=R2), the    
      corrector convergence failed repeatedly     
      or with ABS(H) = HMIN   
In above message, R1 =
[1] 1.394785e-229 2.455938e+225
DLSODA-  ISTATE (=I1) illegal.
In above message, I = 
[1] -5
DLSODA-  Run aborted.. apparent infinite loop.    
Error in tran_mrgsim(<S4 object of class "mrgmod">, data = c(70, 70, 70,  : 
  error from XERRWD
```

An issue that I'm having is that it's not a reliable issue:  When I rerun the model several times, I may get different results (just a warning or success):

```r
> simresult <-
+   model %>%
+   data_set(simdataset %>% filter(freq==4, DOSE==60)) %>%
+   mrgsim()
DLSODA-  Warning..Internal T (=R1) and H (=R2) are
      such that in the machine, T + H = T on the next step  
     (H = step size). Solver will continue anyway.
In above message, R1 =
[1] 1.395553e-229 2.455090e+225
DINTDY-  T (=R1) illegal      
In above message, R = 
[1] 2
      T not in interval TCUR - HU (= R1) to TCUR (=R2)      
In above message, R1 =
[1] 1.487716e-297 1.487934e-297
> simresult <-
+   model %>%
+   data_set(simdataset %>% filter(freq==4, DOSE==60)) %>%
+   mrgsim()
> 
```

I don't see any integration controls in mrgsim or update.  Do you  have any insight into how I can either stabilize the model more for mrgsim (e.g. is there some way that I can indicate to the integrator, "here be monsters" when it's going through the switch or where I can decrease the integration time step size throughout)?

**Comment by vjd** [comment]
@billdenney  strange -- I got the exact same error yesterday for a long-running integration, however, when I drop the integration end time (mrgsim(end=<value>)) to be 800 hours instead of 1000, it works fine. 

```
> out1 <- 
+   mod1 %>%
+   ev(amt=200, rate=200) %>%
+   mrgsim(end=1000)
DLSODA-  Warning..Internal T (=R1) and H (=R2) are
      such that in the machine, T + H = T on the next step  
     (H = step size). Solver will continue anyway.
In above message, R1 =
[1] 4.211140e-200 7.402325e-199
DLSODA-  Warning..Internal T (=R1) and H (=R2) are
      such that in the machine, T + H = T on the next step  
     (H = step size). Solver will continue anyway.
In above message, R1 =
[1] 4.211140e-200 7.402325e-199
DLSODA-  Warning..Internal T (=R1) and H (=R2) are
      such that in the machine, T + H = T on the next step  
     (H = step size). Solver will continue anyway.
In above message, R1 =
[1] 4.211140e-200 7.402325e-199
DLSODA-  Warning..Internal T (=R1) and H (=R2) are
      such that in the machine, T + H = T on the next step  
     (H = step size). Solver will continue anyway.
In above message, R1 =
[1] 4.211140e-200 7.402325e-199
DLSODA-  Warning..Internal T (=R1) and H (=R2) are
      such that in the machine, T + H = T on the next step  
     (H = step size). Solver will continue anyway.
In above message, R1 =
[1] 4.211140e-200 7.402325e-199
DLSODA-  Warning..Internal T (=R1) and H (=R2) are
      such that in the machine, T + H = T on the next step  
     (H = step size). Solver will continue anyway.
In above message, R1 =
[1] 4.211140e-200 7.402325e-199
DLSODA-  Warning..Internal T (=R1) and H (=R2) are
      such that in the machine, T + H = T on the next step  
     (H = step size). Solver will continue anyway.
In above message, R1 =
[1] 4.211140e-200 7.402325e-199
DLSODA-  Warning..Internal T (=R1) and H (=R2) are
      such that in the machine, T + H = T on the next step  
     (H = step size). Solver will continue anyway.
In above message, R1 =
[1] 4.211140e-200 7.402325e-199
DLSODA-  Warning..Internal T (=R1) and H (=R2) are
      such that in the machine, T + H = T on the next step  
     (H = step size). Solver will continue anyway.
In above message, R1 =
[1] 4.211140e-200 7.402325e-199
DLSODA-  Warning..Internal T (=R1) and H (=R2) are
      such that in the machine, T + H = T on the next step  
     (H = step size). Solver will continue anyway.
In above message, R1 =
[1] 4.211140e-200 7.402325e-199
DLSODA-  Above warning has been issued I1 times.  
     It will not be issued again for this problem.
In above message, I = 
[1] 10
DINTDY-  T (=R1) illegal      
In above message, R = 
[1] 980.5
      T not in interval TCUR - HU (= R1) to TCUR (=R2)      
In above message, R1 =
[1] -1.896581e+230  7.402325e-199
DINTDY-  T (=R1) illegal      
In above message, R = 
[1] 981
      T not in interval TCUR - HU (= R1) to TCUR (=R2)      
In above message, R1 =
[1] -1.896581e+230  7.402325e-199
DLSODA-  Trouble in DINTDY.  ITASK = I1, TOUT = R1
In above message, I = 
[1] 1
In above message, R = 
[1] 981
DLSODA-  ISTATE (=I1) illegal.
In above message, I = 
[1] -3
DLSODA-  Run aborted.. apparent infinite loop.    
Error in (function (x, data, idata = NULL, carry.out = character(0), mtime = numeric(0),  : 
  error from XERRWD

```

**Comment by billdenney** [comment]
Increasing the density of the output time grid resolved the issue.  Previously, I was simulating `seq(0, 24*168, by=24)`, and switching it to `seq(0, 24*168, by=1)` seemed to fix it.  It'd be nice if I could have the intermediate simulations take a finer time grid (via some integrator setting) and have the output stay as-is.

**Comment by billdenney** [comment]
I spoke too soon.  I still have the issue.

**Comment by kylebmetrum** [comment]
@billdenney @vjd I (already) have some commits to master and dev that give some help with solver settings.  It's probably still not enough, but it is on my radar and working on it.  Pieces are there, but need better integration (so to speak).

@billdenney Try `mrgsim(..., hmax = 0.1)`... that tells the solver not to take a step larger than 0.1 time units; something along the same lines of asking for denser grid. 

I often try this out thinking that it is something problem specific.  But frequently it is an issue with the model: what I coded, something went negative or nan.  But obviously, I can't make that assessment here without seeing the code. 

Sometimes, when the solver failure is random, I have forgotten to write an equation for one of the compartments.  However, there is an audit that is done and hopefully a warning is generated.

```r
> library(mrgsolve)
> 
> code <- '
+ 
+ $CMT A B
+ 
+ $ODE
+ dxdt_A = 0;
+ '
> 
> mod <- mcode("forgot", code)
Compiling forgot ... done.
Warning message:
Audit: missing differential equation(s) for B 
```

**Comment by kylebmetrum** [comment]
@billdenney @vjd 

As usual, if there is any code you can share (here or via email), I'd be happy to take a look.  Or just any additional clue about the model or input data set. I realize we don't have CDA and unlikely that the model can get blasted out to the interweb.

**Comment by billdenney** [comment]
For the audit part, I had assumed that ODEs with `dxdt_CMTNAME=0;` was automatically added.  (Perhaps that's a feature request, perhaps that's a bad idea for a reason I don't see.)

In my model, concentrations are definitely going negative, but I think it' an integration rather than a modeling issue.  My snippet for a relatively standard TMDD model that I think covers the relevant parts is:

```
double CCALC=CMTC/V1;
if (CCALC < 0.0) CCALC = 0.0;
// Michaelis-Menten Elimination for TMDD
double KMMCALC=CMTC*VMAX/(CCALC+KM);
dxdt_CMTC  = - K10*CMTC - KMMCALC - K12*CMTC - K13*CMTC + K21*CMTP1 + K31*CMTP2;
dxdt_CMTP1 =                        K12*CMTC            - K21*CMTP1;
dxdt_CMTP2 =                                   K13*CMTC             - K31*CMTP2;
```

KMMCALC has a KM so low that it is nearly the same as a zero-order elimination.  The relative rate of elimination causes CMTC to go negative (ergo the CCALC protection).

`hmax` didn't fix my issue.  Should it work in mrgsolve 0.8.9?  0.8.10?  Do I need git master?

P.S. "Pieces are there, but need better integration (so to speak)." got a good groan.  :)

**Comment by dpastoor** [comment]
One thought to narrow it down to where it may be blowing up, is to serialize the state at certain time steps (or every one) and just output as text files. It will obviously slow the model down to a crawl, but can see what is going on up to the point of implosion. 

A little more elegant way would be to use actual logging from C++ https://github.com/krlmlr/plogr and just push everything to stdout, - faster but can sometimes be more annoying to parse and share around

**Comment by kylebmetrum** [comment]
Debugging you can use `report` to write to stdout
```r
$ODE
report(SOLVERTIME, CMTC);
```

When `CMTC` goes negative, is it because the value gets super small and randomly goes negative?  if so, `mrgsim(..., atol = 1E-50)`  ... make the absolute tolerance small so you can get the precision of your machine. 

I wonder if negative CMTC is causing problems in other equations?  Maybe more comprehensive protection?

```r
$ODE
double CMTC2 = std::max(0.0, CMTC);
// then use CMTC2 in all the other calculations
```

You have always been able to change solver settings (like `hmax`); just hasn't been super-well documented.  If it didn't work, then that wasn't the problem.

**Comment by billdenney** [comment]
Thank you!

On further investigation, `hmax=0.001` appears to have fixed my issue.  Now that I have smoother integration, I can see that the dynamics of the system goes from CMTC ~= 1 to CMTC < 1e-100 in 4 hours.  This is a real effect based on the observed data-- the little bit of data available in my system for the concentrations < 10 suggest a half-life of ~30 days becomes a half-life of <1 hour in that concentration range, and the transition happens in some amount of time <1 day.

Now that we've solved my issue, I wonder if a section of the user's guide and `mrgsim` help page on integrator settings could help?

**Comment by kylebmetrum** [comment]
@billdenney 

`hmax=0.001` might slow things down quite a bit; not sure if you could get better behavior with lower `atol` and reasonable `hmax`.   Or just call it a day and truncate at zero once CMTC gets less than 1E-10?  Not sure about the other details ... if this would be a bad assumption. 

There is already a section in the user guide:
http://mrgsolve.github.io/user_guide/model-components.html#solver-settings

Obviously, we need the details here.  I tucked this into the package documentation (below) ... again needs some clarification and better integration. 

## mrgmod object documentation
https://github.com/metrumresearchgroup/mrgsolve/blob/dev/R/class_mrgmod.R#L172-L178

## The update help topic
https://github.com/metrumresearchgroup/mrgsolve/blob/dev/R/update.R#L56-L61

## aboutsolver
These link to the aboutsolver help topic that is original DLSODA documentation;  I will 
finish the links to the solver settings there
https://github.com/metrumresearchgroup/mrgsolve/blob/dev/R/update.R#L56-L61

**Comment by billdenney** [comment]
My best of the current tested solutions was setting `atol=1e-50`.

"Or just call it a day and truncate at zero once CMTC gets less than 1E-10?"  I tried that, but the integrator didn't like my attempt.  I think it jumped over 1e-10 too quickly.

Thanks for the documentation updates!

**Comment by billdenney** [comment]
(From my perspective, you can close the issue if you'd like, but maybe you'd like to continue to track the doc need until completed.)

**Comment by kylebmetrum** [comment]
Ok.  Thanks for working it through.  I'll keep this open as a reminder to get more explicit about this in the documentation. 

I frequently have to run with `atol = 1E-50` when doing viral dynamic modeling; the viral load keeps getting smaller and smaller and you just run out of precision.  

Thanks for the question and good discussion.  Hopefully this will help people coming along.
