### ISSUE TITLE
Downloadable User's Guide?

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#319]
Is it possible to download the mrgsolve user's guide as either a .pdf or all the web pages at http://mrgsolve.github.io/user_guide/?

**Comment by dpastoor** [comment]
https://github.com/mrgsolve/mrgsolve.github.io/tree/master/user_guide

I serve it with https://github.com/dpastoor/gows/releases, but anything that will serve http (eg python SimpleHTTPServer etc is fine.

**Comment by dpastoor** [comment]
steps are:

* download gows per platform and add to path (or use homebrew on mac) 
* download/clone mrgsolve repo
* navigate to user_guide folder and run the command `gows`

**Comment by kylebmetrum** [comment]
@billdenney I'll look into rendering that to pdf.  I think I need some dependency to make that happen.

**Comment by kylebmetrum** [comment]
@billdenney 

https://mrgsolve.github.io/user_guide/user-guide.pdf

This now links at the top of the user_guide gitbook page.

**Comment by billdenney** [comment]
That's great!  Thank you!

**Comment by billdenney** [comment]
@kylebaron, the link from the top of the gitbook page doesn't appear to be there anymore (though the link above is up to date).  Any chance that you could re-link it?  (It worked for me now, but I assume that it is helpful for others.)

**Comment by kylebaron** [comment]
Should be back again.

**Comment by billdenney** [comment]
Thanks!
