### ISSUE TITLE
Feature Request: Allow Symbolic CMT Names

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#326]
When building a dataset, I know that I must use numeric names for the CMT rather than symbolic.  But, when I'm working through model revisions, I may want to update the compartment order to make it more logical.

For example, a model I'm working on now with a monoclonal antibody that has only used IV dosing to date wants to simulate potential SC administration.  Logically, I'd add the SC dosing compartment as the first compartment, but then I had to adjust all my code to update the compartment numbering.

As a thought for potential implementation (if this is helpful, go for it, but you know the internals better than I, and there could be a better way):

* If `CMT` is numeric, work as is.
* In the model compilation, generate a CMT name-to-number mapping as a factor.
* If `CMT` is a factor, convert to character (so that the factor order doesn't have to match) and proceed to the character rule below.
* If `CMT` is a character, check if all CMT values are in the levels of the `CMT` name-to-number mapping factor.
    * If yes, map to those factors and internally convert it to a number.
    * If no, throw an error indicating which `unique(CMT)` values don't match.

**Comment by kylebmetrum** [comment]
Hi @billdenney  - 

This has been available for a while.  I don't use it that much, so I'm sure there are some gotchas somewhere.  But in general, mrgsolve will map character compartment names to their numeric equivalent if it finds cmt/CMT that is character in a data set or an event object.  I'll work on the factors.  Please let me know if you find any strange behaviors or errors that don't make sense. 

KTB

``` r
library(mrgsolve)

library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

data <- realize_addl(ev(amt = 100, ii = 24, addl = 3, ID = 1))

data <- mutate(data, cmt = rep(c("EV", "CENT"), 2))

data
#> Events:
#>   ID time  cmt amt ii addl evid
#> 1  1    0   EV 100  0    0    1
#> 2  1   24 CENT 100  0    0    1
#> 3  1   48   EV 100  0    0    1
#> 4  1   72 CENT 100  0    0    1

mod <- mread_cache("pk1", modlib())
#> Compiling pk1 ...
#> done.

mrgsim(mod, data = data, end = 120, delta = 0.1) %>% plot()
```

![](https://i.imgur.com/3jbGpEM.png)

**Comment by billdenney** [comment]
Mea culpa!

Thanks.  The factor part wasn't really a big deal to me.
