### ISSUE TITLE
Issue in runing mrgsolve

### ISSUE THREAD

**Issue by RajuKadam** [metrumresearchgroup/mrgsolve#329]
Hi,
I have recently  installed "mrgsolve" on my system and trying to run it first time. I have downloaded all required R packages. When I am trying to compile the model, I am getting following error message.

"mod <- mcode("demo", code)
Compiling demo ... Warning message:
running command 'make -f "C:/PROGRA~1/R/R-34~1.2/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-34~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="demo-mread-source.dll" WIN=64 TCLBIN=64 OBJECTS="demo-mread-source.o"' had status 127 "

I tested the installation of C++ and Fortran complier installation as below and giving me the message  that "running command 'R CMD shlib R_Cpp_Test.cpp' had status 1 " and "running command 'R CMD shlib R_FORTRAN_Test.f' had status 1 "

> # Test C compiler
> ccode <- 'extern "C" {void test() {double x=2.1; x = x+1;}}\n'
> cat(file="R_Cpp_Test.cpp", ccode)
> system("R CMD shlib R_Cpp_Test.cpp")
'shlib' is not recognized as an internal or external command,
operable program or batch file.
Warning message:
running command 'R CMD shlib R_Cpp_Test.cpp' had status 1 
> fcode <- '
+ subroutine bar(n, x)
+ integer n
+ double precision x(n)
+ integer i
+ do 100 i = 1, n
+ x(i) = x(i) ** 2
+ 100 continue
+ end
+ '
> cat(file="R_FORTRAN_Test.f", fcode)
> system("R CMD shlib R_FORTRAN_Test.f")
'shlib' is not recognized as an internal or external command,
operable program or batch file.
Warning message:
running command 'R CMD shlib R_FORTRAN_Test.f' had status 1 

I am not able to figure out what is error. Any help and guidance on this issue is highly appreciated.

Best Regards,
Raj

**Comment by kylebmetrum** [comment]
Hi @RajuKadam - 

> SHLIB="demo-mread-source.dll" WIN=64 TCLBIN=64 OBJECTS="demo-mread-source.o"' had status 127 

The `status 127` means that R cannot find the toolchain required to install the model.  

Can you tell us:

1. Did you install Rtools? 
1. If so, where is it installed and what version is it
1. What is your `sessionInfo()`
1. What is the result of `Sys.getenv("PATH")`

Thanks,
Kyle
