### ISSUE TITLE
Model compilation error

### ISSUE THREAD

**Issue by indysandaradura** [metrumresearchgroup/mrgsolve#337]
Hi fellow users, I get the following error when trying to compile my model (mrgsolve 0.8.6.9)

Error in modMATRIX(x, context = oclass, ...) : 
  mrgsolve: NA values generated when forming matrix (sigmalist).

Is this to do with how I've specified my OMEGA matrix (below)? Any help would be appreciated!

$OMEGA @block		

  0.14585                                                         
  -0.22850  1.65961                                                 
  -0.10320  0.59704  0.31847                                        
  0.05657  0.08935  0.05669  0.06527                               
  0.06148  0.12982  0.03287  0.06874  0.14519                      
  0.13242 -0.31811 -0.01619  0.08642  0.06991  0.27656             
  0.07435  0.04947  0.06082  0.07887  0.07401  0.12777  0.09990    

$OMEGA
    0.0225      
    0.0225

**Comment by kylebmetrum** [comment]
Hi @indysandaradura  - 
It looks like it's not OMEGA but SIGMA instead??  Can you post those blocks?

>Error in modMATRIX(x, context = oclass, ...) :
>mrgsolve: NA values generated when forming matrix (sigmalist).

Also ... `0.8.6` is pretty old now;  any way you could upgrade?

**Comment by kylebmetrum** [comment]
@indysandaradura Please re-open if you are still having an issue with this.
