### ISSUE TITLE
Problem while installing R packages in R

### ISSUE THREAD

**Issue by Meraki0918** [metrumresearchgroup/mrgsolve#338]
I am using my R studio on EC2 instance  in AWS.

I am trying to install packages in R, but everytime I end up with an error. 

The error is shown below. I would be thankful, if anyone could guide me on how i can resolve the error.

`ERROR: compilation failed for package ‘robustbase’
* removing ‘/home/deepthi/R/x86_64-redhat-linux-gnu-library/3.4/robustbase’
Warning in install.packages :
  installation of package ‘robustbase’ had non-zero exit status
ERROR: dependencies ‘minqa’, ‘RcppEigen’ are not available for package ‘lme4’
* removing ‘/home/deepthi/R/x86_64-redhat-linux-gnu-library/3.4/lme4’
Warning in install.packages :
  installation of package ‘lme4’ had non-zero exit status
ERROR: dependency ‘SparseM’ is not available for package ‘quantreg’
* removing ‘/home/deepthi/R/x86_64-redhat-linux-gnu-library/3.4/quantreg’
Warning in install.packages :
  installation of package ‘quantreg’ had non-zero exit status
ERROR: dependency ‘lmtest’ is not available for package ‘vcd’
* removing ‘/home/deepthi/R/x86_64-redhat-linux-gnu-library/3.4/vcd’
Warning in install.packages :
  installation of package ‘vcd’ had non-zero exit status
ERROR: dependency ‘lme4’ is not available for package ‘pbkrtest’
* removing ‘/home/deepthi/R/x86_64-redhat-linux-gnu-library/3.4/pbkrtest’
Warning in install.packages :
  installation of package ‘pbkrtest’ had non-zero exit status
ERROR: dependencies ‘pbkrtest’, ‘quantreg’ are not available for package ‘car’
* removing ‘/home/deepthi/R/x86_64-redhat-linux-gnu-library/3.4/car’
Warning in install.packages :
  installation of package ‘car’ had non-zero exit status
ERROR: dependencies ‘data.table’, ‘car’, ‘robustbase’, ‘vcd’ are not available for package ‘VIM’
* removing ‘/home/deepthi/R/x86_64-redhat-linux-gnu-library/3.4/VIM’
Warning in install.packages :
  installation of package ‘VIM’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpcH9Dy9/downloaded_packages’`

**Comment by kylebmetrum** [comment]
I don't see the connection here.  Can you try asking on a more-general help list?
https://stat.ethz.ch/mailman/listinfo/r-help
