### ISSUE TITLE
Feature Request: Control of Rate and Duration of Infusion Simultaneously

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#340]
Section 3.2.17 and 3.2.18 of the user guide indicate that `rate` = -1 or -2 enable setting of `D_CMT` or `R_CMT`.  What if I want to set both `D_CMT` and `R_CMT` (ignoring the `amt` column)?

Brainstorming a solution (if it does not already exist), maybe setting `amt=-1` and `rate=-3` or `amt=-1` and (`rate=-1` or `rate=-2`)?

**Comment by kylebaron** [comment]
@billdenney I was originally thinking you'd do this through mtime but might be easier to just model the duration and fiddle with the bioavailability fraction.

``` r
library(rbenchmark)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter

options(mrgsolve.soloc = "build")

code <- '
$PARAM CL = 1, V = 2, D1 = 4, RATE1 = 100
$PKMODEL cmt = "CENT"

$MAIN
D_CENT = D1;
F_CENT = D1*RATE1/self.amt;
'

mod <- mcode_cache("foo", code, delta  = 0.1, end = 10)
#> Creating build directory: build
#> Building foo ... done.

dose <- ev(amt = 100, rate = -2)

mod %>% ev(amt = 100, rate = -2) %>% mrgsim() %>% plot
```

![](https://i.imgur.com/WJNvBLL.png)

``` r

idata <- expand.idata(RATE1 = seq(30,300,50), D1  = c(1,2,3,4))

mod %>% mrgsim_ei(dose,idata,carry_out = "RATE1,D1") %>% 
  plot(CENT~time|factor(D1), scales="same")
```

![](https://i.imgur.com/oeoaR4J.png)

<sup>Created on 2019-06-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
Def some hack in there  but not terrible.  I'd rather stick with this than maintain a new special rate (although if we started needing this all the time, I like the `amt=-3` idea.

**Comment by billdenney** [comment]
Thanks!
