### ISSUE TITLE
Feature Request: Introduce Solver Discontinuities at Times Specified within $MAIN (or $ODE?)

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#343]
Related to #340 

Is there any way to introduce a solver discontinuity from within the model?

Specifically, I'd like to have the ability to turn on/off an infusion during the simulation based on other parameters during the simulation.  I could keep the solver happy by doing a change over the course of e.g. one second with a continuous approximation of the heaviside function, but if there is a simpler and better way to do it, I'd prefer that.

I recognize that the feature request part of this where the discontinuity is introduced in the `$ODE` block may be infeasible, but you never know until you ask.

**Comment by kylebmetrum** [comment]
I can give you a workaround for now in a minute.  

This can definitely be done; it used to be a feature a while ago (before public release) but I dropped it when refactoring the main simulation routine.  

It's definitely a feature that would come in handy for a bunch of different situations. I'm working on something that will (hopefully) be flexible enough across different applications.
