### ISSUE TITLE
Feature Request:  Add More self.* macros

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#345]
Section 3.3 of the User Guide gives a list of all macros.  It would be helpful to add a `self.*` macro for all special-meaning columns.  Specifically, I was just looking for `self.rate`.  While I can't necessarily think of a use right now, it may also be helpful to have `self.ii`, `self.addl`, and probably others that I'm not immediately thinking of.

More generally, since `mrgsolve` only allows one capitalization of parameters that affect modeling, it would be helpful if instead of self.* all potential values were equivalent (`AMT` is identical to `amt` is identical to `self.amt`).

**Comment by kylebaron** [comment]
Done.

**Comment by billdenney** [comment]
Thanks!

**Comment by Eliford** [comment]
Hi @kylebaron 
Thank you for coming up with model event time implementation in mrgsolve. It is very helpful.

I have a similar request for self.* macro (issue #345)
I am trying to write a code that will stop infusion once a critical concentration is reached.

In the code below if delta value is greater than 0.01, infusion is not stopped. Infusion stops only when delta=0.01 or less.

I would love a `self.delta` feature which I can use to update the below section of the code

```
if(TIME == timetostop-0.01) {
stoptime=true;
} else {
stoptime=false;
}
```

The complete code is below


```
infmodel <-"
$PARAM
CL = 1, V = 20, IDUR=6, MAXCP=3, MINTV=0.25

$CMT
CENT

$GLOBAL
#define CP (CENT/V)

$PKMODEL
ncmt=1

$MAIN
if(NEWIND<=1){
     double timetostop = MINTV;
     bool stoptime = false;
    }
if(TIME == timetostop-0.01) {
stoptime=true;
} else {
stoptime=false;
}
  
if(NEWIND>=0){
if(stoptime){
timetostop = timetostop+MINTV;
}
} 

D_CENT=IDUR;
if(stoptime && CP>MAXCP){
mrg::evdata ev(timetostop-MINTV, 4);
        ev.cmt = 1;
        ev.amt= CENT;
        self.mevector.push_back(ev);
}

$CAPTURE
CP
"

mod <- mread(code = infmodel, model = "mod")
mod %>% param(MAXCP=1, IDUR=3, MINTV=0.25) %>% ev(amt=100, cmt="CENT", rate=-2) %>% mrgsim(end=8, delta=0.01) %>% plot(CENT+CP~ time)
```
