### ISSUE TITLE
Error?  Cannot Access RATE Parameter

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#346]
When writing a model, I do not think that I have the ability to access the `RATE` column from the data within the `$MAIN` block.  I want to make another model parameter depend on the rate.

I can't use it within `$MAIN` as a right-hand-side-only variable because during compilation, I get the following error:

```
mod17-mread-source.cpp:110:35: error: 'rate' was not declared in this scope
   if ((EVID == 1 || EVID == 4) && rate > 0) {
```

And, I can't add it as a `$PARAM` becasue during mcode execution, I get:

```
model_raw <- mcode("mod17", mod_17_code)
Error in validObject(.Object) : 
  invalid class “mrgmod” object: 1: Reserved words in model names: rate
invalid class “mrgmod” object: 2: 
```

My workaround was to add another column called `doserate` to the dataset that just duplicates `rate` and then use that new `doserate` column in the model.

**Comment by kylebmetrum** [comment]
That's all right.  I might have gotten too heavy-handed with the reserved words there; not sure that __needs__ to be the case. 

What we were discussing in the other thread: it's be reasonable to expose the infusion rate __at the record level__ in `$MAIN` (so a dosing record with a rate entry ... let you check that value) as well as tinkering with the total current infusion rate in `$ODE`.  Going to try to make that happen.

**Comment by billdenney** [comment]
I think that keeping rate un-writable makes sense, but it can help to read it (at the record level).
