### ISSUE TITLE
Option to force warning no match when attempting to update parameter via param()

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#35]
``` r
code <- '
$PARAM CL = 1, VC=2
$PKMODEL ncmt=1, depot=FALSE
'

mod <- mcode("foo", code)

mod %<>% param(cl = 1.5) ## This will generate a warning
mod %<>% param(cl=1.5, VC = 2.5) ## No warning by design ... there was somethign updated
mod %<>% param(cl=1.5, VC = 2.5, .warn=TRUE) ## propose that an warning is issued here
```

**Comment by dpastoor** [comment]
I see great value in this kind of defensive setup - however I would be surprised if someone actually spent the time to type out warn, I see this error arising from copy-pasting code much more frequently than a person activating it in case of spelling mistakes.

What if instead it was actually an option to set globally, the same 

```
# ggplot style 
mrgsolve_options_set(all = true, # could set all warnings to true
param = true #or just single, where warnings tied to function name in which they are invoked
)

## knitr style
opt_warnings$set(...)
```

**Comment by kylebmetrum** [comment]
Yeah ... one of the features is that this update method will only update parameters that match by name.  There is already a warning if __nothing__ matches.  That seems reasonable ... if you bothered to try it you should be expecting something to match and update.  

I guess if you do `mod %>% param(CL=1, VC=2, ZIPCODE  = 1)` ... and `ZIPCODE` didn't match, you might have high probability that it was a typo.  But otherwise, when scanning lists (`mod %>% param(candidate_list) %>% ` I'd expect there to be lots of non-matches. And silently passing them up is a feature. 

I just got burned by this .... with bigger models, it's harder to think of short informative parameter names and typos or "I thought I spelled it this way but it was that way instead" happen more frequently.  When I was optimizing, I had the parameter name not-quite-right and there was no warning when __every__ name should have matched.  There used to be a `strict` flag that controlled whether you could add to the parameter list or not.  That is always off limits now ... so maybe you could signal a strict update where everything better match.

Another thing I was thinking of is some sort of reconciliation process where you could compare colnames in a data set with the parameter list to see what doesn't match.  It's easy enough to code yourself, but maybe more likely to do it if there is a quick call to make the check just prior to simulating.  I wouldnt' do it absolutely routinely, but for project work or QC it might be helpful.
