### ISSUE TITLE
EVID == 4 ignores ALAG_CMT setting

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/mrgsolve#351]
packageVersion: 0.8.10

noticed when setting EVID = 4, all of a sudden the dosing ignores the lag time and gives it immediately, (when changed back to EVID = 1, the lag time is appropriately present).

Is this expected behavior of EVID 4, or a likely bug. If not expected, I can add a reproducible example.

**Comment by kylebmetrum** [comment]
I believe this has been fixed last December:

``` r
library(mrgsolve)

code <- "
$PARAM CL = 1, V = 10

$PKMODEL cmt = \"CENT\"

$MAIN
ALAG_CENT = 5;
"
mod <- mcode("evid4", code)
#> Compiling evid4 ... done.

e <- seq(ev(amt = 100), wait = 5, ev(amt = 100, evid = 4, addl = 2, ii = 5))

e
#> Events:
#>   time cmt amt evid ii addl
#> 1    0   1 100    1  0    0
#> 2    5   1 100    4  5    2

mod %>% ev(e) %>% mrgsim(delta = 0.1) %>% plot()
```

![](https://i.imgur.com/mVTG7WX.png)

**Comment by kylebmetrum** [comment]
Hopefully we'll get the CRAN version updated soon.
