### ISSUE TITLE
Documentation and Feature Request:  Parameter Extraction

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#354]
On the help page for `param`, an `allparam` function is mentioned, but it is not clear when it would be used.

I found this because I was trying to find a simple way to extract all the parameters (fixed effects defined in the `$PARAM` section, random effects in the `$OMEGA` section, and residual error in the `$SIGMA` section).  And then my next goal was to be able to load all of these back in later (to setup a model in one R script and then use it again in a Shiny app).

My thought was that something like `allparam` could exist (but now with a different name) that does something like:

```
all_param <- function(.x) {
  list(param=param(.x),
       omat=omat(.x),
       smat=smat(.x))
}

`all_param<-` <- function(.x, value) {
  .x %>%
    param(value$param) %>%
    omat(value$omat) %>%
    smat(value$smat)
}
```

(Now, the above code has at least been run once.)

**Comment by billdenney** [comment]
This version works without #355, but my preference would be to implement #355 and use something like the above.

```r
`all_param<-` <- function(.x, value) {
  ret <-
    .x %>%
    param(value$param)
  if (length(value$omat)) {
    ret <-
      ret %>%
      omat(value$omat)
  }
  if (length(value$smat)) {
    ret <-
      ret %>%
      smat(value$smat)
  }
  ret
}
```

**Comment by kylebmetrum** [comment]
@billdenney 

There is a `data` argument to the `update` method where you can pass in a list of stuff to update.  That has been there forever; the documentation currently says it is unused ... but it is.  I'll change that.

Also, I just made some tweaks to the `as.list()` method to make sure the update-able stuff in that list can be passed to the update method. 

So you could do the code below, allowing updates to anything and everything that can be updated:


```r
> mod <- mread("popex", modlib())
Compiling popex ... done.
> 
> l <- as.list(mod)
> 
> mod <- update(mod, 
+               maxsteps = 50000,
+               hmax = 0.1, end = 120, delta = 0.1, 
+               param = list(TVKA = 33.3))
> mod


-------- mrgsolve model object (unix) --------
  Project: /Users/kyleb/Rli...gsolve/models
  source:        popex.cpp
  shared object: popex-so-fa44225051d3 

  Time:          start: 0 end: 120 delta: 0.1
  >              add: <none>
  >              tscale: 1

  Compartments:  GUT CENT [2]
  Parameters:    TVKA TVCL TVV WT [4]
  Omega:         3x3 
  Sigma:         1x1 

  Solver:        atol: 1e-08 rtol: 1e-08
  >              maxsteps: 50000 hmin: 0 hmax: 0.1

> param(mod)

 Model parameters (N=4):
 name value . name value
 TVCL 1     | TVV  24   
 TVKA 33.3  | WT   70   
> 
> mod <- update(mod, data = l)
> 
> mod


-------- mrgsolve model object (unix) --------
  Project: /Users/kyleb/Rli...gsolve/models
  source:        popex.cpp
  shared object: popex-so-fa44225051d3 

  Time:          start: 0 end: 240 delta: 0.5
  >              add: <none>
  >              tscale: 1

  Compartments:  GUT CENT [2]
  Parameters:    TVKA TVCL TVV WT [4]
  Omega:         3x3 
  Sigma:         1x1 

  Solver:        atol: 1e-08 rtol: 1e-08
  >              maxsteps: 2000 hmin: 0 hmax: 0

> 
> param(mod)

 Model parameters (N=4):
 name value . name value
 TVCL 1     | TVV  24   
 TVKA 0.5   | WT   70   
> 
```

**Comment by billdenney** [comment]
@kylebmetrum That covers the need!  Thanks!

(I'll let you close this with the doc update.)

**Comment by billdenney** [comment]
I think that what you committed documented it.
