### ISSUE TITLE
smat with No Matrix to Update and an Empty Matrix Should be OK

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#355]
I have a simple model with no residual error.  When I tried to work on #354, I hit an error that

```
 Error in update_matlist(x@sigma, smat(args$sigma), open = open, context = "smat") : 
  smat: there is no matrix to update 
```

I think that the intent of these lines
https://github.com/metrumresearchgroup/mrgsolve/blob/a31b4bd7c95c72dbaf2babb72e74360135c49e53/R/update.R#L157-L159
could be something like:
```
 if(length(x)==0 & length(y) == 0) {
   message(paste0(context, ": there is no matrix to update and an empty matrix was given"))
   return(x)
 } else if(length(x)==0) {
   stop(paste0(context, ": there is no matrix to update"))
 }
```

**Comment by kylebmetrum** [comment]
@billdenney I think we should drop the the whole check on `length(x)` there.  If there is no matrix list in that slot, then it should be ok to pass in something that matches (a length zero list or a matrix with no rows and no columns ... each will get turned into a length 0 `matlist`).   To be safe, I think we'll still do the check, but return `x` early when  both`length(x)` and `length(y)` are zero.

**Comment by kylebmetrum** [comment]
Behavior changed: bc17344ad2f3aae711e88a80be901e1d7aa6cd73

There will be no error or message if an empty slot is updated with an empty matlist object

**Comment by billdenney** [comment]
Thanks!
