### ISSUE TITLE
Model building problem in mrgsolve

### ISSUE THREAD

**Issue by Veltine** [metrumresearchgroup/mrgsolve#370]
Is there any problem when I installed mrgsolve? I encounter the issue below. Please help me solve this. Thank you,

> library(mrgsolve)
> mod <- mread("popex", modlib())
Compiling popex ... Warning message:
In system(cmd) : 'make' not found
-------------
Error: there was a problem building the model.

**Comment by kylebmetrum** [comment]
Hi @Veltine - 

It looks like you don't have a toolchain installed or something along those lines.  

Can you tell us what R version and operating system you are using?

Did you work through the instructions here?
https://github.com/metrumresearchgroup/mrgsolve/wiki/compilers-and-mrgsolve

Kyle

**Comment by Veltine** [comment]
Hi Kyle:
Thank you for your information. Now, mrgsolve works on my computer. Here is the solution. 

The R-3.5.0 was installed on Win10 system. The installation issue was solved via the following steps. 
1. Reinstall R-3.5.0 and Rtool34 into a directory whose filename (path) has no "space."
2. During Rtool34 installation, edit the system PATH via ticking off "Current Value" 
![1](https://user-images.githubusercontent.com/39159036/39925087-ed4b7074-555c-11e8-9dcb-8c30764b73d3.jpg)

**Comment by kylebmetrum** [comment]
Thanks @Veltine I will be revising the install instructions on the Wiki.  I'll make sure to include a graphic of the check box for the path.  That is definitely getting missed by a lot of people during the install.
