### ISSUE TITLE
Topical administration

### ISSUE THREAD

**Issue by jgonlop3** [metrumresearchgroup/mrgsolve#373]
I would like to know if someone can help me to make a topical administration model. Has someone a model file done? I can use it as an example. Thanks

**Comment by kylebmetrum** [comment]
@jgonlop3 Let us know if you did find a model structure for this.  We'd be happy to help out with the implementation.

**Comment by jgonlop3** [comment]
No, I didnt found a model yet. I need help with this issue, please.
