### ISSUE TITLE
Time above threshold calculation

### ISSUE THREAD

**Issue by indysandaradura** [metrumresearchgroup/mrgsolve#375]
Hi,

I've been trying to capture time above a threshold during an mrgsolve simulation, using a similar method to that which is frequently performed in NONMEM.
ie. http://cognigencorp.com/nonmem/current/2007-December/4125.html

The relevant model code appears below. However, when this is run, COMP4 just accumulates 1s irrespective of whether the conditions are met or not.

Is anyone able to provide me some advice on how to go about this?

regards,

$INIT 

COMP4 = 0

$GLOBAL
 
double MIC1 = 0.125;
double RT1 = 0;
		
$ODE

double C1 = CENT/V1;

if (SOLVERTIME > 1 && C1 > MIC1) RT1 = 1;
dxdt_COMP4 = RT1;

**Comment by kylebmetrum** [comment]
Hi @indysandaradura 

I didn't see any PK getting simulated in your example, so not able to diagnose what might be going on. 

I made the following example that appears to work for a single dose.  But I'm sure with some post-processing you can make it work for any dose.  

  

``` r
library(mrgsolve)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

code <- '
$PARAM CL = 1, V = 2, MIC1 = 0.125

$CMT CENT TAMIC

$ODE

dxdt_CENT = -(CL/V)*CENT;

double C1 = CENT/V;

double RT1 = 0;

if(C1 > MIC1) RT1 = 1.0;

dxdt_TAMIC = RT1;

$CAPTURE C1

'

mod <- mcode_cache("tamic", code)
#> Compiling tamic ...
#> done.

out <- 
  mod %>% 
  ev(amt = 10) %>%
  mrgsim(end = 12, delta = 0.1)

plot(out)
```

![](https://i.imgur.com/y1jONff.png)

``` r

max(out$TAMIC)
#> [1] 7.377759

filter(out, C1 < mod$MIC1)
#> # A tibble: 49 x 5
#>       ID  time   CENT TAMIC     C1
#>    <dbl> <dbl>  <dbl> <dbl>  <dbl>
#>  1     1   0    0      0    0     
#>  2     1   0   10      0    0     
#>  3     1   7.4  0.247  7.38 0.124 
#>  4     1   7.5  0.235  7.38 0.118 
#>  5     1   7.6  0.224  7.38 0.112 
#>  6     1   7.7  0.213  7.38 0.106 
#>  7     1   7.8  0.202  7.38 0.101 
#>  8     1   7.9  0.193  7.38 0.0963
#>  9     1   8    0.183  7.38 0.0916
#> 10     1   8.1  0.174  7.38 0.0871
#> # ... with 39 more rows

filter(out, time > 7.2)
#> # A tibble: 48 x 5
#>       ID  time  CENT TAMIC     C1
#>    <dbl> <dbl> <dbl> <dbl>  <dbl>
#>  1     1   7.3 0.260  7.3  0.130 
#>  2     1   7.4 0.247  7.38 0.124 
#>  3     1   7.5 0.235  7.38 0.118 
#>  4     1   7.6 0.224  7.38 0.112 
#>  5     1   7.7 0.213  7.38 0.106 
#>  6     1   7.8 0.202  7.38 0.101 
#>  7     1   7.9 0.193  7.38 0.0963
#>  8     1   8   0.183  7.38 0.0916
#>  9     1   8.1 0.174  7.38 0.0871
#> 10     1   8.2 0.166  7.38 0.0829
#> # ... with 38 more rows
```

Created on 2018-06-06 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by indysandaradura** [comment]
Thanks @kylebmetrum. This works.
The only change was to move MIC1 and RT1 out of $GLOBAL into $PARAM and $ODE respectively. Can you please explain why they couldn't be defined in $GLOBAL?

**Comment by mrgsolve-sp18** [comment]
Hi @indysandaradura - 

It might have worked putting these items in `$GLOBAL`.  Maybe just reset `RT1` to 0 prior to checking to see if concentration is above MIC (see below)?

Kyle


```r
$INIT

COMP4 = 0

$GLOBAL

double MIC1 = 0.125;
double RT1 = 0;

$ODE

double C1 = CENT/V1;

// RT1 = 0;  /// ADD THIS??
if (SOLVERTIME > 1 && C1 > MIC1) RT1 = 1;
dxdt_COMP4 = RT1;
```
