### ISSUE TITLE
Expanding addl with dplyr grouped dataframes

### ISSUE THREAD

**Issue by drexell0680** [metrumresearchgroup/mrgsolve#376]
Using `realize_addl` on a `data.frame` with a `group` attribute causes [this](https://github.com/metrumresearchgroup/mrgsolve/blob/master/R/realize_addl.R#L77) mutate to break.  Ungrouping `x` should fix it.

**Comment by kylebmetrum** [comment]
Thanks @drexell0680; will get that fixed.
