### ISSUE TITLE
[Question] Consequence of using PKMODEL vs ODE blocks

### ISSUE THREAD

**Issue by nguyenjq** [metrumresearchgroup/mrgsolve#379]
Hi all,

I am seeking a clarification on using PKMODEL vs ODE in mrgsolve. 

Is using PKMODEL in mrgsolve code the same as using the pre-defined ADVAN TRANS routines in NONMEM? For example, in a two compartment model with first order absorption, if I used PKMODEL with depot = TRUE, will this simulation procedure be the same as calling ADVAN4 TRANS4 in NONMEM? Or is this completely different? 

I have a model in NONMEM that I would like to simulate from using mrgsolve and am checking that the model components are correct. I coded the model in mrgsolve using the PKMODEL block, the original NONMEM code is using ADVAN4 TRANS4. I generated simulated data in mrgsolve and used it as my "observed data" to generate a VPC via PsN.  Central tendency is captured well but problems arise at 5% and 95% interval as there are red asterisks outside the boundary of these shaded areas. In addition, PREDs (no variability) are identical in both models. I believe I have implemented it correctly but I am still learning how to use mrgsolve; if they are meant to be the same then there is a mistake on my end with how I coded variability in the model. If not, then should I be using the ODE block instead?

Thanks for all your time and hard work, this is a great learning tool for me.

**Comment by nguyenjq** [comment]
Hi Kyle,

Thanks for providing the document for me to look at and the sample R snippet to illustrate. 

I was wondering if you could provide some further insight on the differences in simulation of the variability components between NONMEM and mrgsolve.  I ask because in the VPC that I generated, the median and 5th percentile is fine. But there is a bit of an overshoot in the 95th percentile that is persistent with multiple simulations in the same observation time points. Are there some internal differences when it comes to simulation of the variability components in NONMEM and mrgsolve, in addition to the points you mentioned above about tolerance and significant digits?

Jenny

**Comment by kylebmetrum** [comment]
Hi Jenny - 

Here is what `mrgsolve` is doing with respect to the random effects in the model.  

Is there any part of the model code that you could share that would help us diagnose this?

Kyle


``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tidyr)
library(mrgsolve)

code <- '
$OMEGA 2.2 3.3 4.4
$SIGMA 5.5 10.1

$CAPTURE ETA(1) ETA(2) ETA(3) EPS(1) EPS(2)
'

mod <- mcode("foo", code, end = -1)
#> Compiling foo ...
#> done.

set.seed(11010)
out <- mrgsim(mod, nid = 1000000)

out %>% 
  as_data_frame %>% 
  summarise_at(vars(ETA_1, ETA_2, ETA_3, EPS_1, EPS_2), funs(mean,var)) %>%
  gather(variable,value,ETA_1_mean:EPS_2_var)
#> # A tibble: 10 x 2
#>    variable        value
#>    <chr>           <dbl>
#>  1 ETA_1_mean  -0.000841
#>  2 ETA_2_mean  -0.000868
#>  3 ETA_3_mean   0.00104 
#>  4 EPS_1_mean  -0.000272
#>  5 EPS_2_mean  -0.00227 
#>  6 ETA_1_var    2.20    
#>  7 ETA_2_var    3.31    
#>  8 ETA_3_var    4.40    
#>  9 EPS_1_var    5.51    
#> 10 EPS_2_var   10.1
```

Created on 2018-06-22 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by kylebmetrum** [comment]
@nguyenjq 
I added this vignette to the nonmem test repo to address your question.  I'll link to the bottom line, but please see the code and models to understand what is going on.  

https://github.com/mrgsolve/nmtests/blob/master/nmtest5.md#plot

Let me know if you have questions about this.

Kyle

**Comment by kylebmetrum** [comment]
Just pushed a new version here:
https://github.com/mrgsolve/nmtests/blob/master/nmtest5.md#plot

There was an (unintended) WT effect on KA in the mrgsolve model but not the nonmem model in the earlier version:
https://github.com/mrgsolve/nmtests/blob/86f75f83904d348bf3669a2e4f3c1442ca35d606/nmtest5.R#L94

**Comment by kylebmetrum** [comment]
Best wishes with your project.  Please let me know if we can be of further help.
