### ISSUE TITLE
[F] PKMODEL library

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#38]
Provide either canned code or pre-compiled models for PK models via `$PKMODEL`.

**Comment by vjd** [comment]
pre-compiled models would be better, however basic, without any covariates etc. you can have a parameter in the function that spits out the "code" in case people want to edit the code and fine tune the model

**Comment by kylebmetrum** [comment]
``` r
library(dplyr)
library(magrittr)
library(mrgsolve)
```

``` r
mod <- pkmodel(ncmt=2, depot=TRUE, end=120)
```

``` r
out <- 
  mod %>% 
  ev(amt=100) %>% 
  obsonly %>%
  mrgsim
```

``` r
head(out)
```

    ## Model:  modpk2po

    ##      ID time      DEPOT     CENT   PERIPH        CP
    ## [1,]  1    0  0.0000000  0.00000  0.00000 0.0000000
    ## [2,]  1    1 33.2871084 39.15440 26.14579 1.9577201
    ## [3,]  1    2 11.0803158 31.60483 54.09221 1.5802417
    ## [4,]  1    3  3.6883167 23.08877 68.64918 1.1544387
    ## [5,]  1    4  1.2277340 18.46244 74.71135 0.9231222
    ## [6,]  1    5  0.4086771 16.34771 76.78205 0.8173857

``` r
tail(out)
```

    ## Model:  modpk2po

    ##        ID time        DEPOT     CENT   PERIPH        CP
    ## [116,]  1  115 1.152784e-53 6.208041 32.34229 0.3104021
    ## [117,]  1  116 3.837285e-54 6.158256 32.08292 0.3079128
    ## [118,]  1  117 1.277321e-54 6.108869 31.82563 0.3054435
    ## [119,]  1  118 4.251833e-55 6.059879 31.57040 0.3029940
    ## [120,]  1  119 1.415312e-55 6.011282 31.31722 0.3005641
    ## [121,]  1  120 4.711166e-56 5.963074 31.06607 0.2981537

``` r
mod %>% Req(CP) %>% init(DEPOT = 1000) %>% mrgsim
```

    ## Model:  modpk2po.cpp 
    ## Dim:    121 x 3 
    ## Time:   0 to 120 
    ## ID:     1 
    ##      ID time     CP
    ## [1,]  1    0  0.000
    ## [2,]  1    1 19.577
    ## [3,]  1    2 15.802
    ## [4,]  1    3 11.544
    ## [5,]  1    4  9.231
    ## [6,]  1    5  8.174
    ## [7,]  1    6  7.710
    ## [8,]  1    7  7.496

**Comment by kylebmetrum** [comment]
Almost put the pre-compiled PKMODEL models in but rolled it back. There is already a pre-compiled house model (that function should probably get exported).  

I have a package full of pre-compiled models; let's put PKMODELs in there and get that released.  Just need some updating.

**Comment by kylebmetrum** [comment]
Precompiled:
https://github.com/metrumresearchgroup/modmrg#pk-model-with-analytical-solution-not-based-on-odes
