### ISSUE TITLE
error message: computation of PTS as per Metrum ISOP PHMX tutorial

### ISSUE THREAD

**Issue by amitvtaneja** [metrumresearchgroup/mrgsolve#381]
Hi all

 I am trying to compute the PTS as per the ISOP Phmx tutorial hand-out from Metrum. When I use the following code(page 11, section 8 ) I get an error message

tvdat<-sumry%>%group_by(arm,N,tvf,tv)%>% do(.density(.$frac))

Error in .density(.$frac) : could not find function ".density"

Secondly in the subsequent ggplot code the layer geom_ribbon_density appears to be a non standard function.

Any help is welcome

Thanks

Amit Taneja

**Comment by kylebmetrum** [comment]
Hi @amitvtaneja  - 

You can get the functions here: 
https://github.com/mrgsolve/examples/blob/master/PrTS/src/functions.R#L6-L9

and here:

https://github.com/mrgsolve/examples/blob/master/PrTS/src/functions.R#L46-L49

Might as well pull the whole file:
https://github.com/mrgsolve/examples/blob/master/PrTS/src/functions.R

clone the repository.

Kyle

**Comment by kylebmetrum** [comment]
Closing this for lack of response.

**Comment by amitvtaneja** [comment]
Sorry for not responding earlier Kyle, and many thanks for providing the custom functions. The required functions work as desired.

best regards

Amit Taneja

**Comment by kylebmetrum** [comment]
Thanks for the report, Amit.  That code is pretty old now so I'm glad it's still holding together (to some degree or another).  Please be in touch if we can help with anything else. 

Kyle
