### ISSUE TITLE
model without $des

### ISSUE THREAD

**Issue by tonggne** [metrumresearchgroup/mrgsolve#382]
Hello Mrgsolve developers,
Can Mrgsove handle model without $des (only $PRED)? such as the model in the following. or mrgsolve requires an ODE component to run? 

Thanks a lot!
Tong

$PRED
KL = exp(THETA(1)+ETA(1))
KD = exp(THETA(2)+ETA(2))
DM= exp(THETA(3)+ETA(3))
BSL  = exp(THETA(4)+ETA(4))
IPRED = BSL * EXP( KL*TIME ) 
IF(TIME.GT.0) IPRED = BSL * EXP( KL*(TIME) - (KD/DM)*(1-EXP(-DM*(TIME))) ) 
Y = IPRED + SQRT(THETA(5)) * ERR(1)

TTG =( LOG(KD) - LOG(KL) )/ DM
W8 = BSL * EXP( KL*(8) - (KD/DM)*(1-EXP(-DM*(8))) )
TR = W8 / BSL
W24 = BSL * EXP( KL*(24) - (KD/DM)*(1-EXP(-DM*(24))) )
TR24 = W24 / BSL
IWRES = (DV - IPRED)/SQRT(THETA(5))

$THETA  
$OMEGA

**Comment by kylebmetrum** [comment]
@tonggne 

I did this pretty quick, but hopefully you get the idea.  I'm 99% sure you could do all of the mrgsolve code in either `$MAIN` or `$TABLE` (it wouldn't matter) ... there is just no separate `$PRED` block like nonmem.  

Kyle


## Original code
```c

$PRED
KL = exp(THETA(1)+ETA(1))
KD = exp(THETA(2)+ETA(2))
DM= exp(THETA(3)+ETA(3))
BSL = exp(THETA(4)+ETA(4))
IPRED = BSL * EXP( KLTIME )
IF(TIME.GT.0) IPRED = BSL * EXP( KL(TIME) - (KD/DM)(1-EXP(-DM(TIME))) )
Y = IPRED + SQRT(THETA(5)) * ERR(1)

TTG =( LOG(KD) - LOG(KL) )/ DM
W8 = BSL * EXP( KL*(8) - (KD/DM)(1-EXP(-DM(8))) )
TR = W8 / BSL
W24 = BSL * EXP( KL*(24) - (KD/DM)(1-EXP(-DM(24))) )
TR24 = W24 / BSL
IWRES = (DV - IPRED)/SQRT(THETA(5))

$THETA
$OMEGA
```

### Translated code
```c
$MAIN
double KL  = exp(THETA1 + ETA(1));
double KD  = exp(THETA2 + ETA(2));
double DM  = exp(THETA3 + ETA(3));
double BSL = exp(THETA4 + ETA(4));

$TABLE
double IPRED = BSL * exp(KLTIME);
if(TIME > 0) IPRED = BSL * exp(KLTIME - (KD/DM)*(1-exp(-DM*TIME)));
double Y = IPRED = sqrt(THETA5)*EPS(1);
double TTG = (log(KD) - log(KL))/DM;
double W8 = BSL * exp(KL*(8) - (KD/DM)*(1-exp(DM*8)));
double TR = W8/BSL;
double W24 = BSL * exp(KL*24 - (KD/DM)*(1-exp(-DM*24)));
double TR24  = W24/BSL;
double IWRES = (DV-IPRED)/sqrt(THETA5);

$THETA

$OMEGA

$SIGMA
1
```

**Comment by tonggne** [comment]
Thanks Kyle for sharing the Mrgsolve code. Two follow-up questions:

1) The Mrgsolve model you suggested will compile but it will not simulate from the data set, because there is no mention of CMT in the dataset. As we know every input dataset has to have an ID, time, and cmt column. 

Below, the name of the data set is "full":  
> out2 <- 
+   mod %>%
+   zero_re %>% 
+   data_set(full) %>% 
+   carry_out(C, ID, TIME, AMT, MDV, EVID) %>% 
+   mrgsim(tad = TRUE) %>% 
+   as.data.frame

**Error in valid_data_set(data, x, verbose) : 
  Could not find cmt/CMT column in data set**

So we add the dummy compartment in both the model file and dataset and it will run without error message.  Does that make sense to you? or there is other workaround?

2) The TIME can be negative in our case, but mrgsolve does not allow TIME < 0 even there is no [ODE]. How to handle the negative TIME in Mrgsolve? Negative TIME is allowed in NONMEM when using $PRED.

Thanks a lot!
Tong

**Comment by kylebmetrum** [comment]
Hi @tonggne  - 

Right.  You do need `CMT` in there.  I've been looking at trying to undo that requirement and I think I can.  Just need some time to make sure all the bases are covered.  But, yes, you should just add a dummy `CMT` column for now. 

You can't have negative time in `mrgsolve`.  I didn't know that it was possible in NONMEM.  The easiest workaround is to set a dummy `TIME` column and then actually use `TIME2` that might have negatives:

```r
library(mrgsolve)
mod <- mrgsolve:::house()
data <- data.frame(ID = 1, time2 = c(-1,0,1,2), time = 0, cmt = 1)  
mrgsim_d(mod,data, carry.out = "TIME = time2")  
```

```r
Model:  housemodel 
Dim:    4 x 8 
Time:   0 to 0 
ID:     1 
     ID time TIME GUT CENT RESP DV CP
[1,]  1    0   -1   0    0   50  0  0
[2,]  1    0    0   0    0   50  0  0
[3,]  1    0    1   0    0   50  0  0
[4,]  1    0    2   0    0   50  0  0
```

I'm sorry for the inconvenience.  I will do my best to relax some of this in next version.

**Comment by kylebmetrum** [comment]
Currently working on a more-formal `$PRED` implementation.

**Comment by tonggne** [comment]
Thanks a lot Kyle! Could you please also indicate what specific
improvements you have made? That will be very helpful

Best,
Tong

Sent from my iPhone

On Aug 2, 2018, at 6:45 AM, Kyle Baron <notifications@github.com> wrote:

Currently working on a more-formal $PRED implementation.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/metrumresearchgroup/mrgsolve/issues/382#issuecomment-409931144>,
or mute the thread

**Comment by tonggne** [comment]
thanks Kyle for all your efforts!

**Comment by kylebmetrum** [comment]
@tonggne 

``` r
library(purrr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(mrgsolve) 
  
code <- '
$PARAM B = -1, beta0 = 100, beta1 = 0.1

$OMEGA 2 0.3

$PRED
double beta0i = beta0 + ETA(1);
double beta1i = beta1*exp(ETA(2));

capture Y = beta0i + beta1i*B;

'

data <- data_frame(A = 1, B = seq(1,100))  %>% ev_rep(ID = seq(100))

head(data)
#>   A B ID
#> 1 1 1  1
#> 2 1 2  1
#> 3 1 3  1
#> 4 1 4  1
#> 5 1 5  1
#> 6 1 6  1

mod <- mcode("pred", code)
#> Compiling pred ...
#> done.

mrgsim_d(mod,data,carry.out = "B") %>% plot(Y ~ B)
```

![](https://i.imgur.com/zygMQfR.png)

Created on 2018-08-28 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
