### ISSUE TITLE
installing modmrg Package

### ISSUE THREAD

**Issue by melagha** [metrumresearchgroup/mrgsolve#389]
I am having problems installing modmrg.
I tried the following command but no success:

library(devtools) 
devtools::install_github("metrumresearchgroup/modmrg", subdir="rdev")

This did not work both on MAC and windows. I keep receiving the following massage:

Downloading GitHub repo metrumresearchgroup/modmrg@master
from URL https://api.github.com/repos/metrumresearchgroup/modmrg/zipball/master
Installation failed: Not Found (404)

I also tried by downloading the package  from (https://github.com/dpastoor/modmrg) and install it using R-studio by browsing to its location but no success.

Your help deeply appreciated

**Comment by melagha** [comment]
I also tried by downloading the package  from (https://github.com/dpastoor/modmrg) and install it using R-studio by browsing to its location but no success.

your help deeply appreciated

**Comment by melagha** [comment]
Thank you Kyle for the prompt response. I will get started as you suggested.
The video link is not working on my side.

Best regards
Mela

**Comment by kylebmetrum** [comment]
Maybe the youtube site (hosting the video) is getting blocked?  The vignette should show the same content.  Feel free to keep asking here if anything is confusing.  I'd be happy to help out.

**Comment by melagha** [comment]
Thank you Kyle, I really appreciate you help.
