### ISSUE TITLE
error in installing mrgsim package

### ISSUE THREAD

**Issue by pharmdwoman** [metrumresearchgroup/mrgsolve#390]
Hi, 

I'm trying to install mrgsim package via devtools, ie,
devtools::install_github("mrgsolve/mrgsim", type="source")

but I got the error message below. Can you please help?

* installing *source* package 'mrgsim' ...
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
Error : object 'ev_seq' is not exported by 'namespace:mrgsolvetk'
ERROR: lazy loading failed for package 'mrgsim'

Thank you,
-Thuy

**Comment by kylebmetrum** [comment]
Thanks @pharmdwoman .  I pushed a change that should fix this.  It is currently passing R CMD check and the handful of unit tests that I created.  Definitely the project is work in progress ... but a lot of work for over a year now :).  Any feedback would be appreciated.  If you could post here: 
https://github.com/mrgsolve/mrgsim/issues

Thanks
