### ISSUE TITLE
knobs on a `data_set`

### ISSUE THREAD

**Issue by vjd** [metrumresearchgroup/mrgsolve#391]
I am trying to get `knobs` working on a `data_set`. I understand clearly how it works on an `ev` object easily as there is no `id` associated with the resulting event row. I am trying to see if `knobs` works on a dataset of different individuals (no random effects) with different doses. Ideally, I would want the set of parameters in knobs to be tested for each ID (or dose in this case). 

```
foo <- data.frame(id = 1:3, amt=c(1000,2000,3000), cmt=1, addl=4, ii=12) %>% as_data_set()
mod <- mrgsolve:::house(end=60)
out <- mod %>% data_set(foo) %>% Req(CP) %>%  knobs(CL=c(1,2,3))
plot(out)

```

It seems like `knobs` includes the `mrgsim` call which is nice. But, using that don't we loose the extra functionality that we get with mrgsim? if I have to e.g. sample only the SS value e.g. at 52 hours, I guess I cannot  use `add = 52`? Otherwise, I could do `mod %>% update(end =52)` and then `filter`?

**Comment by dpastoor** [comment]
you can construct the dataset in knobs as well

```
mod <- mrgsolve:::house(end=60)
out <- mod %>% knobs(amt=c(1000,2000,3000), CL=c(1,3), cmt=1, addl=4, ii=12)
plot(out)
```

**Comment by kylebmetrum** [comment]
Yeah ... knobs really takes responsibility for assembling the data set for you; that's something you have to cede to the function.  But you can pass in stuff to update the model object like you would with `mrgsim`;  like this:

``` r
library(mrgsolve)

out <- 
  mrgsolve:::house() %>%
  knobs(
    CL = 1, amt = 100, ii = 24, 
    addl = 3400, delta = 2, end = 2400
  )

plot(out,CP~time)
```

![](https://i.imgur.com/o9XJRJT.png)

Created on 2018-08-24 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).


I haven't used knobs in ages; I re-factored it a while ago to make it easier to understand what was going to be the result given the inputs (it wasn't super clear all the time).  But so much of the more-recent work has been aimed at making `knobs()` no-longer needed.  

But I do totally understand your use-case. We could really use a function that takes a data set and a pool of parameters and runs that data set for each set of parameters.  You could totally code this on your own, but it's be nice to just hand off to the function and say "take care of this for me".

**Comment by vjd** [comment]
Thanks guys! This helps. I did end up "setting" up a dataframe with multiple parameter combinations of interest. Found that easier, but for one-off dosing, `knobs` is cool!
