### ISSUE TITLE
Documentation Request: Specify mread ... destination

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#393]
Currently, the documentation for `mread()` indicates that the `...` argument is "passed along":

https://github.com/metrumresearchgroup/mrgsolve/blob/73018a1c75809f4362bc6d3a948389897db6511e/R/mread.R#L48

1. If I read the code correctly, the user-facing way that it is passed along is to the `update()` function.  Could you please update the docs to indicate that (and anywhere else that it is passed)?  I see that it is also passed to `check_spec_contents()`, but that appears to be internal.
2. Could you also please link to `update()` and any other function that it may be passed to in the `@seealso` section?

Thanks!

**Comment by kylebmetrum** [comment]
Thanks;  agree that the connection to update needs to be there and probably some more discussion in @details.  I'll get on it.

**Comment by kylebmetrum** [comment]
Done.
