### ISSUE TITLE
as_bmat with correlation

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#394]
Could you please update as_bmat to work with correlation matrices?  I think it would just add making the ... argument pass through to `bmat` on this line:

https://github.com/metrumresearchgroup/mrgsolve/blob/f650c7946cbfa96ad3deabc544b7dbce6e970362/R/matrix.R#L208

**Comment by kylebmetrum** [comment]
We also have these `cmat` functions.  So, how about adding:

``` r
library(mrgsolve) 
  
x <- c(a1 = 0.234, a2 = 0.55, a3 = 1.2, b1 = 1111)



cmat(x[1:3])
#>           [,1]      [,2]
#> [1,] 0.2340000 0.2914481
#> [2,] 0.2914481 1.2000000

as_cmat(x, "a")
#>           [,1]      [,2]
#> [1,] 0.2340000 0.2914481
#> [2,] 0.2914481 1.2000000

as_bmat(x, "a")
#>       [,1] [,2]
#> [1,] 0.234 0.55
#> [2,] 0.550 1.20
```

Created on 2018-09-05 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).


```r
##' @export
##' @rdname as_bmat
as_cmat <- function(x,...) {
  x <- as_bmat(x,...)
  decorr(x)
  x
}

```

**Comment by billdenney** [comment]
That would cover my need.  Thanks!

Perhaps the documentation for `as_bmat()` could also be updated so that:

"..." being "passed along" in the `as_bmat()` documentation could be updated to indicate that it is "passed along to subsequent \code{as_bmat} methods"

I had anticipated that it is passed along to `bmat()` which has the correlation argument when that isn't the case.

**Comment by kylebmetrum** [comment]
Will do.

**Comment by kylebmetrum** [comment]
OIC ... yeah, the doc is plain old wrong there.

**Comment by kylebmetrum** [comment]
I get it now.   Per the original request:

``` r
library(mrgsolve) 
  
x <- c(a1 = 0.234, a2 = 0.55, a3 = 1.2, b1 = 1111)


cmat(x[1:3])
#>           [,1]      [,2]
#> [1,] 0.2340000 0.2914481
#> [2,] 0.2914481 1.2000000

as_cmat(x, "a")
#>           [,1]      [,2]
#> [1,] 0.2340000 0.2914481
#> [2,] 0.2914481 1.2000000

as_bmat(x, "a", correlation = TRUE)
#>           [,1]      [,2]
#> [1,] 0.2340000 0.2914481
#> [2,] 0.2914481 1.2000000

as_bmat(x, "a")
#>       [,1] [,2]
#> [1,] 0.234 0.55
#> [2,] 0.550 1.20
```

Created on 2018-09-05 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by billdenney** [comment]
That looks perfect!
