### ISSUE TITLE
Error: Mat::operator(): index out of bounds ?

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#399]
I recently updated to R 3.5.1 and the current version of `mrgsolve` along with all my other packages.

With the update, a simulation that previously ran now gives the error:

``` r
> vpcresult <-
+   model %>%
+   data_set(vpc_dataset %>%
+              mutate(ID=as.numeric(factor(ID)))) %>%
+   mrgsim()
Dropping non-numeric columns: C EXCLUDE_TEXT Treatment_Text USUBJID CMT_name

error: Mat::operator(): index out of bounds
Error in (function (x, data, idata = null_idata, carry.out = character(0),  : 
  Mat::operator(): index out of bounds
> 
```

I found the issue appears to be the fact that there is an `NA` value for `NDOSE`, and I have the following line in my `$PARAM` and `$MAIN` blocks:

```
$PARAM
...
 NDOSE=-1.0, CYCLE=-1.0, WTKG=-1.0
...
$MAIN
...
double CL = exp(LTVCL + ETA1)*pow((WTKG/70), EWCL)*pow(NDOSE, EDOSECL);
...
```

I can try to work up a reprex, but I think that the solution would be to give a warning or error indicating something like `parameter NDOSE has NA values` for any value in the `$PARAM` block.  I don't think that there would be almost any time that NA values are reasonable to go into the model (but maybe I'm missing a time when it would be valid).

**Comment by kylebmetrum** [comment]
Are you saying that `NDOSE` has `NA` in the input data set?

**Comment by billdenney** [comment]
Yes, `NDOSE` has an `NA` in the input data set.  That is definitely a problem, and it would help if an error message indicated that a column has an NA value (unless there are times when that is valid in which case it should probably be a warning).

**Comment by kylebmetrum** [comment]
We talked about this before in #312 I did add (last night) a check for `NA` in parameter columns.  I'll be refactoring that a touch over the weekend.

But still wondering why its the Armadillo stuff that is complaining.  

I tried to make a small example to get that error back but couldn't.  I'm not sure why this would appear with 3.5 but not with 3.4 (or whatever you were using before).

Seems like we need to keep looking?

**Comment by billdenney** [comment]
I’ll retry to generate a reproducible example.  There is something still going on.

**Comment by billdenney** [comment]
Is there a good way that I could add some form of logging to my model so that I could detect exactly where the error is occurring?  (I will try using the base `print` method via the example at https://mrgsolve.github.io/user_guide/model-specification.html#block-plugin; if there is a better way, please let me know.)

**Comment by kylebmetrum** [comment]
@billdenney https://github.com/metrumresearchgroup/mrgsolve/blob/5d85cd22f4cc02068d4fac292438216a1fafbd20/inst/base/modelheader.h#L163-L168


You can use `report()`

**Comment by kylebmetrum** [comment]
Try logging the ID or  ID number and or the row number

https://mrgsolve.github.io/user_guide/model-specification.html#self.idn

I'm wondering if somehow there is confusion about how many individuals are in the data set or how many rows.

**Comment by billdenney** [comment]
The error occurs 99.7% of the way through the dataset-- I think that you're onto something with there being a row count issue.  How can I find the length of every parameter vector (or any other relevant quantity)?

**Comment by billdenney** [comment]
Alrighty, we are narrowing onto the right solution, I think.

The dataset is 34380 rows long, and the error occurs on an individual that start on row 34261 (19 from the last row), and there are 20 NA values in the `NDOSE` column.  All the NA values are on the last row for the subject. But the error doesn't occur at row 34361.  I thought I could try to convert this to a simple example issue, but I'm not quite able to.

A few things I'd like to test:

1. Is there a way that I can find the length of every parameter vector on input?
2. Is there a way that I can find the length of every parameter vector for the current subject?
3. Might `NA`s be handled differently if they are the first or last row for a subject?

**Comment by kylebmetrum** [comment]
There's only one parameter vector;  the values just get copied over for different subjects at different times.  And it's implemented as an array of doubles.  So fixed size.

I'd really like to know if the error happens __without__ the `NDOSE` column.  It seems like that shouldn't be doing it.  If it's a row number issue, I think the issue is likely elsewhere. But obviously I'm trying to reproduce this as well to get a handle on it.

**Comment by billdenney** [comment]
Shoot!  We are barking up the wrong tree:

```
> vpcresult <-
+   model %>%
+   data_set(vpc_dataset) %>%
+   mrgsim()
Dropping non-numeric columns: C EXCLUDE_TEXT Treatment_Text USUBJID CMT_name

error: Mat::operator(): index out of bounds
Error in (function (x, data, idata = null_idata, carry.out = character(0),  : 
  Mat::operator(): index out of bounds
> 
> vpcresult2 <-
+   model %>%
+   param(NDOSE=1) %>%
+   data_set(vpc_dataset %>% select(-NDOSE)) %>%
+   mrgsim()
Dropping non-numeric columns: C EXCLUDE_TEXT Treatment_Text USUBJID CMT_name

error: Mat::operator(): index out of bounds
Error in (function (x, data, idata = null_idata, carry.out = character(0),  : 
  Mat::operator(): index out of bounds
> 
```

After that test, I also updated the model to remove the NDOSE calculation:

```
  // Model update to remove NDOSE - begin
  // double CL = exp(LTVCL + ETA1)*pow((WTKG/70), EWCL)*pow(NDOSE, EDOSECL);
  double CL = exp(LTVCL + ETA1)*pow((WTKG/70), EWCL);
  //  Model update to remove NDOSE - end
```

And, I still had the same issue.

I then cycled through the columns that have NA values, and it looks like `TIME` has 110 `NA` values, and dropping those fixed the issue:

```
> vpcresult2 <-
+   model %>%
+   data_set(vpc_dataset %>% filter(!is.na(TIME))) %>%
+   mrgsim()
Dropping non-numeric columns: C EXCLUDE_TEXT Treatment_Text USUBJID CMT_name
> vpcresult <-
+   model %>%
+   data_set(vpc_dataset) %>%
+   mrgsim()
Dropping non-numeric columns: C EXCLUDE_TEXT Treatment_Text USUBJID CMT_name

error: Mat::operator(): index out of bounds
Error in (function (x, data, idata = null_idata, carry.out = character(0),  : 
  Mat::operator(): index out of bounds
> 
```

I'm currently working with `mrgsolve` from CRAN, not the current dev version.  The test you just pushed may fix it, but there are times when I think that the `TIME` column could be `NA`.  Off the top of my head, a reset event (`evid=3`) doesn't need a time, and in general, I think that a reset event could accept `NA` in most columns.  Similarly, `evid=2` could probably accept `NA` in a lot of columns (though not `TIME`, I don't think).

**Comment by kylebmetrum** [comment]
Here's what I pushed:

If there are no NA values anywhere, Great!  keep going. 

If there are NA values, first check for parameter columns.  If we find NA there, list each column name where we find NA.  

Next, check ID, TIME, time.  If we find NA there, list the column names. 

If we find NA in parameter columns or ID, TIME, time, we stop and it needs to get fixed.  This would allow you to still have junk columns in the data set that just get ignored.  With the tools we have now, it should go back on the user to fix this stuff. I stopped short of checking EVID, CMT, etc.  I think the simulation can go on without blowing up.  But we'll see if we need to add those. 

I'm also going to make a function that will "audit" your data set.  Look for missing values, check for other inconsistency or weirdness.  That would help people diagnose problems and give them a safer road when using data sets that might be messy, indicating where some clean up might be needed.  I'd even be willing to optionally fill in missing parameter values with the previous value (locf) as a convenience.  I think that would be helpful.  That probably can't / shouldn't be done with the other data items. 

So I think an error is definitely needed with ID and time (as we've seen here).  It probably isn't needed for parameters, but I think 99.9% of the time you want an error there.

**Comment by billdenney** [comment]
I agree that the solution you pushed is probably the right one.  FYI, it's more strict than the current implementation:

```
simdata <-
  bind_rows(
    data.frame(
      ID=1,
      time=0,
      evid=1,
      amt=1,
      cmt="GUT",
      stringsAsFactors=FALSE
    ),
    data.frame(
      ID=1,
      time=c(0, 1, NA, 3:24),
      cmt="CENT",
      evid=0,
      stringsAsFactors=FALSE
    )
  )

result <-
  mrgsolve:::house() %>%
  data_set(simdata) %>%
  mrgsim()

as.data.frame(result)
   ID time           GUT      CENT     RESP         DV         CP
1   1    0  1.000000e+00 0.0000000 50.00000 0.00000000 0.00000000
2   1    0  1.000000e+00 0.0000000 50.00000 0.00000000 0.00000000
3   1    1  3.011942e-01 0.6782976 49.89018 0.03391488 0.03391488
4   1   NA            NA        NA       NA         NA         NA
5   1    3  2.732372e-02 0.8696184 49.78749 0.04348092 0.04348092
6   1    4  8.229748e-03 0.8457402 49.78709 0.04228701 0.04228701
7   1    5  2.478753e-03 0.8100752 49.79408 0.04050376 0.04050376
8   1    6  7.465864e-04 0.7722487 49.80305 0.03861243 0.03861243
9   1    7  2.248669e-04 0.7350921 49.81231 0.03675460 0.03675460
10  1    8  6.772815e-05 0.6993937 49.82134 0.03496969 0.03496969
11  1    9  2.039995e-05 0.6653298 49.82999 0.03326649 0.03326649
12  1   10  6.144320e-06 0.6328951 49.83825 0.03164476 0.03164476
13  1   11  1.850492e-06 0.6020327 49.84611 0.03010163 0.03010163
14  1   12  5.567209e-07 0.5726724 49.85359 0.02863362 0.02863362
15  1   13  1.681300e-07 0.5447432 49.86071 0.02723716 0.02723716
16  1   14  5.089745e-08 0.5181759 49.86749 0.02590880 0.02590880
17  1   15  1.478941e-08 0.4929042 49.87393 0.02464521 0.02464521
18  1   16  4.199990e-09 0.4688650 49.88007 0.02344325 0.02344325
19  1   17  3.933872e-09 0.4459982 49.88590 0.02229991 0.02229991
20  1   18  9.552236e-10 0.4242466 49.89146 0.02121233 0.02121233
21  1   19  3.900175e-10 0.4035559 49.89674 0.02017779 0.02017779
22  1   20  8.267439e-09 0.3838742 49.90176 0.01919371 0.01919371
23  1   21  8.908822e-09 0.3651524 49.90655 0.01825762 0.01825762
24  1   22 -6.334530e-09 0.3473437 49.91110 0.01736719 0.01736719
25  1   23 -1.134397e-08 0.3304036 49.91542 0.01652018 0.01652018
26  1   24 -9.700317e-09 0.3142896 49.91954 0.01571448 0.01571448
```

I'll give it a shot soon.

**Comment by billdenney** [comment]
After some in-person back-and-forth, the issue boiled down to some `NA values for `time`.  That affected the way that `sigma`s were created.

The solution:  Make sure you don't have `NA` in your `time` column when you expect a result.

@kylebmetrum, please correct my summary if I missed anything.
