### ISSUE TITLE
Feature Request: Data Cleaning Requirements and Assistance

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#405]
As discussed in person, my notes are:

* Add a new function named something like `clean_data_set()` (and maybe equivalents for idata and events or they are included in the same function, to be determined).
    * The call would be something like: `clean_data_set(data, model, cleaners=list(cleaning_functions), verbose=TRUE)` where:
        * `data` is a data.frame or similar of the data to be cleaned,
        * `model` is the model (to allow understanding of what parameter names and compartment names are for checking); it is optional and `NULL` disables cleaning for aspects where the model is needed,
        * `cleaners` is a list of functions to apply for cleaning the data, and
        * `verbose` indicates if messages should be printed or if cleaning should just be done without messages.
* Add a new argument to `data_set()` called `clean=c("none", "report", "clean")` (and the same for idata and events) which:
    * Ignores the below choices, if `"none"`,
    * Reports on cleanings that may be required, but does not modify the data, if `"report"`, and
    * Reports and cleans the data, if `"clean"`.

A default set of `cleaners` would be run which may include:
* Are `time` and `ID` columns present, numeric, and with no `NA` values?
* Do the compartment names and/or numbers match the model?
* Is the `time` column sorted correctly?
* Others to grow over time.

**Comment by kylebaron** [comment]
This issue should get moved to what ever package will be hosting this.
