### ISSUE TITLE
What is the best/cleanest way to simulate IOV on a param with many doses

### ISSUE THREAD

**Issue by justinpenz** [metrumresearchgroup/mrgsolve#408]
Using idata with many OCCs and ETAs would be unreasonable due to the number of doses.  

I have been pondering a way to use addl

Thanks

**Comment by mhismail** [comment]
Can't think of a clever way to do this using addl, but you can eliminate the need for using OCCs by using simeta():
``` r
library(mrgsolve)
library(ggplot2)
library(dplyr)

mod_text <-"
$PROB 2 cmt PK Model

$PARAM
CL = 10
VC = 20
VP = 20
Q = 20

$CMT X1 X2 

$MAIN  

if(NEWIND < 2){
  capture CLi = CL * exp(ETA(1));
}

//resimulate eta on dosing records
if(self.amt > 0) {
  simeta();
}

capture CLij = CLi * exp(ETA(2));

$ODE
dxdt_X1 = -(Q + CLij)/VC * X1 + Q/VP * X2;
dxdt_X2 = Q/VC * X1 - Q/VP * X2;

$OMEGA 0.1 0.1

$TABLE
capture PK = X1/VC;
"

mod <- mcode("model", mod_text)
```

### Generate dosing table

``` r
# 10 individuals QD dosing for 10 days
dosing <- data.frame(ID = 1:10, 
                     time = rep(seq(0, 120, 12), each = 10),
                     amt = 100, 
                     cmt = 1, 
                     evid = 1) %>%
          arrange(ID) 
```

### Run simulation

``` r
out <- mod %>%
  data_set(dosing) %>%
  obsonly() %>% 
  mrgsim(end = 144, delta = 1) %>%
  as.data.frame()

print(out[1:24,])
```

    ##    ID time        X1        X2      CLi      CLij         PK
    ## 1   1    0  0.000000  0.000000 10.03666  7.199420 0.00000000
    ## 2   1    1 31.679220 31.401550 10.03666 13.500932 1.58396100
    ## 3   1    2 19.896303 26.551879 10.03666 13.500932 0.99481517
    ## 4   1    3 14.640695 20.287513 10.03666 13.500932 0.73203476
    ## 5   1    4 11.008651 15.324778 10.03666 13.500932 0.55043257
    ## 6   1    5  8.299673 11.560129 10.03666 13.500932 0.41498364
    ## 7   1    6  6.259331  8.718844 10.03666 13.500932 0.31296656
    ## 8   1    7  4.720759  6.575767 10.03666 13.500932 0.23603797
    ## 9   1    8  3.560392  4.959442 10.03666 13.500932 0.17801962
    ## 10  1    9  2.685246  3.740409 10.03666 13.500932 0.13426231
    ## 11  1   10  2.025211  2.821015 10.03666 13.500932 0.10126057
    ## 12  1   11  1.527414  2.127608 10.03666 13.500932 0.07637068
    ## 13  1   12  1.151975  1.604641 10.03666 13.500932 0.05759873
    ## 14  1   13 41.952605 37.312253 10.03666  7.518339 2.09763025
    ## 15  1   14 30.601248 35.427595 10.03666  7.518339 1.53006242
    ## 16  1   15 25.279240 30.312319 10.03666  7.518339 1.26396202
    ## 17  1   16 21.259653 25.610115 10.03666  7.518339 1.06298264
    ## 18  1   17 17.921602 21.601987 10.03666  7.518339 0.89608011
    ## 19  1   18 15.112355 18.217265 10.03666  7.518339 0.75561773
    ## 20  1   19 12.743979 15.362452 10.03666  7.518339 0.63719894
    ## 21  1   20 10.746827 12.954967 10.03666  7.518339 0.53734133
    ## 22  1   21  9.062661 10.924760 10.03666  7.518339 0.45313305
    ## 23  1   22  7.642427  9.212711 10.03666  7.518339 0.38212134
    ## 24  1   23  6.444761  7.768962 10.03666  7.518339 0.32223806

### Plot results

``` r
ggplot(out, aes(x= time, y = PK, color = CLij, group = ID)) + geom_line() +
  facet_wrap("ID")
```
![unnamed-chunk-4-1](https://user-images.githubusercontent.com/27981719/46773593-bc9e9a80-ccc3-11e8-8c29-e6eb8ef99b62.png)

**Comment by justinpenz** [comment]
This is exactly what I needed.  I had not thought of storing CLi upon NEWIND, then using simeps.  Cheers!!!

**Comment by kylebmetrum** [comment]
Very elegant @mhismail  Thanks!

@justinpenz I'm sorry it took so long for a response here.  The post didn't get on my radar.  But worth the wait IMO ... I wouldn't have come up with something this good. 

KTB
