### ISSUE TITLE
Can't use OMEGA values in $GLOBAL?

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#412]
I tried to make the slight modification of "pk3cmt.cpp" to have IIV in VC and CL.  For this, I wanted to simplify life by having VC and CL defined in $GLOBAL.  When I tried this, I got the following error.  While I know I can put the VC and CL definitions in $MAIN, I'm curious why it didn't work in $GLOBAL (and if it's possible to make it work in $GLOBAL).

```
> model_raw <- mread("pk3cmt.cpp")
Compiling pk3cmt_cpp ... c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/BILLDE~1/DOCUME~1/R/WIN-LI~1/3.5/mrgsolve/base" -I"C:/git/prj/CUSTOM~1/AMPHIV~1/AMPH-2~3/Code"        -O2 -Wall  -mtune=generic -c pk3cmt_cpp-mread-source.cpp -o pk3cmt_cpp-mread-source.o
In file included from pk3cmt_cpp-mread-source.cpp:13:0:
pk3cmt_cpp-mread-source.cpp: In function 'void _model_pk3cmt__cpp_ode__(const double*, const double*, double*, const dvec&, const double*)':
C:/Users/BILLDE~1/DOCUME~1/R/WIN-LI~1/3.5/mrgsolve/base/modelheader.h:124:18: error: 'self' was not declared in this scope
 #define _xETA(a) self.ETA[a-1]
                  ^
pk3cmt_cpp-mread-source.cpp:66:15: note: in expansion of macro '_xETA'
 #define IIVCL _xETA(1)
               ^
pk3cmt_cpp-mread-source.cpp:27:22: note: in expansion of macro 'IIVCL'
 #define CL (TVCL*exp(IIVCL))
                      ^
pk3cmt_cpp-mread-source.cpp:81:34: note: in expansion of macro 'CL'
 dxdt_CENT = KA1*EV1 + KA2*EV2 - (CL+CLNL+Q+Q2)*CP  + Q*CT + Q2*CT2;
                                  ^
make: *** [C:/PROGRA~1/R/R-35~1.1/etc/x64/Makeconf:215: pk3cmt_cpp-mread-source.o] Error 1
-------------
Error: there was a problem building the model.
```

(The important bits are below here.)

```
$PARAM @annotated
TVCL :   1 : Clearance (volume/time)
TVVC :  20 : Central volume (volume)

$OMEGA @annotated
IIVCL : 0 : IIV in CL
IIVVC : 0 : IIV in VC

$GLOBAL
#define VC (TVVC*exp(IIVVC))
#define CL (TVCL*exp(IIVCL))
```

(The full model is below.)

```
$PROB
# Model: `pk3cmt`
  - Three-compartment PK model
      - Dual first-order absorption
      - Optional nonlinear clearance from `CENT`
  - Source: `mrgsolve` internal library 
  - Date: `r Sys.Date()`
  - Version: `r packageVersion("mrgsolve")`
  
$PARAM @annotated
TVCL :   1 : Clearance (volume/time)
TVVC :  20 : Central volume (volume)
Q    :   2 : First inter-compartmental clearance (volume/time)
VP   :  10 : First peripheral volume (volume)
Q2   :   2 : Second inter-compartmental clearance (volume/time)
VP2  : 100 : Second peripheral volume (volume) 
KA1  :   1 : Absorption rate constant 1 (1/time)
KA2  :   1 : Absorption rate constant 2 (1/time)
VMAX :   0 : Maximum velocity (mass/time)
KM   :   2 : Michaelis Constant (mass/volume)

$OMEGA @annotated
IIVCL : 0 : IIV in CL
IIVVC : 0 : IIV in VC

$CMT  @annotated
EV1     : First extravascular compartment (mass)
CENT    : Central compartment (mass)
PERIPH  : First peripheral compartment (mass) 
PERIPH2 : Second peripheral compartment (mass)
EV2     : Second extravascular compartment (mass)
  
$GLOBAL
#define VC (TVVC*exp(IIVVC))
#define CL (TVCL*exp(IIVCL))
#define CP (CENT/VC)
#define CT (PERIPH/VP)
#define CT2 (PERIPH2/VP2)
#define CLNL (VMAX/(KM+CP))

$ODE
dxdt_EV1 = -KA1*EV1;
dxdt_EV2 = -KA2*EV2;
dxdt_CENT = KA1*EV1 + KA2*EV2 - (CL+CLNL+Q+Q2)*CP  + Q*CT + Q2*CT2;
dxdt_PERIPH = Q*CP - Q*CT;
dxdt_PERIPH2 = Q2*CP - Q2*CT2;

$CAPTURE @annotated 
CP : Plasma concentration (mass/volume)
```

**Comment by kylebmetrum** [comment]
Why this happens:

When you write:
`#define VC (TVVC*exp(IIVVC))`

the preprocessor goes and finds the `VC` and subs in `(TVVC*exp(IIVVC))`.  So, in `$ODE` it's not `VC` its `(TVVC*exp(IIVVC))`.   `IIVVC` isn't available in `$ODE` ... it's just an alias to an the `ETA()` vector and that data object isn't passed into the `$ODE` function.  It is passed into `$MAIN` (where you typically use it) and `$TABLE` (you might use it or you might want to just capture it ... the action around `capture` and `$CAPTURE` happens in `$TABLE`).  

All of this isn't obvious but that is the way it is.  Of course, you're the one who finds this stuff b/c you're always pushing thing to the limits and beyond ... one of the things I like about you, @billdenney. 

As you note, the overall design and intended use is to do this in `$MAIN`

I know this isn't very satisfying but the closest I could get is this:

``` r
code <- '
$PROB
# Model: `pk3cmt`
- Three-compartment PK model
- Dual first-order absorption
- Optional nonlinear clearance from `CENT`
- Source: `mrgsolve` internal library 
- Date: `r Sys.Date()`
- Version: `r packageVersion("mrgsolve")`

$PARAM @annotated
TVCL :   1 : Clearance (volume/time)
TVVC :  20 : Central volume (volume)
Q    :   2 : First inter-compartmental clearance (volume/time)
VP   :  10 : First peripheral volume (volume)
Q2   :   2 : Second inter-compartmental clearance (volume/time)
VP2  : 100 : Second peripheral volume (volume) 
KA1  :   1 : Absorption rate constant 1 (1/time)
KA2  :   1 : Absorption rate constant 2 (1/time)
VMAX :   0 : Maximum velocity (mass/time)
KM   :   2 : Michaelis Constant (mass/volume)

$OMEGA @annotated
IIVCL : 0 : IIV in CL
IIVVC : 0 : IIV in VC

$CMT  @annotated
EV1     : First extravascular compartment (mass)
CENT    : Central compartment (mass)
PERIPH  : First peripheral compartment (mass) 
PERIPH2 : Second peripheral compartment (mass)
EV2     : Second extravascular compartment (mass)

$GLOBAL
#define CP (CENT/VC)
#define CT (PERIPH/VP)
#define CT2 (PERIPH2/VP2)
#define CLNL (VMAX/(KM+CP))

$MAIN
double VC = TVVC*exp(IIVVC);
double CL  = TVCL*exp(IIVCL);

$ODE
dxdt_EV1 = -KA1*EV1;
dxdt_EV2 = -KA2*EV2;
dxdt_CENT = KA1*EV1 + KA2*EV2 - (CL+CLNL+Q+Q2)*CP  + Q*CT + Q2*CT2;
dxdt_PERIPH = Q*CP - Q*CT;
dxdt_PERIPH2 = Q2*CP - Q2*CT2;

$CAPTURE @annotated 
CP : Plasma concentration (mass/volume)
'

library(mrgsolve)
mod <- mcode("foo", code)
#> Compiling foo ... done.

mrgsim_e(mod, ev(amt = 100), end = 120, delta = 0.1) %>% plot
```

![](https://i.imgur.com/5pwLNYo.png)

Created on 2018-10-24 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by billdenney** [comment]
> one of the things I like about you
:)

Thanks, that is a very clear explanation!  I did something similar to what you suggested (though less elegant since I did it last night before reading your response), and it worked without an issue.

As I try to give back when I can, I wonder if there is a way to make the fact that `OMEGA` values cannot be used directly in `$ODE` and other sections clearer to the user at runtime.

As I'm not the best C++ programmer, I'm not sure (read as, "This is what Bill just Googled, and I'm a better WebMD doctor than I am a Google C++ programmer"), but could you do something like auto-code generation with a static assertion like `#define <insert each of the OMEGA variable names> static_assert(1, "Cannot use <insert OMEGA variable name> in the $ODE section.  Try assigning a value in $MAIN to use it in $ODE.")` (guessed from https://en.wikipedia.org/wiki/C%2B%2B11#Static_assertions)?

And for documentation, I'll suggest a user guide pull request shortly to insert the fact that you can't use $OMEGA values in $ODE in sections 3.2.6 and 3.2.10.

**Comment by kylebmetrum** [comment]
I'll make the add to the user guide.  It's just too messy building that ... I'd rather do it myself.  

The assert thing won't work; but I have some code to tokenize the different blocks and check what is there and not there.  I can add it there.

**Comment by billdenney** [comment]
I didn't try for a build, but I just suggested a couple of tweaks.  Feel free to ignore, modify, or augment the suggestions.

**Comment by kylebmetrum** [comment]
I think this is the best that I'll be able to do for now. 

```r
> code <- '
+ 
+ // [ $PARAM ] 
+ KE=0.1, V2 = 3, KA = 1
+ 
+ $OMEGA
+ 0.1 0.2 0.3 0.4
+ 
+ $MAIN
+ double a = THETA(2);
+ 
+ $ODE
+ double FOO = V2*ETA(1);
+ dxdt_GUT = -KA*GUT;
+ dxdt_CENT = KA*GUT - KE*CENT;
+ double x= ETA(4);
+ 
+ // [ $CMT ] 
+ GUT CENT
+ '
> 
> mod <- mcode("err", code)
 Error: ETA(n) is not allowed in ODE block:
 * FOO = V2*ETA(1);
 * x= ETA(4); 
```
