### ISSUE TITLE
Updating OMEGA values when doing simulations

### ISSUE THREAD

**Issue by abuhelwa** [metrumresearchgroup/mrgsolve#413]
I was wondering if there is a way to update OMEGA values when doing simulations from a PK model. This is of value to explore the effect of BSV on PK. I appreciate that there are different ways of updating model parameters (THETAs) as explained [here](https://mrgsolve.github.io/user_guide/topics.html#topic-parameter-update) but this doesn't seem to be working equally for ETA values. 

Here is a toy example:
   
    ` code <- '
    $THETA @annotated
    15  : CL
    30  : VC
    1.3 : KA

    $SET delta=0.1

    $CMT GUT CENT
    
    $MAIN
    double CL = THETA1*exp(ETA(1));
    double VC = THETA2*exp(ETA(2));
    double KA = THETA3*exp(ETA(3));

    $ODE
    dxdt_GUT = -KA*GUT;
    dxdt_CENT = KA*GUT - (CL/VC)*CENT;

    $OMEGA @block
    0.0772 0.0749  0.0849

    $OMEGA
    0.2
    
    $TABLE
    double CP = CENT/VC;
    
    $CAPTURE CP
    '

    mod <- mcode("demo", code)

    #Checks
    init(mod) #initail conditions
    omat(mod) #omega matrix
    smat(mod) #SIGMA
    param(mod) #parameter values
    
    #update parameters
    mod <- param(mod, THETA1 = 2)
    
    #check
    param(mod) #parameter values`

May be a workaround is to put ETAs as THETAs? interested in your thoughts about this.

NOTE: In fact, I just tried to put ETAs as THETAs and update them but that didn't work either.

**Comment by kylebmetrum** [comment]
Hi @abuhelwa - 

I'm sorry to miss the issue yesterday; I was out of the office. 

Can you try this?

``` r
library(reprex)
library(mrgsolve)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

code <- '
$THETA @annotated
15  : CL
30  : VC
1.3 : KA

$SET delta=0.1

$CMT GUT CENT

$MAIN
double CL = THETA1*exp(ETA(1));
double VC = THETA2*exp(ETA(2));
double KA = THETA3*exp(ETA(3));

$ODE
dxdt_GUT = -KA*GUT;
dxdt_CENT = KA*GUT - (CL/VC)*CENT;

$OMEGA @block
0.0772 0.0749  0.0849

$OMEGA
0.2

$TABLE
double CP = CENT/VC;

$CAPTURE CP
'
```

``` r
mod <- mcode("demo", code)
#> Compiling demo ... done.
```

``` r
omat(mod)
#> $...
#>       [,1]   [,2]
#> 1:  0.0772 0.0749
#> 2:  0.0749 0.0849
#> 
#> $...
#>     [,1]
#> 3:   0.2
```

``` r
omat(mod, list(dmat(1.1,2.2), dmat(3.3))) %>% omat()
#> $...
#>     [,1] [,2]
#> 1:   1.1  0.0
#> 2:   0.0  2.2
#> 
#> $...
#>     [,1]
#> 3:   3.3
```

Do this by name

``` r
code <- '
$OMEGA @block @name first
0.0772 0.0749  0.0849

$OMEGA @name second
0.2

'
```

``` r
mod <- mcode("demo2", code)
#> Compiling demo2 ... done.
```

``` r
omat(mod)
#> $first
#>       [,1]   [,2]
#> 1:  0.0772 0.0749
#> 2:  0.0749 0.0849
#> 
#> $second
#>     [,1]
#> 3:   0.2
```

``` r
omat(mod, second = dmat(3.3), first = dmat(1.1,2.2)) %>% omat()
#> $first
#>     [,1] [,2]
#> 1:   1.1  0.0
#> 2:   0.0  2.2
#> 
#> $second
#>     [,1]
#> 3:   3.3
```

<sup>Created on 2018-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by kylebmetrum** [comment]
`dmat`, `bmat` and `cmat` are just convenience to make an R matrix for input

```
> dmat(1.1, 2.2, 3.3)
     [,1] [,2] [,3]
[1,]  1.1  0.0  0.0
[2,]  0.0  2.2  0.0
[3,]  0.0  0.0  3.3
```

**Comment by abuhelwa** [comment]
Hi @kylebmetrum 

Thank you but still have a question and a comment:
how can you keep in the correlation value between the ETA1 and ETA2 when updating ETAs? Also, I ran into the error below when running sims after updating ETAs.

     ` #update parameters
     mod <- param(mod, THETA1 = 2)
     param(mod) #OK

     Model parameters (N=3):
     name   value . name   value
     THETA1 2     | THETA3 1.3  
     THETA2 30    | .      .    
     
     #update Omega values
     mod <- omat(mod, list(dmat(1.1,2.2), dmat(3.3))) %>% omat()
     omat(mod)
     $ ... 
     [,1] [,2]
    1:   1.1  0.0
    2:   0.0  2.2

    $...
     [,1]
     3:   3.3

     
    #check
    param(mod) #ERROR!
    Problem with names:
    ...,...Error in validObject(.Object) : 
      invalid class “parameter_list” object: 1: invalid names
      invalid class “parameter_list” object: 2: all parameters must be single numbers
     omat(mod)
    $ ... 
    [,1] [,2]
    1:   1.1  0.0
    2:   0.0  2.2

    $...
    [,1] 
    3:   3.3

      out <- 
          mod %>%
         ev(amt=100, ii=24, addl=0) %>%
         mrgsim(end=10, nid=500) %>%
         as.data.frame()
    
     Error in (function (classes, fdef, mtable)  : 
     unable to find an inherited method for function ‘ev’ for signature ‘"omegalist"’
     `

**Comment by kylebmetrum** [comment]
@abuhelwa 

You can make OMEGA any matrix you want;  I showed a diagonal matrix.  Here is a "correlation" matrix ... but `cmat` and `dmat` are __just helper functions; you can create the matrix however you want; it's just a matrix in R__.

``` r
library(mrgsolve)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

code <- '
$THETA @annotated
15  : CL
30  : VC
1.3 : KA

$SET delta=0.1

$CMT GUT CENT

$MAIN
double CL = THETA1*exp(ETA(1));
double VC = THETA2*exp(ETA(2));
double KA = THETA3*exp(ETA(3));

$ODE
dxdt_GUT = -KA*GUT;
dxdt_CENT = KA*GUT - (CL/VC)*CENT;

$OMEGA @block
0.0772 0.0749  0.0849

$OMEGA
0.2

$TABLE
double CP = CENT/VC;

$CAPTURE CP
'
```

``` r
mod <- mcode("demo", code)
#> Compiling demo ... done.
```

``` r
omat(mod)
#> $...
#>       [,1]   [,2]
#> 1:  0.0772 0.0749
#> 2:  0.0749 0.0849
#> 
#> $...
#>     [,1]
#> 3:   0.2
```

``` r
modd <- omat(mod, list(cmat(1.1,0.98765,2.2), dmat(3.3))) 
omat(modd)
#> $...
#>         [,1]     [,2]
#> 1:  1.100000 1.536423
#> 2:  1.536423 2.200000
#> 
#> $...
#>     [,1]
#> 3:   3.3


cov2cor(as.matrix(omat(modd)))
#>        [,1]    [,2] [,3]
#> 1:  1.00000 0.98765    0
#> 2:  0.98765 1.00000    0
#> 3:  0.00000 0.00000    1
```

<sup>Created on 2018-11-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by kylebmetrum** [comment]
For the  error, it is here:

```r
#update Omega values
 mod <- omat(mod, list(dmat(1.1,2.2), dmat(3.3))) %>% omat()
```

After this line, `mod` is a omega matrix object, not a model object.

**Comment by kylebmetrum** [comment]
Please let me know if this handles the issue.  Or keep posting if it still isn't right.

**Comment by kylebmetrum** [comment]
@abuhelwa  Here's the code again with some intermediate steps shown.  The "new" matrices are shown. 

``` r
library(mrgsolve)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

code <- '
$THETA @annotated
15  : CL
30  : VC
1.3 : KA

$SET delta=0.1

$CMT GUT CENT

$MAIN
double CL = THETA1*exp(ETA(1));
double VC = THETA2*exp(ETA(2));
double KA = THETA3*exp(ETA(3));

$ODE
dxdt_GUT = -KA*GUT;
dxdt_CENT = KA*GUT - (CL/VC)*CENT;

$OMEGA @block
0.0772 0.0749  0.0849

$OMEGA
0.2

$TABLE
double CP = CENT/VC;

$CAPTURE CP
'
```

``` r
mod <- mcode("demo", code)
#> Compiling demo ... done.
```

``` r
omat(mod)
#> $...
#>       [,1]   [,2]
#> 1:  0.0772 0.0749
#> 2:  0.0749 0.0849
#> 
#> $...
#>     [,1]
#> 3:   0.2
```

``` r
new_matrix1 <- cmat(1.1,0.98765,2.2)
new_matrix1
#>          [,1]     [,2]
#> [1,] 1.100000 1.536423
#> [2,] 1.536423 2.200000

new_matrix2 <- dmat(3.3)
new_matrix2
#>      [,1]
#> [1,]  3.3

modd <- omat(mod,list(new_matrix1,new_matrix2)) 
omat(modd)
#> $...
#>         [,1]     [,2]
#> 1:  1.100000 1.536423
#> 2:  1.536423 2.200000
#> 
#> $...
#>     [,1]
#> 3:   3.3
```

<sup>Created on 2018-11-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by abuhelwa** [comment]
and then how do you simulate `out` from the same model using the updated omega matrix?

**Comment by abuhelwa** [comment]
@kylebmetrum. Yep! This answers my questions and is working. I think `%>% omat()` in a previous answer `mod <- omat(mod, list(dmat(1.1,2.2), dmat(3.3))) %>% omat()` was causing some issues. All good now. Thank you for yours explanations.
