### ISSUE TITLE
Simulate large model

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#415]
>I still believe the model code is OK

@metelkin There was a mistake in the code (#414).  I realize that the result below as isn't matching what you were posting from other tools.  But I'm sure we can eventually track down that issue as well.  

Anyway ... the size of the model does not seem to be an issue here.  

``` r
library(mrgsolve)
library(withr)


with_dir("/data/th1", {
  mod <- mread("default.cpp.txt")
})
#> Compiling default_cpp_txt ... done.

mrgsim(mod) %>% plot(Th1_ln__amt~time)
```

![](https://i.imgur.com/1bwoFqr.png)

``` r

packageVersion("mrgsolve")
#> [1] '0.8.12'
```

<sup>Created on 2018-11-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by metelkin** [comment]
Wow! Thanks Kyle.
Can you please show me where was the mistake or share the correct model code?

**Comment by kylebmetrum** [comment]
@metelkin Yes; I will post the code and the solution to fix the translator.  

I was comparing the wrong output in the previous comment.  This looks like it matches up with the other tools (using `Th1_ln` rather than `Th1_ln_amt`).  

``` r
library(mrgsolve)
library(withr)


with_dir("/data/th1", {
  mod <- mread("default.cpp.txt")
})
#> Compiling default_cpp_txt ... done.

mrgsim(mod) %>% plot(Th1_ln~time)
```

![](https://i.imgur.com/nqeSxoH.png)

``` r


packageVersion("mrgsolve")
#> [1] '0.8.12.9000'
```

<sup>Created on 2018-11-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>


And a quick comparison shows same results:

```
> filter(mrg, time %in% c(11,100)) %>% select(time,Th1_ln,TNFa_ld)
  time   Th1_ln  TNFa_ld
1   11  743.602 10.93810
2  100 1773.459 34.69451
> filter(rxo, time %in% c(11,100)) %>% select(time,Th1_ln,TNFa_ld)
  time   Th1_ln  TNFa_ld
1   11  743.602 10.93810
2  100 1773.459 34.69451
```

**Comment by kylebmetrum** [comment]
@metelkin 

Basically I moved everything that was in `$MAIN` to `$ODE` ... __except__ for setting the initial conditions.  There were a ton of derived quantities that were functions of one of the state variables and were getting calculated in `$MAIN`.  All of that needs to be in `$ODE`.  I can't tell if any of those calculations really could have been in `$MAIN` (not function of compartment amount) and I'd keep as much in `$MAIN` as you can.  But when I've translated models like this before, I've just thrown pretty much everything in `$ODE` just to be safe. 

I hope this helps.  I've really only been focusing on getting the model to run.  Not if there are other efficiencies to gain in the setup.  But IMO just getting a model this large to run is pretty good ... so maybe we can think of that another day.  I hope this is running properly now.


```
library(mrgsolve)

mod <- mread("fixed.cpp.txt")

mrgsim(mod) %>% plot(Th1_ln~time)
```

[fixed.cpp.txt](https://github.com/metrumresearchgroup/mrgsolve/files/2612013/fixed.cpp.txt)

**Comment by metelkin** [comment]
Thank you so much, Kyle. It works!
It was my fault. I understand the difference between $MAIN and $ODE. It was just misprint in my code generator. Sorry for spending your time.

Anyway now we know that the mrgsolve can adopt large model easily.

BTW playing with solver settings I found that RxODE and mrgsolve give the similar results with approximately runtimes: apx. 3-4 sec for single simulation. The difference was much more significant in code compilation time: 4 hr for RxODE vs 20 sec for mrgsolve. So mrgsolve wins.

I suppose the issue can be closed. Thank you again and best regards to you and your team.

**Comment by mattfidler** [comment]
I'm glad you got it working @metelkin.  `mrgsolve` indeed is an excellent tool.  I'm not surpized that mrgsolve is a bit faster in compiling than RxODE.  However 4 hrs seems a bit extreme.  I have opened an RxODE issue for your extra long compile time.  For me the model you provided did not take nearly that long...

Congrats again.
