### ISSUE TITLE
add help for zero.re() into user guide

### ISSUE THREAD

**Issue by janelleh** [metrumresearchgroup/mrgsolve#416]
I don't see `zero.re()` mentioned anywhere in the current user guide: https://mrgsolve.github.io/user_guide/user-guide.pdf 

Does it exist and I am missing it? If not, request to add to the user guide information about `zero.re()`. How to run a simulation temporarily removing random effects, without hard coding 0's into the model file's omega/sigma matrices, to see the population level output. 

Thanks.

**Comment by kylebmetrum** [comment]
Ok?
https://mrgsolve.github.io/user_guide/topics.html#fill-a-matrix-with-zeros
