### ISSUE TITLE
save and load pre-compiled model

### ISSUE THREAD

**Issue by JasonW000** [metrumresearchgroup/mrgsolve#421]
Is there a way to save a compiled model and then load it without having to recompile?  Similar to the house() model example, but so that one can write and store user written models that are already compiled? 

thanks

**Comment by kylebmetrum** [comment]
Hi @JasonW000  - 

It would be something like this.  Read it once and it gets cached.  Once it is cached you can load it without compiling again. 

I wouldn't think of this as being portable (move around to another computer).  But some checks in there to try to avoid something bad happening.  Anyway, the intention for this was that the build artifacts would just stay where they are until you want to access them again.

Let me know if this gets at what you wanted to do.  

Kyle
  
```r
> library(mrgsolve)
> 
> dir.create("build", showWarnings=FALSE)
> 
> mod <- mread_cache("pk1", modlib(), soloc = "build")
Compiling pk1 ... done.
> 
> list.files("build", recursive=TRUE) %>% cat(sep = "\n")
mrgsolve-so-0.8.12-x86_64-apple-darwin15.6.0/pk1/mrgmod_cache.RDS
mrgsolve-so-0.8.12-x86_64-apple-darwin15.6.0/pk1/pk1-mread-source.cpp
mrgsolve-so-0.8.12-x86_64-apple-darwin15.6.0/pk1/pk1-mread-source.o
mrgsolve-so-0.8.12-x86_64-apple-darwin15.6.0/pk1/pk1-mread-source.so
mrgsolve-so-0.8.12-x86_64-apple-darwin15.6.0/pk1/pk1-so-cc38501e487b.so
> 
> mod <- mread_cache("pk1", modlib(), soloc = "build")
Loading model from cache.
```
