### ISSUE TITLE
Repeat ODEs in a loop?

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#423]
I'm looking to implement a set of ODEs for either a 12- or 29-compartment transit compartment model (https://link.springer.com/article/10.1007%2Fs10928-012-9261-5).  I'm lazy.  :)  I don't want to type nearly the same equations 11 or 28 times, so I'd like to be able to loop over compartments 2 to 29 with math like:

```
$ODE
for (int current_cmt = RBC1; current_cmt < RBC29; current_cmt = current_cmt + 1) {
    dadt[current_cmt + 1] = ktr * (AMOUNT[current_cmt] - AMOUNT[current_cmt + 1]);
}
```

I think it's pretty unlikely that would work, but is there something like that which would work?  The feature here is that I'd like to be able to index into the dadt and amount vectors.

**Comment by kylebmetrum** [comment]
@billdenney  You can definitely do it ... I haven't done it on that scale, but something with the same concept.  But might take a try or two to get it right. 

Use:
```c
_DADT_[n] // for  the nth differential equation (ydot)
_A_[n]    // for the amount in the nth compartment
```

Remember these are zero-indexed and just regular arrays.  So no bound checking.  But you'll know it if you step too far.

**Comment by kylebmetrum** [comment]
This might be helpful too:

Say you have a bunch of compartments; use `$CMTN` to get an alias to the compartments you specify.  

For example:
```
$CMTN  C M

$CMT A B C D E F G H I J K L M N O P
```
You will be able to use:
```
#define N_C 3
#define N_M 13
```
These are zero-indexed so you'll still have to subtract 1 to get it right.  But If `C` through `M`were the transit compartments, you could get the numbers this way.  At least you wouldn't be hacking them in and potentially losing track of where they are.

**Comment by billdenney** [comment]
Thanks!  I'll give it a shot in the next couple of days.

**Comment by kylebmetrum** [comment]
@billdenney 
``` r
library(mrgsolve)
mod <- mread("ncmt", project = "/Users/kyleb/git/m4solve/", audit=FALSE)
#> Building ncmt ... done.
mrgsim(mod, events = ev(amt = 1000), end = 480) %>% plot()
```

![](https://i.imgur.com/vQpAtEC.png)

``` r
see(mod)
#> 
#> Model file:  ncmt.cpp 
#> 
#> $CMTN  C D M
#> 
#> $CMT C D E F G H I J K L M
#> 
#> $PARAM KTR = 0.1
#> 
#> $ODE
#> 
#> dxdt_C = -KTR*C;
#> 
#> for(int i = N_C-1; i < N_M-1; i++) {
#>   _DADT_[i+1] =  KTR*(_A_[i] - _A_[i+1]);
#> }
```

<sup>Created on 2018-12-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by billdenney** [comment]
You rock, thanks!  (I assume that `audit=FALSE` is a requirement for not using the named parameters.)

**Comment by kylebmetrum** [comment]
It'll complain that it can't find some of the differential equations; just a warning though

```
> mod <- mread("ncmt", project = "/Users/kyleb/git/m4solve/")
Building ncmt ... done.Warning message:
Audit: missing differential equation(s) for D,E,F,G,H,I,J,K,L,M 

```

**Comment by kylebmetrum** [comment]
I don't think it is possible to put enough disclaimers in there to protect against the firestorm when stuff blows up.

**Comment by billdenney** [comment]
That's perfectly reasonable.

Related to this, do you think that interface is likely to change?  I'm wondering if code that I write today with it will work with future versions of `mrgsolve`.  (I'm not trying to pin you down-- just wondering if it is stable, probably won't change, or changes are planned with implementation of some upcoming feature.)
