### ISSUE TITLE
Feature Request: Standardize PK Parameter Names in the Standard Model Library

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#426]
Currently in the `modlib()` library, PK parameters and compartments have many different names.  It would be helpful if they were standardized so that users can (i.e. I can :) ) seamlessly transition between e.g. 1, 2, and 3-compartment models and possibly beyond.

Currently the below are used (not a comprehensive list):

* pk1.cpp:
    * Parameters: CL, V, KA
    * Compartment names: EV, CENT
* pk1cmt.cpp:
    * Parameters: CL, VC, KA1, KA2, VMAX, KM
    * Compartment names: EV1, CENT, EV2
* pk1cmt_pop.cpp
    * Ignored Parameters: CL, VC, KA1, KA2 (these don't appear to have an effect on the model)
    * Parameters: F1, TVCL, TVVC, TVKA1, TVKA2, VMAX, KM
        * Omega parameters: numbered (not annotated)
    * Compartment names: EV1, CENT, EV2
* pk2.cpp:
    * Parameters: CL, V2, Q, V3, KA
    * Compartment names: EV, CENT, PERIPH

I'd like to propose that these are standardized to the following:

* Compartments: EV1, EV2, ...; CENT, PERIPH1, PERIPH2, ...
* Parameters (tv to indicate that they are typical values):
    * Absorption: tvF1; tvKA1, tvKA2, ...
    * Volumes: tvVCENT, tvVPERIPH1, tvVPERIPH2
    * Clearances: tvCL, tvQCENTPERIPH1, tvQCENTPERIPH2
* Omegas: all annotated with a prefix of iiv like "iivCL"

The down side to this is it breaks things.  The up side is that it's consistent and simpler to change between models.

**Comment by billdenney** [comment]
Thanks!

**Comment by kylebmetrum** [comment]
Trying to get this as cleaned up and consistent as I can.  But not always super-straight forward, since the parameters for the closed-form models conform to NONMEM conventions etc.  It's not like we can't make a workaround, but would like to think it through a bit.  That said, I did get a bunch of inconsistencies addressed and will continue to think / work on it.

**Comment by billdenney** [comment]
As the `modlib()` models are intended to be examples of how to use the models and how to use `mrgsolve`, it's completely reasonable to keep them so that they mirror normal use of the closed form solutions with the normal parameter names.

**Comment by kylebmetrum** [comment]
I also added a `pk2iv` model that uses `V1` and `V2` rather than `V2` and `V3`.  This might be helpful.  The `pk1` model doesn't change names so the model with oral absorption works the same as the iv model.

**Comment by billdenney** [comment]
Thanks!

**Comment by kylebmetrum** [comment]
Re-opening this as reminder to comb through the Rd files to make sure names match up (pretty sure some don't at this point).
