### ISSUE TITLE
$NMXML example 

### ISSUE THREAD

**Issue by blalovic** [metrumresearchgroup/mrgsolve#431]
Hi Kyle, 

Should code in the $NMXLML example:  

https://github.com/metrumresearchgroup/mrgsolve/wiki/nmxml 

use **s_**(ECL, EVC....) for olabels and slabels rather than s(...)?  This edit worked for me. Otherwise, I get the 
"error in s(ECL, EVC, EKA) : could not find function "s" ".

Cheers,
Bojan

**Comment by kylebmetrum** [comment]
Yes; that `s` function was removed because of this:
https://github.com/tidyverse/ggplot2/issues/2535

Updated:
https://github.com/metrumresearchgroup/mrgsolve/wiki/nmxml/_history

**Comment by kylebmetrum** [comment]
Thank you for the report!
