### ISSUE TITLE
Updating Dose amount as a covariate in PopPK model

### ISSUE THREAD

**Issue by DuyTran16** [metrumresearchgroup/mrgsolve#446]
Can you advise on coding dose amount as a covariate for PK parameter in mrgsolve so that there is no interference with the model name **amt** reserved in mrgsolve  for use in data_set() to update variety of dosing?

For example, Dose on KA (THETA2)

`[MAIN]`
`double LTVKA = THETA1  + THETA2*log(AMT/100);`
`double KA = exp(LTVKA + ETA(1));`

**Comment by DuyTran16** [comment]
Thank you! Using the mutate function solved it!

**Comment by kylebmetrum** [comment]
Or you can do this:

``` r

library(mrgsolve)

library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

data <- expand.ev(amt = c(100, 200, 300))

data
#>   ID amt evid cmt time
#> 1  1 100    1   1    0
#> 2  2 200    1   1    0
#> 3  3 300    1   1    0

code <- '
$PARAM  CL = 1, V = 10, TVKA = 1.2

$PKMODEL cmt = "GUT CENT", depot = TRUE

$PREAMBLE capture last_dose = TVKA;

$MAIN

if(self.amt > 0) last_dose = self.amt;

capture KA = TVKA + (last_dose-200)/200;
'

mod <- mcode("pkmodel", code, delta = 0.1, req = "CENT")
#> Building pkmodel ...
#> done.

mod %>% mrgsim_d(data) %>% plot()
```

![](https://i.imgur.com/ANLtRDt.png)

<sup>Created on 2019-01-31 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
