### ISSUE TITLE
[R] Proper handling of negative istate

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#457]
# Summary 

When lsoda returns with negative istate, issue a message saying what is the value of istate and a brief description of what that means.  Throw an exception at that time. 

The `istate` messages come from ODEPACK DLSODA code and are found in `./src/mrgsolve.cpp`.

See https://github.com/metrumresearchgroup/mrgsolve/commit/84f43b8dddb244afc4873c12dea9db07292aa633

See https://github.com/metrumresearchgroup/mrgsolve/commit/386ee929fed841edc88108a668c2c38386a81e1d

# Tests
- tests/testthat/test-mrgsim.R
  - negative istate is reported issue-457

**Comment by kylebaron** [comment]
This is done with new cxxlsoda.

**Comment by kylebaron** [comment]
See

**Comment by dpastoor** [comment]
LGTM
