### ISSUE TITLE
Imprecise Error with EVID=3

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#460]
Can you please help me not shoot myself in the foot (or at least bandage it quickly after I do so)?  :)

On EVID=3 rows I just set CMT=0.  When I did that, I got the error:

```r
sim_result <-
+   sim_model %>%
+   data_set(sim_data) %>%
+   mrgsim()
Error: Compartment number in dosing record out of range
```

The error actually relates to the reset record, so it would be helpful to find the issue if "dosing record" were changed to "reset record" when that is the intent.

**Comment by kylebmetrum** [comment]
I guess it should be 
`Error: Compartment number in non-observation record out of range`

Basically if you have EVID=0 then you can get away with anything.  If it is any other EVID, you have to put some valid compartment number in there.

**Comment by billdenney** [comment]
That would help, perhaps to drive people more quickly to the issue could:

* The message be `Compartment number in non-observation record (EVID != 0) out of range`
* Is it reasonable to give the data row to point right to the issue: `Compartment number in non-observation record (EVID != 0) out of range in row(s): 1, 5, 23` (detecting the rows)?

Thanks!

**Comment by kylebmetrum** [comment]
@billdenney I don't think we'll be reporting every row that is problematic; but when the first issue comes up, we can error out like this:


```r
> mod <- modlib("pbpk")
> 
> e <- ev(amt = 100, cmt = c(1,2,3,30))
> 
> mod %>% ev(e) %>% mrgsim

 Error: event record cmt must be between 1 and 16: 
 ID 1, row: 4, cmt: 30, evid: 1 
```

Hopefully that'll provide the direction for what this basic issue is.

**Comment by billdenney** [comment]
That does help a lot!

While asking for the world, perhaps the message could be:
```
event record cmt must be between 1 and 16 or the compartment name:
ID 1, row: 4, cmt: 30, evid: 1
```

Adding "or the compartment name" since that is also allowed.

**Comment by kylebaron** [comment]
Closing this; again.  See #534
