### ISSUE TITLE
Feature Request: Assign Omegas (and Sigmas) by Named Matrix

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#461]
In an attempt to generalize my modeling and simulation, I'm trying to come up with some template models.  I've found one area where I think that a change to `omat()` and `smat()` may help.

I'd like to be able to assign to the `$OMEGA` and `$SIGMA` matrices with named matrices such that `omat()` and `smat()` would find the correct value by name and make the assignment for me.  Additionally, it would give an error if a value were nonzero and not assigned (if a value were zero, no message is required).

As a specific example, I have an omega matrix from modeling that looks like the following:

```r
> omegas
       IIVF IIVLAG IIVKA   IIVCL IIVQ2 IIVQ3 IIVVC IIVVP1 IIVVP2
IIVF      0      0     0 0.00000     0     0     0      0      0
IIVLAG    0      0     0 0.00000     0     0     0      0      0
IIVKA     0      0     0 0.00000     0     0     0      0      0
IIVCL     0      0     0 0.09999     0     0     0      0      0
IIVQ2     0      0     0 0.00000     0     0     0      0      0
IIVQ3     0      0     0 0.00000     0     0     0      0      0
IIVVC     0      0     0 0.00000     0     0     0      0      0
IIVVP1    0      0     0 0.00000     0     0     0      0      0
IIVVP2    0      0     0 0.00000     0     0     0      0      0
```

My omega matrix from my model looks like the following:

```r
omat(sim_model_raw)
$`...`
         [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
IIVF:       0    0    0    0    0    0    0    0    0     0
IIVLAG:     0    0    0    0    0    0    0    0    0     0
IIVKA1:     0    0    0    0    0    0    0    0    0     0
IIVKA2:     0    0    0    0    0    0    0    0    0     0
IIVCL:      0    0    0    0    0    0    0    0    0     0
IIVQ:       0    0    0    0    0    0    0    0    0     0
IIVQ2:      0    0    0    0    0    0    0    0    0     0
IIVVC:      0    0    0    0    0    0    0    0    0     0
IIVVP:      0    0    0    0    0    0    0    0    0     0
IIVVP2:     0    0    0    0    0    0    0    0    0     0
```

Not all the names overlap, but I don't care about items that are zero, so the only one that I'd like to assign in this case is the "`IIVCL`" value (yes, this example is trivial and I have spent more time on this GitHub issue than just making the assignment and moving on).

What I'm thinking of is a new `omat_named()` function (and `smat_named()`) that would search for the assignments that were required and make them for you.  These functions would have the light complexity that they would have to search through the list of omega and sigma matrices, but that seems to be overall easy enough.

Does that sound useful to you?  Would you accept a PR for that?

**Comment by billdenney** [comment]
Related to this, is there a supported way to access the internals of an `omegalist` object?  Specifically, I'd like to be able to find out the names of the rows, but I don't see a way to extract the first element while keeping the names attributes.

**Comment by kylebmetrum** [comment]
``` r
library(mrgsolve)

mod <- modlib("popex")
#> Building popex ... done.

names(mod)
#> $param
#> [1] "TVKA" "TVCL" "TVV"  "WT"  
#> 
#> $init
#> [1] "GUT"  "CENT"
#> 
#> $capture
#> [1] "CL"    "V"     "IPRED" "DV"    "ECL"  
#> 
#> $omega
#> [1] "..."
#> 
#> $sigma
#> [1] "..."
#> 
#> $omega_labels
#> $omega_labels[[1]]
#> [1] "ECL" "EV"  "EKA"
#> 
#> 
#> $sigma_labels
#> $sigma_labels[[1]]
#> [1] "."

as.list(mod)$random
#> $omega
#> [1] "..."
#> 
#> $sigma
#> [1] "..."
#> 
#> $omega_labels
#> $omega_labels[[1]]
#> [1] "ECL" "EV"  "EKA"
#> 
#> 
#> $sigma_labels
#> $sigma_labels[[1]]
#> [1] "."
```

<sup>Created on 2019-02-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by billdenney** [comment]
I decided that I really wanted it, so I made this.  Should I add docs and tests and make a PR?

```r
#' Drop rows and columns from x that are all zeros
drop_zero_row_column <- function(x) {
  for (i in rev(seq_len(nrow(x)))) {
    if (all(x[i,] == 0)) {
      x <- x[-i, , drop=FALSE]
    }
  }
  for (j in rev(seq_len(ncol(x)))) {
    if (all(x[,j] == 0)) {
      x <- x[, -j, drop=FALSE]
    }
  }
  x
}

omat_named <- function(.x, .y, ...) {
  UseMethod("omat_named")
}

omat_named.mrgmod <- function(.x, .y, ...) {
  omat(.x, omat_named(.x=omat(.x), .y=.y))
}

omat_named.omegalist <- function(.x, .y, ...) {
  .y <- drop_zero_row_column(.y)
  if (any(names(.y) == ".")) {
    stop("Cannot match a name of '.' for .y.")
  } else if (any(duplicated(names(.y)))) {
    stop("Names of .y cannot be duplicated.")
  }
  for (idx in seq_along(.x)) {
    tmp_omat <-
      matrix(
        data=0,
        nrow=nrow(.x@data[[idx]]),
        ncol=ncol(.x@data[[idx]]),
        dimnames=list(.x@labels[[idx]], .x@labels[[idx]])
      )
    if (any(rownames(.y) %in% rownames(tmp_omat))) {
      tmp_omat <- omat_named(.x=tmp_omat, .y=.y, ...)
    }
    .x@data[[idx]] <- tmp_omat
  }
  .x
}

omat_named.matrix <- function(.x, .y, ...) {
  .y <- drop_zero_row_column(.y)
  if (any(names(.y) == ".")) {
    stop("Cannot match a name of '.' for .y.")
  } else if (any(duplicated(names(.y)))) {
    stop("Names of .y cannot be duplicated.")
  }
  for (i in seq_len(nrow(.y))) {
    for (j in seq_len(ncol(.y))) {
      if (.y[i,j] != 0) {
        row_n <- rownames(.y)[i]
        col_n <- colnames(.y)[j]
        if ((row_n %in% rownames(.x)) &
            (col_n %in% colnames(.x))) {
          .x[row_n, col_n] <- .y[row_n, col_n]
        } else {
          stop("A value was found in .y[", row_n, col_n, "] but .x does not have that row/column name pair.")
        }
      }
    }
  }
  .x
}
```

**Comment by billdenney** [comment]
... and thanks for the names pointer!

**Comment by kylebmetrum** [comment]
Let's just think about this for a minute before putting a PR together.   Trying to think through what features should be delivered and maintained by mrgsolve (forever!) and what should be maintained by the template setup or maybe in an `Extra` type package.

**Comment by dpastoor** [comment]
hey Bill - very cool idea. Here are a couple thoughts on the matter.

From a templating perspective, I dig it, however am concerned that the utility and need is highly dependent on following a particular way of attacking that generalization problem. This is an area that I think we, mostly kyle :-), have tried to keep outside the scope of mrgsolve itself, so as not to overextend the surface area we manage inside the package itself.

To that end, I think this would be more valuable, initially, as an extension package akin to `mmts` -> `mrgsolve model templating system` or the like. That way the entire philosophy could be laid out clearly, with the appropriate helper functions incorporated. This could also provide an opportunity to gather feedback and other use cases to see if there are other alternative approaches that such an effort would inspire surfacing into the open. 

Another benefit the separate package would offer, is this would provide is an opportunity to iron out the apis, function signatures, and other requirements that really only emerge as people test it out. By being in a second package, this minimizes overall churn to mrgsolve core. We even do this with "experimental" functionality like sensitivity analysis https://github.com/mrgsolve/parseq that makes sense to let it collect some real world use before determining the overall future. 

Happy to continue to discuss...

**Comment by billdenney** [comment]
@kylebmetrum and @dpastoor, You raise excellent points that this functionality is not integral to `mrgsolve`.  I've had identical discussions about `PKNCA` functionality and saying "statistics after descriptive statistics of parameters are not part of NCA" and "data management beyond what is required to compute parameters is not part of NCA" and "plotting is (mostly) not part of NCA".

My impression from the above messages is that no `mrgsolveExtra` package currently exists (or more accurately, that there are a few packages like that which have specific, directed functionality and are currently in alpha or beta stage and wouldn't be catch-all style `Extra` packages like might receive this functionality).  Is that correct?
