### ISSUE TITLE
time-varying covariates for dosing events and time-varying covariates in the model

### ISSUE THREAD

**Issue by DuyTran16** [metrumresearchgroup/mrgsolve#467]
For dosing events, could you advise how to code in mrgsolve for dosing that is dependent on weight and age, which varies for every record in the data for each ID?  For example for a one-compartment model with depot, 
10 mg/kg Q24H if AGE2 < 30 weeks, then 15 mg/kg Q24H if AGE2 >= 30 weeks.

I generated **data1** with 5 ID subjects and three covariates:

- Age since birth in days (**AGE1**) up to 50 days

- different starting age in weeks (**AGE2**)

- weight (**WTKG**)

I have something like this for the simulation:

mod %>% 
  zero_re() %>% 
  Req(CP) %>% 
  data_set(data1) %>%
  carry.out(AGE1, AGE2, WTKG) %>%
  **c(ev(amt = 10 * (mod$AGE2 < 30) * mod$WTKG, ii = 24, cmt = 1), 
    ev(amt = 15 * (mod$AGE2 >= 30) * mod$WTKG, ii = 24, cmt = 1)) %>%** 
  mrgsim(start = 0, end = 50*24, delta = 1, tad = T) %>% 
  plot(CP ~ time/ 24)

In addition, is there anything unique in the dataset and model specification code that I should consider for mrgsolve **mod** for these three time-varying covariates so that it changes as a function of Clearance?

**Comment by kylebmetrum** [comment]
Hi @DuyTran16  - 

You have to do the modification to `data1` and bypass the event object.  Can you post that data set as an attachment to a comment? 

Kyle

**Comment by DuyTran16** [comment]
`library(tibble)`

```
data1 <- tibble(ID = rep(1:5, each = 41), 
                GAWKB = rep(c(28, 30, 32, 34, 40), each = 41), # 5 diff gestational age at birth in week
                time = rep(seq(from = 0, to = 24*40, by = 24), times = 5)) %>% # time from 0 h to 960 h (40w)
  mutate(BWGM = case_when(GAWKB == 28 ~ 1147,
                          GAWKB == 30 ~ 1468,
                          GAWKB == 32 ~ 1825,
                          GAWKB == 34 ~ 2206,
                          GAWKB == 40 ~ 3288)) %>% # typical BW in grams given GAWK. 
  mutate(PNAD = time/24) %>% # AGE1
  mutate(GAWK = GAWKB + (PNAD / 7)) %>% # AGE2
  mutate(WTKG = if_else(PNAD <= 120, 
                        true = (BWGM + BWGM*0.005953*PNAD) / 1000,
                        false = (BWGM + BWGM*0.005953*120 + BWGM*0.0015*(PNAD - 119.5) / 1000))) %>% 
  select(-BWGM, - time, -GAWKB)
```

**Comment by kylebmetrum** [comment]
``` r
library(tibble)
library(tidyverse)
library(mrgsolve)

data1 <- tibble(ID = rep(1:5, each = 41), 
                GAWKB = rep(c(28, 30, 32, 34, 40), each = 41), # 5 diff gestational age at birth in week
                time = rep(seq(from = 0, to = 24*40, by = 24), times = 5)) %>% # time from 0 h to 960 h (40w)
  mutate(BWGM = case_when(GAWKB == 28 ~ 1147,
                          GAWKB == 30 ~ 1468,
                          GAWKB == 32 ~ 1825,
                          GAWKB == 34 ~ 2206,
                          GAWKB == 40 ~ 3288)) %>% # typical BW in grams given GAWK. 
  mutate(PNAD = time/24) %>% # AGE1
  mutate(GAWK = GAWKB + (PNAD / 7)) %>% # AGE2
  mutate(WTKG = if_else(PNAD <= 120, 
                        true = (BWGM + BWGM*0.005953*PNAD) / 1000,
                        false = (BWGM + BWGM*0.005953*120 + BWGM*0.0015*(PNAD - 119.5) / 1000))) %>% 
  select(-BWGM, - time, -GAWKB)


ggplot(data1, aes(PNAD,WTKG, group=ID)) + geom_line()
```

![](https://i.imgur.com/lI09MfJ.png)

``` r


data1 <- mutate(
  data1, 
  amt = case_when(
    PNAD < 30 ~ 10*WTKG, 
    PNAD >=30 ~ 15*WTKG
  ), 
  ii = 24, cmt = 1, evid = 1, time = PNAD
)


head(data1)
#> # A tibble: 6 x 9
#>      ID  PNAD  GAWK  WTKG   amt    ii   cmt  evid  time
#>   <int> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1     1     0  28    1.15  11.5    24     1     1     0
#> 2     1     1  28.1  1.15  11.5    24     1     1     1
#> 3     1     2  28.3  1.16  11.6    24     1     1     2
#> 4     1     3  28.4  1.17  11.7    24     1     1     3
#> 5     1     4  28.6  1.17  11.7    24     1     1     4
#> 6     1     5  28.7  1.18  11.8    24     1     1     5


mod <- modlib("pk1") %>% param(CL = 1, V = 0.1)
#> Building pk1 ... done.
mod %>% mrgsim_d(data1, end = 48, delta = 0.1) %>% plot(CP~time)
```

![](https://i.imgur.com/KDZ7WQU.png)

<sup>Created on 2019-03-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DuyTran16** [comment]
Is there anything unique for mrgsolve in the model specification .ccp for time-varying covariates in the model?
I initially bypass the events and had all dosing incorporated in the data and got similar to what you have above before posting, but when compared with NONMEM simulation results, the plots do not match.  I thought maybe there is something unique in mrgsolve that I have to specify for time-varying covariates.

**Comment by kylebmetrum** [comment]
mrgsolve does next observation carried backward, like nonmem does.  If you want to compare with nonmem, you should use identical input data set, no random effects,  control tolerances, control digits in the final answer etc.  And when I say identical input data set, I mean identical. You need to code all of the observations into the data.

**Comment by DuyTran16** [comment]
Thanks Kyle.  I only did the mrgsolve component to the simulation, and I did not do the NONMEM simulation.  I will asked for the NONMEM control stream simulation and dataset  and recode it because both tools should match from you indicated.

**Comment by kylebmetrum** [comment]
I see.  Yeah, I think you need to get your hands on the NONMEM stuff if you want start comparing.  Especially with time-varying covariates, all the details matter when you're comparing outputs. 

Could you please close the issue if this is settled for the time being?  Otherwise, happy to help out with anything else.

**Comment by DuyTran16** [comment]
I was to able to perform the simulation on both mrgsolve and NONMEM with time-varying dose and time-varying covariates.  I coded both control stream and cpp myself to compare.   For mrgsolve, I used the mrgsim_d() variant function to load the completed simulation dataset (ID, time, time-varying covariates, AMT, CMT, EVID, DV, MDV).  For NONMEM, the control stream has parameters fixed and simulation was denoted in the block $SIM.

The output time-varying parameters (CL and V) per each time in the simulation were **identical for both tools.**  NONMEM gave predicted concentrations, but for mrgsolve the predicted concentration (CP and all compartments depot and central) output to **zero** for all time points.    

I wasn't sure if there is anything extra that is missing for mrgsolve specification since I was able to perform simulation before in mrgsolve (but results didn't match NONMEM).  The dataset is identical for both tools with the exception for NONMEM where a dot "." for AMT is indicated for non-dosing events (EVID = 0) and all DV are inputted as ".".  In  mrgsolve, the R object for the simulation dataset has NA instead of  "."

**Comment by kylebmetrum** [comment]
Hi @DuyTran16 - 

Are you saying that all predicted values are zero for the mrgsolve run?  You should post what you're doing there ... I can't guess what it is.

Here is an example of identical input data set that gives identical result:
https://github.com/mrgsolve/nmtests/blob/master/nmtest_time_varying.md

I don't doubt that your input data sets are identical and the result is different.  Just posting this as a positive example showing identical result with identical input. 

I'm not sure if NONMEM will take / update covariate values on dosing records or not.  mrgsolve will do this.  I could see that being one possibility for discrepancy.  You could bridge this gap by putting observation records with each dose that you want to make sure that covariate is as you wish.  But I would still check NONMEM behavior first before going too far down that path. 

Time-varying is tricky.  You might just think about what is the proper way for the system to advance for your problem (as NONMEM does it?  Or as mrgsolve does it? Maybe look at RxODE or mlxR?).  Use the tool that will give you the simulation that you want. 

Maybe we'll try to get the mrgsolve simulation going first?

Kyle

**Comment by DuyTran16** [comment]
The values for predicted amounts in the compartments are zero in mrgsolve, but the PK parameters that I outputted in mrgsolve are identical to NONMEM for each time point.  I think it maybe something minor that I left out in the mrgsolve specification.  
Let me provide you with the example:

```
library(tidyverse)
library(mrgsolve)
```


```
code <- '
$PARAM
TVCL = 0.138 
TVV = 3.5 
TVKA = 0.9
EC50 = 15
PNAD = 13
GAEFFECT = 11
GAWK = 36
WTKG = 2.4

$CMT 
DEPOT
CENT

$PKMODEL 
ncmt = 1, depot = TRUE

$MAIN
double MAT = PNAD / (EC50 + PNAD);
double CL = TVCL * MAT * pow(GAWK / 34, GAEFFECT) * (1 - MAT) * pow(WTKG, 0.75) * exp(ETA(1));
double V = TVV * pow(WTKG, 1) * exp(ETA(2));
double KA = TVKA;

$OMEGA block = TRUE
0.417
0.232 0.509

$TABLE
double CP = (CENT / V);

$CAPTURE 
DEPOT CENT CP CL V KA
'
```

```
BWKG_fun <- function(M_BWG_GA40 = 3000, GAWK){
  BWG_GA = (M_BWG_GA40 / 3705) * exp(0.578 + 0.332*(GAWK + 0.5) - 0.00354*(GAWK + 0.5)^2)
  BWKG = BWG_GA / 1000
}

data1 <- tibble(ID = 1:7, 
               GAWKBirth = seq(from = 28, to = 40, by = 2)) %>%
  expand_observations(times = 1:(30*24)) %>% 
  group_by(ID) %>% 
  mutate(timeH = 0:(30*24), 
         PNAD = timeH / 24, 
         GAWK = GAWKBirth + (PNAD / 7), 
         WTKG = BWKG_fun(GAWK = GAWK), 
         time = if_else(PNAD >= 1, true = 0:(30*24)-24, false = 0)
         ) %>% 
  filter(PNAD >= 1)

Simulation1 <- data1 %>%
  mutate(EVID = if_else((timeH %% 24) == 0, true = 1, false = 0)) %>% 
  mutate(CMT = if_else(EVID == 1, true = 1, false = 2)) %>%
  mutate(AMT = case_when(EVID == 1 & GAWK < 30 ~ 10*WTKG, 
                         EVID == 1 & GAWK >= 30 ~ 15*WTKG)) %>%
  mutate(DV = NA) %>%
  mutate(MDV = 1)


mod <- mread(model,  project)

mrgsolve_sim1 <- mod %>% 
  zero_re() %>%
  Req(DEPOT, CENT, CP, CL, V, KA) %>% 
  carry.out(GAWKBirth, GAWK, PNAD, WTKG) %>%
  mrgsim_d(data = Simulation1) %>% 
  as_tibble()
```

The outputted mrgsolve simulation data *mrgsolve_sim1* shows the parameters CL and V, but could you help on what I may have done wrong for the predicted amounts in the compartment to be zero?

**Comment by kylebmetrum** [comment]
This should have given you a warning but it didn't.  I'll go look at that under a different issue. 

```r
> head(Simulation1)
# A tibble: 6 x 12
# Groups:   ID [1]
     ID GAWKBirth timeH  PNAD  GAWK  WTKG  time  EVID   CMT   AMT
  <dbl>     <dbl> <int> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
1     1        28    24  1     28.1  1.07     0     1     1  10.7
```

This is what you need to fix:
```r
time = if_else(PNAD >= 1, true = 0:(30*24)-24, false = 0)
```

You need to use `TIME` here, not `time` to be consistent with `EVID`, `CMT`, and `AMT`.  There is some consistency check in the package for this, but for some reason it's not happening here.  

Kyle

**Comment by DuyTran16** [comment]
That was a silly error on my part.  I will just capitalize all data column names on mrgsolve like in NONMEM $INPUT block from now on.  After fixing `time`  to `TIME`, the mrgsolve simulation was able to produce predicted CP and the amounts in the compartments.  All values in mrgsolve simulation match identical to NONMEM simulation.  When I read 

> The current amt value regardless of whether it was given as amt or AMT in the data set. 

in the manual, I assumed that lower or upper cases names in mrgsovle does not matter.  I will just be consistent and use uppercase from now on.  THANKS for your help again!

**Comment by kylebmetrum** [comment]
Sorry for the confusion; You *should have* gotten a note that something wasn't right.  I will fix.
