### ISSUE TITLE
Question/Feature Request: Root finding

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#468]
I'm working to implement a literature model with no simple algebraic equation for the steady-state, but it does have a well-defined (single-value) for steady-state in a known range.  I'd like to set the initial condition to that steady-state, but to do that, I need to do root-finding.

Is there a straightforward way to implement root-finding within `mrgsolve`?  I think that this is mostly a C++ question and likely a parallel documentation request.  I found the following ways to implement it with Boost (https://www.boost.org/doc/libs/1_62_0/libs/math/doc/html/math_toolkit/roots.html), but my C++ skills aren't sufficient to use that in my code.

(Right now, I'm just pre-computing the steady-state with the `uniroot()` R command, but it would be more elegant to have it within the model.)

**Comment by kylebmetrum** [comment]
Hi @billdenney - 

I've used the boost root finding stuff before, but for a different purpose.  I don't think you could (reasonably) code the process to find the steady-state initial value into the model itself.  

If `uniroot()` is working well, I think I'd just stick with that.  For most of my stuff, it's pretty cheap to just let a model run and wait for it to settle down.  Not elegant, I know.  But maybe some of this could get boxed up into the mrgsolveExtra package.

**Comment by billdenney** [comment]
OK, that sounds reasonable to me.  Thanks for the quick reply.
