### ISSUE TITLE
Typos: in user guide section 2.5.3 population Pk model with covariates

### ISSUE THREAD

**Issue by amitvtaneja** [metrumresearchgroup/mrgsolve#469]
Dear Kyle

A cursory look suggested that the closing brackets were missing in the aforementioned section of the users guide. Please ignore if this has already been fixed,

best regards

Amit

double VCi = exp(log(TVVC) + EVC;
double KAi = exp(log(TVKA) + EKA;

**Comment by kylebmetrum** [comment]
Thanks for the report @amitvtaneja.  This has been fixed.

Kyle
