### ISSUE TITLE
mrgsolve stopped working / issues reinstalling

### ISSUE THREAD

**Issue by burumun** [metrumresearchgroup/mrgsolve#470]
I'm pretty new to R and mrgsolve, but my code was working last week. This week I'm having trouble building my model and kept getting this error:
Building FIHmodel ... error.
---:: stdout ::---------------------------------------------
---:: stderr ::---------------------------------------------
Warning message:
In system(cmd) : 'make' not found
------------------------------------------------------------
Error: The model build step failed.

I'm trying to re-install mrgsolve but that isn't working either. I keep getting different errors, most of them are as follows:
  (converted from warning) installation of package ‘C:/Users/fchandra/AppData/Local/Temp/Rtmp6PKIh9/file607835566732/mrgsolve_0.9.0.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

Any ideas / suggestions what might be wrong?

**Comment by kylebmetrum** [comment]
HI @burumun  - 

`In system(cmd) : 'make' not found` means that R lost track of the compilers and other pieces of the toolchain.  

IMO it's easiest to just re-install Rtools, making sure the PATH environment variable gets set.  Not sure what happened since last week to cause this.  And it might be that Rtools is still around and installed just fine, but just a matter of getting the PATH environment variable set properly.

Can you give that a try and report back?

Kyle

**Comment by nanhung** [comment]
You can check whether Rtools is in the PATH by using

```
Sys.getenv("PATH")
```

Ideally, you should have output looks like this

```
## [1] "C:\\Program Files\\R\\R-3.5.0\\bin\\x64;C:\\Rtools\\bin;C:\\Windows\\system32;
```
If you can not find the Rtools in the your PATH such as
```
[1] "c:\\Rtools\\bin;c:\\Rtools\\mingw_64\\bin
```
You will need to add the location of your bin folder in Rtools to your path manually, as follow
```
Sys.setenv(PATH = paste("c:\\Rtools\\bin", Sys.getenv("PATH"), sep=";"))
Sys.setenv(BINPREF = "c:\\Rtools\\bin")
```
Then, try to use following command to check the whether you can find and run your compiler correctly.
```
Sys.which("gcc")
system('g++ -v')
```

**Comment by burumun** [comment]
Thank you! I added Rtools to my path manually as @nanhung suggested and reinstalled mrgsolve. It seems to be working now!

**Comment by jx0109** [comment]
Hi, sorry to ask on a closed thread, but I'm experiencing the same issues. After trying what is discussed above:

```
Sys.getenv("PATH")
path <- Sys.getenv("PATH")
path <- c("C:\\Rtools\\bin", "C:\\Rtools\\gcc-4.6.3\\bin", path)
path <- paste(path,collapse=";")
Sys.setenv(PATH=path)
Sys.setenv(BINPREF = "c:\\Rtools\\bin")
```
I would get the following output and error message:

```
Building 2cmt ... error.

---:: stdout ::---------------------------------------------
c:\Rtools\bing++
-I"C:/Users/kkvr097/DOCUME~1/R/R-35~1.2/include" -DNDEBUG
-I"C:/Users/kkvr097/Documents/R/R-3.5.2/library/mrgsolve/base"
-I"C:/Users/kkvr097/AppData/Local/Temp/RtmpklFvtm" -O2
-Wall -mtune=generic -c 2cmt-mread-source.cpp -o
2cmt-mread-source.o

---:: stderr ::---------------------------------------------
sh: c:Rtoolsbing++: command not found
make: *** [C:/Users/kkvr097/DOCUME~1/R/R-35~1.2/etc/x64/Makeconf:215: 2cmt-mread-source.o] Error 127
------------------------------------------------------------
NOTE: 'Error 127' was detected in the above message.
 This possibly indicates that the build toolchain
 could not be found. Please check for proper compiler 
 installation ('Rtools.exe' on Windows).  Also consider
 trying 'pkgbuild::check_build_tools(debug=TRUE)' to
 assist in diagnosing this issue.
------------------------------------------------------------ 
Error: The model build step failed.

```

I referred to another thread on Error 127 here: https://github.com/metrumresearchgroup/mrgsolve/issues/160 

But if I'm not mistaken, the steps discussed there (which I also tried) are the same but with "RBuildTools" instead. So what I can do to resolve my errors?

Thank you!

**Comment by kylebmetrum** [comment]
This
```
c:\Rtools\bing++
```
and this
```
sh: c:Rtoolsbing++: command not found
```

make me wonder if there is some issue with (back) slashes in the path?

When I hide my Rtools installation from R I get

```
> mod <- modlib("pk1")
Building pk1 ... error.

---:: stdout ::---------------------------------------------
c:/Rtools/mingw_64/bin/g++
-I"C:/PROGRA~1/R/R-devel/include" -DNDEBUG
-I"c:/Rlibs/mrgsolve/base" -I"c:/Rlibs/mrgsolve/models" -O2
-Wall -mtune=generic -c pk1-mread-source.cpp -o
pk1-mread-source.o

---:: stderr ::---------------------------------------------
sh: c:/Rtools/mingw_64/bin/g++: No such file or directory
make: *** [C:/PROGRA~1/R/R-devel/etc/x64/Makeconf:215: pk1-mread-source.o] Error 127
------------------------------------------------------------
NOTE: 'Error 127' was detected in the above message.
```

Could you switch to front-slashes in your path?  Also, could you post the relevant portion of your path?

Mine is:

```
> Sys.getenv("PATH") %>% strsplit(';') %>% unlist() %>% cat(sep="\n")
C:\Program Files\R\R-devel\bin\x64
C:\RBuildTools\3.5\bin
C:\Rtools\bin
c:\R\R-3.3.1\bin\x64
```

**Comment by jx0109** [comment]
Ok I've just tried using front-slashes (both single and double), but I'm still getting the same error, only with "No such file or directory" instead of "No such file or directory" underneath ": : stderr : :".

As for my paths, I'm assuming these would be the most relevant:

```
> Sys.getenv("PATH") %>% strsplit(';') %>% unlist() %>% cat(sep="\n")
C://Rtools//bin
C://Rtools//gcc-4.6.3//bin
C:\Users\kkvr097\Documents\R\R-3.5.2\bin\x64
C:\Users\kkvr097\Documents\rstudio.exe
```

**Comment by jx0109** [comment]
One thing I forgot to mention earlier was that all those error messages from my 1st post here was from loading an mcode() line where the model is named "2cmt".

And even though the error messages suggest so, I'm now wondering if the lack of a properly installed Rtools() is really the main source of my errors. Here's one thing I've ran:

```
> library(installr)
Loading required package: stringr

Welcome to installr version 0.21.0

More information is available on the installr project website:
https://github.com/talgalili/installr/

Contact: <tal.galili@gmail.com>
Suggestions and bug-reports can be submitted at: https://github.com/talgalili/installr/issues

			To suppress this message use:
			suppressPackageStartupMessages(library(installr))

Warning message:
package ‘installr’ was built under R version 3.5.3 
> install.Rtools()
No need to install Rtools - You've got the relevant version of Rtools installed

```

**Comment by burumun** [comment]
I’m not sure whether you did or not, but one thing that fixed mine was to reinstall Rtools as admin / elevated.
Otherwise in the past I had to not only set the path to Rtools but reinstall mrgsolve every time I open R

**Comment by kylebmetrum** [comment]
As @burumun suggested, I would only try to set the path within R if I knew I were locked out of manipulating the PATH via the Rtools installer.  Is that true?  Are you on a corporate computer where you know you can't tweak PATH? If not, definitely try to nuke any existing Rtools install and re-install from scratch, making sure to opt-in when it asks about changing PATH.  

If that isn't the case, then, IMO, we should look at the details for your Rtools installation and make sure the R code that sets PATH is right.  It's easy to mess up ... which is why I tend to point people back to the Rtools installer.  it's usually worth it if you have access.  

If you know that you don't have access on your computer, could you post a directory listing of what is in `c:/Rtools/`?

**Comment by jx0109** [comment]
I am using my company's computer yes.

**Comment by jx0109** [comment]
This may be more than you'd like to see but below was my attempt at installing Rtools and other things I thought might be relevant: 

```
> library(processx)
Warning message:
package ‘processx’ was built under R version 3.5.3 
> # install devtools R tools etc
> install.packages("devtools")
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/devtools_2.0.2.zip'
Content type 'application/zip' length 383668 bytes (374 KB)
downloaded 374 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\kkvr097\AppData\Local\Temp\RtmpKiaQuV\downloaded_packages
> install.packages("pkgbuild")
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/pkgbuild_1.0.3.zip'
Content type 'application/zip' length 133661 bytes (130 KB)
downloaded 130 KB

package ‘pkgbuild’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\kkvr097\AppData\Local\Temp\RtmpKiaQuV\downloaded_packages
> library(devtools)
Warning message:
package ‘devtools’ was built under R version 3.5.3 
> devtools::install_github("r-lib/pkgbuild", force = TRUE)
Downloading GitHub repo r-lib/pkgbuild@master
√  checking for file 'C:\Users\kkvr097\AppData\Local\Temp\RtmpKiaQuV\remotes4de46d225191\r-lib-pkgbuild-79cb7a0/DESCRIPTION' ... 
-  preparing 'pkgbuild':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'pkgbuild_1.0.3.tar.gz'
   
* installing *source* package 'pkgbuild' ...
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'pkgbuild'
    finding HTML links ... done
    build                                   html  
    clean_dll                               html  
    compile_dll                             html  
    compiler_flags                          html  
    has_build_tools                         html  
    has_compiler                            html  
    has_latex                               html  
    has_rtools                              html  
    needs_compile                           html  
    pkg_has_src                             html  
    pkg_links_to_rcpp                       html  
    pkgbuild_process                        html  
    rcmd_build_tools                        html  
Rd warning: C:/Users/kkvr097/AppData/Local/Temp/RtmpEPrNjF/R.INSTALLd083c7759f1/pkgbuild/man/rcmd_build_tools.Rd:14: file link 'rcmd_safe_env' in package 'callr' does not exist and so has been treated as a topic
    with_debug                              html  
    without_compiler                        html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (pkgbuild)
In R CMD INSTALL
> check_build_tools()
Error in check_build_tools() : 
  could not find function "check_build_tools"
> library(pkgbuild)

Attaching package: ‘pkgbuild’

The following object is masked from ‘package:devtools’:

    build

> install.packages("githubinstall")
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/githubinstall_0.2.2.zip'
Content type 'application/zip' length 68253 bytes (66 KB)
downloaded 66 KB

package ‘githubinstall’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\kkvr097\AppData\Local\Temp\RtmpKiaQuV\downloaded_packages
> library(githubinstall)
Warning message:
package ‘githubinstall’ was built under R version 3.5.3 
> install.packages("installr")
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/installr_0.21.0.zip'
Content type 'application/zip' length 335981 bytes (328 KB)
downloaded 328 KB

package ‘installr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\kkvr097\AppData\Local\Temp\RtmpKiaQuV\downloaded_packages
> library(installr)
Loading required package: stringr

Welcome to installr version 0.21.0

More information is available on the installr project website:
https://github.com/talgalili/installr/

Contact: <tal.galili@gmail.com>
Suggestions and bug-reports can be submitted at: https://github.com/talgalili/installr/issues

			To suppress this message use:
			suppressPackageStartupMessages(library(installr))

Warning message:
package ‘installr’ was built under R version 3.5.3 
> install.Rtools()
No need to install Rtools - You've got the relevant version of Rtools installed
```

What's more, when I try running this line:
`devtools::install_github("metrumresearchgroup/mrgsolve", type="source")`
A message would pop up:

"Building R package from source requires installation of additional build tools. Do you want to install the additional tools now?" And it would prompt to select yes or no, but either way I'd get the following error.

`Error: Could not find tools necessary to compile a package`

**Comment by kylebmetrum** [comment]
Can you try from this?

https://cran.r-project.org/bin/windows/Rtools/Rtools35.exe

Use the regular installer.  If there is anything in c:/RBuildTools or c:/Rtools already, please nuke that (or rename to something inert for now).  

When you work through the installer, take time to look for a check box that asks you if you want to update the path.  You might have to opt-in (not sure why, but I've seen it both ways). 

I'm probably going to remove the installr stuff from the install instructions; seems like that has been more trouble than it's worth lately.

**Comment by jx0109** [comment]
Thanks and once I have that installed, should I retry the following?

```
Sys.getenv("PATH")
path <- Sys.getenv("PATH")
path <- c("C:\Rtools\bin", "C:\Rtools\gcc-4.6.3\bin", path)
path <- paste(path,collapse=";")
Sys.setenv(PATH=path)
Sys.setenv(BINPREF = "c:\Rtools\bin")
```

**Comment by kylebmetrum** [comment]
Not yet;  after restarting R / Rstudio,  check `Sys.getenv("PATH")` to see if the path to your Rtools is properly set.  

If so, try `mod <- mread("pk1", modlib())` or something simple to see if you can compile a model. 

If we can prove that your company locked the installer out from modifying environment variables, we can try controlling `PATH` from the R session. 

Let me know what happens.

**Comment by jx0109** [comment]
If I just run Sys.getenv("PATH") right now, I'd get:
```
> Sys.getenv("PATH")
[1] "C:\\Users\\kkvr097\\Documents\\R\\R-3.5.2\\bin\\x64;rstudio.exe;C:\\Program Files (x86)\\Python36-32\\Scripts\\;C:\\Program Files (x86)\\Python36-32\\;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\1E\\NomadBranch\\;C:\\Program Files (x86)\\Box\\Box Edit\\;C:\\Program Files\\PuTTY\\;C:\\Users\\kkvr097\\AppData\\Local\\Microsoft\\WindowsApps;"
```
So I'm not seeing Rtools in this path

**Comment by kylebmetrum** [comment]
Ok;  sorry to pick on this ... confirming that (1) you did see the box to opt in to setting PATH and (2) you re-started everything (R / Rstudio) and (3)  R still isn't showing Rtools in PATH (as you are showing)?

**Comment by jx0109** [comment]
I'm retrying that procedure. Is the box you're talking supposed to have all this?

> 
>                             Rtools 3.5
> 
> This bundle contains the Windows Toolchain and Build Utilities for R.
> The original collection was put together by Prof. Brian Ripley and 
> Duncan Murdoch; it is currently maintained by Jeroen Ooms.
> 
> More information: https://cran.r-project.org/bin/windows/Rtools/
> 
> 
>                            BUILD UTILITIES
> 
> Rtools includes some standard utilities such as make, bash, sed, which 
> are required to build R packages with compiled code. These utilities
> need to be on the PATH when installing R packages from source. 
> 
> You can either modify your Windows system PATH, or instead define a line 
> like below in your ".Renviron" file in your Documents folder. See also
> the manual page for ?Startup in R for saving variables.
> 
>     PATH="C:\Rtools\bin;${PATH}"
> 
> Note that Windows PATH uses backslashes. You can skip this step if your
> PATH already has working make and sh, for example from CYGWIN or msys2.
> However you should not put other toolchains (gcc, g++, ld) on the PATH.
> 
> 
>                              GCC TOOLCHAIN
> 
> Versions 3.3, 3.4, and 3.5 of Rtools ship with a mingw-w64 toolchain 
> based on gcc 4.9.3. We do not use multilib compilers, instead we ship 
> separate compilers targeting 32 and 64 bit.
> 
> By default, R looks for compilers in the default installation path in
> C:\Rtools\. If you install Rtools anywhere else, you have to point R 
> to the path of gcc, g++, ld, by setting a variable called BINPREF.
> For example:
> 
>     BINPREF="M:/R/Rtools-3.5/mingw_$(WIN)/bin/"
> 
> Note how we embed another variable $(WIN) which is set by R to either 
> "32" or "64" depending on the target. Thereby this BINPREF works for 
> both architectures. Also note that R requires forward slashes here.
> 
> You can either store this variable in your Windows system or define it
> in your ".Renviron" file in the user home (Documents) folder. See also
> the manual page for ?Startup in R.
>

**Comment by kylebmetrum** [comment]
Kind of .... specifically, you might have to take action at step 5 listed here (from the stan website):

https://github.com/stan-dev/rstan/wiki/Installing-RStan-from-source-on-Windows#download-and-install-rtools

Opt in here:

![image](https://user-images.githubusercontent.com/16908301/56763004-d9ce1e80-6766-11e9-8b56-724915847b63.png)

**Comment by jx0109** [comment]
I'm on that step, but only the 2nd option ("Save version information to registry") is shown. The 1st option doesn't even appear.

**Comment by burumun** [comment]
You need to run the installer as an admin or "elevated" for the 2nd option
to appear. Same issue happened with me.

**Comment by jx0109** [comment]
I'm unsure of how to do that. Also, the instructions Kyle sent me says to choose the "Save version..." option but I wasn't sure if Kyle was suggesting the other option.

**Comment by kylebmetrum** [comment]
It might be something to ask IT about so you don't have to mess around with the `.Renviron` stuff. 

If `c:/Rtools/` now has the build tools
```
Sys.getenv("PATH")
path <- Sys.getenv("PATH")
path <- c("C:/Rtools/bin",  path)
path <- paste(path,collapse=";")
Sys.setenv(PATH=path)
Sys.getenv("PATH")
```

should give back the path that includes the toolchain?

**Comment by jx0109** [comment]
Do you mean I should ask IT which option to choose? Or how to run the installer as an admin/elevated?

**Comment by kylebmetrum** [comment]
It seems to me that you can't let the installer set the `PATH` for you.  I'd doubt that you could go and do it yourself either.  Maybe IT could give you access to do that.   Once it was set, you wouldn't have to do more configure. 

For now, as far as I can tell, the only option that you have is to get `c:/Rtools/bin` into `PATH` using the R code.

**Comment by jx0109** [comment]
And to do that, I would use those same 6 lines, correct? Which I would do after getting access from IT?

**Comment by kylebmetrum** [comment]
If you got access from IT (you can log on with some better access ... admin or elevated user as @burumun did) I would just re-install Rtools, opting in when it asks about setting PATH.  It's not that you need to re-install, but you need to set PATH and it seems easiest to let the program do it.  If you had admin access and still didn't see the opt in box, that's a different story.  But at this point, I'd say I'd expect to see it if you were admin.

**Comment by kylebmetrum** [comment]
@burumun @jx0109 

I spent some time on my Windows box tonight.  I was able to replicate the issue that @jx0109 was having after nuking my previous install and bypassing the PATH stuff in the installer.  I was eventually able to figure out some things and revised the docs.  I know there have been a lot of attempts here, but 
wondering if you could try the new approach.


I revised the docs recommending the following:

Edit your `$HOME/.Renviron` file by running the following R command:

```r
file.edit("~/.Renviron")
```

If you have Rtools installed at `c:/Rtools` then put this into the `.Renviron` file and save

```
PATH="c:/Rtools/bin;${PATH}"
```
Be sure to put a semi-colon between the `Rtools` and the other `PATH` items.

You shouldn't need `BINPREF` if you have everything installed in the standard location `c:/Rtools`

Re-start R and check the path.  Test by compiling a model.

```r
Sys.getenv("PATH")

library(mrgsolve)
foo <- mread("pk1",modlib(), ignore.stdout = FALSE, preclean=TRUE)
```

You should see
```r
c:/Rtools/mingw_64/bin/g++
-I"C:/PROGRA~1/R/R-devel/include" -DNDEBUG
-I"c:/Rlibs/mrgsolve/base" -I"c:/Rlibs/mrgsolve/models" -O2
-Wall -mtune=generic -c pk1-mread-source.cpp -o
pk1-mread-source.o
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o
pk1-mread-source.dll pk1-mread-source-win.def
pk1-mread-source.o -LC:/PROGRA~1/R/R-devel/bin/x64 -lR
```

This is all assuming a recent install of Rtools for 3.5

The new guidance is here
https://github.com/metrumresearchgroup/mrgsolve/wiki/Windows-issues#persistent-change-to-path-for-r

**Comment by jx0109** [comment]
It seems like your last suggestion works! For a record:

```
> Sys.getenv("PATH")
[1] "c:/Rtools/bin;C:\\Users\\kkvr097\\Documents\\R\\R-3.5.2\\bin\\x64;rstudio.exe;C:\\Program Files (x86)\\Python36-32\\Scripts\\;C:\\Program Files (x86)\\Python36-32\\;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\1E\\NomadBranch\\;C:\\Program Files (x86)\\Box\\Box Edit\\;C:\\Program Files\\PuTTY\\;C:\\Users\\kkvr097\\AppData\\Local\\Microsoft\\WindowsApps;"
> library(mrgsolve)
Warning message:
package ‘mrgsolve’ was built under R version 3.5.3 
> foo <- mread("pk1",modlib(), ignore.stdout = FALSE, preclean=TRUE)
c:/Rtools/mingw_64/bin/g++
-I"C:/Users/kkvr097/DOCUME~1/R/R-35~1.2/include" -DNDEBUG
-I"C:/Users/kkvr097/Documents/R/R-3.5.2/library/mrgsolve/base"
-I"C:/Users/kkvr097/Documents/R/R-3.5.2/library/mrgsolve/models"
-O2 -Wall -mtune=generic -c pk1-mread-source.cpp -o
pk1-mread-source.o
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o
pk1-mread-source.dll pk1-mread-source-win.def
pk1-mread-source.o
-LC:/Users/kkvr097/DOCUME~1/R/R-35~1.2/bin/x64 -lR
> # 2 cmt PK model
> rcode_2cmt <- "
+   $PARAM
+   CL=0.4
+   V1=3.87
+   Q=0.609
+   V2=4.11
+   
+   $SET
+   delta=0.1, end=600
+   
+   $CMT CENT PERI
+   
+   $MAIN
+   
+   double K10 = CL/V1 ;
+   double K12 = Q/V1 ;
+   double K21 = Q/V2 ;
+   
+   $ODE
+   dxdt_CENT= -K10*CENT - K12*CENT + K21*PERI ;
+   dxdt_PERI= K12*CENT-K21*PERI;
+   
+   
+   $TABLE
+   double CP=CENT/V1;
+   
+   $CAPTURE
+   CP 
+ "
> model_2cmt <- mcode("2cmt", code = rcode_2cmt)
Building 2cmt ... done.
```

Thank you very much!

**Comment by kylebmetrum** [comment]
Great.  Thanks for your patience working through this and trying all of the suggestions when we didn't know what was going on.  I did my best to capture what we learned in better advice for others facing the same issues in the future.  So @jx0109 and @burumun thanks again!
