### ISSUE TITLE
mrgsolve/drake Incompatibility?

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#471]
When using drake with mrgsolve, I just got the following error:

```r
There was a problem accessing the model shared object.
  Either the model object is corrupted or  
  the model was not properly compiled and/or loaded.
Check mrgsolve:::funset(mod) for more information.
> mrgsolve::funset(readd(model))
Error: 'funset' is not an exported object from 'namespace:mrgsolve'
> mrgsolve:::funset(readd(model))
$`symbols`
  name loaded
1 <NA>  FALSE
2 <NA>  FALSE
3 <NA>  FALSE
4 <NA>  FALSE

$shlib
            package version compiled
1 pku-so-3549ba2a85   0.9.0     TRUE

> 
```

Both mrgsolve and drake do magical things with R, and it appears their magic is incompatible in at least this instance.

To reproduce this requires more complexity than a standard reproducible example.

1. Start R
2. `source("run1.txt")`
3. Quit R
4. Start R
5. `source("run2.txt")`

[run1.txt](https://github.com/metrumresearchgroup/mrgsolve/files/2986063/run1.txt)
[run2.txt](https://github.com/metrumresearchgroup/mrgsolve/files/2986064/run2.txt)

**Comment by kylebmetrum** [comment]
Try this: 

```r
library(mrgsolve)
options(mrgsolve.soloc = "i_love_drake")
mod <- mread_cache("my_model_file.cpp")
```

I don't know how to use drake; but set the option and use `mread_cache` rather than `mread`  ... or `mcode_cache` rather than `mcode`.   I use this in my everyday (drake-less) workflow now.  

If that still doesn't work try adding  `loadso(mod)` after the `mread_cache` call; that will force the loading of the shared object.

**Comment by billdenney** [comment]
`loadso()` fixes it, if I manually run it.  `drake` works to only re-run code that has changed while tracking dependencies, so `mread()` or `mcode()` isn't run if the model is already current (i.e. the model code hasn't changed).  But, I changed my dataset and resimulated, so mrgsim was called in a session where `mcode()` wasn't called.

Would it be reasonable to add an attempt to load the shared object, if not already loaded, before throwing the error here:

https://github.com/metrumresearchgroup/mrgsolve/blob/ea18191039dcb20ad84bb60756660557598a2021/R/funset.R#L71-L76

(And anywhere else that may be an issue)

This code appeared to work:

```r
library(mrgsolve)
library(drake)

model_text <- "
$PARAM @annotated
CL   :  1 : Clearance (volume/time)
V    : 20 : Central volume (volume)
KA   :  1 : Absorption rate constant (1/time)

$CMT  @annotated
EV   : Extravascular compartment
CENT : Central compartment

$GLOBAL
#define CP (CENT/V)

$PKMODEL ncmt = 1, depot = TRUE

$CAPTURE @annotated
CP : Plasma concentration (mass/volume)
"

mrgsim_load <- function(x, ...) {
  loadso(x)
  mrgsim(x, ...)
}

my_plan <-
  drake_plan(
    model=mcode_cache(model_text, model="pk1"),
    my_idata=data.frame(ID=2),
    sim_result=mrgsim_load(model, idata=my_idata),
    strings_in_dots="literals"
  )

make(my_plan)
as.data.frame(readd(sim_result))
```

**Comment by billdenney** [comment]
Also, `drake` is one of my favorite new (to me) R tools.  Especially for long-running projects (such as model fitting or larger `mrgsolve` simulations), it lets me iterate on the reporting side without rebuilding everything from scratch or worrying about dependencies or stale outputs (like saved files).

https://ropensci.org/technotes/2019/03/18/drake-700/

**Comment by kylebmetrum** [comment]
Thanks for the report.  I'll open tickets to fix the `funset` output (not sure why the names are not showing up there).  Also, will add pointer to try `loadso` when the model functions are not loaded.
