### ISSUE TITLE
IPRED = F vs. IPRED = AMT/V in mrgsolve?

### ISSUE THREAD

**Issue by nguyenjq** [metrumresearchgroup/mrgsolve#475]
Hi,

This question deals with mrgsolve but I also believe I am not understanding some NONMEM concepts correctly and would really appreciate receiving advice for both. 

I'm working on implementing a NONMEM model into mrgsolve and verifying this by having both models simulate from the same dataset. I noticed that if I defined `IPRED = F` in the NONMEM file, it produces different PRED/IPRED/DV from the simulation produced in mrgsolve. However, if I define it as `IPRED = A(2)/V2`, it produces the same as in mrgsolve, which makes sense as it's coded as `IPRED = CENT/V2` in mrgsolve. 

However, I am not sure if it is totally correct to use `IPRED = A(2)/V2` in my NONMEM model (most NONMEM models I have seen only use `IPRED = F`), and I was actually surprised that `IPRED = F` and `IPRED = A(2)/V2` produced very different numbers, with the former giving a value of 85 but the latter giving a value of 0.12. I initially thought they should be similar but I do not understand why they are not. Additionally, what is the equivalent of `IPRED = F` in mrgsolve?

Thank you in advance for your time and support.

**Comment by kylebmetrum** [comment]
@nguyenjq 

I put a vignette here that does some comparisons with a simple model
https://github.com/mrgsolve/nmtests/blob/master/ipred/ipred.md

The model and data are here:
https://github.com/mrgsolve/nmtests/tree/master/ipred

Not sure if this totally answers all of the angles or not.  Do you have `CMT` or `DEFOBS` set properly in your data set / model file?  I could look farther with you if you could share part of the model and data. 

There is no `IPRED = F` equivalent for mrgsolve; the user is always required to state explicitly the definition for each output.

**Comment by mhismail** [comment]
@nguyenjq Without seeing your code, another thing that could be causing the discrepancy is not having your scale parameter set in your NONMEM control stream. Do you have S2 = V2 in the $PK block of your control stream? Without this, your output would be in the same units as your input - likely mass units - and you need to scale it by V2 to get concentrations.

**Comment by kylebaron** [comment]
Closing this - no follow up .

**Comment by liangqiongyue** [comment]
> @nguyenjq
> 
> I put a vignette here that does some comparisons with a simple model https://github.com/mrgsolve/nmtests/blob/master/ipred/ipred.md
> 
> The model and data are here: https://github.com/mrgsolve/nmtests/tree/master/ipred
> 
> Not sure if this totally answers all of the angles or not. Do you have `CMT` or `DEFOBS` set properly in your data set / model file? I could look farther with you if you could share part of the model and data.
> 
> There is no `IPRED = F` equivalent for mrgsolve; the user is always required to state explicitly the definition for each output.

Hi kylebaron. With your example, can I understand that CP=A2/V calculated using mrgsolve is equal to PRED calculated using NONMEM?

<img width="488" alt="1694070661438" src="https://github.com/metrumresearchgroup/mrgsolve/assets/52445962/3f3ea887-46b1-413f-b1bb-d144017c9c31">
<img width="275" alt="1694070654474" src="https://github.com/metrumresearchgroup/mrgsolve/assets/52445962/2f85412d-1026-444a-b7f7-8cb87a6885e4">
