### ISSUE TITLE
Makevars-<...>-on-macOS wiki suggestion

### ISSUE THREAD

**Issue by benthestatistician** [metrumresearchgroup/mrgsolve#477]
This is a suggestion about the mrgsolve wiki, not the mrgsolve project itself. 

I was led some time ago to your [helpful wiki page](https://github.com/metrumresearchgroup/mrgsolve/wiki/Makevars-file-for-%22alternate%22-gfortran-configuration-on-macOS) setting up Makevars for an "alternate" gfortran configuration on macOS.  This is just a note to say that when I upgraded recently to R version 3.6.0, I found that I needed to replace line

     FC = $F77 
with 

    FC = $(F77)

This in order to avoid compile-time errors along the lines of 

     make: 77: No such file or directory

(In any case thanks for the helpful wiki page.)

**Comment by kylebmetrum** [comment]
Thanks for the tip!  The page is updated.
