### ISSUE TITLE
wrong calculation of expressions

### ISSUE THREAD

**Issue by metelkin** [metrumresearchgroup/mrgsolve#480]
Hi,
When I use long expressions in $ODE part I have wrong results. It doesn't matter if I use variables inside expressions or just numbers. The minimal code to reproduce error.

**model.cpp**
```cpp
$SET end=10, delta=0.1, hmax=0.01, hmin=0

$PARAM CL = 1, VC = 30, KA = 1.3

$CMT GUT CENT

$MAIN
GUT_0 = 10;

$ODE
double xxx = 10;
double yyy = 9632537/0.787  * 3.14 * 0.0000001 + (94169710 + 49359170)/0.787 * (4 / 3) * 3.14 * 0.000001;

dxdt_GUT = -KA*GUT;
dxdt_CENT = KA*GUT - (CL/VC)*CENT;

$CAPTURE xxx yyy
```

**code.R**
```R
library(mrgsolve)

model <- mread(model = "mdl1", file = "model.cpp")
model_sim <- model %>% mrgsim(end = 10)

plot(model_sim$time, model_sim$CENT)
# OK
plot(model_sim$time, model_sim$xxx)
# get 10 OK
plot(model_sim$time, model_sim$yyy)
# get 576 ???

# but calculating yyy manually
 9632537/0.787  * 3.14 * 0.0000001 + (94169710 + 49359170)/0.787 * (4 / 3) * 3.14 * 0.000001
# 767.3853  !!!
```

**Comment by kylebaron** [comment]
In your C++ code, `4/3` will evaluate to 1 (integer division) but in the R code it will evaluate to `1.333`.

Try writing `4.0/3.0` in the model:

```c
double yyy = 9632537/0.787  * 3.14 * 0.0000001 + (94169710 + 49359170)/0.787 * (4.0 / 3.0) * 3.14 * 0.000001;
```

**Comment by metelkin** [comment]
Thank you, Kyle.
I see. It helps.
It is absolutely not evident for many endpoint users to understand the difference between 4 and 4.0. This is a big pitfall for those who have not read and remembered the documentation from begin to the end.
Maybe it's reasonable: to redefine "/" operator or to make all numbers in expressions to be double as default or to include description of operations in user manual.

Anyway thank you for your help, problem solved.
Best.
