### ISSUE TITLE
[R] Simplify request / Request

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#483]
# Summary

See PR #523 

- Adds two integer members: one indexing the currently requested compartments, the other indexing the currently requested captures
- Two character vectors are kept: (re)names for compartments and (re)names for captures
- The  calculation of the integer vectors is now done by the update method rather than on the fly as the simulation goes
- Rather than "Request" we'll update `outvars`, listing both compartments and captures
- Added initialize method to set this up along with some other parts of the model object
- Two new functions: one to update these new indices; the other to handle updates through `request` (working only on the compartment index)
- Add strict argument to model update method; when an option is turned on, the update will generate a warning if the user tries to update a non-existent member
- Don't allow duplicate names in `outvars` and `request`
- Output variables in the simulated data will be ordered as they are in the model: first, compartments according to compartment number, then captures according to capture number
- The user can ask for `outvars="(all)"` to get all compartments and captures in the simulated 
output
- The user can ask for `request=(all)` to get all compartments

# Tests
- tests/testthat/test-update.R
  - update outvars issue-483
  - update req issue-483
- inst/maintenance/unit/test-request.R
  - request is made in SET block
  - request is (all) by default

**Comment by kylebaron** [comment]
Done.

**Comment by dpastoor** [comment]
LGTM
