### ISSUE TITLE
Error using mrgsolve

### ISSUE THREAD

**Issue by Won-ho** [metrumresearchgroup/mrgsolve#486]
I have just installed Rtools 35.exe in the https://cran.r-project.org/bin/windows/Rtools/ and then installed mrgsolve on R (ver. 3.5.0, through RStudio under Windows 10) installed directly under C drive. 
Now, I'm doing what you do using mrgsolve at the YouTube vedio(https://www.youtube.com/watch?v=gXEOA… ). However, when I tried to mread simple.cpp, I kept getting the error. I would put error message and Sys.getenv("PATH"). Could you explain what's the matter with me?

Error message that I have gotten.
> setwd("C:/Users/Wonho Kang/Desktop/practice_mrgsolve")
> mod <- mread("simple", "model")
Building simple ... error.

---:: stderr ::---------------------------------------------
C:/PROGRA~1/R/R-35~1.0/etc/x64/Makeconf:230: warning: overriding commands for target `.m.o'
C:/PROGRA~1/R/R-35~1.0/etc/x64/Makeconf:223: warning: ignoring old commands for target `.m.o'
process_begin: CreateProcess(NULL, basename simple-mread-source.dll .dll, ...) failed.
process_begin: CreateProcess(NULL, basename simple-mread-source.dll .dll, ...) failed.
process_begin: CreateProcess(NULL, basename simple-mread-source.dll .dll, ...) failed.
"zsimple-mread-source.o"은(는) 예상되지 않았습니다.
make: *** [simple-mread-source.dll] Error 255
------------------------------------------------------------
Error: the model build step failed.

My Sys.getenv("PATH")
> Sys.getenv("PATH")
[1] "
C:\\Program Files\\R\\R-3.5.0\\bin\\x64;
C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;
C:\\Program Files (x86)\\Intel\\iCLS Client\\;
C:\\Perl64\\site\\bin;
C:\\Perl64\\bin;C:\\Program Files\\Intel\\iCLS Client\\;
C:\\WINDOWS\\system32;C:\\WINDOWS;
C:\\WINDOWS\\System32\\Wbem;
C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;
C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;
C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;
C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;
C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;
C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Intel\\WiFi\\bin\\;
C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;
C:\\Users\\Wonho Kang\\AppData\\Local\\Microsoft\\WindowsApps;
C:\\Program Files (x86)\\gfortran\\bin;
C:\\Program Files\\Intel\\WiFi\\bin\\;
C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;
C:\\Program Files\\Bandizip\\"

**Comment by nanhung** [comment]
I don't find Rtools in your "PATH". Perhaps, you forgot to set it. 

```
Sys.setenv(PATH = paste("c:/Rtools/bin", Sys.getenv("PATH"), sep=";"))
```

**Comment by kylebaron** [comment]
@Won-ho Your problem is with Rtools, not mrgsolve.  There are no Rtools directories in your path; please re-install, making sure to add to your path.  Alternatively, you can add it to your path manually.  There are many examples out there to do this.
