### ISSUE TITLE
Using event object when model specifies dose

### ISSUE THREAD

**Issue by needshelp101** [metrumresearchgroup/mrgsolve#487]
Hello,

The PK model I am coding includes dose as one of the parameters within $PARAM. Additionally, this value is incorporated in one of the $MAIN and one of the $ODE equations. However, I still want to update the model with an event that contains multiple dosing. I am not sure how setting 'amt', 'ii' or 'addl' will work with dose already being specified within the model as a parameter. Is there a way to make the event object use the dose parameter already defined or how should I go about doing this?

Thanks in advance

**Comment by kylebaron** [comment]
A couple of different ways you could go, depending on what you're really after here: 

If you just want to use the dose amount from the event object in $MAIN and $ODE, you can get that with

```c
$MAIN 
double the_dose = 0;
if(EVID==1) the_dose = self.amt;
```
or something along those lines.  

If you really want the dose amount determined by what value you have in the parameter, then I guess you'd have to put a unit dose into the event object and then use dose amount parameter value
as the bioavailability fraction

```c
$PARAM DOSE = 100

$MAIN
F_CMT = DOSE;
```

Is one of those two what you're getting at?

**Comment by needshelp101** [comment]
Yes, accessing the amt value with self.amt seems to work, except for the fact that it gives different y-values for the outputted plots. By this I mean if I am to put, say, 100 into the $MAIN equation where dose is found I get the first set of plots attached below, but if I put self.amt (where amt has been specified as 100 in an event piped to mod), I get the second set of plots attached below.

When amt is set to 100, for example, is its value not actually 100? What am I missing?

<img width="426" alt="regular" src="https://user-images.githubusercontent.com/52749525/60980364-57371300-a302-11e9-8669-a25ad4f7a05a.PNG">
<img width="429" alt="with self amt" src="https://user-images.githubusercontent.com/52749525/60980374-5aca9a00-a302-11e9-9683-2e1d4a116a09.PNG">

**Comment by needshelp101** [comment]
Just for clarification, the first set of plots is with a $MAIN equation containing the raw value 100.
The second set is with self.amt in place of 100, with a value specified as 100 in an event.

**Comment by kylebaron** [comment]
Sorry ... bad (untested) code on my part.  Try this:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter

code <- '
$CMT A

$PREAMBLE 
double the_dose = 0;

$MAIN
if(NEWIND <=1) the_dose = 0;

if(EVID==1) the_dose = self.amt;

$CAPTURE the_dose

$ODE dxdt_A = 0;
'

mod <- mcode("amt", code)
#> Building amt ...
#> done.

mod %>% ev(amt = 100) %>% mrgsim() %>% plot()
```

![](https://i.imgur.com/c5TVBOA.png)

With `recsort = 3`

``` r
mod %>% ev(amt = 100) %>% mrgsim(recsort = 3) %>% plot()
```

![](https://i.imgur.com/8EMgUrW.png)

<sup>Created on 2019-07-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kylebaron** [comment]
Did this solve your problem?

**Comment by kylebaron** [comment]
Feel free to re-open if there is something else here.
