### ISSUE TITLE
[R] Remove qsim and re-implement from mrgsimple

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#490]
# Summary

There is some significant overhead to calling mrgsim that is very noticeable when running short problems.  We created these functions to have a streamlined simulation sequence for these cases.  

- Remove qsim.R
- Re-factor `to_mrgsimple` (previously unexported) and re-brand as `qsim`
- Various minor efficiency gains targeted to this quick turnaround scenario

See #523 for request refactor.  This eliminates a lot of that overhead. 

See  https://github.com/metrumresearchgroup/mrgsolve/commit/8c20fca9eb94297b67961e526a9fd71558e2ecb5

# Tests
- tests/testthat/test-mrgsim_q.R
  - qsim issue-490
  - simcall=1 is deprecated

**Comment by kylebaron** [comment]
Done.  But see #521.  After refactoring the request mechanism, there should be only one of these quick functions.

**Comment by kylebaron** [comment]
https://github.com/metrumresearchgroup/mrgsolve/pull/494

**Comment by dpastoor** [comment]
@kylebaron given we are removing a piece of the api here, as well as other changes, I think we need to increment the version to 0.10.0

**Comment by dpastoor** [comment]
change LGTM
