### ISSUE TITLE
[R] Refactor SS

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#496]
# Summary 

The code for when to advance to steady state was re-factored.  The reason for refactoring is that there are currently some steady state scenarios that mrgsolve can't do (mainly SS when infusion time is greater than the dosing interval and there is a lag time).

There is no user-facing change associated with this.

__External tests__
- https://github.com/mrgsolve/nmtests
- pdf attached

[nmtest7_20191004.pdf](https://github.com/metrumresearchgroup/mrgsolve/files/3692727/nmtest7_20191004.pdf)

# Tests 
- inst/maintenance/unit/test-pk.R
  - one-compartment, bolus, ss
  - one-compartment, oral, first, ss
  - two-compartment, bolus, ss
  - two-compartment, bolus, first, ss
  - two-compartment, infusion, ss

**Comment by dpastoor** [comment]
Thanks for the details around the decisions. LGTM
