### ISSUE TITLE
[F] SS=1 and F_CMT is 0

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#497]
# Summary

The user should be able to run the system to steady state when `F_CMT` is zero. 

Also, better error message:
`“Error: Cannot use ss flag when F(n) is zero.`

See 510b78a

See b778070e4725251611bc2974e3843e583d95a139

# Tests
- inst/maintenance/unit/test-z-alag-f.R
  - ss=1 and F_CMT =0 issue-497

**Comment by kylebaron** [comment]
Dosing record gets disarmed when Fn is 0

**Comment by kylebaron** [comment]
510b78a8e302269625382e86a704bfb6b2fde6a7

**Comment by dpastoor** [comment]
@kylebaron can you clarify a little more why this was high risk? how is this impacting existing functionality in a way that disrupts prior behavior.

My understanding was that it was previously throwing an error, but now you're allowing that new behavior, as well as more effectively communicating incorrect combo?. That seems like a medium/low risk item

**Comment by kylebaron** [comment]
- It was previously throwing an error because I didn't have the code in place to handle infusion dosing with `F_CMT =0`
- It wasn't a major change to handle that properly

That's right that it is allowing new behavior where it used to throw an error.  I initially had it hight risk because the implementation seemed like it might be more complicated at first; but it was pretty simple after all; so at this point, I'm not thinking it is really high risk (especially with the new ss control parameters we implemented).

**Comment by dpastoor** [comment]
Agree - suggest adjustment to low risk as no impact to existing (correct) user behavior

**Comment by kylebaron** [comment]
@dpastoor I changed to low-risk.  Can you review and close?

**Comment by dpastoor** [comment]
LGTM
