### ISSUE TITLE
[BUG] Fix position for additional doses

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#499]
# Summary

They need to get positioned relative to absolute location in the data set; for large data sets, can't currently force additional doses to happen after observations at the same time.  

The only way to do this is to make the position greater than the number of rows in the data set; that needs to get passed into `schedule`.

Comprehensive testing for this issue as well as all 4 recsort values are in 
`tests/testthat/test-recsort.R`

See 3fb45ab263c9d68aa47aa3963f109cd110f4499b
See f84b0fb0b4ed13a7806e9f09a6299dc45e91aa48

# Tests
- tests/testthat/test-recsort.R
  - recsort 1 and 2, data
  - recsort 3 and 4, data
  - recsort 2 and 4, addl
  - recsort 1 and 3, addl

**Comment by kylebaron** [comment]
f84b0fb0b4ed13a7806e9f09a6299dc45e91aa48

**Comment by dpastoor** [comment]
LGTM
