### ISSUE TITLE
is this an installation issue?

### ISSUE THREAD

**Issue by edahmane** [metrumresearchgroup/mrgsolve#50]
I ran the example code in the readme page for the IDR model and I get the following error. Installation on my windows computer did not throw an error, so not sure what is happening. I get the same error for all models that I try to compile

```
> mod <- mcode("test",code=code)
Compiling test.cpp.cpp ... Warning messages:
1: running command 'make -f "C:/PROGRA~1/R/R-32~1.5/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-32~1.5/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="C:/Users/Elyes/AppData/Local/Temp/RtmpsLHco7/test23fc7d0c13bb.dll" WIN=64 TCLBIN=64 OBJECTS="C:/Users/Elyes/AppData/Local/Temp/RtmpsLHco7/test.cpp.o" shlib-clean' had status 127 
2: running command 'make -f "C:/PROGRA~1/R/R-32~1.5/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-32~1.5/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="C:/Users/Elyes/AppData/Local/Temp/RtmpsLHco7/test23fc7d0c13bb.dll" WIN=64 TCLBIN=64 OBJECTS="C:/Users/Elyes/AppData/Local/Temp/RtmpsLHco7/test.cpp.o"' had status 127 
Warning: Compile did not succeed.  Returning NULL.
Warning message:
running command 'R CMD SHLIB  --preclean C:/Users/Elyes/AppData/Local/Temp/RtmpsLHco7/test.cpp.cpp -o C:/Users/Elyes/AppData/Local/Temp/RtmpsLHco7/test23fc7d0c13bb.dll' had status 1 
```

**Comment by kylebmetrum** [comment]
I think it is.  Something same error reported here:
https://groups.google.com/a/metrumrg.com/forum/#!msg/mrgsolve/cXwQBJuI-vw/wnC-BcZwEgAJ

Note that it's not even getting to the compiler step.  Something is wrong with make before it even before it gets that far.

In the above example, the PATH to Rtools wasn't correctly set.  The user actually didnt' have sufficient access to his computer to let the installer make the change.   Not sure how locked down your computer is.  But  I would check that out first.  

Successful compile looks like this:
https://github.com/metrumresearchgroup/mrgsolve/issues/8#issuecomment-191487157

And this illustrates what the path should look like.
https://github.com/metrumresearchgroup/mrgsolve/issues/8#issuecomment-192095835


What Rtools version are you using?
https://cran.r-project.org/bin/windows/Rtools/

**Comment by edahmane** [comment]
Thank you for your answers. I will go through your response and I will keep you informed about the results.

**Comment by kylebmetrum** [comment]
I would be grateful if you would report back.  This sort of thing comes up from time to time and we're trying to build up better understanding about it ... to recognize specific cause earlier or provide direction to avoid in the first place.  Feedback about what went wrong or what fixed the issue really helps.

**Comment by edahmane** [comment]
I have the R-2.3.5 version and Rtools33 version.
Rtools was not installed in the correct PATH. I reinstalled Rtools33 in
C:\Program Files\R\R-3.2.5\bin\x64\Rtools.

However the same problem remains
````
> code <- '
+ #define CP (CENT/VC)
+ #define INH (CP/(IC50+CP))
+ $SET delta=0.1
+ $PARAM TVCL=1, TVVC=20, KA = 1.3, KIN=100, KOUT=2, IC50=10
+ $CMT GUT, CENT, RESP
+ $MAIN
+ double CL = exp(log(TVCL) + ETA(1));
+ double VC = exp(log(TVVC) + ETA(2));
+ RESP_0 = KIN/KOUT;
+ $OMEGA 0 0
+ $ODE
+ dxdt_GUT = -KA*GUT;
+ dxdt_CENT = KA*GUT - (CL/VC)*CENT;
+ dxdt_RESP = KIN*(1-INH) - KOUT*RESP;
+ $TABLE capture(CP);
+ '
> mod <- mcode("test",code=code)
Compiling test.cpp.cpp ... Warning messages:
1: running command 'make -f "C:/PROGRA~1/R/R-32~1.5/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-32~1.5/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="C:/Users/Elyes/AppData/Local/Temp/Rtmp8OkL8H/test260c45353e4f.dll" WIN=64 TCLBIN=64 OBJECTS="C:/Users/Elyes/AppData/Local/Temp/Rtmp8OkL8H/test.cpp.o" shlib-clean' had status 127 
2: running command 'make -f "C:/PROGRA~1/R/R-32~1.5/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-32~1.5/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="C:/Users/Elyes/AppData/Local/Temp/Rtmp8OkL8H/test260c45353e4f.dll" WIN=64 TCLBIN=64 OBJECTS="C:/Users/Elyes/AppData/Local/Temp/Rtmp8OkL8H/test.cpp.o"' had status 127 
Warning: Compile did not succeed.  Returning NULL.
Warning message:
running command 'R CMD SHLIB  --preclean C:/Users/Elyes/AppData/Local/Temp/Rtmp8OkL8H/test.cpp.cpp -o C:/Users/Elyes/AppData/Local/Temp/Rtmp8OkL8H/test260c45353e4f.dll' had status 1 
> sessionInfo()
R version 3.2.5 (2016-04-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.3         mrgsolve_0.6.1.9000

loaded via a namespace (and not attached):
[1] lazyeval_0.1.10 magrittr_1.5    R6_2.1.2        assertthat_0.1  parallel_3.2.5 
[6] DBI_0.4-1       tools_3.2.5     Rcpp_0.12.5   

````

**Comment by kylebmetrum** [comment]
Get Rtools32 instead.  It's frozen and I know it works with R 3.2.x  
https://cran.r-project.org/bin/windows/Rtools/

Re-install Rcpp and RcppArmadillo from source:
`install.packages(c("Rcpp", "RcppArmadillo"), type="source")`

Re-install mrgsolve:
`install.packages("mrgsolve_0.6.1.tar.gz", repos=NULL, type="source")`
modify the call above depending on what  / where the source package is.

Can you show me the following output after you've loaded `mrgsolve`?
`Sys.getenv("PATH")`

`sessionInfo()`

Thanks.

**Comment by kylebmetrum** [comment]
Ah ... sorry.  Just saw `sessionInfo` on the end of the last message.

**Comment by kylebmetrum** [comment]
Also:  put `$GLOBAL` above the `#define` stuff.  Maybe that got clipped out.  But you'd get a specific warning about `CP` and `INH` if the compiler ever got to the code.

```
code <- '
$GLOBAL # <<<-----**
#define CP (CENT/VC)
#define INH (CP/(IC50+CP))

$SET delta=0.1

$PARAM TVCL=1, TVVC=20, KA = 1.3, KIN=100, KOUT=2, IC50=10

$CMT GUT, CENT, RESP

$MAIN
  double CL = exp(log(TVCL) + ETA(1));
  double VC = exp(log(TVVC) + ETA(2));

  RESP_0 = KIN/KOUT;

$OMEGA 0 0

$ODE
  dxdt_GUT = -KA*GUT;
  dxdt_CENT = KA*GUT - (CL/VC)*CENT;
  dxdt_RESP = KIN*(1-INH) - KOUT*RESP;

$TABLE capture(CP);
'
```

**Comment by edahmane** [comment]
I reinstalled Rtools3.2 into the correct path.
And I reinstalled Rcpp, RcppArmadillo through the R Gui not Rstudio to get it work.

Thanks for you help.

**Comment by kylebmetrum** [comment]
So working now?

**Comment by edahmane** [comment]
Yes

**Comment by kylebmetrum** [comment]
Great.  I'm going to put a note in the install instructions about that.  Seems like we should be avoiding the unfrozen Rtools for whatever reason.  

Thanks for your patience.
