### ISSUE TITLE
code for inter-occasion variability

### ISSUE THREAD

**Issue by samitganguly** [metrumresearchgroup/mrgsolve#500]
I am working on a dataset with multiple occasions. I need to add inter-occasion variability term, which is going to be same for all occasions. 
Is there a possibility of coding, for example, like: ETAOCC(n) = "value"? So that I do not have to repeat this for a finite number of Occasions?

**Comment by kylebaron** [comment]
There is an example here:
https://github.com/mrgsolve/gallery/blob/master/population/iov.md

We could provide more flexible / convenient implementation with more information / details about your specific case.

**Comment by samitganguly** [comment]
Thank you Kyle! 
It was helpful. 

Regards
Samit

**Comment by mhismail** [comment]
You can also have a look at this issue which asked a similar question.

https://github.com/metrumresearchgroup/mrgsolve/issues/408

**Comment by kylebaron** [comment]
@samitganguly Agree that @mhismail has a really elegant solution in #408 and worth a look.  

Let us know if we can help with anything else.
