### ISSUE TITLE
infinite loop for complex TMDD model

### ISSUE THREAD

**Issue by JasonW000** [metrumresearchgroup/mrgsolve#501]
Hello, 

I am trying to code a TMDD model I had previously implemented in NONMEM where one mAb binds to two targets in the central compartment.  One issue is the interdependence of two equations in $DES.  The approach that seems to work in NONMEM is to set the complexes = 0 and then redefine each for time greater than 0... as shown:

$DES 
...
CPX1 = 0
CPX2 = 0 

IF (TIME.GT.0) CPX2 = 0.5*((KD2*VC+TAB+TCR-CPX1)-SQRT((KD2*VC+TAB+TCR-CPX1)**2 -4*(TAB-CPX1)*TCR))
IF (TIME.GT.0) CPX1 = 0.5*((KD1*VC+TAB+TSR-CPX2)-SQRT((KD1*VC+TAB+TSR-CPX2)**2 -4*(TAB-CPX2)*TSR))
...

When I try to implement this in mrgsolve (code attached) ...

[mrgsolve_2targetTMDD.txt](https://github.com/metrumresearchgroup/mrgsolve/files/3566792/mrgsolve_2targetTMDD.txt)

...the model compiles but during simulation I get an infinite loop error message.  I've tried a few approaches so far but cannot seem to get it to work. Any help would be greatly appreciated. 

thanks!

**Comment by kylebaron** [comment]
Hi @JasonW000 - 

This works for me out of the box.  Can you post the error message you get and also the version of R and mrgsolve you're working with and what platform?

Thanks,
Kyle

``` r
library(tidyverse)
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter

#################### model ################################

code <- '

$PARAM CLA=0.933, VC=1.07, Q=1.1, VP=4.96, BIO=0.5, KA=0.209, CLSR=2.45, CLC1=0.197,
KD1=1.01, BLSR=0.45, CLCR=9.39, KD2=0.285, BLCR=1.58

$CMT TAB, ABP, TSR, TCR, SC

$SET delta=72

$MAIN 
_F(1) = 1/0.15;
_F(5) = BIO*(1/0.15);

double CLC2=CLCR;

TSR_0 = BLSR;
TCR_0 = BLCR;

double KSY1=BLSR*CLSR;
double KSY2=BLCR*CLCR;

$ODE

double CPX1 = 0.5*((KD1*VC+TAB+TSR-CPX2)-sqrt(pow(KD1*VC+TAB+TSR-CPX2,2) -4*(TAB-CPX2)*TSR));
double CPX2 = 0.5*((KD2*VC+TAB+TCR-CPX1)-sqrt(pow(KD2*VC+TAB+TCR-CPX1,2) -4*(TAB-CPX1)*TCR));
double FAB = TAB-CPX1-CPX2;
double FSR = TSR-CPX1;
double FCR = TCR-CPX2;

dxdt_TAB = KA*SC +Q*(ABP/VP -FAB/VC) -(CLA/VC)*FAB -(CLC1/VC)*CPX1 -(CLC2/VC)*CPX2;
dxdt_ABP = Q*(FAB/VC -ABP/VP);
dxdt_TSR = KSY1 -(CLSR/VC)*FSR -(CLC1/VC)*CPX1;
dxdt_TCR = KSY2 -(CLCR/VC)*FCR -(CLC2/VC)*CPX2;
dxdt_SC = -KA*SC;

$TABLE
double CTAB = 150*(TAB-CPX2)/VC;
double CFAB = 150*(TAB-CPX1-CPX2)/VC;
double CTSR = 30*TSR/VC;
double FREE = ((TCR-CPX2)/TCR)*100;

$CAPTURE CTAB CFAB CTSR FREE

'
#######################################################################
# COMPILE MODELS
#######################################################################

dir<-tempdir()
mod <- mread(code=code, model="pkpd",proj=dir) # 
#> Building pkpd ...
#> done.
#######################################################################
wt <- 70

data<-data.frame(ID=1, evid=1, time=0, cmt=5,amt=1*wt,addl=5,ii=14,dose=1)
sim1<- mod %>% data_set(data) %>% carry.out(evid,time,amt,dose,CTAB) %>% update(start=0,end=70,delta=0.1) %>% mrgsim
sim1<-as.data.frame(sim1)
sim1<-subset(sim1, evid==0)

ggplot(sim1,aes(x=time,y=CTAB))+
  geom_line()+
  scale_y_log10(limits=c(0.1,100000))+
  scale_x_continuous(breaks=c(0,14,28,42,56,70,84))+
  labs(y='Concentration (ng/mL)', x="Time (day)")
#> Warning: Transformation introduced infinite values in continuous y-axis
```

![](https://i.imgur.com/F2uUx9s.png)

<sup>Created on 2019-09-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by JasonW000** [comment]
Hi @kylebaron, 

Thanks for letting me know you were successful with the original code.  I updated my packages and still get the message:   

DLSODA-  At current T (=R1), MXSTEP (=I1) steps   
      taken on this call before reaching TOUT     
In above message, I = 
[1] 2000
In above message, R = 
[1] 0.0261458
DLSODA-  ISTATE (=I1) illegal.
In above message, I = 
[1] -1
DLSODA-  Run aborted.. apparent infinite loop.    
Error in tran_mrgsim(<S4 object of class "mrgmod">, data = c(1, 1, 0,  : 
  error from XERRWD

**My session information:**
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
 [
1] PKNCA_0.8.5     metrumrg_5.57   MASS_7.3-47     XML_3.98-1.9    lattice_0.20-35 reshape_0.8.7  
 [7] mrgsolve_0.9.2  tidyr_0.7.2     dplyr_0.8.3     ggplot2_2.2.1  

thanks!

**Comment by kylebaron** [comment]
```
DLSODA- At current T (=R1), MXSTEP (=I1) steps
taken on this call before reaching TOUT
In above message, I =
[1] 2000
```

This means that the solver took 2K steps and didn't get to the destination yet.  Not sure why it's happening on your system and not mine.  

But you can try running with:
```
mod %>% ... %>% mrgsim(maxsteps = 10000)
```

That just says "don't error out until you've tried 10K steps".

**Comment by kylebaron** [comment]
Also:

```
DLSODA- Run aborted.. apparent infinite loop.
Error in tran_mrgsim(<S4 object of class "mrgmod">, data = c(1, 1, 0, :
error from XERRWD
```

This says that an old version of mrgsolve was used to generate the problem (this function doesn't exist in 0.9.2).  

Can you re-start your R process and generate the error again so I can see what is happening with 0.9.2?

**Comment by kylebaron** [comment]
Yeah ... this is why it isn't working:

```
> mod


----------------  source: pkpd.cpp  ----------------

  project: /private/var/fol.../T/Rtmp07rsJ4
  shared object: pkpd-so-349153d2dd43 

  time:          start: 0 end: 24 delta: 72
                 add: <none>

  compartments:  TAB ABP TSR TCR SC [5]
  parameters:    CLA VC Q VP BIO KA CLSR CLC1 KD1 BLSR
                 CLCR KD2 BLCR [13]
  captures:      CTAB CFAB CTSR FREE [4]
  omega:         0x0 
  sigma:         0x0 

  solver:        atol: 1e-08 rtol: 1e-08 maxsteps: 5000
```

The default maxsteps used to be 2000; now it is 5000.  When I run with 2K I hit the max too.  But with the new default of 5K I get a reasonable (?) result. 

Make sure you're loading `0.9.2` and the example should run due to more maxsteps by default.

**Comment by kylebaron** [comment]
Information on `maxsteps`:
https://mrgsolve.github.io/user_guide/model-components.html#maxsteps

**Comment by JasonW000** [comment]
Somehow after updating all my packages all of my previous mrgsolve models are not working (including the one I posted earlier) and giving the error message: 

Error in (function (x, data, idata = no_idata_set(), carry_out = carry.out,  : 
  Index out of bounds: [index='mtime'].

Sorry if this is an issue you already discussed, I have not been able to find a solution online.  Do you know how to fix this?

**Comment by kylebaron** [comment]
There is probably some remnant of the previous version.  

1. Restart your R session
1. remove.packages("mrgsolve")
1. Restart your R session
1. install.packages("mrgsolve")

Then try.

**Comment by JasonW000** [comment]
This solved everything, I'm back in business. Thank you VERY much for your help!

**Comment by kylebaron** [comment]
Ok; sorry for the scare there :).
