### ISSUE TITLE
[BUG] tad calculation doesn't recognize evid 4

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#502]
# Summary

The bug is that records are only checked for evid 1

- Look for both evid 1 and 4 when looking for first dose
- Reset time of dose when evid is 1 or 4
- Add test to make sure tad is calculated the same with evid 1 or 4

See 8a66ffac8b89de0dd2f34456b7779825ec6de3a9

# Tests
- tests/testthat/test-tad.R
  - tad recognizes evid 1 and 4 issue-502

**Comment by kylebaron** [comment]
#503

**Comment by dpastoor** [comment]
LGTM
