### ISSUE TITLE
[F] Implement libsoda ode solver

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#504]
# Summary

Replace ODEPACK ode solver with lsoda solver written in C++

https://github.com/dilawar/libsoda

FIrst step is to just get the simulation going with the new solver.  I'd like to get it implemented alongside ODEPACK so we can still easily benchmark; but if it does well, tempted to just leave the FORTRAN code behind. 

See pull request #519 

- The odepack fortran code has been removed
- The only available solver is the C++ lsoda
- All of the same options can be passed through
  - hmax
  - hmin
  - atol and rtol (both implemented as scalar values for now)
  - maxsteps
- I refactored part of the LSODA object
  - Changed printf statements (and other message printing) to REprintf
  - Moved certain data items to be members of LSODA
  - Moved certain members to public for ease of access

The switch and code were discussed briefly with @chousand-metrum and @dpastoor 

The switch was necessary due to repeated compiler warnings coming from the old ODEPACK code as CRAN moves to newer fortran compilers.

# Tests
-  tests/testthat/test-iv-po.R
    - CP from oral model is identical to closed form result
    - CP from iv model is identical to closed form result
- inst/validation/test-validation.R
    - non-stiff problem
    - stiff problem

**Comment by kylebaron** [comment]
See . dc19112c2956498c172e6b4881040872384ffa81

**Comment by dpastoor** [comment]
LGTM
