### ISSUE TITLE
Feature Request: Dataset Error Check (AMT with EVID=1)

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#508]
I just accidentally created a dataset with an EVID column with 1s in it, but I had no AMT column.  I know that there are data quality checks, and I think it'd be useful to add the requirement to have an AMT column when EVID=1 is present.  Maybe there is a reason you'd want to have no AMT when EVID=1, but I can't think of one.

**Comment by kylebaron** [comment]
Placebo doses?

**Comment by billdenney** [comment]
Fair enough.

**Comment by kylebaron** [comment]
I know nonmem complains when you have this.  I allowed it b/c it seems to give this flexibility.  Also helps some one some tests (so I can dose and see dosing records come through while still having easy odes to solve). 

Anyway ... I did create a repo to start working on data checking functions.  Added you as write collaborator if you would like to work together on it. 

https://github.com/mrgsolve/mrgsolve.data

Happy to remove mrgsolve references from the title etc if you wanted to make it more general ... for anything NMTRAN-like.  But assuming then that some subset of the functionality would be set up to address specifics to mrgsolve.

**Comment by billdenney** [comment]
That sounds great!  I assume that the intent is that it would be focused on the idea of the following (for the DESCRIPTION file):

Assist with data errors, data cleaning, and potential data issues for data to be used in mrgsolve (and similar software)

The "and similar software" is to acknowledge that it may help for NONMEM, nlmixr, etc.  ;)
