### ISSUE TITLE
[F] Get NONMEM output from ext file

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#509]
# Summary

- Add NMEXT block
- Reference run / proj or file to read the nonmem EXT output

PR #662 
Lots of discussion and motivation in #589 

# Tests
- testthat/test-nmxml.R
  - NONMEM estimates from nmext

**Comment by billdenney** [comment]
I have a hope that all packages that work with NONMEM could move toward a single, consolidated model and results reader interface.  I'd like to suggest that if this is implemented, that it is implemented by integration with another package that already does that work (with feature updates to that package, if needed).

**Comment by kylebaron** [comment]
See also #589
