### ISSUE TITLE
[BUG] NMXML needs to check for nm namespace

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#510]
# Summary

A user reported NONMEM output in xml file that didn't have the `nm` namespace and this causes `nmxml()` to break.  It is not clear how or why nonmem writes the xml file with nm namespace some time and without the nm namespace other times.

Put in code that checks for `nm` namespace and works as is if found.  If the `nm` namespace is not found, the user can use a new argument to `nmxml()` called `xpath` for addressing where the `estimation` block is in the xml file.

A test has been added to inst/validation with the example `.xml` files shared by the user reporting this issue.

See PR #511 

# Tests
- inst/validation/test-validation.R
  - nm xml with no namespace issue-510

**Comment by dpastoor** [comment]
LGTM
