### ISSUE TITLE
[F] Evaluate arguments to ev constructor

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#512]
# Summary
For example, we want some items to be a function of other items.  We commonly do this:

`ev(amt = 100, rate = amt/2)`

See PR #515 

See https://github.com/metrumresearchgroup/mrgsolve/commit/b31f011e288b05d51b187501297b9587926c35d2 

# Tests
- tests/testthat/test-ev.R
  - create ev with evaluation issue-512

**Comment by dpastoor** [comment]
LGTM
