### ISSUE TITLE
[R] Event object constructor and update

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#513]
# Summary

Adds operators and standardized processing of event objects

- Add `$` and `[[` operators
- Standard column ordering
- Recalculate upon mutate or coersion
  - tinf / rate
  - addl / total
  - addl / until
- The tinf column is retained in result 4dc1926
  - This means that, as long as tinf is in the event object, it will always control the rate; 
    the *only* way to control rate is via tinf until tinf is removed from the object
- Add tests
- Standardize column order, recalculate rate (tinf), addl (total), addl (until) for 
  data sets created through `expand.ev` as well
- Error faab13c
  - attempt to update rate when tinf exists
  - attempt to include both rate and tinf
  - attempt to include both addl and total 
  - attempt to include both addl and until

PR #558 
PR #559 

See `finalize_ev`

# Tests
- tests/testthat/test-ev.R
  - tinf issue-513
  - total  issue-513
  - until  issue-513
- tests/testthat/test-utils.R
  - expand.ev issue-513

**Comment by kylebaron** [comment]
Look into ev_seq and ev_rep; these either aren't calling that finalizer or just getting columns out of sort.  Not a bug, but I'd like to see the result better organized (ID,time,...).

**Comment by dpastoor** [comment]
LGTM
