### ISSUE TITLE
Error: invalid operands to binary expression

### ISSUE THREAD

**Issue by sueinchoi** [metrumresearchgroup/mrgsolve#514]
Hi I'm suein choi in Catholic university of korea.
I was wondering if i can use this equation in [MAIN] or [ODE] part

[Main]
double FporeSad = (1 - GammaSad)^2*(1 - 2.105*GammaSad + 2.087*GammaSad^3 - 1.707*GammaSad^5 + 0.726*GammaSad^6)/(1 - 0.7586*GammaSad^5);

double FporeLad = (1 - GammaLad)^2*(1 - 2.105*GammaLad + 2.087*GammaLad^3 - 1.707*GammaLad^5 + 0.726*GammaLad^6)/(1 - 0.7586*GammaLad^5);

I got error message like 

![image](https://user-images.githubusercontent.com/48196612/65299082-f43ae580-dba8-11e9-8593-bd620b20e9c6.png)

is that mean I can't use this type of equation?

Also, is 'EXP' available in differential equation? such as 

dxdt_AIlu = LFlu*(1 - VRlu)*CVlung + (PSSlu*PNSlu/(**exp**(PNSlu)-1) + PSLlu*PNLlu/(**exp**(PNLlu)-1))*(CVlung - CIlung) - LFlu*(1 - VRlymph)*CIlung;

Thank you for your support in advance :)

**Comment by kylebaron** [comment]
Hi @sueinchoi - 

Some languages (FORTRAN / NONMEM) let you write `base**exponent` or `base^exponent`.  In C++ you have to use a function called pow: `pow(base,exponent)`.

So, you can replace
```
FporeSad = 3^2*GammaSad:
```
with 

```
FporeSad = pow(3,2*GammaSad);
```

You can use `exp` or any other C++ math function in your ODEs.  There is some limit on the data structures maintained by mrgsolve that can be accessed in `ODE` (you can't use `ETA(1)`).  But you can use any C++ function there. 

Let me know if that answers your question.

Best Regards,
Kyle

**Comment by kylebaron** [comment]
@sueinchoi Please re-open if I can be of help
