### ISSUE TITLE
[R] Switch to C++ 11

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#517]
# Summary

See pull request #519 

Since we are no-longer using fortran code via ODEPACK, we can change to C++ 11.

- Using C++11 now with shared pointer
- There are possibly code in the new ODE solver that requires C++11
- Best to set this as a System Requirement in addition to setting in Makevars

I believe the switch is desired in order to take advantage of more-modern features of C++11. 

Also, I believe the lsoda source code was developed using modern compiler and there is some chance that, without the C++11 requirement, some of the code may not be compatible with older compilers.  Rather than trying to obtain and test on a slew of old compilers I believe it would be better to just modernize with C++11.

### From the Rcpp FAQ:

> 3.13. Can I use C++11, C++14, C++17, . . . with Rcpp. But of course.
> In a nutshell, this boils down to what your compiler supports, and
> also what R supports. We expanded a little on this in Rcpp Gallery
> article providing more detail. What follows in an abridged summary.
> You can always locally set appropriate PKG_CXXFLAGS as an
> environment variable, or via ~/.R/Makevars. You can also plugins
> and/or R support from src/Makevars:
>   - C++11: has been supported since early 2013 via a plugin selecting 
> the language standard which is useful for sourceCpp()
> etc. For packages, R has supported it since R 3.1.0 which
> added the option to select the language standard via CXX_STD
> = CXX11. As of early 2017, over 120 packages on CRAN use
> this.

### From Writing R Extensions 

> 1.2.4 Using C++11 code
> 
> As from version 3.6.0, R selects a default C++ compiler with options that conform as far as possible42 to C++11

### Kevin Ushey from 2016
https://kevinushey.github.io/blog/2016/09/14/pitfalls-in-writing-portable-c++98-code/
> C++11
> If you can use C++11 (or greater) when compiling your package’s C++ code, just do it. The C++11 standard adds a slew of excellent features, while fixing a few omissions of the C++98 standard. Overall, C++11 makes it easier to write cross-platform, portable C++ programs. All of the platforms used on CRAN support C++11 now – most recently, Windows joined the club with the toolchain update spearheaded by Jeroen Ooms et. al, and with much help from Duncan Murdoch + others.
> 

> The only reason not to use C++11 nowadays is if your package needs to build on older machines

# Tests
- Check that C++11 is listed as a SystemRequirement in the DESCRIPTION file
- This is also set in the Makevars

**Comment by kylebaron** [comment]
Leave it for now.

**Comment by kylebaron** [comment]
See

**Comment by dpastoor** [comment]
LGTM
