### ISSUE TITLE
Intravenous Infusion and SC administration Simulations 

### ISSUE THREAD

**Issue by Ravua1992** [metrumresearchgroup/mrgsolve#522]
Hello, 

I am trying to simulate a TMDD model with both IV infusion and SC administration. I am creating my input data sets using idata. The individual parameters which were obtained from a log normal distribution as columns in the idataset. The SC model is working fine and results are as expected. However, when I am trying to use the same model for my IV simulation I keep running into some error. The duration of infusion is 15 min or 0.25 hour. 

In My current model: 
cmt=1 (SC compartment)
cmt=2 (central compartment)

"In above message, I = 
[1] -1
DLSODA-  Run aborted.. apparent infinite loop"

Columns in my idata set for IV infusion: 
```
amt=150 ,evid=1, doserate=amt/0.25,rate=doserate, time=0,cmt=2

mod%>% data_set(idata) %>% mrgsim(end=4000,delta=1) %>% as.data.frame()
```

I also tried to use D_CENT=0.25 in $MAIN block and setting rate=-2 in my idata set. 
This doesn't seem to help either. 
Is this happening because I have depot compartment with KA and F ? The F for my SC cmt is set to 0.5 and IV cmt  is set to 1 in $MAIN as shown below. 
All the compartment in the model are defined in $CMT block.  

```
$MAIN
F_EV1=F1;  F1=0.5
F_CENT=F2; F2=1
```

I am new to using mrgsolve and I know I am missing something very basic here. Any input would be helpful. 

Thank you,
Abhi

**Comment by kylebaron** [comment]
Hi @Ravua1992  - 

It's hard to say why it's happening.  I'm including some code with a non-TMDD model that shows (I think) the basic setup that you've shared (SC and IV dosing, KA, F, etc).   

If you can share more of the model, we could start to look at other pieces where it is getting hung up. 

Kyle

``` r


library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
```

# Model with IV and SC dosing

``` r
code <- '
[ param ] F1 = 0.5, F2 = 1, CL = 1, V = 7, KA = 1

[ pkmodel ] cmt = "EV1 CENT", depot = TRUE

[ main ] 
F_EV1=F1; 
F_CENT=F2; 
'

mod <- mcode("ivsc", code)
#> Building ivsc ... done.
```

# SC dose

``` r
data <- tibble(ID = 1, amt = 150, evid = 1, time = 0, cmt = 1)

data
#> # A tibble: 1 x 5
#>      ID   amt  evid  time   cmt
#>   <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1     1   150     1     0     1

mod %>% data_set(data) %>% mrgsim(end = 12, delta =0.1) %>% plot
```

![](https://i.imgur.com/asgJmYa.png)

# IV dose

``` r
data <- mutate(data, doserate = amt/2, rate = doserate, cmt = 2)

data
#> # A tibble: 1 x 7
#>      ID   amt  evid  time   cmt doserate  rate
#>   <dbl> <dbl> <dbl> <dbl> <dbl>    <dbl> <dbl>
#> 1     1   150     1     0     2       75    75

mod %>% data_set(data) %>% mrgsim(end = 12, delta =0.1) %>% plot
```

![](https://i.imgur.com/xCuFFZx.png)

<sup>Created on 2019-09-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Ravua1992** [comment]
Hello Kyle, 

Thank you for the response. 
I have tried to set up my dataset similar to the example which you have shared above. The model runs now as an IV bolus dose (rate=0) and I get the same error for IV infusion (rate=amt/0.25) for 15 min infusion. 

I wanted to understand what are the units for rate in mrgsolve simulations ? If I am giving an infusion for 15 min to dose the compound how do I set up the rate in the event such that total dose is delivered in exactly 15 min ? The time units for my simulation is hours which is why I am dividing the amt/0.25 to get the calculate the rate for 15 min. 

Thank you,
Abhi

**Comment by kylebaron** [comment]
Yeah; you have it right: it would be 0.25 hours if you have the rest of the model parameterized in hours too. 

I'd run the example I gave and make sure you can reproduce that result.   You can try to divide the amount by 0.25 to convince yourself that the infusion lasts for 15 min.

After that, we'd need to see more of the model or more of the code to generate inputs to diagnose.  And we need to see exact code rather than pseudo code summaries of your code.

**Comment by Ravua1992** [comment]
data set: 

```
nsim<-1000
set.seed(33020)
conversion=10
idata1<- data.frame(expand.idata(amt=c(1,2,3,4,5),ID=c(1:1000)) %>%
 mutate_random(WT ~ sample(wtdist$WT, size=nsim, replace = TRUE))%>%
  mutate_random(TVRR0~ rlnorm(meanlog=(meanTarget),sdlog=sdTarget))%>%
  mutate_random(TVKEL~ rlnorm(meanlog=mean1,sdlog=sd1))%>%
  mutate_random(TVV1~ rlnorm(meanlog=meanv1,sdlog=sdv1)) %>% 
  mutate_random(TVKCOM~ rlnorm(meanlog=meankcom,sdlog=sdkcom)) %>% 
  mutate_random(TVKDEG~ rlnorm(meanlog=meankdeg,sdlog=sdkdeg)) %>%
  mutate(MEAN_TVRR0=mean(TVRR0)) %>%
  group_by(ID)%>%
  mutate(MEAN_TVRR0=MEAN_TVRR0*conversion,TVRR0=TVRR0*conversion,TOTALCMT4_0=TVRR0)%>%
  mutate(KEL=TVKEL)%>%
  mutate(KCOM=TVKCOM)%>%
  mutate(KCOM=KCOM)%>%
  mutate(KDEG=TVKDEG)%>%
  mutate(KDEG=KDEG)%>%  
  mutate(K12= mu_K12) %>% 
  mutate(K21= mu_K21) %>%
  mutate(TVKA= mu_KA )%>%
  mutate(KA=TVKA)%>%
  mutate(amt=amt*(70/WT),evid=1,cmt=2,rate=-2,
         time=0))

```
Model CODE: 

```
$PLUGIN Rcpp

  $PARAM @annotated
  
  F1:0.5: Bio EV1
  F2:1: Bio central
  D1:0.25: Duration
  FACTOR:0:factor 
    
$CMT  @annotated
    EV1    : First extravascular compartment (mass)
    CENT   : Central compartment (mass)
    PERIPH : Peripheral compartment (mass) 
    CMT4: Total Target
    CMT5: Total Complex (mass)
    
$MAIN
CMT4_0=TVRR0;
F_EV1=F1;
F_CENT=F2;
D_CENT=D1;


$ODE
double CP= (CENT/TVV1);
double CF= (CP- COMPLEX);
double CFA= (CENT-(COMPLEX*TVV1));

dxdt_EV1    = -KA*EV1; 
dxdt_CENT   =  KA*EV1 + K21*PERIPH -FACTOR*KEL*CFA-K12*CFA-KCOM*TVV1*COMPLEX;
dxdt_PERIPH   = -K21*PERIPH + K12*CFA;
dxdt_CMT4   = KDEG*TVRR0 - CMT4*KDEG- KCOM*COMPLEX+KDEG*COMPLEX;
dxdt_CMT5 = KON*CF*(CMT4-COMPLEX)-(KCOM+KOFF)*COMPLEX;


$CAPTURE @annotated
CP: Tot DRUG 
CMT4 : Tot Target 

```
Simulation 
`Sim<- mod%>%data_set(idata1) %>%carry.out(ID)%>% mrgsim(end=10,delta=0.1) %>% as.data.frame()`

**Comment by Ravua1992** [comment]
Hello Kyle, 

I shared both the codes for data set and model. Hope this helps. The model is working when rate=0, rate=10 and doesnt work when the rate=25, 50 or 100. I am just trying to understand why is it so sensitive to different values of rate of infusion ?

**Comment by kylebaron** [comment]
Thanks; there's not a lot I can do without something that runs.  If you could make a running reproduction of the issue, 

For now, I'd try to simplify the inputs and model and see if the issue still persists:

1 - Do your simulation with no variability in the parameters to see if you have simulated some wacky parameter sets that are causing the model to crump
2 - Cut the TMDD part out of the model until you get the dosing figured out

Feel free to email me https://github.com/kylebaron if you'd like to chat privately.

KTB

**Comment by Ravua1992** [comment]
Thanks Kyle. I will try to make up something which runs and share it soon. I will definitely reach out to you after trying to troubleshoot more at my end and if this problem still persists.

**Comment by Ravua1992** [comment]
Hello Kyle,

My name is Abhigyan Ravula and I am writing this email with regard to the issue I am experiencing with mrgsolve.
I recently posted on github page and the title for the issue was "Intravenous Infusion and SC administration Simulations<https://github.com/metrumresearchgroup/mrgsolve/issues/522>"

Solution:

I was able to manage the model to run by increasing the maxsteps to 10000 and changing the atol and rtol settings(atol=1e-13,rtol=1e-13). This is working fine when I am doing single dose simulations and multiple dose simulations up to 3-4 additional doses. However, when I try to do the same for 15 additional doses the I get the same error saying that.

DLSODA-  At current T (=R1), MXSTEP (=I1) steps
      taken on this call before reaching TOUT
In above message, I =
[1] 10000
In above message, R =
[1] 3528.028
DLSODA-  ISTATE (=I1) illegal.
In above message, I =
[1] -1
DLSODA-  Run aborted.. apparent infinite loop.


Further, if I change the tolerance setting to atol=1e-15/20,rtol=1e-15/20, I get an error saying that I am requesting for too much precision.

Can you please help me with this situation ? Why is this happening and how do I get around it ?

Thank you,
Abhi

________________________________
