### ISSUE TITLE
[F] Refactor control of advance to ss

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#533]
# Summary

New arguments for mrgsim to control how the PK system is advanced to steady state.  The basic process is the same for bolus, intermittent infusion, or ss infusion, but these parameters can expose some control over determining ss.

- `ss_n` max number of iterations (doses to administer) to try
- `ss_fixed` assume ss is achieved after `ss_n` iterations
- a warning is generated if the PK system does not advance to steady state with specified tolerance within specified maximum number of iterations unless `ss_fixed` is true
- ss is achieved when the difference between the current trough and the previous trough is less than the local error estimate based on model atol and rtol

See PR #557

See https://github.com/metrumresearchgroup/mrgsolve/commit/450d97ce14334aee0f548754067c793a2228e8dd

From: http://www.netlib.no/netlib/alliant/ode/prog/lsoda.f
```
c rtol   = relative tolerance parameter (scalar).
c atol   = absolute tolerance parameter (scalar or array).
c          the estimated local error in y(i) will be controlled so as
c          to be less than
c             ewt(i) = rtol*abs(y(i)) + atol     if itol = 1, or
c             ewt(i) = rtol*abs(y(i)) + atol(i)  if itol = 2.
c          thus the local error test passes if, in each component,
c          either the absolute error is less than atol (or atol(i)),
c          or the relative error is less than rtol.
```

# Tests
- tests/testthat/test-ss.R
  - ss_n and ss_fixed issue-533
- inst/maintenance/unit/test-pk.R
  - one-compartment, bolus, ss
  - one-compartment, oral, first, ss
  - two-compartment, bolus, ss
  - two-compartment, bolus, first, ss
  - two-compartment, infusion, ss

**Comment by dpastoor** [comment]
LGTM - though there might be some user ergonomic changes that make sense around tolerances that have been discussed internally. Should create a new issue
