### ISSUE TITLE
[F] Add more informative error messages when parsing data set

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#534]
# Summary

The details vary with the error message, but try to print the ID, the data set row and the relevant value (e.g. for `cmt` out of range, give the value of cmt in the data set).

See dbf4c8556e756d1154a4195b45e4df548d74ce77

# Tests
- inst/maintenance/test-event-combinations.R
  - bad events issue-249

**Comment by dpastoor** [comment]
LGTM
