### ISSUE TITLE
[BUG] REFERENCE 484: SS with ALAG and no prior observation

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#539]
# Summary

This issue is a reference to #484 

>I've found that SS doses with an ALAG model are only working for me when there is an observation immediately prior to the dose (or at the same time, but sorted so that the observation occurs first in the data frame).

>In this example, the doses at 0 and 168 h show what concentrations look like after a single dose and with 1-week washout, and then there's a SS dose at 336 h. If the data frame is sorted by evid (i.e. observation first at 336 h), it looks like the SS dose works as expected. But if I sort by desc(evid) (dose first) the dose isn't at steady state.

This bug was fixed.  See #484 

# Tests
- inst/maintenance/unit/test-alag.R
  - ss dose with lag time issue-484

**Comment by dpastoor** [comment]
LGTM - In the future it would be good to also have an output record showing the test _failing_ before the code change was pushed. Eg run test-alag and screenshot/add the testthat output showing it failing.
