### ISSUE TITLE
Need help to install

### ISSUE THREAD

**Issue by danielcml** [metrumresearchgroup/mrgsolve#54]
Hi, after installing Rccp, RccpArmadillo, BH and dplyr, I am encountering problems installing mrgsolve. The R console message is:

> install.packages("mrgsolve_0.5.001.tar.gz", repos=NULL, type="source")
* installing *source* package 'mrgsolve' ...
** package 'mrgsolve' successfully unpacked and MD5 sums checked
** libs

*** arch - i386
Warning: running command 'make -f "Makevars.win" -f "D:/R/etc/i386/Makeconf" -f "D:/R/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="mrgsolve.dll" SHLIB_LIBADD='$(FLIBS)' OBJECTS="RcppExports.o Rodeproblem.o dataobject.o datarecord.o devtran.o housemodel.cpp.o maketran.o mrgsolve.o odepack_dlsoda.o odeproblem.o opk_dlsoda_mrg.o opkda1_mrg.o opkda2_mrg.o pkevent.o tofunptr.o"' had status 127
ERROR: compilation failed for package 'mrgsolve'
* removing 'D:/R/library/mrgsolve'
Warning in install.packages :
  running command '"D:/R/bin/x64/R" CMD INSTALL -l "D:\R\library" "mrgsolve_0.5.001.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘mrgsolve_0.5.001.tar.gz’ had non-zero exit status

> library(mrgsolve)
Error in library(mrgsolve) : there is no package called ‘mrgsolve’

Please help!

**Comment by kylebmetrum** [comment]
I can help you with this.  Can you first grab the latest release?
https://github.com/metrumresearchgroup/mrgsolve/releases/download/v0.6.1/mrgsolve_0.6.1.tar.gz

This isn't the cause of the problem, but `0.5.001` is pretty old now.

Did you install `Rtools` (https://cran.r-project.org/bin/windows/Rtools/).  If so, which version?  If it was `Rtools33.exe` change back to `Rtools32.exe` and re-install `Rcpp`, `RcppArmadillo`.  

Also can you share the output to these `R` commands:
* `sessionInfo()`
* `Sys.getenv("PATH")`

**Comment by danielcml** [comment]
Hi Kyle,

Thanks for your advice! It's working now.

Daniel
