### ISSUE TITLE
[R] Update default solver settings

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#540]
# Summary 

Changing the default values of these solver settings

- Increase default maxsteps to 20K f80993cda6965988c67ef29774656556f9a4045b 
- Set initial mxhnil to 2 f80993cda6965988c67ef29774656556f9a4045b
- The default `rtol` will remain at `1e-08`

# Tests
- tests/testthat/test-mrgmod.R
  - defaults issue-540

**Comment by dpastoor** [comment]
@kylebaron can you explain a little more around the choice to adjust these defaults, and if there are any situations where increasing the max steps could result in issues? For example, could users be accidentally leveraging the 'functionality' of only having 5000 steps and with this change would get different results?

**Comment by kylebaron** [comment]
@dpastoor 

- mxhnil - limiting this to 2 just means it will stop printing messages after it prints 2 times; when it stops printing messages, it says that it will stop; so reducing it to 2 just means less junk printed to the console 

- maxsteps - this just has the solver error out if it takes more than this many steps when integrating to the next time point;  so when it was 5K, we had people integrating across a long time and it could easily require more than 5K steps.  When the error message comes, it was confusing because it suggested something was wrong with the model etc.  Increasing it to 20k will allow more steps to be tried before it gives up.  I don't think this would otherwise change the answer: when the model is really bad, IMO it will fail for some other reason

**Comment by dpastoor** [comment]
Sounds reasonable to me - adjusted to low risk and can close out.
