### ISSUE TITLE
[BUG] Need to check that mod is there

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#547]
# Summary

There needs to be an error if the model object isn't passed.  

Create a function that tests and reports; this will get used in several functions

```
> out <- mrgsim_ei(d, idata)
Error in combine_list(x@args, args) :
  trying to get slot "args" from an object (class "data.frame") that is not an S4 object
Calls: mrgsim_ei -> mrgsim_e -> combine_list
```

See PR #549 

# Tests
- tests/testthat/test-mrgsim.R
  - error to not pass model object issue-547

**Comment by dpastoor** [comment]
LGTM
