### ISSUE TITLE
[R] Error if compartment is listed in capture

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#555]
# Summary

Generate an error if a compartment name is found as a capture name

- Do this in mread for nicer error
- Also check this in the valid object method

See PR #556 

<hr>

Example:

Error:
```r
$CMT A
$CAPTURE A
```

Not an error:
```r
$CMT A
$CAPTURE B = A
```

# Tests

- inst/maintenance/unit/test-capture.R
  - error if cmt in capture issue-555

**Comment by dpastoor** [comment]
LGTM
