### ISSUE TITLE
[F] Add position argument to expand_observations

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#565]
# Summary

- Add integer argument to expand_observations that says how records are to be sorted; the user can control if new observations happen before or after existing records at the same time
- A negative integer will put additional observations prior to existing records at the same time
- User controlled integer - usually large - ensure that additional observations are placed after existing records at the same time; the user determines appropriate value given the input

See PR #566 

# Tests

- tests/testthat/test-data_set.R
  - add position argument to expand observations issue-565

**Comment by dpastoor** [comment]
LGTM
