### ISSUE TITLE
accessing "t" in $MAIN

### ISSUE THREAD

**Issue by vjd** [metrumresearchgroup/mrgsolve#57]
I am trying to parameterize a model with time-varying absorption. e.g. 

```
$MAIN
double KA =1;
double if (t <2) KA=2*t;
``` 

how do I access the simulation time that we specify in `$SET` via the `delta` and `end` parameters
should I be using `t` or `time` or something else to set up this simulation? Notice that if `t<2`, then KA is a function of `t`.

**Comment by kylebmetrum** [comment]
http://mrgsolve.github.io/user_guide/model-specification.html#time

`TIME` if it is in `$MAIN`; `SOLVERTIME` inside `$ODE`.

**Comment by kylebmetrum** [comment]
@vjd  There is also this example. Not exactly the same but similar to what you are doing.

https://github.com/metrumresearchgroup/mrgsolve/wiki/time-varying-ka

There is also a way to force a discontinuity into the simulation at the time that `ka` changes.  Need a little bit to work up that example.

**Comment by vjd** [comment]
To use `TIME` in $MAIN, do I need to have a `data_set` with the complete simulation time records, or will it be read from the generated values based on `$SET`?

**Comment by kylebmetrum** [comment]
Good point; that documentation probably should be "observation record time" not "data set time".  I'll make the update.

`TIME` gets set any time there is an observation record; this could be records in a `data_set` or the observations that get inserted from `$SET start/end/delta/add`.

**Comment by vjd** [comment]
Perfect. Thanks.

**Comment by kylebmetrum** [comment]
Ack ... `TIME` isn't just for observations ... for any record.  Every record has a time; and `TIME` always has a value.
