### ISSUE TITLE
Feature Consideration:  Stochastic Integrators

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#575]
Note that I'm not even calling this to the level of a feature request.

The Gillespie algorithm is used to simulate stochastic, countable chemical reactions (and similar): https://en.wikipedia.org/wiki/Gillespie_algorithm

I'm trying to implement a CAR-T model which includes a stochastic probability of cure: https://www.biorxiv.org/content/10.1101/717074v2

It would be interesting to me if mrgsolve also included a hybrid deterministic/stochastic integrator that could combine typical ODE solutions with the Gillespie algorithm (perhaps simplifying life using the Tau-leap version of the algorithm so that an explicit algorithm switch would not be required: https://en.wikipedia.org/wiki/Tau-leaping).

This would be a massive change, I understand, but it would open up a new class of problems that is not possible today with mrgsolve.

**Comment by kylebaron** [comment]
Closing this.  Maybe is is something that would be doable in the julia package.
