### ISSUE TITLE
Coding categorical covariate

### ISSUE THREAD

**Issue by melagha** [metrumresearchgroup/mrgsolve#581]
Hell,
I need help on how to code categorical covariant  that has more than two categories. Binary covariates that can be coded (0,1) are easy incorporated in the model. However I was unable to build a model that has the RACE that has four categories.

your help greatly appreciated.

Best regards

**Comment by kylebaron** [comment]
Hi @melagha 

You can try something like this:

```r
$PARAM 
RACE = 1
CL_REF = 1
RACE_EFF_2 = 1.1
RACE_EFF_3 = 0.9
RACE_EFF_4 = 0.99

$MAIN
double TVCL = CL_REF;
if(RACE==2) TVCL = TVCL * RACE_EFF_2;
if(RACE==3) TVCL = TVCL * RACE_EFF_3;
if(RACE==4) TVCL = TVCL * RACE_EFF_4;

double CL = TVCL * exp(ETA(1));

```

`RACE` could be 1 or 2 or 3 or 4 and probably would be included in the data set (doesn't have to be).

`CL_REF` is the typical clearance for the reference patient (`RACE==1`)

The system would advance with the value in `CL`

I didn't include the OMEGA block but it should be there to get the ETA(1) simulated.

**Comment by melagha** [comment]
Very very thankful for prompt response.
Best regards

**Comment by kylebaron** [comment]
No problem.  Thanks for reaching out.
