### ISSUE TITLE
Feature request: self.cmt_name macro?

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#582]
I'm working on model composition to combine models for PK from one paper with PD from another paper.  For this, the model is getting moderately complex, and it would be helpful if there were a way to check what compartment the model is in within the main block by name.

Currently, I have code that looks like:

```
if (NEWIND <= 1) {
  capture TDOSE_CHEMO = -1;
  capture TDOSE_CART  = -1;
} else if (self.evid == 1 & self.cmt == 1) {
  TDOSE_CHEMO = self.time;
} else if (self.evid == 1 & self.cmt == 3) {
  TDOSE_CART = self.time;
}
```

It would be much easier at the model composition stage if the code could look like:

```
if (NEWIND <= 1) {
  capture TDOSE_CHEMO = -1;
  capture TDOSE_CART  = -1;
} else if (self.evid == 1 & self.cmt_name == "CHEMO") {
  TDOSE_CHEMO = self.time;
} else if (self.evid == 1 & self.cmt_name == "CART") {
  TDOSE_CART = self.time;
}
```

I'd hope that this could be as simple as something like the following on the C++ side, but I'm probably missing a lot here.

```
char cmt_names[detected maximum number of compartments][maximum number of characters in a compartment name] = {"CHEMO", "CHEMO_PERIPH", "CART"};
#define self.cmt_name (cmt_names[self.cmt + 1])
```

**Comment by kylebaron** [comment]
You can try this:
``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter


code <- '
$CMTN GUT CENT PERIPH

$PARAM CL = 1, V2 = 3, Q = 2, V3 = 20, KA = 1

$PKMODEL cmt = "GUT,CENT,PERIPH", depot = TRUE

$MAIN
capture check = 0; 

if(CMT==N_GUT)    check = 1;
if(CMT==N_CENT)   check = 2;
if(CMT==N_PERIPH) check = 3;

'

mod <- mcode("foo", code,soloc = '.')
#> Building foo ...
#> done.

data <- data.frame(amt = 0, cmt = c(1,2,3), time = c(1.1,2.2,3.3), evid=0,ID=1)

data
#>   amt cmt time evid ID
#> 1   0   1  1.1    0  1
#> 2   0   2  2.2    0  1
#> 3   0   3  3.3    0  1

mod %>% mrgsim(data)
#> Model:  foo 
#> Dim:    3 x 6 
#> Time:   1.1 to 3.3 
#> ID:     1 
#>     ID time GUT CENT PERIPH check
#> 1:   1  1.1   0    0      0     1
#> 2:   1  2.2   0    0      0     2
#> 3:   1  3.3   0    0      0     3
```

<sup>Created on 2019-11-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This is pretty ancient functionality; you have to list each compartment you want to be able to check; today, I'd revise this to default to all compartments.  Does that sound ok?

**Comment by billdenney** [comment]
@kylebaron, that looks like it does what I'm asking about, but I'm not sure exactly what the important parts of the model that you wrote are.  Is the important detail that I should list something in both `$CMTN` and `$CMT` to have the value `N_GUT` work?

**Comment by kylebaron** [comment]
Right; you have to list the compartment names that you want the numbers for in `$CMTN`.   Not quite what I would implement today; but that is currently now it works.


For example

``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter


code <- '
$CMTN GUT

$PARAM CL = 1, V2 = 3, Q = 2, V3 = 20, KA = 1

$PKMODEL cmt = "GUT,CENT,PERIPH", depot = TRUE

$MAIN
capture check = 0; 

if(CMT==N_GUT)    check = 1;
if(CMT==N_CENT)   check = 2;
if(CMT==N_PERIPH) check = 3;

'

mod <- mcode("foo", code,soloc = '.')
#> Building foo ...
#> error.
#> 
#> ---:: stderr ::---------------------------------------------
#> 13:9: error: use of undeclared identifier 'N_CENT'
#> if(CMT==N_CENT)   check = 2;
#>         ^
#> 14:9: error: use of undeclared identifier 'N_PERIPH'
#> if(CMT==N_PERIPH) check = 3;
#>         ^
#> 2 errors generated.
#> make: *** [foo-mread-source.o] Error 1
#> 
#> ------------------------------------------------------------
#> Error: the model build step failed.
```

<sup>Created on 2019-11-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by billdenney** [comment]
OK, thanks for that help!  Perhaps as a minor feature request, remove the requirement of the `$CMTN` block (and just always have the `N_CMTNAME` constants defined?

**Comment by kylebaron** [comment]
Will do.

**Comment by kylebaron** [comment]
Also required:

- Document new macro
- Do something with `$CMTN`; it is probably not used very much;  maybe just issue warning  if someone uses

**Comment by kylebaron** [comment]
Closing this.  It was addressed in #606 ... opening a new issue for that to help with SDLC.

**Comment by kylebaron** [comment]
This got rolled out in 0.10.1; see #606  Thanks, @billdenney

**Comment by billdenney** [comment]
Thanks!
