### ISSUE TITLE
Performing bootstrap 

### ISSUE THREAD

**Issue by samitganguly** [metrumresearchgroup/mrgsolve#583]
Hi Kyle, 

Can you please explain the steps for performing a bootstrap? 
The model already has required omega and sigma. We can then "capture" them in the output file. Then utilize the output file for performing bootstrap? What is the utility of Omega and Sigma matrix? 

Regards
Samit

**Comment by kylebaron** [comment]
Hi Samit - 

mrgsolve can simulate from your bootstrap parameter estimates but won't so much to generate them. 

To perform a bootstrap, you first re-sample from your data set many times (100 or 300 or 1000) to create a series of bootstrap data sets.  Then fit your model to each of the bootstrap data sets.  At the end you will have 100 or 300 or 1000 sets of parameter estimates (THETA, OMEGA, and SIGMA).  Those are your bootstrap parameter estimates.  

To re-sample the data set, you might look at the `resample` function in the metrumrg package.
https://github.com/metrumresearchgroup/metrumrg

There is probably something on CRAN that does the same thing ,but this is what I use.

Kyle

**Comment by kylebaron** [comment]
@samitganguly please re-open the issue if there is anything else we can help with regarding bootstrap.
