### ISSUE TITLE
log-transformed data

### ISSUE THREAD

**Issue by melagha** [metrumresearchgroup/mrgsolve#586]
I am working on a model that used log- transformed PK data and used additive residual model as following:  lnCobs=lnCpred + e.
How can I implement this in mrgsolve?

Best regards

**Comment by kylebaron** [comment]
```c
[ sigma ] 
0.12345

[ table ] 
double Cpred = CENT/V2; // if you have a compartment named CENT and volume is V2

capture lnCobs = log(Cpred) + eps(1);

```

**Comment by melagha** [comment]
Very appreciated

**Comment by kylebaron** [comment]
Corrected the code snippet ... it should be `EPS(1)` rather than `eps(1)`.
