### ISSUE TITLE
Selfish Feature Request: Warn on an ID used more than once

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#590]
As I called this out in the title, this is a selfish feature request.

I never intentionally reuse an ID number.  In my datasets, ID=1 is always one individual.  Occasionally, I forget to sort my data before simulating, and I end up with difficult-to-interpret results because the dose is separated from the time points, for example.

It would help me if the same ID used separately were warned.  (I understand why the feature of allowing ID reuse is there.)

**Comment by dpastoor** [comment]
Perhaps more to the point of the request a warning if the data is not sorted by say ID and time by default, also even that could be customizable so you could also add, if so desired things like OCC

**Comment by kylebaron** [comment]
I think this sort of thing should go into the data cleaner package or maybe somewhere else.  Just want to avoid having to check ID reuse _every single time_ the model is run, regardless of the users desire.  There are some checks at run time, but those are more safety checks, to make sure your input doesn't cause the run to explode when you push Go.  But I'm totally for an optional, pre-validation step that users can implement to get warned about this sort of thing.  You could use it just for information ("oops, it doesn't look like your data set is sorted by ID") or run the check and then get a validated input object prior to running the simulation.  But I think the way to allow users to opt into the warning messages is to give a function that can get called.  If you are actively programming a data set, it shouldn't be too much to just call the function when you're done to make sure you didn't do something foolish.

I'm still hopeful there can be a very robust data cleaning package and I believe that package could be really helpful beyond mrgsolve.  But for now, how about I start working on a function that will do the essentials, with a focus on generating errors, warnings, messages after checking out the data.  This could easily be worked into a simulation pipeline or just tacked on to the end of your DA code chunk. 

?

**Comment by billdenney** [comment]
@kylebaron, that's a fair assessment.  I think that there is a way to move issues.  Can you move this one to the data package?

**Comment by kylebaron** [comment]
This will have to so somewhere else.
