### ISSUE TITLE
Documentation Request:  How is @covariates used?

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#592]
Can you please add in https://mrgsolve.github.io/user_guide/model-specification.html#block-param and in the help for `PARAM` how the covariates annotation is used?  My guess/hope is that it is required to be in the `data_set()` or `idata_set()`, but I'm not sure.

**Comment by kylebaron** [comment]
@billdenney - I will add this to the documentation.  But it just allows you to tag some of the parameters as "covariates".  It's somewhat arbitrary and for information only.  

``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter

code <- '
$PARAM CL = 1, V = 10, KA = 1.3

$PARAM @covariates
WT = 70, SEX = 1, ALB = 4.2

'

mod <- mcode("covariates", code)
#> Building covariates ...
#> done.

l <- as.list(mod)

l$covariates
#> [1] "WT"  "SEX" "ALB"
```

<sup>Created on 2019-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by billdenney** [comment]
Thanks!

**Comment by kylebaron** [comment]
Thinking more about the "required" parameters idea.  We did implement something along the lines of that, but it is an argument to the  `data_set` function rather than a set of parameters that is embedded in the model object.  So you can get something along those lines, but I realize it's not exactly what you were thinking about.  It could probably be worked into the data set check out routine as well. 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter

mod <- mrgsolve:::house()

data <- expand.ev(amt = 1)

try(mod %>% data_set(data, need = c("WT", "KA")))
#> Error : missing parameters in 'data'
#>  - WT
#>  - KA

data <- mutate(data, WT = 70, KA = 1.2)

mod %>% data_set(data, need = c("WT", "KA"))
#> 
#> 
#> --------------  source: housemodel.cpp  --------------
#> 
#>   project: /Users/kyleb/Rli...solve/project
#>   shared object: mrgsolve 
#> 
#>   time:          start: 0 end: 120 delta: 0.25
#>                  add: <none>
#> 
#>   compartments:  GUT CENT RESP [3]
#>   parameters:    CL VC KA F1 D1 WT SEX WTCL WTVC SEXCL
#>                  SEXVC KIN KOUT IC50 [14]
#>   captures:      DV CP [2]
#>   omega:         4x4 
#>   sigma:         1x1 
#> 
#>   solver:        atol: 1e-08 rtol: 1e-08 maxsteps: 20k
#> ------------------------------------------------------
```

<sup>Created on 2019-11-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by billdenney** [comment]
Ah, I wasn’t aware of the `need` argument.  I suppose that some form of overloading the argument with `need=“@covariates”` could cover the request, but I would understand not wanting to overload arguments.

**Comment by kylebaron** [comment]
Added some discussion and an example in the user guide.   Thanks, @billdenney for the report.
