### ISSUE TITLE
`vector::_M_range_check` error when running mrgsim

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#595]
When running the attached model (change the extension to .Rmd), I get the following error:

```r
library(mrgsolve)
model <- mread(model="test", file="mrgsolve_model_example.Rmd")
mrgsim(model)
```

Gives the error: 
```
Error in (function (x, data, idata = no_idata_set(), carry_out = carry.out,  : 
  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 50)
```

Any ideas what is causing this?

[mrgsolve_model_example.txt](https://github.com/metrumresearchgroup/mrgsolve/files/3882877/mrgsolve_model_example.txt)

**Comment by kylebaron** [comment]
`double FCENT = exp(lFCENT + ETA(IIVFCENT));`

should be

`double FCENT = exp(lFCENT + IIVFCENT);`

**Comment by billdenney** [comment]
Whew!  Thank you!  I was rooting around in C++ vector handling on StackOverflow and (obviously) not going down the right path.

**Comment by billdenney** [comment]
Would it be reasonable to require the value of `n` within `ETA(n)` to be an integer or add a range check within mrgsolve to clarify that the eta value is invalid?  (In other words, help me and others who may have the same problem in the future with a more direct error message.)
