### ISSUE TITLE
reproducible simulations including residual error

### ISSUE THREAD

**Issue by indysandaradura** [metrumresearchgroup/mrgsolve#626]
Hi, I understand that either setting a seed or passing pre-defined parameter values via the input data to mrgsolve allows reproducible simulations of the 'same patient' or "same population'. I have successfully used the latter approach to create and simulate a predefined (in terms of covariates) population.

However, I now want to do the same but include RUV (sigma), whilst simulating the 'same population'. Despite using set.seed() I am ending up with the same patients and same individual predictions (IPRE) but different observations (DV) on repeated simulations.

Any advice on how to reproduce the RUV and get the same DV each time for each 'patient' would be much appreciated!

**Comment by kylebaron** [comment]
Hi @indysandaradura - 

Please see code below to make simulations reproducible, including residual error.  If you have a setup where it isn't reproducible, please share it here.

``` r

library(tidyverse)
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter

data1 <- expand.ev(amt = c(100,200,300)) %>% expand_observations(seq(1,48,1))
data2 <- mutate(data1, ID = ID + 10)


mod <- modlib("popex") %>% smat(matrix(0.05))
#> Building popex ...
#> done.
revar(mod)
#> $omega
#> $...
#>       [,1] [,2] [,3]
#> ECL:   0.3  0.0  0.0
#> EV:    0.0  0.1  0.0
#> EKA:   0.0  0.0  0.5
#> 
#> 
#> $sigma
#> $...
#>     [,1]
#> 1:  0.05

set.seed(123)
out1 <- mrgsim(mod,data1)
plot(out1)
```

![](https://i.imgur.com/oN1xxYU.png)

``` r

set.seed(123)
out2 <- mrgsim(mod,data2) %>% mutate_sims(ID=ID-10)

identical(out1,out2)
#> [1] TRUE

summary(out1$DV-out2$DV)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>       0       0       0       0       0       0
```

<sup>Created on 2020-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Kyle

**Comment by indysandaradura** [comment]
Thanks for the speedy reply as always Kyle. 

For some reason the set.seed operation doesn't work for me in this instance. I've copied my code and uploaded the input population files that I'm using as a zip. As you can see it is the same population, and I get the same IPRE but different DV. I'm on mrgsolve 0.10.0. 

I'd be very grateful for any insights you have!

[input_pops.zip](https://github.com/metrumresearchgroup/mrgsolve/files/4124453/input_pops.zip)


# Clear workspace
rm(list=ls(all=TRUE))
graphics.off()

# Load package libraries
library(tidyverse)
library(mrgsolve)

# Source PopPK model script
# POPULATION PHARMACOKINETIC MODEL FINAL (fAUC capture)

# ------------------------------------------------------------------------------
# Define the model parameters and equations

code <- '

//INITIAL CONDITIONS 
$INIT
CENT  = 0, AUC1  = 0, AUC2 = 0, AUC3 = 0, AUC4 = 0, AUC5 = 0, AUC6 = 0, AUC7 = 0, AUC8 = 0, AUC9 = 0, AUC10 = 0, AUC11 = 0, AUC12 = 0, AUC13 = 0, AUC14 = 0

//SET DIFF EQ SOLVER OPTIONS
$SET			
atol = 1e-9

//POPULATION PHARMACOKINETIC PARAMETERS
$PARAM @annotated
  POPCLR : 0.705 : Systemic clearance
  POPCLC : 1.914 : CVVH clearance
  POPV   : 46.337 : Volume of distribution

// COVARIATE EFFECTS
  CLREN : 0.635 : Renal function on systemic clearance
  VWT : 0.900 : Weight on volume of distribution

// DEFAULT COVARIATE VALUES
  CRCL: 120 : 120mL/min
  WT : 70 : 70kg
  CVVH  : 0 : No CVVH

// DEFAULT ETA VALUES
  ETA1  : 0 : PopMean CLR
  ETA2  : 0 : PopMean CLC
  ETA3  : 0 : PopMean V

//POPULATION PARAMETER VARIABILITY
// variance covariance
$OMEGA @annotated @block
PPVCLR : 0.157 : PPV renal clearance
PPVV : 0.046  0.109 : PPV volume

$OMEGA @annotated
PPVCLC : 0.015 : PPV CRRT

//RESIDUAL UNEXPLAINED VARIABILITY
$SIGMA @annotated
ERRPROP : 0.002 : prop error
ERRADD : 5.083 : additive error

//INDIVIDUAL PHARMACOKINETIC PARAMETERS
$MAIN
  R_CENT = 200;   // infusion rate, 200mg/hr
  
  double CL = POPCLR*pow(CRCL/120,CLREN)*exp(ETA1);
    if(CVVH == 1) 
         CL = POPCLC*exp(ETA2);
  double V  = POPV*pow(WT/70,VWT)*exp(ETA3);

//DIFFERENETIAL EQUATIONS
$ODE
  double C1 = CENT/V;
  
  dxdt_CENT = -CL*C1;
  dxdt_AUC1 =  C1 * 0.88;
  dxdt_AUC2 =  0;
    if(SOLVERTIME > 24) 
      dxdt_AUC2 = C1 * 0.88;
  dxdt_AUC3 =  0;
    if(SOLVERTIME > 48) 
      dxdt_AUC3 = C1 * 0.88;
  dxdt_AUC4 =  0;
    if(SOLVERTIME > 72) 
      dxdt_AUC4 = C1 * 0.88;
  dxdt_AUC5 =  0;
    if(SOLVERTIME > 96) 
      dxdt_AUC5 = C1 * 0.88;
  dxdt_AUC6 =  0;
    if(SOLVERTIME > 120) 
      dxdt_AUC6 = C1 * 0.88;
  dxdt_AUC7 =  0;
    if(SOLVERTIME > 144) 
      dxdt_AUC7 = C1 * 0.88;
  dxdt_AUC8 =  0;
    if(SOLVERTIME > 168) 
      dxdt_AUC8 = C1 * 0.88;
  dxdt_AUC9 =  0;
    if(SOLVERTIME > 192) 
      dxdt_AUC9 = C1 * 0.88;
  dxdt_AUC10 =  0;
    if(SOLVERTIME > 216) 
      dxdt_AUC10 = C1 * 0.88;
  dxdt_AUC11 =  0;
    if(SOLVERTIME > 240) 
      dxdt_AUC11 = C1 * 0.88;
  dxdt_AUC12 =  0;
    if(SOLVERTIME > 264) 
      dxdt_AUC12 = C1 * 0.88;
  dxdt_AUC13 =  0;
    if(SOLVERTIME > 288) 
      dxdt_AUC13 = C1 * 0.88;
  dxdt_AUC14 =  0;
    if(SOLVERTIME > 312) 
      dxdt_AUC14 = C1 * 0.88;

//DETERMINES VALUES AND INCLUDES IN OUTPUT
$TABLE		
  double IPRE = C1;
  double DV   = double (IPRE)*(1+ERRPROP)+ERRADD;

$CAPTURE	
  IPRE DV CL V PPVCLR PPVCLC PPVV ETA1 ETA2 ETA3 WT CRCL CVVH

'

# ------------------------------------------------------------------------------
# Compile the model code
mod <- mcode("PopPKModel",code)

# simulate and compare
# ------------------------------------------------------------------------------
input1 <- read.csv("input1.csv")
# Simulate initial dosing regimen
set.seed(1234)
test.1 <- mrgsim(mod,input1)
test.1 <- as.data.frame(test.1)

compare.1 <- test.1[test.1$time==48,] %>% select(ID, time, IPRE, DV, CL,V)

# ------------------------------------------------------------------------------
input2 <- read.csv("input2.csv")
# Simulate best TDM dosing regimen
set.seed(1234)
test.2 <- mrgsim(mod,input2)
test.2 <- as.data.frame(test.2)
compare.2 <- test.2[test.2$time==48,] %>% select(ID, time, IPRE, DV, CL,V)

identical(compare.1, compare.2)

**Comment by kylebaron** [comment]
Hi @indysandaradura - 

You won't get reproducible residual errors unless you have the same inputs (individuals and observations). 

You don't have this here

```r
> count(input1,evid)
# A tibble: 2 x 2
   evid     n
  <int> <int>
1     0 96000
2     1  2000
> count(input2,evid)
# A tibble: 1 x 2
   evid     n
  <int> <int>
1     1 15000
```



Kyle

**Comment by indysandaradura** [comment]
Thanks for pointing me towards my obvious error. Having fixed this, many but not all my repeated simulations are identical. There are still some notable differences in both IPRE and DV

matching files:
[input_pops.zip](https://github.com/metrumresearchgroup/mrgsolve/files/4125974/input_pops.zip)

library(arsenal)
summary(comparedf(compare.1,compare.2))


Table: Summary of data.frames

version   arg          ncol   nrow
--------  ----------  -----  -----
x         compare.1       6   1000
y         compare.2       6   1000



Table: Summary of overall comparison

statistic                                                      value
------------------------------------------------------------  ------
Number of by-variables                                             0
Number of non-by variables in common                               6
Number of variables compared                                       6
Number of variables in x but not y                                 0
Number of variables in y but not x                                 0
Number of variables compared with some values unequal              2
Number of variables compared with all values equal                 4
Number of observations in common                                1000
Number of observations in x but not y                              0
Number of observations in y but not x                              0
Number of observations with some compared variables unequal       44
Number of observations with all compared variables equal         956
Number of values unequal                                          88

Table: Differences detected by variable

var.x   var.y     n   NAs
------  ------  ---  ----
ID      ID        0     0
time    time      0     0
IPRE    IPRE     44     0
DV      DV       44     0
CL      CL        0     0
V       V         0     0



Table: Differences detected (68 not shown)

var.x   var.y    ..row.names..  values.x           values.y            row.x   row.y
------  ------  --------------  -----------------  -----------------  ------  ------
IPRE    IPRE                36  17.4773274382683   21.5061227039711       36      36
IPRE    IPRE                46  13.455892599628    16.6477386598992       46      46
IPRE    IPRE                77  18.2819328106987   22.6644678031408       77      77
IPRE    IPRE               138  14.3425599380228   18.1792344694307      138     138
IPRE    IPRE               157  20.0094944251933   26.098109762241       157     157
IPRE    IPRE               177  19.0885738623115   23.6478894860291      177     177
IPRE    IPRE               199  16.7844688261339   20.8952660590932      199     199
IPRE    IPRE               244  20.9554186327228   26.2904623507202      244     244
IPRE    IPRE               250  12.5470754167575   15.9514078988771      250     250
IPRE    IPRE               313  12.3133421698901   15.1125836795593      313     313
DV      DV                  36  18.1141462220003   22.2353766235412       36      36
DV      DV                  46  11.5629457600768   14.7801798259492       46      46
DV      DV                  77  20.6314936143749   25.0787148628359       77      77
DV      DV                 138  16.8684804641946   20.5562498791708      138     138
DV      DV                 157  20.8392309129315   26.856428309003       157     157
DV      DV                 177  17.0364718595338   21.6635464051237      177     177
DV      DV                 199  14.3826509719812   18.1992688461338      199     199
DV      DV                 244  20.3386186992219   25.6214913763218      244     244
DV      DV                 250  13.7061386009012   16.9767673904915      250     250
DV      DV                 313  15.6556309681306   18.5242923501318      313     313



Table: Non-identical attributes

|                            |
|:---------------------------|
|No non-identical attributes |

**Comment by kylebaron** [comment]
Not matching.

```r
> count(input1,evid)
# A tibble: 2 x 2
   evid      n
  <int>  <int>
1     0 108000
2     1   2000
> count(input2,evid)
# A tibble: 2 x 2
   evid     n
  <int> <int>
1     0 95000
2     1 15000
```

**Comment by indysandaradura** [comment]
Hi Kyle,
Close, but still not 100%. The simulated 1st 48h is now identical with the exception of time == 0, where I am getting different IPRE and DV values for each patient. Am I missing something?

inputs:
[input_pops.zip](https://github.com/metrumresearchgroup/mrgsolve/files/4143690/input_pops.zip)

# ------------------------------------------------------------------------------
input1 <- read.csv("input1.csv")
#input.1 <- input1[input1$time<=48,]
# Simulate initial dosing regimen
set.seed(1234)
test.1 <- mrgsim(mod,input1)
test.1 <- as.data.frame(test.1)
head(test.1)
compare.1 <- test.1[test.1$time<=48,] %>% select(ID, time, IPRE, DV, CL,V)

# ------------------------------------------------------------------------------
input2 <- read.csv("input2.csv")
#input.2 <- input2[input2$time<=48,]
# Simulate 2nd dosing regimen
set.seed(1234)
test.2 <- mrgsim(mod,input2)
test.2 <- as.data.frame(test.2)
head(test.2)
compare.2 <- test.2[test.2$time<=48,] %>% select(ID, time, IPRE, DV, CL,V)

> count (input1,evid)
# A tibble: 2 x 2
   evid     n
  <int> <int>
1     0 95000
2     1 15000

> count (input2,evid)
# A tibble: 2 x 2
   evid     n
  <int> <int>
1     0 95000
2     1 15000

> identical(compare.1,compare.2)
[1] FALSE

> summary(comparedf(compare.1,compare.2))

Table: Summary of data.frames

version   arg          ncol    nrow
--------  ----------  -----  ------
x         compare.1       6   98000
y         compare.2       6   98000



Table: Summary of overall comparison

statistic                                                      value
------------------------------------------------------------  ------
Number of by-variables                                             0
Number of non-by variables in common                               6
Number of variables compared                                       6
Number of variables in x but not y                                 0
Number of variables in y but not x                                 0
Number of variables compared with some values unequal              2
Number of variables compared with all values equal                 4
Number of observations in common                               98000
Number of observations in x but not y                              0
Number of observations in y but not x                              0
Number of observations with some compared variables unequal      898
Number of observations with all compared variables equal       97102
Number of values unequal                                        1796



Table: Variables not shared

|                        |
|:-----------------------|
|No variables not shared |



Table: Other variables not compared

|                                |
|:-------------------------------|
|No other variables not compared |



Table: Observations not shared

|                           |
|:--------------------------|
|No observations not shared |



Table: Differences detected by variable

var.x   var.y      n   NAs
------  ------  ----  ----
ID      ID         0     0
time    time       0     0
IPRE    IPRE     898     0
DV      DV       898     0
CL      CL         0     0
V       V          0     0



Table: Differences detected (1776 not shown)

var.x   var.y    ..row.names..  values.x           values.y            row.x   row.y
------  ------  --------------  -----------------  -----------------  ------  ------
IPRE    IPRE                 1  15.7006708285147   29.8342196845424        1       1
IPRE    IPRE                99  14.257487480935    11.8291648829214       99      99
IPRE    IPRE               197  17.7954911654567   14.0127105033936      197     197
IPRE    IPRE               295  11.6841149628886   13.0794898581059      295     295
IPRE    IPRE               393  21.7079763830051   13.1897388729925      393     393
IPRE    IPRE               491  62.7904501739937   23.8352094532013      491     491
IPRE    IPRE               589  13.7405556665887   10.8711514668069      589     589
IPRE    IPRE               687  32.4073874099473   22.50475371149        687     687
IPRE    IPRE               785  26.4498748045577   13.7860102584098      785     785
IPRE    IPRE               883  61.2971603462917   14.1587046946117      883     883
DV      DV                   1  15.9684698624962   29.9942039392034        1       1
DV      DV                  99  11.379271996496    8.90748661371246       99      99
DV      DV                 197  19.0426786031992   15.2361180371607      197     197
DV      DV                 295  14.0311795511676   15.3943341908142      295     295
DV      DV                 393  22.4888845465123   13.9328566699083      393     393
DV      DV                 491  58.4802313016782   20.6943980159444      491     491
DV      DV                 589  14.4190536752578   11.5696440372147      589     589
DV      DV                 687  31.10680957766     21.1754807149415      687     687
DV      DV                 785  23.50476087703     10.5416114518547      785     785
DV      DV                 883  65.9083942526935   16.8419912604815      883     883



Table: Non-identical attributes

**Comment by kylebaron** [comment]
You have to **calculate** `IPRE` in $TABLE

```
$TABLE		
  double IPRE = CENT/V;
  double DV   = double (IPRE)*(1+ERRPROP)+ERRADD;

```

**Comment by indysandaradura** [comment]
Hi Kyle, I do this in the model file (see below). However, despite defining the individual PK parameters for each individual and setting the seed to ensure consistent RUV is applied, I am not getting consistent simulation results each time this is run. The issue with lack of reproducibility only seems to be occurring at time==0.

code <- '

//INITIAL CONDITIONS
$INIT
CENT = 0, AUC1 = 0, AUC2 = 0, AUC3 = 0, AUC4 = 0, AUC5 = 0, AUC6 = 0, AUC7 = 0, AUC8 = 0, AUC9 = 0, AUC10 = 0, AUC11 = 0, AUC12 = 0, AUC13 = 0, AUC14 = 0

//POPULATION PHARMACOKINETIC PARAMETERS
$PARAM @annotated
POPCLR : 0.705 : Systemic clearance
POPCLC : 1.914 : CVVH clearance
POPV : 46.337 : Volume of distribution

// COVARIATE EFFECTS
CLREN : 0.635 : Renal function on systemic clearance
VWT : 0.900 : Weight on volume of distribution

// DEFAULT COVARIATE VALUES
CRCL: 120 : 120mL/min
WT : 70 : 70kg
CVVH : 0 : No CVVH

// DEFAULT ETA VALUES
ETA1 : 0 : PopMean CLR
ETA2 : 0 : PopMean CLC
ETA3 : 0 : PopMean V

//POPULATION PARAMETER VARIABILITY
// variance covariance
$OMEGA @annotated @block
PPVCLR : 0.157 : PPV renal clearance
PPVV : 0.046 0.109 : PPV volume

$OMEGA @annotated
PPVCLC : 0.015 : PPV CRRT

//RESIDUAL UNEXPLAINED VARIABILITY
$SIGMA @annotated
ERRPROP : 0.002 : prop error
ERRADD : 5.083 : additive error

//INDIVIDUAL PHARMACOKINETIC PARAMETERS
$MAIN
R_CENT = 200; // infusion rate, 200mg/hr

double CL = POPCLRpow(CRCL/120,CLREN)exp(ETA1);
if(CVVH == 1)
CL = POPCLCexp(ETA2);
double V = POPVpow(WT/70,VWT)*exp(ETA3);

//DIFFERENETIAL EQUATIONS
$ODE
double C1 = CENT/V;

dxdt_CENT = -CL*C1;
dxdt_AUC1 = C1 * 0.88;
dxdt_AUC2 = 0;
if(SOLVERTIME > 24)
dxdt_AUC2 = C1 * 0.88;
dxdt_AUC3 = 0;
if(SOLVERTIME > 48)
dxdt_AUC3 = C1 * 0.88;
dxdt_AUC4 = 0;
if(SOLVERTIME > 72)
dxdt_AUC4 = C1 * 0.88;
dxdt_AUC5 = 0;
if(SOLVERTIME > 96)
dxdt_AUC5 = C1 * 0.88;
dxdt_AUC6 = 0;
if(SOLVERTIME > 120)
dxdt_AUC6 = C1 * 0.88;
dxdt_AUC7 = 0;
if(SOLVERTIME > 144)
dxdt_AUC7 = C1 * 0.88;
dxdt_AUC8 = 0;
if(SOLVERTIME > 168)
dxdt_AUC8 = C1 * 0.88;
dxdt_AUC9 = 0;
if(SOLVERTIME > 192)
dxdt_AUC9 = C1 * 0.88;
dxdt_AUC10 = 0;
if(SOLVERTIME > 216)
dxdt_AUC10 = C1 * 0.88;
dxdt_AUC11 = 0;
if(SOLVERTIME > 240)
dxdt_AUC11 = C1 * 0.88;
dxdt_AUC12 = 0;
if(SOLVERTIME > 264)
dxdt_AUC12 = C1 * 0.88;
dxdt_AUC13 = 0;
if(SOLVERTIME > 288)
dxdt_AUC13 = C1 * 0.88;
dxdt_AUC14 = 0;
if(SOLVERTIME > 312)
dxdt_AUC14 = C1 * 0.88;

//DETERMINES VALUES AND INCLUDES IN OUTPUT
$TABLE
double IPRE = C1;
double DV = double (IPRE)*(1+ERRPROP)+ERRADD;

$CAPTURE
IPRE DV CL V PPVCLR PPVCLC PPVV ETA1 ETA2 ETA3 WT CRCL CVVH

'

mod <- mcode("PopPKModel",code)

**Comment by kylebaron** [comment]
@indysandaradura Please use the code I provided above.

**Comment by indysandaradura** [comment]
Thanks @kylebaron! Can you please explain to me why with the model code as I'd specified in $ODE + $TABLE didn't work at time==0, so that I can better understand my mistake?

**Comment by kylebaron** [comment]
NONMEM makes you recalculate the values in $ERROR. We've put in an extra call to ODE for you so you don't have to do that.  It got left out when we switched from the FORTRAN to C++ implementation.  You won't have to do it in the next version.

See this issue:
https://github.com/metrumresearchgroup/mrgsolve/issues/613

**Comment by kylebaron** [comment]
I think the code should work as expected.  Please use 0.10.1.
