### ISSUE TITLE
System Dependent Build Failure

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#638]
Hi @kylebaron,

I'm working with someone who wants to replicate my work on their systems.  A model that compiles for me without error was giving them problems.  The problem stemmed from the fact that they were using a 32-bit R version with a 64-bit Rtools in Windows.  Is there a way to check for compatible number of bits in R and Rtools and provide a clearer error to the user when compilation fails?

If it's difficult to check, perhaps the error given when a build fails on windows could have something like "Perhaps verify that the version of R and Rtools you are running match for R version and 32- vs 64-bits."

**Comment by kylebaron** [comment]
Hi @billdenney - 

Thanks for the report.

Sounds like a tricky situation.  I don't think it would be feasible to to actually get involved in diagnosing 32-bit R with 64-bit Rtools.  But what we can do is start a man page and point people to that when the build doesn't work.  Could start listing different possibilities there and also suggest some diagnostics with pkgbuild.  Good suggestion will roll this out in the next version (after 0.10.2).

Kyle

**Comment by kylebaron** [comment]
Maybe later.
