### ISSUE TITLE
How to simulate inter-study variabitly 

### ISSUE THREAD

**Issue by aalhadab** [metrumresearchgroup/mrgsolve#642]
I wonder if we can simulate inter-study variability effect in mrgsolve that only changes when study ID changes. So for subjects within a study, they will have same ISV while they have their own IIV. 

I would appreciate an example. 

Thanks 
Ali

**Comment by kylebaron** [comment]
Hi Ali - 

As we discussed in email, there isn't functionality baked into mrgsolve to do this.  But a couple of approaches you can do. 

Do you have any preference for accomplishing this through input data (easier to understand the code and probably easier to maintain, but obviously requires you to run a data step prior to simulating. 

Also can do this within the model; nice because you don't have to fiddle with the data, but more to maintain inside the model. 

Any preference here?  I would personally rather do the data option but not sure about your context.

KTB

**Comment by aalhadab** [comment]
Either will be fine. We can do the data option.

**Comment by kylebaron** [comment]
I did this sort of thing with a model where we had truncated random effect distributions.  I wrote a set of functions to attach random effects on to the data set.  

I wrote a package called dmutate a while ago, where it will simulate random variables at different "levels" of your data.  I was envisioning exactly this sort of scenario and intended to plug it in more to mrgsolve.  But It might work just as well alongside mrgsolve (just getting the data ready to pass off to mrgsim). 

So if you do this and then add "STUDYEF" as a parameter to the model, you can use it as a STUDY-level random effect.  

You can do it any other way too if that's easier; the dmutate stuff is just convenience to get the column on there at the right level.  ALso, there is a pretty decent NSE mechanism in there, so you can write the expression and evaluate it later or in a different environment.  I did a little bit of that here; maybe you want to do more or less of that or just not use dmutate to begin with.

Also, you **could** put the individual random effects on the data too, but if they  don't need any special processing, might as well handle them in the model as usual.  

Let me know if this is what you were looking for. 

kyle


``` r

library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(tidyverse)
library(dmutate)

data <- expand.ev(STUDY = c(100,300,500), ID = 1:3,AMT = 5) %>% 
  expand_observations(times=c(24,72,96))

omega_ISV <- 1

set.seed(12345)

data <- mutate_random(data, STUDYEF ~ rnorm(0, omega_ISV)|STUDY)

head(data, n = 11)
#>    ID time amt cmt evid STUDY AMT    STUDYEF
#> 1   1    0   0   1    1   100   5  0.5855288
#> 2   1   24   0   0    0   100   0  0.5855288
#> 3   1   72   0   0    0   100   0  0.5855288
#> 4   1   96   0   0    0   100   0  0.5855288
#> 5   2    0   0   1    1   300   5  0.7094660
#> 6   2   24   0   0    0   300   0  0.7094660
#> 7   2   72   0   0    0   300   0  0.7094660
#> 8   2   96   0   0    0   300   0  0.7094660
#> 9   3    0   0   1    1   500   5 -0.1093033
#> 10  3   24   0   0    0   500   0 -0.1093033
#> 11  3   72   0   0    0   500   0 -0.1093033

distinct(data,ID,STUDYEF) %>% arrange(STUDYEF)
#>   ID    STUDYEF
#> 1  3 -0.1093033
#> 2  6 -0.1093033
#> 3  9 -0.1093033
#> 4  1  0.5855288
#> 5  4  0.5855288
#> 6  7  0.5855288
#> 7  2  0.7094660
#> 8  5  0.7094660
#> 9  8  0.7094660
```

<sup>Created on 2020-02-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kylebaron** [comment]
@aalhadab did this work?  If not, what did you decide to do?
