### ISSUE TITLE
How to do something like NONMEM NSUBPROBLEMS = 500?

### ISSUE THREAD

**Issue by UNCcrawler** [metrumresearchgroup/mrgsolve#643]
Hi, I am new to mrgsolve and would like to explore more. Could you please advise on how to do trial simulation like in NONMEM $SIM NSUBPROBLEM = 500? I typically do this to calculate the 95% prediction interval of the prediction. I am wandering if there is an established function in mrgsolve?

**Comment by kylebaron** [comment]
``` r

library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(tidyverse)
theme_set(theme_bw())
```

Get your data

``` r
data(extran3)
data <- select(extran3, -CL, -VC, -KA)

head(data)
#>   ID time cmt evid  amt addl ii rate
#> 1  1    0   1    1 1000    3 24    0
#> 2  1    0   0    0    0    0  0    0
#> 3  1    1   0    0    0    0  0    0
#> 4  1    2   0    0    0    0  0    0
#> 5  1    3   0    0    0    0  0    0
#> 6  1    4   0    0    0    0  0    0
```

Load the model

``` r
mod <- modlib("popex")
#> Building popex ... done.
```

# Simulate sequential

  - 30 replicates
  - Set up a small function to execute one simulation `subproblem`



``` r
subproblem <- function(i) {
  mrgsim_df(mod, data) %>% mutate(irep = i) 
}
```

simulate

``` r
set.seed(101)
sims <- map_df(seq(30), subproblem)
```

plot

``` r
ggplot(sims) + 
  geom_line(aes(time,DV,group=irep)) + 
  facet_wrap(~ID)
```

![](https://i.imgur.com/17noEbh.png)

# Simulate parallel

  - Now, do this in parallel
  - We use `furrr` backed by the `future` package
  - We select `multiprocess` plan; this will use forked processes when on
    unix-alike



``` r
library(furrr)
#> Loading required package: future
options(future.fork.enable = TRUE)
plan(multiprocess)

set.seed(303)
simsp <- future_map_dfr(seq(30),subproblem,.options=future_options(seed=TRUE))
```

Plot

``` r
ggplot(simsp) + 
  geom_line(aes(time,DV,group=irep)) + 
  facet_wrap(~ID)
```

![](https://i.imgur.com/maEFpUG.png)

<sup>Created on 2020-03-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by UNCcrawler** [comment]
Thank you so much for the detailed example!

**Comment by kylebaron** [comment]
No problem.  Please re-open with further questions, if something isn't working the way you expect, or you're looking for implementation advice.  Happy to comment / help.
