### ISSUE TITLE
ss=1 flag does not pick up time-dependent values from $MAIN

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#65]
I'm still not sure that `ss=1` record should acknowledge variables set in `$MAIN` that are a function of `TIME`.  A simple workaround would be to call `$MAIN` with the times of the doses when implementing the `ss` algorithm.  But not sure that's what we want to do.  Seems like this should be handled by some `MTIME` system (see context below); `mrgsolve` has a very simplistic `mtime` feature that just forces records into the simulation sequence at specific, user-defined times to make sure the system actually advances to that time and makes a hard stop.  

Context: EHC model where gallbladder emptying times are determined based on time of day from a calculation in `$MAIN`.  A NONMEM model using `MTIME` inside `$ODE` should / would? properly implement the emptyings while the system advances.

**Comment by vjd** [comment]
@kylebmetrum I can confirm that the `ss=1` is not working with a `TIME` component. I was working on a time varying clearance model and wanted to get the steady-state metrics and realized that it does not give me what I want. I can send out a reproducible code later today

**Comment by kylebmetrum** [comment]
@vjd Thanks for the report.  If you can share a simple example for future use that would be great.  We know that when the system advances in response to the `ss` flag, it __only__ involves calls to `$ODE` (or the PK polyexponential functions if using `$PKMODEL`).  So we don't expect variables that have a `TIME` dependence to be properly incorporated into that.  

The question I'm trying to work through is *should* that be the case? Is this a bug or expected behavior?  I'm not really sure.  During the `ss` procedure, we advance the system in `TIME` intervals equal to `ii`.   We could always include a call to `$MAIN` in there once we go to the next `TIME` to capture any `TIME` dependence, but I'm thinking that isn't necessarily the right thing to do ... it could make matters worse and more confusing and the behavior won't ever be what we'd really need it to be, which is `SOLVERTIME` dependence not `TIME` dependence.

`mrgsolve` also has a pseudo-mtime-type feature: basically, you can insert phantom observation records into the simulation where you can be assured that the simulation will happen at a specific time ... and that time doesn't need to be known prior to the simulation.  We don't have `MPAST(n)` available but I don't think it would be too hard to hack around that.    This seems like the better direction to go but I still haven't wrapped my head around it enough to know if or how it would actually work. 

We also came across this http://www.page-meeting.org/?abstract=2912  I'm not sure what was wrong with the simulation involving `MTIME` + `SS` in NONMEM, but it seems like even if we emulated NONMEM perfectly in `MTIME` and `SS`, it still wouldn't be correct for getting the `TIME` dependence correct.

**Comment by vjd** [comment]
@kylebmetrum Here is a reproducible example. Hopefully, the code is correct !

# SS=1 when TIME used in $MAIN

```r
library(mrgsolve)
library(dplyr)
```

# Model Specification

A simple one compartment model with a time varying clearance component. Notice the use of `TIME` in the definition for `CLt`.


```r
test <- '

$PARAM TVCL=0.005, TVVC=3, TVEMAX=-0.2, TVT50=500, WT=70

$CMT CENT AUC

$OMEGA
prefix="E", labels = s(CL,VC,EMAX, T50)
0 0 0 0

$MAIN
double EMAX = TVEMAX+EEMAX;
double T50 = TVT50+ET50;
double CLt = exp(EMAX*TIME/(T50+TIME));

double CLi = TVCL*CLt*exp(ECL);
double VCi = TVVC*exp(EVC);


double cl =  CLi;


$ODE
dxdt_CENT = -(CLi/VCi)*CENT;
dxdt_AUC = CENT/VCi;

$TABLE
table(CP) = CENT/VCi;
table(cAUC) = AUC;
table(cl) = cl;
'
```


```r
mod <- mread(code=test, model="ss")
```

# Regimen
A bi-weekly IV bolus regimen given over a year


```r
reg1 <- ev(amt=c(3), cmt=1, addl=25,ii=336) %>% as.data.frame %>% as.tbl %>% 
  mutate(ID=1, WT=c(rep(80,1)), dose = amt*WT,amt=dose)
```

## Simulated Regimen

```r
mod %>% data_set(reg1) %>% Req(CP) %>% carry.out(dose) %>% 
  obsonly %>% 
  mrgsim(end=9000, delta=2) %>% plot
```

![image](https://cloud.githubusercontent.com/assets/1425562/16509825/c860e5b6-3f0e-11e6-8a49-4b846cb2b213.png)


# Simulation without SS=1

The following metrics were evaluated

* cmin1 (pre-dose before the 2nd dose)  
* cavg1 (avergage concentration over first dosing interval) 
* cminss (pre-dose concentration in the 42nd week, assuming stead state is acheived)
* cavgss (average concentration at steady state, computed using the cumulative AUC between the 40th and 42nd week)


```r
out_nss <- mod %>% data_set(reg1) %>% Req(CP,cl,cAUC) %>% carry.out(dose) %>% 
  obsonly %>% 
  mrgsim(end=9000, delta=2) %>% as.data.frame %>% as.tbl %>% 
  mutate(cAUC7056 = cAUC[time==7056],
         cAUC6720 = cAUC[time==6720],
         cavg1 = (cAUC[time==336])/336,
         cavgss = (cAUC7056-cAUC6720)/336,
         cmin1 = CP[time==336],
         cminss = CP[time==7056]) %>% 
  filter(time%in%c(0,336,7056)) %>% select(-starts_with("cAUC")) %>% 
  mutate_each(funs(round(.,2)),-cl) 
out_nss %>% knitr::kable()
```

![image](https://cloud.githubusercontent.com/assets/1425562/16509851/09c96ec4-3f0f-11e6-8bfe-8b716ae879ac.png)


# Simulation with SS=1

When we use the same model with `ss=1` in the `mrgsim` function, we expect the system to start at steady state. This means, that the metrics of `cmin1` and `cavg1` in this case should technically represent the `cminss` and `cavgss` from the previous table. However, you can see below that they do not. 


```r
out_ss <- mod %>% data_set(reg1) %>% Req(CP,cl,cAUC) %>% carry.out(dose) %>% 
  obsonly %>% 
  mrgsim(end=9000, delta=2,ss=1) %>% as.data.frame %>% as.tbl %>% 
  mutate(cavg1 = (cAUC[time==336])/336, # this should tecnically be the SS value
         cmin1 = CP[time==336]) %>%# this should tecnically be the SS value
  filter(time%in%c(0,336)) %>% select(-starts_with("cAUC")) %>% 
  mutate_each(funs(round(.,2)),-cl)
out_ss %>% knitr::kable()
```

![image](https://cloud.githubusercontent.com/assets/1425562/16509859/1897a9c0-3f0f-11e6-8960-d5d452c0a9bd.png)

**Comment by kylebmetrum** [comment]
- Put `ss=1` into the data set, not as an argument to `mrgsim`
- Also, using `TIME` to advance `CL` in `$MAIN` absolutely won't work; but, in this case, using `SOLVERTIME` inside of `$ODE` comes close
- I think it only comes close to working because `CL` is a function of `SOLVERTIME` and it gets smaller (I think) when `mrgsolve` is finding `ss` (`SOLVERTIME` is getting bigger); but when it goes on to advance from `ss`, `CL` is still a function of `SOLVERTIME` so it goes back to where it started when it should be `TVCL*exp(EMAX)` (???)
- It seems like there should be a way to trick this into working the way you want; I might be able to see what it is after some sleep


```r
library(mrgsolve)
library(dplyr)

test <- '

$PARAM TVCL=0.005, TVVC=3, TVEMAX=-0.2, TVT50=500, WT=70

$CMT CENT AUC

$OMEGA
prefix="E", labels = s(CL,VC,EMAX, T50)
0 0 0 0

$MAIN
double EMAX = TVEMAX+EEMAX;
double T50 = TVT50+ET50;


double ETACL = ECL;

double VCi = TVVC*exp(EVC);
double cl =  CLi;


$ODE
double CLt = exp(EMAX*SOLVERTIME/(T50+SOLVERTIME));
double CLi = TVCL*CLt*exp(ETACL);

dxdt_CENT = -(CLi/VCi)*CENT;
dxdt_AUC = CENT/VCi;

$TABLE
table(CP) = CENT/VCi;
table(cAUC) = AUC;
table(cl) = cl;
table(CLi) = CLi;
'

mod <- mread(code=test, model="ss")
reg1 <- ev(amt=c(3), cmt=1, addl=25,ii=336) %>% as.data.frame %>% as.tbl %>% 
  mutate(ID=1, WT=c(rep(80,1)), dose = amt*
           WT,amt=dose)

mod %>% data_set(reg1) %>% Req(CP) %>% carry.out(dose) %>% 
  obsonly %>% 
  mrgsim(end=9000, delta=2) %>% plot


out_nss <- 
  mod %>% 
  data_set(reg1) %>% 
  Req(CP,cl,CLi,cAUC) %>% carry.out(dose) %>% 
  obsonly %>% 
  mrgsim(end=9000, delta=2)

plot(out_nss)

out_nss %>% 
  as.data.frame %>% as.tbl %>% 
  mutate(cAUC7056 = cAUC[time==7056],
         cAUC6720 = cAUC[time==6720],
         cavg1 = (cAUC[time==336])/336,
         cavgss = (cAUC7056-cAUC6720)/336,
         cmin1 = CP[time==336],
         cminss = CP[time==7056]) %>% 
  filter(time%in%c(0,336,7056)) %>% select(-starts_with("cAUC")) %>% 
  mutate_each(funs(round(.,2)),-cl) %>% knitr::kable()


reg2 <- mutate(reg1, ss=1)
out_ss <- mod %>% data_set(reg2) %>% 
  Req(CP,cl,CLi,cAUC) %>% carry.out(dose) %>% 
  obsonly %>% 
  mrgsim(end=9000, delta=2, add=0.00001) 

plot(out_ss)


out_ss %>% 
  as.data.frame %>% as.tbl %>% 
  mutate(cavg1 = (cAUC[time==336]-cAUC[time==0.00001])/336, # this should tecnically be the SS value
         cmin1 = CP[time==336]) %>%# this should tecnically be the SS value
  filter(time%in%c(0,336)) %>% select(-starts_with("cAUC")) %>% 
  mutate_each(funs(round(.,2)),-cl) %>% knitr::kable()
```

**Comment by vjd** [comment]
Thank you, Kyle. Using `SOLVERTIME` definitely helped to get closer, but I preferred putting in a lot of doses to get to `SS` at this point. As to one of your comment on the using `ss=1` in the dataset as opposed to in the `mrgsim` function - is there something to do specifically regarding the way simulation datasets are read in before the `mrgsim` function is called?

The other aspect I am testing is the following - if I am using a time varying clearance equation along with the `ss=1` then would my baseline clearance be misrepresented to be my steady state clearance? I think that is where the problem lies too, don't you think?

Lastly, the `TVCL*exp(EMAX)` was mainly to avoid negative clearances as the `CL` is decreasing with time.

**Comment by kylebmetrum** [comment]
I agree ... the `ss` flag just isn't set up to handle something like this.  If I were doing this I would also just dose until you think you're at steady state and go from there.  It's the safest and easiest thing to do at this point.  If you really wanted to do this, I would make `CL` a compartment in the model, initialize it at the starting value, and try to find a way to get it decrease the way you want it to.  That's the only safe way to do it, IMO.  But it is clunky to do ...

For the `ss` flag: it is a flag that is specific to a dosing record.  So it doesn't do anything when the data set is brought into the problem.  But when `mrgsolve` is working through the records and it sees the `ss=1` on that particular record, it understands that the system needs to get to steady state when that record is actually executed.  

> The other aspect I am testing ...

Right ... it's hard to figure out what needs to happen.  But if you want the PK to advance to steady state on the first record, then the time varying clearance piece doesn't really matter ... it should start out at `CLmax` anyway.

**Comment by vjd** [comment]
>Right ... it's hard to figure out what needs to happen. But if you want the PK to advance to steady state on the first record, then the time varying clearance piece doesn't really matter ... it should start out at CLmax anyway.

True, but we would have to specify to begin at CLmax, or would the system recognize that TIME needs to be advanced to a SS value and hence bring CL to CLmax?

**Comment by kylebmetrum** [comment]
You'd have to start `CL` at `CLmax`.  The whole problem is that `ss` has no concept of `TIME` in `mrgsolve`  ... time only advances once you get to a new record in the data set;  the `ss` flag happens on a single record in the data set.  Things that need to change with time need to change with `SOLVERTIME` (like in NONMEM).  

It would be really nice to find a way to make `TIME`-varying parameters work with ODEs.  But it's really tricky and gets confusing fast.
