### ISSUE TITLE
AMT declardation inside cpp file

### ISSUE THREAD

**Issue by Mutaz94** [metrumresearchgroup/mrgsolve#664]
Hello @kylebaron; I'm trying to define the amount in the ODE system. I tried `#define self.amt AMT` and vice versa but keep shoot me an error. Any tips for that? Thanks

```
$ode 
 #define AMT self.amt  
dxdt_depot1 = AMT*f1 - tvka1*depot1;
dxdt_depot2 = AMT*(1-f1) - tvka2 *depot2;
dxdt_central = (tvka1*depot1 + tvka2*depot2) - (CL/V)*central; 
```

Thanks!

**Comment by kylebaron** [comment]
Hi @Mutaz94  - 

`AMT` is the dose amount on a dosing record.  If you want to use it, you'd have to do something like this: 

```r
$main 
if(AMT > 0) {
  // do something
}
```

But remember that `AMT` will be non-zero for a dosing record but will flip back to zero when you hit the next observation.  So I don't think the snippet you have will do what you want?

**Comment by Mutaz94** [comment]
Thanks for your comment, Kyle! What I'm trying to do to divide the dose into several compartments according to the assigned fraction. I know F_CMT could do that. However, I assumed implementing the `AMT` in the source code could be more efficient?

**Comment by kylebaron** [comment]
The entire dose will go into the compartment that you have on the dosing record.  If you want to split the dose across several compartments, you have to put one dosing record with the full dose for each of the compartments and then split with F.

**Comment by Mutaz94** [comment]
Yes. That what I did before in NONMEM to split the dose into fractions. I will keep the same strategy in mrgsolve. Thank you for your comments. I'm going to close the issue since its resolved.
