### ISSUE TITLE
Mass balance error with increasing model complexity

### ISSUE THREAD

**Issue by AMHGeorgetown** [metrumresearchgroup/mrgsolve#666]
I am developing a PBPK model that focuses on regional CNS distributions of drugs and as my system of ODEs increases in complexity, I run into mass balance errors. The error is about 1-2% but increases with time of simulation.  Ive tried adjust relative and absolute tolerances and nothing really changes. 
I have been building this model in a stepwise fashion and just ran into the issue as I started adding more dimensions to the CNS portion of the model.

**Comment by kylebaron** [comment]
Hi @AMHGeorgetown  - 

There is some error to solutions of ODE and it gets propagated.  You can get some advice for choosing tolerances from this wiki page I created from some of the documentation that is distributed with SUNDIALS:

https://github.com/metrumresearchgroup/mrgsolve/wiki/General-advice-on-choice-of-tolerances

We leave the tolerances up to you and the defaults are what you get for default when using ODEPACK DLSODA.  There isn't anything else going on under the hood.  That would alter mass balance beyond the tolerances of the solver and the equations that you write in $ODE.  

Be aware that it is possible that you'd see unphysiological values (like negative amounts) under certain conditions; this comes with the territory but you can do something to control it as noted here:
https://github.com/metrumresearchgroup/mrgsolve/wiki/Controlling-unphysical-negative-values
(again ... the content was taken from SUNDIALS documentation).
