### ISSUE TITLE
Unkown 'CMT' Column Error

### ISSUE THREAD

**Issue by vjd** [metrumresearchgroup/mrgsolve#67]
When I combine two data frames to use in `data_set()`, to simulate a mixed dosing regimen, I get an error `Error: Unknown column 'CMT'`.
However, when I run the two data frames before binding them together, each of the dataset works by itself. The last part of the code does not work. 

```
library(mrgsolve)
library(dplyr)

code <- '
$PARAM CL = 1.3, VC=28, KA=0.6

$SET delta=0.1

$CMT GUT CENT

$ODE
dxdt_GUT = -KA*GUT;
dxdt_CENT = KA*GUT - (CL/VC)*CENT;

$TABLE table(CP) = CENT/VC;
'

data_1 <- ev(ID=1,time=0,cmt=1,addl=7,amt=100,ii=24) %>% as.data.frame
data_2 <- data_1 %>% mutate(addl=4,time=192,amt=200,ii=48)
data <- bind_rows(data_1,data_2)

egmod <- mread(code=code, model="eg")

## these two work
egmod %>% data_set(data_1) %>% Req(CP) %>%  
  mrgsim(end=900, delta=0.1) 
egmod %>% data_set(data_2) %>% Req(CP) %>%  
  mrgsim(start=192,end=900, delta=0.1)

## this does not work
egmod %>% data_set(data) %>% Req(CP) %>%  
  mrgsim(end=900, delta=0.1) 
```

I am using `mrgsolve     * 0.6.1.9000 2016-05-15 Github (metrumresearchgroup/mrgsolve@94a5111)`

**Comment by kylebmetrum** [comment]
Thx;  I'm getting that now, too, out of the blue .... never used to see it.  But if you combine the data sets  and the coerce to `data.frame` (`bind_rows(data_1, data_2) %>% as.data.frame`) it should work.  AFAIK, you only get that error if you pass in a `tbl`.  

I'll get a permanent fix in later tonight.

**Comment by kylebmetrum** [comment]
@vjd What does your `sessionInfo()` look like?  It seems like this is only happening for me when I have a recent  `tidyr` release loaded.

**Comment by kylebmetrum** [comment]
Or maybe it is `tibble`?  I can't reproduce the error with oldish `tidyr` and `tibble`; `data_1`, `data_2`, and `data` all work without error.  But I started noticing this in my ubuntu environment when I had updated packages.  I'm updating on my macbook now ... I'm sure it will be reproducible then.

**Comment by kylebmetrum** [comment]
yep .... was able to reproduce with updated `tidyr` and no error when `tidyr` isn't loaded.  Committing a fix now ... just having `data_set` call `as.data.frame` on `data`, even for the method with `data.frame` signature.

**Comment by vjd** [comment]
I confirm, that if `tidyr` is NOT loaded, the simulation runs well. After running the simulation successfully, if then load the `library(tidyr)`, surprisingly the error does not show up. The error only shows when tidyr is loaded from the get go!
