### ISSUE TITLE
solvertime and self.tad() give unexpected results at steady-state dose

### ISSUE THREAD

**Issue by bergsmat** [metrumresearchgroup/mrgsolve#670]
Thanks for this very useful package!

When I write 
```
library(mrgsolve)
library(magrittr)

'[ PARAM   ] cl = 1.5, v = 8, ka = 0.2
 [ MAIN    ] double td = self.tad();
 [ CMT     ] gut cent
 [ ODE     ] double st = SOLVERTIME;
             dxdt_gut = -ka*gut;
             dxdt_cent = ka*gut - cl*cent/v;
 [ TABLE   ] double amount = self.amt;
 [ CAPTURE ] amount td st' %>% mcode('mod',.) %>%
  ev(ev(amt = 100, ss = 1, ii = 28, cmt = 1)) %>%
  mrgsim(tad = T)
```
I see 
```
Building mod ... done.
Model:  mod 
Dim:    26 x 8 
Time:   0 to 24 
ID:     1 
    ID time tad    gut   cent amount td  st
1:   1    0   0   0.00  0.000      0  0   0
2:   1    0   0 100.37  2.502    100  0 308
3:   1    1   1  82.18 18.613      0  0   1
4:   1    2   2  67.28 28.971      0  0   2
5:   1    3   3  55.08 35.104      0  0   3
6:   1    4   4  45.10 38.179      0  0   4
7:   1    5   5  36.92 39.083      0  0   5
8:   1    6   6  30.23 38.485      0  0   6
```
It seems like `SOLVERTIME`  at time of steady-state dose is eleven times the value of `ii` (for other tested values as well).  It also seems that `self.tad` doesn't notice the steady state dose (though `mrgsim(tad = T)` does).  

Apologies in advance if this is documented behavior and I missed it. (R 3.5.2, mrgsolve 0.9.0).

**Comment by kylebaron** [comment]
Hi Tim - 

Tabling out `SOLVERTIME` like that won't be helpful.  The system advances in time for a bunch of doses and who knows where that would end up.  I just wouldn't look at it so just no statement on what to expect there. 

There were some gremlins worked out with `self.tad` (see past issues somewhere).  This is what I'm getting with current version on CRAN:

``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(magrittr)

'[ PARAM   ] cl = 1.5, v = 8, ka = 0.2
 [ MAIN    ] double td = self.tad();
 [ CMT     ] gut cent
 [ ODE     ] double st = SOLVERTIME;
             dxdt_gut = -ka*gut;
             dxdt_cent = ka*gut - cl*cent/v;
 [ TABLE   ] double amount = self.amt;
 [ CAPTURE ] amount td ' %>% mcode('mod',.) %>%
  ev(ev(amt = 100, ss = 1, ii = 28, cmt = 1)) %>%
  mrgsim(tad = T)
#> Building mod ...
#> done.
#> Model:  mod 
#> Dim:    26 x 7 
#> Time:   0 to 24 
#> ID:     1 
#>     ID time tad    gut   cent amount td
#> 1:   1    0   0   0.00  0.000      0 -1
#> 2:   1    0   0 100.37  2.502    100  0
#> 3:   1    1   1  82.18 18.613      0  1
#> 4:   1    2   2  67.28 28.971      0  2
#> 5:   1    3   3  55.08 35.104      0  3
#> 6:   1    4   4  45.10 38.179      0  4
#> 7:   1    5   5  36.92 39.083      0  5
#> 8:   1    6   6  30.23 38.485      0  6
```

<sup>Created on 2020-04-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bergsmat** [comment]
Kyle,

Thanks for fast reply.  Indeed, I should have tried current CRAN version first.  I have a use case where $ODE needs TAD, but I can define that in $MAIN using self.tad() and the current behavior works.  

Thanks!

**Comment by kylebaron** [comment]
Thanks, Tim.  

Yes ... that's the way to go: get time after dose in $PK (main) and then derive ode time from that.  I believe that it's possible for the solver to back up a bit too to create a potentially negative time after dose; I think it would be really small and might make sense to prevent that from going negative (however it makes sense).

I have unit tests for that feature, but not a ton of real-world use.  Please let me know how it works or if anything else looks funny. 

Hope everything going well with you and your family. 

Kyle
