### ISSUE TITLE
Error when reading mrgsolve models

### ISSUE THREAD

**Issue by Kagedal** [metrumresearchgroup/mrgsolve#675]
Hi Kyle.
Just installed r (3.6.3) and R-studio on a new laptop. Also installed mrgsolve package and then ran this:
library(mrgsolve)
mod <- mread("irm1", modlib())

I get the following error:
> library(mrgsolve)
> mod <- mread("irm1", modlib())
Building irm1 ... error.

---:: stderr ::---------------------------------------------
Warning message:
In system(cmd) : 'make' not found
------------------------------------------------------------
Error: the model build step failed.

Somebody suggestied it had to to with rtools so I tried but got the following warning.
Warning in install.packages :
  package ‘rtools’ is not available (for R version 3.6.3)

Do you know what could be causing this? Best regards,
Matts

**Comment by kylebaron** [comment]
Hi @Kagedal - 
You still need to install the compiler package for Windows:
https://cran.r-project.org/bin/windows/Rtools/history.html

Get `Rtools35.exe`.  Be careful during installation to **opt in** when it asks if you want to set the `PATH` environment variable.

Kyle
