### ISSUE TITLE
How to implement time-dependent PK parameter

### ISSUE THREAD

**Issue by fklu** [metrumresearchgroup/mrgsolve#677]
Dear mrgsolve team,

I'm implementing a popPK model from the literature (originally developed in NONMEM) and would appreciate your help. In the model, a nonlinear elimination term (Michaels-Menten) is used, where in addition VMAX is decreasing over time. This can be realised in NONMEM via $PK/$DES calling time directly as "TIME"/"T", e.g.:
$DES
DADT(1) = ... *T ...
...

Can this time-dependency also be implemented using mrgsolve? I only found examples how time-varying covariates should be used or how a parameter is changed after x hours, but not how a parameter can be altered calling the elapsed time since first dose directly. 

Thanks for your help!

Franziska

**Comment by kylebaron** [comment]
Hi @fklu - 

In mrgsolve, it is `TIME` / `SOLVERTIME`.  So:

```
[ main ]  // $PK
// use TIME here

[ ode ]  // $DES
// use SOLVERTIME here

[ table ] // $ERROR
// use TIME here
```

There is **some** documentation for `TIME` and `SOLVERTIME` and other internal variables here in the userguide:
https://mrgsolve.github.io/user_guide/model-specification.html#time

It looks like `TIME` / `SOLVERTIME` could use an example.   I'll add that. 

Hope this helps.

Kyle

**Comment by fklu** [comment]
Hi @kylebaron,
thank you very much for your quick response, it worked very well! 
`$MAIN
...
double VMAX = VMAX1*(1-VMAXINH*((TIME-1)/((TIME-1)+(T50-1))));`

Franziska

**Comment by kylebaron** [comment]
Great.  I'm not sure what's going on in the rest of the model, but be sure to remember that VMAX will depend on the design of the input data.  I'm not sure how the paper does it, but if you have ODE, you might model this in ODE with SOLVERTIME just to be safe.  Let me know if I can help with anything else.

**Comment by fklu** [comment]
Indeed, implementation in $MAIN or $ODE makes a difference (same in NONMEM).

Defining the time-dependent parameter in $ODE (green) in contrast to $MAIN (red), was now used to successfully re-create the NONMEM output (black dashed line).

Thanks for the helpful comments!


![ModelComparison](https://user-images.githubusercontent.com/50670486/81164046-f9aa3c00-8f8f-11ea-84ae-26db9adf94b3.jpg)
