### ISSUE TITLE
Sobol Sensitivity Example

### ISSUE THREAD

**Issue by AMHGeorgetown** [metrumresearchgroup/mrgsolve#679]
Is there a good example of running a Sobol sensitivity analysis of an MRGsolve model? 

I see a bunch of packages that can help, but I am struggling to shoe horn it into one - the closest I have gotten is with the Sensobol package.

**Comment by riggsmm** [comment]
Kyle's put together some info on this for an open-course we gave at UF following ASCPT a few years back -- materials are posted here: 
 - https://github.com/mrgsolve/gallery/blob/master/application/sobol.md

Please let us know if this helps or if any additional information would be helpful!

**Comment by AMHGeorgetown** [comment]
Thank you - this is very helpful. Does the Sensitivity package allow for second and third order sensitivity?

**Comment by kylebaron** [comment]
Hi @AMHGeorgetown  - 
As far as I know, the methods in sensitivity will calculate total and first.
Kyle
