### ISSUE TITLE
gfortran 4.8 dependency failure with gfortran 5.x installed on OSX 

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/mrgsolve#7]
Error

![image](https://cloud.githubusercontent.com/assets/3196313/13461182/03e22502-e04e-11e5-9133-35b3123f4b01.png)

When checking gfortran version via:

```
gfortran -v
```

get result 

```
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/5.3.0/libexec/gcc/x86_64-apple-darwin15.0.0/5.3.0/lto-wrapper
Target: x86_64-apple-darwin15.0.0
Configured with: ../configure --build=x86_64-apple-darwin15.0.0 --prefix=/usr/local/Cellar/gcc/5.3.0 --libdir=/usr/local/Cellar/gcc/5.3.0/lib/gcc/5 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew gcc 5.3.0' --with-bugurl=https://github.com/Homebrew/homebrew/issues --enable-plugin --disable-nls --enable-multilib
Thread model: posix
gcc version 5.3.0 (Homebrew gcc 5.3.0)
```

Will update the issue accordingly once solution is found

**Comment by kylebmetrum** [comment]
Maybe F77 in a Makevars file: https://cran.r-project.org/doc/manuals/R-admin.html#Customizing-package-compilation

or 

I think I've seen Ripley say you could just symlink gfortran-4.8 to gfortran-5.whatever.

**Comment by kylebmetrum** [comment]
Devin - it would be great to get a workaround for this, but generally we're supporting / recommending  "the R way" .... using 4.8, which is the only one supported for "Mavericks distribution" (https://cran.r-project.org/doc/manuals/R-admin.html#OS-X) ... usually people with homebrew compilers are rebuffed pretty quickly on the R list (not saying it's right .... just the way it is).

**Comment by dpastoor** [comment]
Actually was a pretty easy fix based on the suggestion [here on the homebrew site](https://github.com/Homebrew/homebrew/issues/43290) to also have R installed via homebrew rather than installing it manually, which I had done previously. After doing so, everything compiled just fine.

steps:

remove old R manual install

```
rm /usr/bin/local/R && rm /usr/bin/local/Rscripts
brew reinstall r
```

**Comment by kylebmetrum** [comment]
So ... a complete Homebrew implementation is:

    brew install gcc
    brew install r

???

**Comment by dpastoor** [comment]
@kylebmetrum I'm fairly certain - I don't recall setting up anything else, however here is the result of my

```
brew list
```

The one thing that is nagging my memory a little bit is maybe having issues with tcl-tk, but I think that was because I 'stupidly' upgraded to el capitan on day 1 so I would not anticipate any other needs.


![image](https://cloud.githubusercontent.com/assets/3196313/13465543/2d7b0b16-e064-11e5-8e0a-926d0f8ad079.png)


Since it still simlinks to /usr/local/bin/R Rstudio will just pick right back up the fresh install without any changes

**Comment by kylebmetrum** [comment]
@dpastoor I added something about homebrew to the install instructions.  Thanks for posting and solving the issue.
