### ISSUE TITLE
execute compiled model with g++

### ISSUE THREAD

**Issue by wilsonmichaelc** [metrumresearchgroup/mrgsolve#70]
Once a model is compiled, can it be run from the command line using g++?

**Comment by kylebmetrum** [comment]
No.  The model code that gets compiled is turned into a shared object that gets dynamically loaded into an R process.  All that does is provide R with a couple of other C++ functions that it can call at the appropriate time.  There is no executable program involved in the process.  

The only way to run a model is via R code in an R session.  You could script the model run (`modelrun.R`) and then run it from the command line (`Rscript modelrun.R`).  If you want a model that is pre-compiled,  let me know ... we do that frequently for shiny apps and it's pretty easy to do.  Just need some care.


https://cran.r-project.org/doc/manuals/R-exts.html#System-and-foreign-language-interfaces
https://cran.r-project.org/doc/manuals/R-exts.html#dyn_002eload-and-dyn_002eunload
https://cran.r-project.org/doc/manuals/R-exts.html#Creating-shared-objects
