### ISSUE TITLE
Question/Documentation Request:  self.tad() Result (and a not-so-sly feature request)

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#700]
I assume that `self.tad()` returns the time after the first dose for any compartment.  So, it is, in effect, a calculation of the time since the most recent EVID=1 record.  Is that correct?  (If so, or if not, can you please update section 2.3.14 of the user guide to clarify the answer?)

Also, based on the [TAD blog post](https://mrgsolve.github.io/blog/time_after_dose.html), can you please update the section 2.3.14 to indicate that "`self.tad()` is -1 before the first dose."?

The other option that I could imagine is that it is the time after dose in the current compartment which could be interesting sometimes.  (Though practically, if I need to specify the compartment for the dose, then I probably have much more complex things going on and need to do more specific tracking.)

Somewhat related (and the reason that I was looking in the documentation for this), I think it could be useful to have a set of macros that do a set of calculations:

* `self.tad()`: Time after the most recent EVID==1 record in any compartment for the current ID.
* `self.tad(CMT)`: Time after the most recent EVID==1 record in `CMT` (where `CMT` can be either a name or number).
* `self.tafd()`: Time after the first EVID==1 record in any compartment for the current ID.
* `self.tafd(CMT)`: Time after the first EVID==1 record in `CMT` (where `CMT` can be either a name or number).

Actually, as I'm reading this the documentation gives a warning which I will not heed to get tafd (and it suggests a documentation update to give the option of `self.tafd()` or `self.tad(CMT)` with only a documentation modification and no code modifications):

I think that this will work:
```
$MAIN
double TAFD;
double TAFD_1;
if (NEWIND <= 1) {
  TAFD = -1;
  TAFD_1 = -1;
}
if (TAFD == -1 & self.tad() >= 0) TAFD = self.time;
if (TAFD == -1 & self.tad() >= 0 & CMT == 1) TAFD_1 = self.time;
```

**Comment by kylebaron** [comment]
Thanks, @billdenney .  The documentation changes have been made.  I opened #702 with the feature request.

**Comment by billdenney** [comment]
Thanks!
