### ISSUE TITLE
Gene Therapy

### ISSUE THREAD

**Issue by Jwetherington** [metrumresearchgroup/mrgsolve#701]
I’m modeling the kinetics of an endogenous protein whose production is being coerced from cells through gene therapy.  Following transduction of cells mediated through the administration of a formulation of DNA, these cells should produce and secrete the endogenous protein at a constant rate.  This should be analogous to an IV infusion with the rate and amount (a mass) dictated by the extend of cellular transduction, and with a very long duration (i.e., multiple years). I’ve modeled over time the kinetics of the formulated DNA as well as the transduction process.  I want to model the kinetics of the resulting endogenous protein via a one compartment model.  How do I input the “dose” of the endogenous protein into this one compartment model within the mrgsolve framework?

**Comment by kylebaron** [comment]
HI @Jwetherington - 

Here is an example of how you might do it.  Use model times to turn this infusion on and off. Your code might need to be more or less complicated than this, but it'll give you a start.  This type of code would allow you to determine the start and end of the infusion as well as allow you to make changes in the rate along the way - either step changes at discrete times or continuous changes as a function of some other species.  But note that if `R0` is a function of the amount in some other compartment, you'd need to calculate that in `[ode]` not `[main]` block. 

If you can share more specifics about what actually needs to get done I can help you find an efficient and maintainable way to get it done.

Kyle



``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter

code <- '
[ param ] kdeg = 0.1, start  = 2, end = 100, production = 100

[ cmt ] protein

[ main ] 

if(NEWIND <= 1) capture R0 = 0; 

double startmt = self.mtime(start);
if(TIME > startmt) R0 = production;

double endmt = self.mtime(end);
if(TIME > endmt) R0 = 0;

[ ode ] 
dxdt_protein = R0 - protein * kdeg;

'

mod <- mcode("endo-protein", code, delta = 0.1, end = 120)
#> Building endo-protein ...
#> done.

mrgsim(mod) %>% plot
```

![](https://i.imgur.com/wNhHueW.png)

<sup>Created on 2020-06-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Jwetherington** [comment]
Kyle, 

A bit more detail that I hope will be helpful to you.
- The first ODE (a count) describes the transduction of abnormal cells to normal cells able to produce a vital protein
- The second ODE (a mass) describes the rate of production of the protein
- The third set of ODEs (a concentration) describes the pk of the protein upon entering circulation in blood.

I'm visualizing the protein entering the circulatory system by a process analagous to a continuous infusion over a very long duration.  I'm currently inputting the protein into a one-compartment model as if it were an oral dose with a rapid absorption constant.  A simple solution that seems unsatisfying due to the need to specify ka.  

Is there a direct way to input the protein into circulation?  I greatly appreciate your help.

Jeff


code <-
  "
[ PARAM ] @annotated
   kin_T    : 0.01   : Transducted cells produced as a first order rate process (1/hr)
  kout_T   : 0.01   : Transducted cells going out as a first order rate process (1/hr)
  H           : 1e10   : Number of cells eligible for transduction
  p_T        : 1e-3   : Transduction rate
  p_A        : 1e-1    : Apoptosis rate
  
  kin_F     : 0.01     : protein produced as a first order rate process (ng/hr)
  kout_F.  : 0.01     : protein going out as a constant rate (1/hr)
  r             : 1e-10  : protein production rate (ng/cell)
  
  ka       :  1          : First order absorption rate constant (1/hr)
  CL_F   :  0.276  : Clearance (L/hr)
  VC_F.  :  2.45    : Volume of central (L)
  VP_F   :  0.923  : Volume of periphal (L)
  Q_F    :  2.51      : Intercompartment clearance (L/hr)


$INIT  @annotated
   TRANS       :   0 : Hepatocyte transduction compartment (count)
    protein      :   0 : Factor VIII production compartment (ng)
    CENT_F     :   0 : Central PK compartment (ng)
    PERI_F       :   0 : Peripheral PK compartment (ng)

$ODE
  dxdt_TRANS = kin_T*(H*p_T) - kout_T*(TRANS*p_A);
  
  dxdt_protein = kin_F*(TRANS*r) - kout_F*protein;
  
  dxdt_CENT_F = ka*protein - (CL_F/VC_F)*(CENT_F) - (Q_F/VC_F)*(CENT_F) + (Q_F/VP_F)*PERI_F;
  dxdt_PERI_F  =                                                                (Q_F/VC_F)*(CENT_F) - (Q_F/VP_F)*PERI_F;


[  TABLE ]
    double FP = CENT_F/VC_F;


[ CAPTURE ] 
    FP
    
  "

mod <- mcode("F8model", code)



sim <- mod %>% 
  tscale((1/24)/7) %>%
  mrgsim(end=10000, delta=1 ,obsonly=TRUE)

**Comment by kylebaron** [comment]
Hi Jeff - 

Yes, you should be able to do it.  Just bear with me as I try to understand.  

The model has the protein produced with rate `kin_F*TRANS*r` and it is cleared with rate constant `kout_F`.  You currently have the protein being absorbed into `CENT` with rate constant `ka`.  And then the protein (?) distributes to `PERI` and is (also) eliminated  with rate constant `CL_F/VC_F`?  So the clearances and the volumes also control distribution of the protein?  I wonder if you could just have input into `CENT_F` with rate `kin_F*TRANS*r`?  Is this getting closer to what you want?

Kyle


Just copying the model re-formatted a bit.


``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

code <- "
[ PARAM ] @annotated
kin_T      : 0.01  : Transducted cells produced as a first order rate process (1/hr)
kout_T     : 0.01  : Transducted cells going out as a first order rate process (1/hr)
H          : 1e10  : Number of cells eligible for transduction
p_T        : 1e-3  : Transduction rate
p_A        : 1e-1  : Apoptosis rate
kin_F      : 0.01  : protein produced as a first order rate process (ng/hr)
kout_F     : 0.01  : protein going out as a constant rate (1/hr)
r          : 1e-10 : protein production rate (ng/cell)
ka         : 1     : First order absorption rate constant (1/hr)
CL_F       : 0.276 : Clearance (L/hr)
VC_F       : 2.45  : Volume of central (L)
VP_F       : 0.923 : Volume of periphal (L)
Q_F        : 2.51  : Intercompartment clearance (L/hr)

$INIT @annotated
TRANS   : 0 : Hepatocyte transduction compartment (count)
protein : 0 : Factor VIII production compartment (ng)
CENT_F  : 0 : Central PK compartment (ng)
PERI_F  : 0 : Peripheral PK compartment (ng)

$ODE
dxdt_TRANS = kin_T*(H*p_T) - kout_T*(TRANS*p_A);

dxdt_protein = kin_F*(TRANS*r) - kout_F*protein;

dxdt_CENT_F = ka*protein - (CL_F/VC_F)*(CENT_F) - (Q_F/VC_F)*(CENT_F) + (Q_F/VP_F)*PERI_F;
dxdt_PERI_F = (Q_F/VC_F)*(CENT_F) - (Q_F/VP_F)*PERI_F;

[ TABLE ] double FP = CENT_F/VC_F;

[ CAPTURE ] FP
"

mod <- mcode("F8model", code)
#> Building F8model ...
#> done.

mod %>%
  tscale((1/24)/7) %>%
  mrgsim(end=10000, delta=1 ,obsonly=TRUE) %>% plot()
```

![](https://i.imgur.com/s3tazRo.png)

<sup>Created on 2020-06-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Jwetherington** [comment]
Kyle,

The model does have the protein produced with rate kin_F*TRANS*r within each cell and it is cleared (i.e., secreted) from each cell with rate constant kout_F. As the model is currently written, the protein is absorbed into CENT with rate constant ka.  And then the protein does distributes to PERI and is (also) eliminated with rate constant CL_F/VC_F.  You are correct:  the clearances and the volumes also control distribution of the protein.  Based on your suggestion, can I just re-write the last set of ODEs as follows? 

dxdt_CENT_F = protein - (CL_F/VC_F)*(CENT_F) - (Q_F/VC_F)*(CENT_F) + (Q_F/VP_F)*PERI_F;
dxdt_PERI_F = (Q_F/VC_F)*(CENT_F) - (Q_F/VP_F)*PERI_F;

Apologies in advance for my naive questions.

Jeff

**Comment by kylebaron** [comment]
Hi @Jwetherington  - 

Thanks for clarifying the model for me.  I guess I'd be inclined to write this:

```c
dxdt_protein = kin_F*(TRANS*r) - kout_F*protein;

dxdt_CENT_F = kout_F*protein - (CL_F/VC_F)*(CENT_F) - (Q_F/VC_F)*(CENT_F) + (Q_F/VP_F)*PERI_F;
```

if `kout_F*protein` is the rate out of the cells and you assume that all of the protein produced in each cell is secreted into the central compartment.  Maybe a certain fraction is degraded or just doesn't make it to `CENT`?  I hope I'm understanding things correctly.

KTB

**Comment by kylebaron** [comment]
Closing this; @Jwetherington please let me know if we can be of further help.
