### ISSUE TITLE
Feature: return time after dose in a specific compartment

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#702]
# Summary

As a user, I want to be able to calculate the time after a dose to a specific compartment

# Tests

- inst/maintenance/unit/test-tad-cmt.R
  - tad-cmt matches tad-no-cmt
  - check against tad
  - tad-cmt with default initialization

**Comment by billdenney** [comment]
I'm commenting to follow the issue.

**Comment by kylebaron** [comment]
@billdenney I have some code worked out for this; would you be willing to give it a spin?

**Comment by billdenney** [comment]
Happily!  How do I test it.

**Comment by kylebaron** [comment]
Thanks.  Let me get the doxygen docs updated; I think that will help.  SHould be close; will let you know.

**Comment by kylebaron** [comment]
``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
code <- '
$cmt foo bar

$param CL = 10, V = 20, KA = 1

$plugin tad

$pkmodel depot = TRUE

$main
static mrg::tadose x(2);
static mrg::tadose y(1);
capture tadx = x.tad(self);
capture tady = y.tad(self);

$table
capture tados = self.tad();
'

mod <- mcode("adfa", code, end = 48)
#> Building adfa ...
#> done.

dose <- c(
  ev(amt = 100, time = 1, cmt = 2, ii = 4, addl = 9),
  ev(amt = 300, time = 4, cmt = 1, ii = 8, addl = 4)
)

a <- mrgsim(mod,dose)
plot(a)
```

![](https://i.imgur.com/bfhy4lj.png)

<sup>Created on 2020-09-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kylebaron** [comment]
https://mrgsolve.github.io/doxygen/classmrgsolve_1_1tadose.html

**Comment by kylebaron** [comment]
The was forked from issue #700
