### ISSUE TITLE
SS=1 in ev for simulation

### ISSUE THREAD

**Issue by lpzno1** [metrumresearchgroup/mrgsolve#711]
Dear Kyle, 

I am new to mrgsolve but want to use it for a simulation project. I would like to simulate at SS and was puzzled by some observations. I am sorry if the question is too naive or has been addressed before. 

I run the following code: 
# mrgsolve library, pk1.cpp
mod1 <- mread_cache("pk1")
e1 <- ev(amt=100, ii=8, addl=100, ss=1)

out1 <- 
  mod1 %>% 
  ev(e1) %>% 
  obsonly() %>% 
  mrgsim(delta=0.2, end=16)  
head(out1, n=4)

# and saw this output. The question is: since this is at SS, at time 0 CP should not be 0. 
#  ID time       EV     CENT       CP
#1  1  0.0  0.00000   0.0000  0.00000
#2  1  0.2 81.90055 106.7780 10.67780
#3  1  0.4 67.05450 119.3574 11.93574
#4  1  0.6 54.89958 129.0241 12.90241

#therefore instead of asking for observation only, I did this 
out1 <- 
  mod1 %>% 
  ev(e1) %>% 
  #obsonly() %>% 
  mrgsim(delta=0.2, end=16)  
head(out1, n=4)

#now I have this. The 2nd row CP at time 0 looks right, which did not start from 0. It looks like when obsonly is used the 2nd row is omitted. but shouldn't the 1st one be skipped instead of 2nd one?
#  ID time        EV      CENT        CP
#1  1  0.0   0.00000   0.00000  0.000000
#2  1  0.0 100.03356  90.62563  9.062563
#3  1  0.2  81.90055 106.77802 10.677802
#4  1  0.4  67.05450 119.35735 11.935735

thank you very much ! 

best regards, Liping Zhang

**Comment by kylebaron** [comment]
Hi @lpzno1 - 

Thanks for the question.  In the example code, there are both doses and observations at `time=0` and mrgsolve has to decide which to do first.  The default is to do the observation first.  You can see this in the (modified) output below.  So the first row is an observation prior to any dosing.  The second record will be the dose and it should reflect the system advanced to steady state.  

You can use the `recsort` option (set to `3`) to change that behavior (it will give you the dose first; see `?mrgsim`). There is a similar consideration for `ADDL` doses (mrgsolve has to make that decision unless you pick with `recsort`).  Note that this a consequence of the fact that we are using event object and asking mrgsolve to fill in the observations.  You could code up a data set that includes both observations and doses and mrgsolve will respect your decisions around sort order.

I agree that most of the time I would prefer to have the dose first.  But this was the behavior for a while and I've been reluctant to change; maybe it should be revisited. :)

I hope this answers your question.  Let me know if I can help with anything else.

Best Regards,
Kyle

``` r

library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter

mod1 <- modlib("pk1")
#> Building pk1 ...
#> done.

e1 <- ev(amt=100, ii=8, addl=100, ss=1)
```

## original code

``` r
out1 <-
  mod1 %>%
  ev(e1) %>%
  carry_out(evid) %>%
  mrgsim(delta=0.2, end=16)

out1
#> Model:  pk1 
#> Dim:    82 x 6 
#> Time:   0 to 16 
#> ID:     1 
#>     ID time evid     EV  CENT    CP
#> 1:   1  0.0    0   0.00   0.0  0.00
#> 2:   1  0.0    1 100.03 214.0 10.70
#> 3:   1  0.2    0  81.90 229.9 11.50
#> 4:   1  0.4    0  67.05 242.4 12.12
#> 5:   1  0.6    0  54.90 252.1 12.60
#> 6:   1  0.8    0  44.95 259.5 12.97
#> 7:   1  1.0    0  36.80 265.0 13.25
#> 8:   1  1.2    0  30.13 269.0 13.45
```

## use recsort = 3

``` r
out2 <-
  mod1 %>%
  ev(e1) %>%
  carry_out(evid) %>%
  mrgsim(delta=8, end=32, recsort = 3)

out2
#> Model:  pk1 
#> Dim:    6 x 6 
#> Time:   0 to 32 
#> ID:     1 
#>     ID time evid  EV CENT   CP
#> 1:   1    0    1 100  214 10.7
#> 2:   1    0    0 100  214 10.7
#> 3:   1    8    0 100  214 10.7
#> 4:   1   16    0 100  214 10.7
#> 5:   1   24    0 100  214 10.7
#> 6:   1   32    0 100  214 10.7
```

## another option

``` r
out3 <-
  mod1 %>%
  ev(e1) %>%
  carry_out(evid) %>%
  mrgsim(delta=8, start = 8, end=32)

out3
#> Model:  pk1 
#> Dim:    5 x 6 
#> Time:   0 to 32 
#> ID:     1 
#>     ID time evid  EV CENT   CP
#> 1:   1    0    1 100  214 10.7
#> 2:   1    8    0 100  214 10.7
#> 3:   1   16    0 100  214 10.7
#> 4:   1   24    0 100  214 10.7
#> 5:   1   32    0 100  214 10.7
```

<sup>Created on 2020-07-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lpzno1** [comment]
Oh thank you so much for the quick and clear answer, Kyle! I have been watching the PAGE2018 videos so much that when I see your notes, I can hear your voice reading over them! Thanks!
