### ISSUE TITLE
Error in eval(parse(text = paste0("list(", x, ")")), envir = envir)

### ISSUE THREAD

**Issue by cardtrick** [metrumresearchgroup/mrgsolve#719]
Hi everyone,

I'm trying my best to understand this error message I receive when I try to use the mread function. I might be naive on this (sorry!) but for the life of me, I can't figure this one out.

Error in eval(parse(text = paste0("list(", x, ")")), envir = envir) : 
  object 'Qli' not found

I'm trying to see if I just defined it incorrectly or if I mistyped, but so far, I'm not seeing it. The code is below.

`[ PROB ] 

# PBPK MODEL

[ SET ] end = 24, delta = 0.25

[ CMT ] 
ADIPOSE BONE BRAIN GUT HEART KIDNEY LIVER LUNG MUSCLE SKIN SPLEEN ART VEN D REST

[ PARAM ] 

//Partition coefficients
Kpad = 0.190  //; adipose
Kpbo = 0.499  //; bone
Kpbr = 0.81   //; brain 
Kpgu = 0.772  //; gut
Kphe = 0.808  //; heart
Kpki = 0.774  //; kidney
Kpli = 0.758  //; liver
Kplu = 0.784  //; lung
Kpmu = 0.755  //; muscle
Kpsk = 0.729  //; skin
Kpsp = 0.796  //; spleen
Kpre = 0.600  //; rest of body

//specific parameters
BW = 7.7	//; BW (kg) based on National Primate Research Center
Qc = 60  //; L/hr 1 L/min * 60 min = 60 from National Centre...Animals in Research

//organ volumes (L)
Vad = 1.02
Vbo = 0.81
Vbr = 0.1
Vgu = 0.19
Vhe = 0.02
Vki = 0.03
Vli = 0.14
Vlu = 0.09
Vmu = 2.5
Vsk = 0.5
Vsp = 0.02
Var = 0.04
Vve = 0.02 

//tissue blood flow (L/h)
Qad = 1.2  // 0.02 L/min * 60 = 1.2
Qbo = 2.4 // 0.04 L/min * 60 = 2.4
Qbr = 4.2 // 0.07 L/min * 60 = 4.2
Qgu = 2.4 // 0.04 L/min * 60 = 2.4
Qhe = 3.6 // 0.06 L/min * 60 = 3.6
Qki = 8.4 // 0.14 L/min * 60 = 8.4
Qli = 3 // 0.05 L/min * 60 = 3
Qlu = 60 // from above
Qmu = 5.4 // 0.09 L/min * 60 = 5.4
Qsk = 3 // 0.05 L/min * 60 = 3
Qsp = 1.2 // 0.02 L/min * 60 = 1.2
Qre = 28.2 // 60 - others
Qha = Qli - (Qgu + Qsp) // hepatic artery
  
//other parameters 
f = 0.93 // bioavailability
fa = 1 // fraction available for absorption from dosage form
fg = 1 // gut availability
Ka = 0.67 // First-order absorption rate constant (1/h)
fup = 0.96 // Fraction of drug unbound in plasma
BP = 1 // blood:plasma ratio
Cl_r = 12.8 // renal clearance for single dose (L/h)
CL_hep = 0 

[ MAIN ]

//Calculation of tissue drug concentrations (mg/L); anything based on the concentration in the compartments needs to go in ODE
double Cadipose = ADIPOSE/Vad;
double Cbone = BONE/Vbo;
double Cbrain = BRAIN/Vbr; 
double Cgut = GUT/Vgu; 
double Cheart = HEART/Vhe; 
double Ckidney = KIDNEY/Vki;
double Cliver = LIVER/Vli; 
double Cskin = SKIN/Vsk;
double Clung = LUNG/Vlu; 
double Cmuscle = MUSCLE/Vmu;
double Cspleen = SPLEEN/Vsp;
double Carterial = ART/Var;
double Cvenous = VEN/Vve;
double Crest = REST/Vre;

double Cplasma = Cvenous/BP; //defining plasma concentration

[ ODE ]
//Diferential equations
dxdt_ADIPOSE = Qad*(Carterial - Cadipose/(Kpad/BP)); 
dxdt_BRAIN = Qbr*(Carterial - Cbrain/(Kpbr/BP));
dxdt_HEART = Qhe*(Carterial - Cheart/(Kphe/BP));
dxdt_KIDNEY = Qki*(Carterial - Ckidney/(Kpki/BP))- Ckidney * (Qki * ((fup * Cl_r)/(Qki + fup * Cl_r)));
dxdt_GUT = Qgu*(Carterial - Cgut/(Kpgu/BP)) + Ka*D*fg*fa;
dxdt_LIVER = Qha*Carterial + Qsp*Cspleen/(Kpsp/BP) + Qgu*Cgut/(Kpgu/BP) - 
  Qli*Cliver/(Kpli/BP) - Cliver * (Qli * ((fup * Cl_hep)/(Qli + fup*Cl_hep))); //need to account for free drug in liver
dxdt_LUNG = Qlu*(Cvenous - Clung/(Kplu/BP));
dxdt_MUSCLE = Qmu*(Carterial - Cmuscle/(Kpmu/BP));
dxdt_SPLEEN = Qsp*(Carterial - Cspleen/(Kpsp/BP));
dxdt_BONE = Qbo*(Carterial - Cbone/(Kpbo/BP));
dxdt_SKIN = Qsk*(Carterial - Cskin/(Kpsk/BP));
dxdt_VEN = Qad*Cadipose/(Kpad/BP) +
  Qbr*Cbrain/(Kpbr/BP) +
  Qhe*Cheart/(Kphe/BP) +
  Qki*Ckidney/(Kpki/BP) +
  Qli*Cliver/(Kpli/BP) +
  Qmu*Cmuscle/(Kpmu/BP) +
  Qbo*Cbone/(Kpbo/BP) +
  Qre*Crest/(Kpre/BP) +
  Qsk*Cskin/(Kpsk/BP) - 
  Qlu*Cvenous;
dxdt_ART = Qlu * (Clung/(Kplu/BP) - Carterial);
dxdt_D = -Ka*fg*fa*D; 
dxdt_REST = Qre*(Carterial-Crest/(Kpre/BP));

[ CAPTURE ] Cplasma Cspleen
  `

**Comment by kylebaron** [comment]
Hi @cardtrick 

You have to move this to `[main]`
```
Qha = Qli - (Qgu + Qsp) // hepatic artery
```


```
[ main ]
double Qha = Qli - (Qgu + Qsp); // hepatic artery
```

Let me know if that works for you.

**Comment by cardtrick** [comment]
Hi @kylebaron thank you so much! I'll close the issue with this comment.
