### ISSUE TITLE
How can I add a parameter to describe the bioavailability?

### ISSUE THREAD

**Issue by Wangchu34** [metrumresearchgroup/mrgsolve#721]
I am a beginner in Mrgsolve. When I start a PBPK model, I set the gutlumen as the first CMT and the equation was dxdt_Lumen=-Kabs*Lumen in the $ODE.  In the oral route, the oral exposure amount was set by the function ev(). I think this means the oral amount was fisrtly introduced to the Lumen (dxdt_Lumen=oral amount-Kabs*Lumen) during the simulation. Do I have a proper understand about this process. Besides, if right, the unit of amount is gram, but the unit of dxdt_Lumen was gram/hour, I am confused about the non-uniform units. Should I convert the oral amount (g) to the oral amount per hour (g/h). In addition, when I want to describe the bioavailability, could I add a parameter of bioavailability (0<F<1) in the dxdt_Lumen=-F*Kabs*Lumen and dxdt_Liver=Qli(Ca-Cv)-CL+F*Kabs*Lumen to describe the process of intake?
I hope to recieve your generous help. Thank you !

**Comment by kylebaron** [comment]
@Wangchu34 - I'm writing up a response for you.  But the answer depends a little bit on how the model is constructed.  

Do the compartment amounts represent concentrations or amounts?

Kyle

**Comment by Wangchu34** [comment]
> @Wangchu34 - I'm writing up a response for you. But the answer depends a little bit on how the model is constructed.
> 
> Do the compartment amounts represent concentrations or amounts?
> 
> Kyle

Thanks for your reply. In my model, the compartments  is expressed in amounts, which means in the equation dxdt_Lumen...the unit of Lumen is gram.

**Comment by kylebaron** [comment]
Great; it gets a little tricky when it is concentration (but not impossible).  I need a bit to finish this; hopefully later this morning.

**Comment by Wangchu34** [comment]
> Great; it gets a little tricky when it is concentration (but not impossible). I need a bit to finish this; hopefully later this morning.

Thank you so much. I look forward to your reply.

**Comment by kylebaron** [comment]
``` r
library(mrgsolve)
```

> I am a beginner in Mrgsolve. When I start a PBPK model, I set the
> gutlumen as the first CMT and the equation was dxdt\_Lumen=-KabsLumen
> in the $ODE. In the oral route, the oral exposure amount was set by
> the function ev(). I think this means the oral amount was fisrtly
> introduced to the Lumen (dxdt\_Lumen=oral amount-KabsLumen) during the
> simulation. Do I have a proper understand about this process.

When you use the `ev()` function, you are telling mrgsolve to stop at a
specific time, add a certain amount of mass to one of the compartments
and then start again advancing the system.

Typically you have this:

``` r
ev(amt = 100)
```

    . Events:
    .   time amt cmt evid
    . 1    0 100   1    1

This says: put 100 units into compartment 1 at time 0

You could also have this:

``` r
ev(amt = 100, time = 12, cmt = 2)
```

    . Events:
    .   time amt cmt evid
    . 1   12 100   2    1

This says: put 100 units into compartment 2 at time 12

You can say when to stop, how much to add to the compartment and which
compartment you add it to. You don’t have to make `Lumen` the first
compartment, but it is more convenient to do that.

# Important

But you have to let mrgsolve handle the dosing. Your model should be
this:

``` r
"
$ODE
dxdt_Lumen = -Kabs * Lumen;
dxdt_Gut_Wall = Kabs * Lumen - ...;
"
```

In other words, you shouldn’t reference the dose or dose input rate or
bioavailability in the ODE; let mrgsolve put the dose into the right
compartment for you.

> Besides, if right, the unit of amount is gram, but the unit of
> dxdt\_Lumen was gram/hour, I am confused about the non-uniform units.
> Should I convert the oral amount (g) to the oral amount per hour
> (g/h).

For example, if you put the dose in as `g` and `Kabs` is `1/hr`, then
yes it will be `g/hr`. If you dose it `mg` it will be `mg/hr` etc. You
can rescale this by changing the dose you administer or by re-scaling
output amounts / concentrations.

The other way you could do it is throu bioavailability parameter.

> In addition, when I want to describe the bioavailability, could I add
> a parameter of bioavailability (0\<F\<1) in the
> dxdt\_Lumen=-FKabsLumen and dxdt\_Liver=Qli(Ca-Cv)-CL+FKabsLumen to
> describe the process of intake?

See the comment above; you shouldn’t reference bioavilability here;

``` r
"
$PARAM 
bioav = 0.8

$MAIN
F_Lumen = bioav;
"
```

    ## [1] "\n$PARAM \nbioav = 0.8\n\n$MAIN\nF_Lumen = bioav;\n"

Usually include this as a parameter; then set `F_CMT` where `CMT` is the
name of your compartment.

See:
<https://mrgsolve.github.io/user_guide/model-specification.html#spec-f>

> I hope to recieve your generous help. Thank you \!

Please let me know if I can help with anything else.

**Comment by Wangchu34** [comment]
I really appreciate your answers. These help me a lot. Thank you so much!
