### ISSUE TITLE
Feature Request: Automatically run loadso()?

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#722]
Hi @kylebaron,

I was just trying to run some models in parallel with `future::plan(future::multiprocess)` with `drake`.  When I did so, I got the error that I need to run `loadso()` which I could have predicted based on #471.  I tried to check previous issues around `loadso()` because I thought I recalled asking before, but I didn't find it.

Would it be reasonable to attempt `loadso()` before giving the error that you need to run `loadso()`?

**Comment by kylebaron** [comment]
Hi Bill - 

The solution to #471 given is currently in place and that's all I'm going to do for now.  IMO, if the model dll isn't loaded, it should just stop and figure out why.  It's understandable why it wouldn't be loaded when multiprocess parallelization is used.  In that case, it makes sense to me to run loadso on the worker prior to simulating.  mrgsolve isn't formally connected with multiprocess, so I don't think we'll be doing this routinely inside mrgsolve.  But I could host the `mrsim_load` function in the mrgsim.parallel package (where we do have a real connection with future). 

Kyle

**Comment by kylebaron** [comment]
You can get this here: https://github.com/kylebaron/mrgsim.parallel

**Comment by kylebaron** [comment]
This is available in mrgsim.parallel and I will add an argument to mrgsim.

**Comment by kylebaron** [comment]
@billdenney reporting back: I did some refactoring of loadso and I think it can sensibly be called when pointers fails.  This is looking better than the argument I was going to add.  Thanks for the report and suggestion.

Kyle

**Comment by billdenney** [comment]
Great, thanks!  And, I'm intrigued to know about the parallel version.
