### ISSUE TITLE
Switch dplyr from Imports to Depends

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#727]

**Comment by dpastoor** [comment]
I don't think we should need to do this - whats the reasoning you believe we need it in depends?

**Comment by kylebaron** [comment]
Been thinking about it for a while - different reasons, but not reason enough to make the switch.  The generics conversation made it seem like something reasonable to consider. Either that or take away the methods which probably shouldn't have even been made in the first place.

**Comment by kylebaron** [comment]
Just leaving an idea here to consider.  Not charging ahead yet.

**Comment by dpastoor** [comment]
ah - but for the overlapping dplyr-generics, I think we can just register the s3 methods without having to explicitly load:

For example, to do that with knitr/mrggt

https://github.com/metrumresearchgroup/mrggt/blob/develop/R/zzz.R#L2
https://github.com/metrumresearchgroup/mrggt/blob/develop/R/zzz.R#L122

**Comment by kylebaron** [comment]
Ok; nice.  I've never done that before.  Will give that a try.
