### ISSUE TITLE
R crashing with modmrg

### ISSUE THREAD

**Issue by mjbrooklyn** [metrumresearchgroup/mrgsolve#74]
Hi, mrgsolve working fine but when l installed modmrg, R and R Studio crashed at mod<-pk1cmt().  I see pk1cmt.cpp file in appropriate directory. Any ideas?

**Comment by kylebmetrum** [comment]
@mjbrooklyn 

Can you share output from call to `sessionInfo()`?  as well as the exact code you are running to get the crash?

Without knowing more, I would suggest re-installing most-recent versions of both `mrgsolve` and `modmrg` from source.

I doubt this would cause a crash, but if you do need to upgrade, you might need to get latest `dplyr` too (https://github.com/metrumresearchgroup/mrgsolve/issues/69).  There were changes in that package that required changes in `mrgsolve`.   

Let me know what happens.

Kyle


```r
    library(modmrg)

    ## Loading required package: mrgsolve

    ## mrgsolve: Community Edition

    ## www.github.com/metrumresearchgroup/mrgsolve

    ## modmrg: Pre-release / Community Edition

    ## www.github.com/metrumresearchgroup

    ## 
    ## Attaching package: 'modmrg'

    ## The following object is masked from 'package:mrgsolve':
    ## 
    ##     pkmodel

    mod <- pk1cmt()

    mod %>% init(EV1=100) %>% mrgsim

    ## Model:  pk1cmt.cpp 
    ## Dim:    25 x 6 
    ## Time:   0 to 24 
    ## ID:     1 
    ##      ID time       EV1  CENT EV2    CP
    ## [1,]  1    0 100.00000  0.00   0 0.000
    ## [2,]  1    1  36.78794 59.66   0 5.966
    ## [3,]  1    2  13.53353 75.93   0 7.593
    ## [4,]  1    3   4.97871 76.78   0 7.678
    ## [5,]  1    4   1.83156 72.44   0 7.244
    ## [6,]  1    5   0.67379 66.64   0 6.664
    ## [7,]  1    6   0.24788 60.70   0 6.070
    ## [8,]  1    7   0.09119 55.07   0 5.507

    sessionInfo()

    ## R version 3.3.0 (2016-05-03)
    ## Platform: x86_64-apple-darwin13.4.0 (64-bit)
    ## Running under: OS X 10.9.5 (Mavericks)
    ## 
    ## locale:
    ## [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
    ## 
    ## attached base packages:
    ## [1] stats     grDevices utils     datasets  graphics  methods   base     
    ## 
    ## other attached packages:
    ## [1] modmrg_0.0.1        mrgsolve_0.6.1.9015
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] Rcpp_0.12.5               digest_0.6.9             
    ##  [3] dplyr_0.5.0               assertthat_0.1           
    ##  [5] R6_2.1.2                  DBI_0.4-1                
    ##  [7] magrittr_1.5              evaluate_0.9             
    ##  [9] stringi_1.1.1             lazyeval_0.2.0           
    ## [11] RcppArmadillo_0.7.100.3.1 rmarkdown_0.9.6          
    ## [13] tools_3.3.0               stringr_1.0.0            
    ## [15] yaml_2.1.13               htmltools_0.3.5          
    ## [17] knitr_1.13                tibble_1.1

```

**Comment by dpastoor** [comment]
also @mjbrooklyn are you running this on an apple machine or on linux/windows. 

@kylebmetrum could there be some platform specific compiled (anything) cached in the modmrg files? I didn't look how you were caching the compiled models.

**Comment by kylebmetrum** [comment]
@dpastoor We used to try to maintain a binary version of this package so you could run a model without a compiler; but it was too hard.  

Now, `modmrg` is __only__ source files that get compiled into a single shared object when the package is installed.  One thing the could cause seg fault is change of compilers between installing the two packages.  Another is: we just made a change to `$CAPTURE` that might be able to do it (if the two packages are out of sync); but I fiddled with the version requirements and I think (hope) that has been addressed.

It might be easier to just package these up into the main `mrgsolve` package to make sure there are no problems with dependencies.

**Comment by dpastoor** [comment]
@kylebmetrum ok good, I remember seeing your first shot with the binaries and was wondering if that'd be an issue down the line. I agree the number of headaches should be drastically reduced by keeping it source-only

**Comment by kylebmetrum** [comment]
@dpastoor But the `R` part of the model (the S4 object) is `save`d.  You can sort of see it here.

https://github.com/metrumresearchgroup/modmrg/blob/master/makescripts/buildmodels.R

**Comment by mjbrooklyn** [comment]
I am running Windows 10-- and I reinstalled the newest version of
 mrgsolve in github and attempted to reinstall modmrg and received the
following message:

Error : package 'mrgsolve' 0.6.0.9000 was found, but >= 0.6.1.9009 is
required by 'modmrg'
ERROR: lazy loading failed for package 'modmrg'

Is there a newer version of mrgsolve on github?

Thanks

**Comment by kylebmetrum** [comment]
Re-install both:

```r
if(!require(devtools)) install.packages("devtools")
library(devtools)
install_github("metrumresearchgroup/mrgsolve", subdir="rdev")
install_github("metrumresearchgroup/modmrg", subdir="rdev")

```

https://github.com/metrumresearchgroup/mrgsolve/blob/master/rdev/DESCRIPTION#L3

**Comment by mjbrooklyn** [comment]
I wasn't using R version 3.31--  problem solved!

**Comment by kylebmetrum** [comment]
Not really sure what the exact problem was; but please do keep us posted if anything else isn't behaving.
