### ISSUE TITLE
Transit model code broken

### ISSUE THREAD

**Issue by benjaminrich** [metrumresearchgroup/mrgsolve#749]
I had some code that was working with version 0.8.12, but somewhere along the line it stopped working.

The code looks like this:

```r
library(mrgsolve)

model_code <- '
$CMT CENT PERI1 PERI2

$PARAM

CL = 10.6365, V1 = 206.799, Q1 = 12.6211, V2 = 114.424, Q2 = 2.66625, V3 = 78.5099, NTR = 2.34887, MTT = 0.907036

$SIGMA 1

$GLOBAL 

double TOD = 0;
double DOSI = 0;
double X = 0.00001;
double BIO = 1;

$MAIN

F_CENT = 0;

if (EVID==1) {
    TOD = TIME;
    DOSI = self.amt;
}

double KTR = (NTR+1.0)/MTT;

// Stirling approximation
double LOGF = 0.5*log(NTR*2.0*3.1415926+X) + NTR*log(NTR+X) - NTR + log(1.0 + (1.0/(12.0*NTR)) + (1.0/(288.0*NTR*NTR)) + X);

$ODE

double TSTAR  = SOLVERTIME - TOD;
if (TSTAR < 0.001) TSTAR = 0.001;

double INP = 0;
if (DOSI > 0) {
    INP = exp(log(BIO*DOSI+X) + NTR*log(KTR*TSTAR+X) + log(KTR+X)- KTR*TSTAR - LOGF);
}
if (INP < 0) INP = 0;

double CP = CENT/V1;

dxdt_CENT  = INP - (CL + Q1 + Q2)*CP + Q1*PERI1/V2 + Q2*PERI2/V3;
dxdt_PERI1 = Q1*(CP - PERI1/V2);
dxdt_PERI2 = Q2*(CP - PERI2/V3);

$CAPTURE CP
'

mod <- mcode("transit", model_code)

sim <- mod %>%
    ev(time=24*(0:20), amt=1000, cmt=1) %>%
    Req(CP) %>%
    mrgsim(start=0, end=24*20, delta=0.01)

plot(sim, main=paste0("mrgsolve version ", packageVersion("mrgsolve")))
```

The output using verion 0.8.12 looks like this:

![Rplot001](https://user-images.githubusercontent.com/17572252/95532829-904fae80-09af-11eb-8ce5-08ac1d1cd7e1.png)

With the current version on CRAN (0.10.4), the same code now outputs this:

![Rplot001](https://user-images.githubusercontent.com/17572252/95532984-fe947100-09af-11eb-84e4-9ee2e10b3193.png)

This output is wrong, but I don't know which update triggered the error.

**Comment by kylebaron** [comment]
Try this: 

```r
sim <- mod %>%
    ev(time=24*(0:20), amt=1000, cmt=1) %>%
    Req(CP) %>%
    mrgsim(start=0, end=24*20, delta=0.01, hmax = 0.01)
```

**Comment by benjaminrich** [comment]
Perfect!

Now can you explain why that works? The documentation says:

> decrease hmax when you want to limit how big of a step the solver can take when integrating from one time to the next time. However be aware that smaller hmax will result in longer run times.

The default seems to be zero (correct?), what does that do, and why should it fail in this case? Do you have any advice on how to choose this parameter?

Thanks.

**Comment by kylebaron** [comment]
The default is 0 which means that the step size can go as big as it wants.  Probably in the old version, it was using the FORTRAN DLSODA code; I swapped that out for a C++ implementation a year-ish ago because the FORTRAN code was running into too many issues on CRAN.  I'm guessing that there is some slight difference in how the step size works between the two.  I obviously don't know the details. It's just running ahead too fast or overshooting or something.  But this is the type of model where I'd expect that limiting the step size could help prevent the behavior you're seeing. 

Not sure if you can convert to this, but I've started using this transit model with better success; I can give you an mrgsolve implementation if you'd like.

```
; Modified from appendix 4 of Jun Shen, Alison Boeckmann & Andrew Vick
; Modified for NONMEM 7.3
; Journal of Pharmacokinetics and Pharmacodynamics
; ISSN 1567-567X Volume 39 Number 3
; J Pharmacokinet Pharmacodyn (2012) 39:251-262 DOI 10.1007/s10928-012-9247-3

$PROBLEM Dose Superposition
$INPUT ID TIME CMT AMT DV ADDL II RATE
$DATA sumdosetf.csv IGNORE=@  ; identical to sall6.csv
$SUBROUTINES ADVAN6 TOL=10 TRANS1

$MODEL COMP=ABS ;(DEFDOSE)
       COMP=CENTRAL;(DEFOBS)
       COMP=PERI

$abbr declare dosetime(100),dose(100)
$abbr declare dowhile i
$abbr declare dowhile ndose

$PK 
CALLFL=-2
IF (NEWIND < 2) NDOSE=0

IF (AMT > 0 .and. cmt==1) THEN
 NDOSE=NDOSE+1
 dosetime(NDOSE)=TIME
 DOSE(NDOSE)=AMT
ENDIF

CL = THETA(1)*EXP(ETA(1))
V2 = THETA(2)*EXP(ETA(2))
Q  = THETA(3)
V3 = THETA(4)

K=CL/V2
S2 =V2
K23=Q/V2
K32=Q/V3

;--------ABSORPTION MODEL-----------
F1=0
MTT  = THETA(5)*EXP(ETA(4))
NN   = THETA(6)*EXP(ETA(5))
BIO  = THETA(7)*EXP(ETA(3))
KTR  = (NN+1)/MTT

NFAC=SQRT(2*3.1416)*NN**(NN+0.5)*(EXP(-NN))*(1+1/(12*NN))
KINPT=BIO*KTR**(NN+1)/NFAC

$DES
INPT=0
I=1
DOWHILE (I<=NDOSE)
IPT=0
IF (T>=dosetime(I)) IPT=DOSE(I)*(T-dosetime(I))**NN*EXP(-KTR*(T-dosetime(I)))
INPT=INPT+IPT
I=I+1
ENDDO

 DADT(1)=KINPT*INPT-KTR*A(1)
 DADT(2)=KTR*A(1)-K23*A(2)-K*A(2)+K32*A(3)
 DADT(3)=K23*A(2)-K32*A(3)

$ERROR

Y = F*EXP(EPS(1))

$THETA 
4 ;CL
3 ;V2
1 ;Q
2 ;V3
10 ;MTT
5 ;NN
0.85 ;BIO

$OMEGA 0 FIX 0 FIX 0 FIX 0 FIX 0 FIX 
$SIGMA 0 FIX
$SIMULATION (123456) ONLY
;$ESTIMATION METHOD=0
$TABLE  ID TIME CMT CL V2 Q V3 MTT NN INPT ONEHEADER NOPRINT FORMAT=s1PE18.11 FILE=sumdosetn.txt

```

**Comment by benjaminrich** [comment]
Thanks for the explanation. Makes sense (different implementation so different behavior). I appreciate the NONMEM code as well. Note that now NONMEM has the GAMLN function, so you don't need Stirling's approximation.

Feel free to close the issue. Thanks.

**Comment by kylebaron** [comment]
Take care, @benjaminrich .
