### ISSUE TITLE
Option to select table number in nmext

### ISSUE THREAD

**Issue by timwaterhouse** [metrumresearchgroup/mrgsolve#750]
I believe nmext is returning parameter values from the first table in a model with multiple $EST blocks.  With `read_fun = "data.table"`, fread will stop early after reading the first result when it encounters the next "`TABLE NO. ...`" (but still returns the first set of parameter values).  With `read_fun = "read.table"` it just returns an error.

Is it possible to add an "index" argument to select the table number, as per nmxml?  Maybe using something like `nonmem2R::extload`?

**Comment by kylebaron** [comment]
Thanks, Tim.

**Comment by kylebaron** [comment]
Closing for #782
