### ISSUE TITLE
Linear interpolation

### ISSUE THREAD

**Issue by jrpirone** [metrumresearchgroup/mrgsolve#751]
Hello,
I'm converting a PBPK model for an industrial solvent from acslX to R/mrgsolve. Most of the conversion is straightforward. However, the inhalation exposure is based on measurements made over a 24hr period under a few different industrial settings. In this 24hr period anywhere from 1000-3000 measurements are made. In the original model, linear interpolation was used to determine the concentration at a particular timepoint. I'd also like to be able to easily pass results obtained under different exposure scenarios to the model. None of this on its own is particularly complicated, but I'm unsure how to implement this efficiently using R/mrgsolve. 
Thanks for your help you can provide.
Best,
Jason

**Comment by kylebaron** [comment]
Hi @jrpirone - 

We don't implement linear interpolation under the hood, but pretty sure we could figure out a way to get it done in your model.  Can you sketch out a little bit more about what / when you want to interpolate?  Not the whole model but just want to get something more to grab on to.  I could make a minimal example that does what you want and that you could bring into the PBPK model. 

Thanks,
Kyle

**Comment by jrpirone** [comment]
Hi @kylebaron ,

First, a disclaimer - I've not used acslX much, so some of my terminology may be imprecise. In the model I'm converting, a vector of times and a vector of concentrations are imported into a 'table' function. The table is callable and accepts time as an argument and returns a concentration found by linear interpolation of the existing values. A skeletal version of the code might look something like:

table TABLE1, 1, 1441 / 1441*0.0, 1441*0.0 / !Define table dimension
CI = TABLE1(T)  ! Call table to obtain linearly interpolated concentration
dADVv/dt = (kpv*SAv/1000.0)*CI !Use in ode 
dABld/dt = QAlv*(CI*f_in - CAlv) + QC*(CVen-CArt) !Use in ode for amount in blood

I can think of ways to incorporate the concentration data (include function fitted to the data), but I'd like to stick to the way it has been done in the past as that method is a little more straightforward.

Let me know if this helps to better define the problem.

Thanks for your help!

Best,
Jason

**Comment by kylebaron** [comment]
Thanks, @jrpirone; yes, I've done this (type of thing) before.   Below are some options.  In the first option, I wrote the code to do the interpolation; in the second I use a callback to R to so that.  The first approach is much more efficient and as far as I can tell it is matching the callback to R. 

If this were my project, I'd do the first approach.  If you implement this, I'd be grateful for your feedback on it ... does it work for you, is it convenient, what can be improved.  I'd like to take this and add it to mrgsolve as a plugin that people could use if we could get it to that point.  For example, it would be nice if we could get rid of the Rcpp code and just read in the vectors without having to go back to R.  But I'd like to take that up down the road if this is really useful the way it is.

Thanks,
Kyle

``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter
```

# Generate some concentrations to interpolate

``` r
x <- seq(0,240,0.01)
mod <- modlib("pk1") %>% param(CL = 1, V = 10)
#> Building pk1 ... done.
out <- mrgsim(
  mod, 
  events = ev(amt = 1000), 
  obsonly = TRUE, 
  atol = 1e-30, 
  end = -1, 
  add = x
)
```

## Plot

``` r
plot(out)
```

![](https://i.imgur.com/KdpvdlT.png)

``` r

x <- c(-1,x)
y <- c(0,out$CP)
```

## Make a matrix

``` r
mat <- matrix(data = c(x,y), nrow = length(x), byrow=FALSE)
```

## Write this out to file

``` r
write.table(
  file = "foo.csv", 
  mat, 
  col.names = FALSE, 
  row.names = FALSE,
  quote = FALSE,
  sep=','
)
```

# Model code - I wrote the approx code

``` r
code1 <- '
$PLUGIN Rcpp, mrgx

$ENV
mat <- read.csv("~/ghe/helpr/foo.csv")
x <- mat[,1]
y <- mat[,2]

$GLOBAL 
Rcpp::NumericVector x;
Rcpp::NumericVector y;

double myapprox(double xout) {
  int start = -1;
  if(xout < x[0] || xout > x[x.size()-1]) {
    return(0);  
  }
  for(int i = 0; i < x.size(); i++) {
    if(xout==x[i]) return y[i];
    if(xout < x[i]) {
      start = i-1;
      break;
    };
  }
  if(start < 0) return(0);
  double delx = x.at(start+1) - x.at(start);
  double dely = y.at(start+1) - y.at(start);
  return y.at(start) + (xout - x.at(start)) * dely / delx;
}

$PREAMBLE
x = mrgx::get<Rcpp::NumericVector>("x", self);
y = mrgx::get<Rcpp::NumericVector>("y", self);

$CMT CENT

$ODE
double inter = myapprox(SOLVERTIME);
dxdt_CENT = -0.1 * CENT;

$CAPTURE inter
'
```

# Model code - using call back to R / approx

``` r
code2 <- '
$PLUGIN Rcpp, mrgx

$ENV
mat <- read.csv("~/ghe/helpr/foo.csv")
x <- mat[,1]
y <- mat[,2]

appr <- function(xout) {
  approx(x,y,xout)$y
}

$GLOBAL 
Rcpp::Function appx("approx");

$PREAMBLE
appx = mrgx::get<Rcpp::Function>("appr", self); 

$CMT CENT

$ODE
double inter = Rcpp::as<double>(appx(SOLVERTIME));
dxdt_CENT = -0.1 * CENT;

$CAPTURE inter
'
```

## Compile and simulate

``` r
mod1 <- mcode("asdf", code1, preclean = TRUE, soloc = '.')
#> Building asdf ... done.
mod2 <- mcode("asdf2", code2, preclean = TRUE)
#> Building asdf2 ... done.

system.time(out1 <- mrgsim(mod1, delta = 0.1))
#>    user  system elapsed 
#>   0.003   0.000   0.003
system.time(out2 <- mrgsim(mod2, delta = 0.1))
#>    user  system elapsed 
#>   0.267   0.069   0.339
```

## Compare

``` r
head(out1)
#>   ID time CENT     inter
#> 1  1  0.0    0  0.000000
#> 2  1  0.1    0  9.468046
#> 3  1  0.2    0 17.940880
#> 4  1  0.3    0 25.514146
#> 5  1  0.4    0 32.274377
#> 6  1  0.5    0 38.299863
head(out2)
#>   ID time CENT     inter
#> 1  1  0.0    0  0.000000
#> 2  1  0.1    0  9.468046
#> 3  1  0.2    0 17.940880
#> 4  1  0.3    0 25.514146
#> 5  1  0.4    0 32.274377
#> 6  1  0.5    0 38.299863

summary(out1$inter - out2$inter)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>       0       0       0       0       0       0

out1
#> Model:  asdf 
#> Dim:    241 x 4 
#> Time:   0 to 24 
#> ID:     1 
#>     ID time CENT  inter
#> 1:   1  0.0    0  0.000
#> 2:   1  0.1    0  9.468
#> 3:   1  0.2    0 17.941
#> 4:   1  0.3    0 25.514
#> 5:   1  0.4    0 32.274
#> 6:   1  0.5    0 38.300
#> 7:   1  0.6    0 43.661
#> 8:   1  0.7    0 48.423

plot(out1, inter~time, type = 'b')
```

![](https://i.imgur.com/8g8IPX2.png)

<sup>Created on 2020-10-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jrpirone** [comment]
Hello @kylebaron, 

This is exactly what I'm looking for - thanks for your help! I'm going to go with method 1, most likely. I will let you know how it works when I have it incorporated into the final model.

Best,
Jason

**Comment by kylebaron** [comment]
Please post again if you need something tweaked here.
