### ISSUE TITLE
Installing mrgsolve on Windows 

### ISSUE THREAD

**Issue by MeenakshiSrini** [metrumresearchgroup/mrgsolve#752]
Hello mrgsolve community,

I am trying to install mrgsolve on windows. I am running R 4.0.2. I've installed Rtools40 in the directory named "C:\Rtools".

 I do see the C:/Rtools/bin when I type Sys.getenv("PATH"). Please see below 

```
> Sys.getenv("PATH")
[1] "C:/Rtools/bin;C:\\R\\R-4.0.2\\bin\\x64;;C:\\Program Files (x86)\\RSA SecurID Token Common;C:\\Program Files\\Java\\jdk-11\\bin;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\windows\\System32\\OpenSSH\\;C:\\Program Files\\Java\\WebStart\\bin;C:\\Program Files (x86)\\Plantronics\\Spokes3G\\;C:\\Users\\ms980510\\AppData\\Local\\Microsoft\\WindowsApps;"
> library(mrgsolve)
> mod <- mread("pk2", modlib())
Building pk2 ... error.

---:: stderr ::---------------------------------------------
Warning message:
In system(cmd) : 'make' not found
------------------------------------------------------------
Error: the model build step failed.
> 
```
I also did `file.edit("~/.Renviron")` and typed the Rtools installation path. 
However I still get the "make" error (as seen above). Any help in this regard is much appreciated. Thank you so much!

**Comment by kylebaron** [comment]
@MeenakshiSrini - did you get the path set up correctly?

**Comment by kylebaron** [comment]
Hi @MeenakshiSrini   
There is a `$PRED` model in the internal library

```r
mod <- modlib("pred1")
see(mod)
param(mod)
```
 
as well as a vignette here:
https://mrgsolve.github.io/vignettes/dollar_pred.html

**Comment by MeenakshiSrini** [comment]
Hi @kylebaron thank you for the info. I get the error ```"Error: The model file pred1.cpp does not exist."``` when I try to run the pred1 example in the model library. It is probably because I currently have access only to an older version of mrgsolve (0.8.9) as opposed to the current version on CRAN (0.10.4) on our institutional server. I will try to find a work around where I use the latest version of mrgsolve to use the pred functionality. Thank you. I appreciate your help and support! :)

**Comment by kylebaron** [comment]
Ok.  I'd get on 0.10.4 asap.  The pred model is:

```
$PROB
An example model expressed in closed form
$PARAM B = -1, beta0 = 100, beta1 = 0.1
$OMEGA 2 0.3
$PRED
double beta0i = beta0 + ETA(1);
double beta1i = beta1*exp(ETA(2));
capture Y = beta0i + beta1i*B;
```
