### ISSUE TITLE
Error using filter_sims

### ISSUE THREAD

**Issue by dan-adi** [metrumresearchgroup/mrgsolve#762]
Hello, I am new to mrgsolve and R.
I used the 2 compartment model example to simulate some drug infusions.
Everything is ok, I get a nice graph with CP vs time, until I run : 
out %>% as.data.frame

I get the error : 
> out %>% as.data.frame
   Error in as.data.frame.default(.) : 
   cannot coerce class ‘"trellis"’ to a data.frame

And when I run : 
out %>% filter_sims(time == 4)
I get the error:
Error in dplyr::filter(.data@data, ...) : 
  trying to get slot "data" from an object (class "trellis") that is not an S4 object 

Here is the full code:
library(mrgsolve)
library(dplyr)

model <- mread("pk2cmt", modlib())
e1 <- ev(amt=20, time=0, cmt=2, rate=5)        #simulate 5mg/h for 4 h
e2 <- ev(amt=97.5, time=4, cmt=2, rate=7.5)    #simulate 7.5 mg/h for 13 h
e3 <- ev(amt=153, time=13, cmt=2, rate=9)      #simulate 9 mg/ h for 17 h
e4 <- ev(amt=50, time=17, cmt=2, rate=10)      #simulate 10mg mg/ h for 5 h
e5 <- ev(amt=195.5, time=5, cmt=2, rate=11.5)  #simulate 11.5 mg / h de 17 h
e <- seq(e1, e2, e3, e4, e5)

out <- model %>%
  param(CL=0.841,VC=3.1, VP=2.23, Q=4.67) %>% 
  ev(e) %>% 
  mrgsim(end = 24*3, delta = 0.1) %>%
  plot(CP~time)

> out

out %>% as.data.frame
out %>% filter_sims(time == 4)

**Comment by kylebaron** [comment]
It should be

```r
out <- model %>%
param(CL=0.841,VC=3.1, VP=2.23, Q=4.67) %>%
ev(e) %>%
mrgsim(end = 24*3, delta = 0.1) 
```

This will make `out` To be simulated data rather than a lattice plot.

**Comment by kylebaron** [comment]
Then all these should work

```r
out %>% plot
out %>% as.data.frame
out %>% filter_sims(time == 4)

```

**Comment by dan-adi** [comment]
It works! You are a lifesaver! 👍 
I only found out about mrgsolve last week, it is amazing. I can use it to teach my residents some pharmacokinetics

**Comment by kylebaron** [comment]
Great!  Please let me know if we can help with anything else to get you started.  Happy to help out and answer questions.
