### ISSUE TITLE
Remove spell check from drone file

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#764]
See #763

**Comment by kylebaron** [comment]
I don't know if this can / should still be in the CI code

```r
    run_r_expression(
      r_bin_var, 
      "spelling::spell_check_package()"
    ),
  ],
```
But I did remove it from `Suggests:` this time at the request of another reviewer.

**Comment by dpastoor** [comment]
don't see any reason to remove it, unless its been deemed not valid/causing too many false positives to be worth it
