### ISSUE TITLE
mrgsolve tick spacing plot

### ISSUE THREAD

**Issue by dan-adi** [metrumresearchgroup/mrgsolve#767]
Hello, 
Is there a way to change the ticks spacing on the mrgsolve plots? I can change titles and labels on x,y axes but not the ticks. I have been trying some examples from the web but not of them work.

Thank you, 
Have a nice day

**Comment by kylebaron** [comment]
Hi @dan-adi  - 

The plots are built using `lattice::xyplot`.  You can pass the `scales` argument to do some of that but it's not the intended use. 

If you need to customize plots to this point, I recommend switching to `ggplot2`.  This is what I do. 

``` r

library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter

mod <- house()

out <- mrgsim(mod, events = ev(amt = 100), end = 24)

plot(
  out, 
  CENT~time,
  scales = list(
    x = list(at = seq(0,24,1)), 
    y = list(at = c(0,50,100))
  )
)
```

![](https://i.imgur.com/7iNouVE.png)

``` r

library(tidyverse)
sims <- as_tibble(out)
ggplot(sims, aes(time,CENT)) + geom_line() + 
  scale_x_continuous(breaks = seq(0,24,1)) + 
  scale_y_continuous(breaks = c(0,50,100)) + 
  theme_bw()
```

![](https://i.imgur.com/Pyl0A3V.png)

<sup>Created on 2020-11-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dan-adi** [comment]
Thank you, it works. Is this a forum only for issues with mrgsolve or can I ask other questions about models?
