### ISSUE TITLE
`sim` key being loaded by default

### ISSUE THREAD

**Issue by vjd** [metrumresearchgroup/mrgsolve#79]
The latest development version released last night seems to keep throwing out an message everytime I type in the word `sim` in an R script or Rmarkdown. The following is the error -

```
Error in fetch(key) : 
  lazy-load database '/Users/vijay/rlibs/mrgsolve/help/mrgsolve.rdb' is corrupt
```
Has no implications on my work, but seems strange that everytime I type in `sim` for e.g. in `simulate` it throws this. Is this one of the snippets that is being loaded by default?

**Comment by kylebmetrum** [comment]
I think it has to do with the documentation?  Not sure.  I pushed a bunch of stuff to `dev` branch last night and discovered a problem with the way the house model was being build.  The   `Makefile` didn't pick up a change I implemented a while ago but it made no difference in function until I started messing around with it last night.  

Working on it now.

**Comment by kylebmetrum** [comment]
Let's see if this works: 53080a770f56697cef7345b72722432f687bb257

**Comment by vjd** [comment]
just re-installed the dev version and this is what I get when I load the package now

```
library(mrgsolve)
mrgsolve: Community Edition
www.github.com/metrumresearchgroup/mrgsolve

Attaching package: ‘mrgsolve’

The following object is masked from ‘package:magrittr’:

    mod

The following object is masked from ‘package:Hmisc’:

    label

Error in fetch(key) : 
  lazy-load database '/Users/vijay/rlibs/mrgsolve/help/mrgsolve.rdb' is corrupt
```

**Comment by kylebmetrum** [comment]
@vjd 

Clean install from github doesn't show any issues on my macbook; also, `R CMD CHECK` is working fine on laptop and on `travis-ci`. 

Can you try manually removing `/Users/vijay/rlibs/mrgsolve` and re-installing?

Also ... you're installing the `master` branch, right?



```r
.libPaths("~/Rtmp")
install.packages(c("dplyr", "RcppArmadillo","Rcpp", "BH"),type="source")
install.packages("devtools")
library(devtools)
install_github("metrumresearchgroup/mrgsolve", 
               subdir="rdev")
library(mrgsolve)

mrgsolve:::house() %>% mrgsim


> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     grDevices utils     datasets  graphics  methods   base     

other attached packages:
[1] mrgsolve_0.6.1.9015 devtools_1.12.0    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5               digest_0.6.9              dplyr_0.5.0              
 [4] withr_1.0.2               assertthat_0.1            R6_2.1.2                 
 [7] DBI_0.4-1                 git2r_0.15.0              magrittr_1.5             
[10] httr_1.2.1                lazyeval_0.2.0            curl_0.9.7               
[13] RcppArmadillo_0.7.100.3.1 tools_3.3.0               rsconnect_0.4.3          
[16] memoise_1.0.0             tibble_1.1        


```

**Comment by vjd** [comment]
Clean reinstall of mrgsolve after removing the folder from rlibs works. 

![image](https://cloud.githubusercontent.com/assets/1425562/16882475/2d1c4a5c-4a8d-11e6-9a8d-4fd7d8a6ada5.png)

Thank you for the rapid fix

**Comment by kylebmetrum** [comment]
Great.  Not sure how that file gets corrupted.  But I wonder if it was related to this:
https://github.com/metrumresearchgroup/mrgsolve/commit/feb225761b82a7dec22a97355b7e096549a1bfa9

Silent problem with the house model source.  I don't know what exactly is the link, but that was the only thing in play recently that comes close.

**Comment by kylebmetrum** [comment]
I'm going to keep this open for a  bit in case this was an issue for others.
