### ISSUE TITLE
Rstudio code completion

### ISSUE THREAD

**Issue by FelicienLL** [metrumresearchgroup/mrgsolve#797]
Hello, 
Just reporting a minor trouble I've been facing for a long time. Not sure if directly related to mrgsolve _per se_ or to Rstudio instead, but I'm still posting it for information.
As you know Rstudio enables [auto-completion](https://support.rstudio.com/hc/en-us/articles/205273297-Code-Completion) and can suggest arguments to pass to functions. I noticed that it does not work when functions are used inside a `%>%` pipe that begins with a mrgmod object. A box with the text "R code execution error" appears and the console return an error message. The code executes perfectly though.

![completion](https://user-images.githubusercontent.com/68648517/109015928-eb134980-76b5-11eb-9966-f51e1066cb66.png)

Interestingly, completion works : 
- when functions are used out of a pipe,
- with the `house()` model, 
- when the model is wrapped inside the `loadso()` function.

This probably tells about where the problem can come from.

![completion works](https://user-images.githubusercontent.com/68648517/109017085-23675780-76b7-11eb-8cfc-5da661c4cddb.png)

Thank you
Félicien

My environment: Windows 10, Rstudio 1.3.1073 (desktop).
``` r
library(mrgsolve)
#> 
#> Attachement du package : 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter
packageVersion("mrgsolve")
#> [1] '0.10.8.9000'

mod <- modlib("irm1") #Whatever the model
#Completion does not work : 
mod %>% 
  Req()

#Completion works : 
Req(mod, )

house() %>% 
  Req()

loadso(mod) %>% 
  Req()
```

<sup>Created on 2021-02-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kylebaron** [comment]
Sorry for the delay on this. I don't use the completion a lot but happy to help look into this.

There is a `[[` method for the model object that is getting called when you tab:

https://github.com/metrumresearchgroup/mrgsolve/blob/develop/R/class_mrgmod.R#L568-L582

That's where the errors are coming from.  I'm not sure why that is getting called here or if I'm doing something wrong in that method.  

More to come.

**Comment by FelicienLL** [comment]
Hello Kyle, 
I think I've got something

Completion seems to call a function `.rs.getRChainCompletions` that extracts the `names` of the mrgmod object, and store them into a `completions` variable. Afterwards, it evaluates the type of each element with `.rs.getCompletionType`, within a `vapply()` where every element is evaluated one by one by executing `object[[i]]`, `i` being the ith element of the `completions` variable.

![image](https://user-images.githubusercontent.com/68648517/125101863-f736fb00-e0da-11eb-8ca6-88f15f85efef.png)

If I do this by myself, here is what we got : 
``` r
code <- "
$PARAM CL = 3, V = 100
$CMT CENTRAL
$TABLE double CP = CENTRAL/V ;
$PKMODEL ncmt = 1
$CAPTURE CP;
"
mod <- mrgsolve::mcode("mod", code)
#> Building mod ... done.

completions <- names(mod)
completions
#> $param
#> [1] "CL" "V" 
#> 
#> $init
#> [1] "CENTRAL"
#> 
#> $capture
#> [1] "CP"
#> 
#> $omega
#> character(0)
#> 
#> $sigma
#> character(0)
#> 
#> $omega_labels
#> named list()
#> 
#> $sigma_labels
#> named list()
mod[[completions[[1]]]]
#> Warning in if (i %in% Pars(x)) {: la condition a une longueur > 1 et seul le
#> premier élément est utilisé
#> [1]   3 100
mod[[completions[[2]]]]
#> [1] 0
mod[[completions[[3]]]]
#> Error: item 'CP' not found or not extractable with $ or [[ operator.
mod[[completions[[4]]]]
#> Error in if (i %in% Pars(x)) {: l'argument est de longueur nulle
```

<sup>Created on 2021-07-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

So, the way I understand it, it comes from the fact R expects that every named element of an object can be extracted using `[[`, like for a data.frame or a list, while it is not the case with an mrgmod object because it was made to return parameters instead (which I agree is pretty useful). I guess that if `[[` did not return an error when the element is not matched, it would be compatible with completion - and maybe with other R behaviours generally speaking ? Could I suggest to silently return `NULL` instead, just like with any R object ?
``` r
list(FOO = 1)[['BAR']]
#> NULL
```
Additional suggestion: could the length of `i` be taken into account in the if statement, in order to avoid error and warning whether length is 0 or higher than 1 ? 

Thanks in advance for your consideration. 
Again, I'm just reporting because I was curious of this bug, but I don't want to be like I was requesting something. I appreciate the job that you made; and having mrgsolve free, open-source and well-maintained like this is awesome.

Thanks again,
Félicien

**Comment by kylebaron** [comment]
Yeah; we should definitely be able to do that. Both the `[[` and `$` operators extract parameters (plus some extra stuff) but IMO we could refactor `[[` so it works the way Rstudio et al. are expecting. I need to read your message more carefully but I think we should be able to do something here that is agreeable.

**Comment by kylebaron** [comment]
Just following up on this: 

yeah, it really comes down to the fact that `names(mod)` returns something non-standard:

```r
> names(house())
$param
 [1] "CL"    "VC"    "KA"    "F1"    "D1"    "WT"    "SEX"   "WTCL"  "WTVC"  "SEXCL" "SEXVC"
[12] "KIN"   "KOUT"  "IC50" 

$init
[1] "GUT"  "CENT" "RESP"

$capture
[1] "DV" "CP"

$omega
[1] "..."

$sigma
[1] "..."

$omega_labels
$omega_labels[[1]]
[1] "ECL"   "EVC"   "EKA"   "EKOUT"


$sigma_labels
$sigma_labels[[1]]
[1] "EXPO"
```

And the reason why we're getting the length problem is because it's trying to pass a list into `[[`. But it seems unlikely that every S4 object is going to have `[[` defined that will return slot information (usually only accessible through methods API functions or `@`  - like `mod@param`). 

I can definitely / easily write some defensive code to return `NUL` if something non-atomic is passed to `[[` or if it doesn't match any valid name.  When I do that this is what you get:

Before tab: 
```r
mod <- house()
mod %>% mrgsim(
```
after tab:

```r
mod <- house()
mod %>% mrgsim(mod
```

This all just makes me think something else isn't right here - could be on my end or on what Rstudio is assuming. What do you think?

**Comment by FelicienLL** [comment]
You're right, there is something else. The fact that completion works with 
```r
house() %>% mrgsim(
```
but not 
```r
ho <- house()
ho %>% mrgsim(
```
also says that it's just not a problem with `[[`... I guess there is something about how this S4 object is handled with completion-related functions... Never mind, it's probably not a big deal if completion does not work - in the sense of providing arguments etc... However, I still think it could be of interest to re-code with the `NULL` output, so that no more errors and warnings get printed in the console if the user press tab (or instantly if completion is set to automatic in global options). What do you think ?

Félicien

**Comment by kylebaron** [comment]
Closing as this seems to have nothing to do with mrgsolve. I don't know if it's Rstudio or magrittr or both. If there's something improperly implemented in mrgsolve, let's get that identified first and re-open if needed.

**Comment by FelicienLL** [comment]
FYI this should be picked up in a forthcoming version of RStudio. https://github.com/rstudio/rstudio/pull/12301

**Comment by kylebaron** [comment]
Great! Thanks for reporting back on this.
