### ISSUE TITLE
Incompatible model types?

### ISSUE THREAD

**Issue by mct941** [metrumresearchgroup/mrgsolve#8]
Just running the included example under 3. Getting Started.
**mrgsolve_example("pkpd")**
**cat(readLines("pkpdExample.cpp"), sep="\n")**
**mod <- mread("pkpdExample")**
Compiling pkpdExample.cpp.cpp ... g++ -m64 -I"C:/Users/mtsai/DOCUME~1/R/R-32~1.0/include" -DNDEBUG     -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c C:/Users/mtsai/Documents/pkpdExample.cpp.cpp -o C:/Users/mtsai/Documents/pkpdExample.cpp.o
g++ -m64 -shared -s -static-libgcc -o C:/Users/mtsai/AppData/Local/Temp/RtmpqOPLjw/pkpdExample19cc30a7425c.dll tmp.def C:/Users/mtsai/Documents/pkpdExample.cpp.o -Ld:/RCompile/r-compiling/local/local320/lib/x64 -Ld:/RCompile/r-compiling/local/local320/lib -LC:/Users/mtsai/DOCUME~1/R/R-32~1.0/bin/x64 -lR
done.
Loading: pkpdExample19cc30a7425c.dll
> **out <- mod %>% init(GUT=1000) %>% mrgsim(delta=0.1,end=168)**
Error: not compatible with requested type
>

Mine say that it is loading *.dll, but the example loads a *.so file.    
Also, I'm not sure if it is related.  But I'm not able to visualize the generated mod object when I enter "mod" from the command prompt after compiling the model.

**Comment by kylebmetrum** [comment]
On windows, the shared object will be `.dll` whereas on unix type systems it will be `.so`.

The error means that the `C++` was expecting data of a certain type, but it wasn't that type ... probably something was null.

Run this:
`mod %>% mrgsim(capture="foo.txt")`

You will / should see the file "foo.txt" in the project directory.  Can you attach that here?

Also, what is the output of `sessionInfo()`?

**Comment by kylebmetrum** [comment]
The foo.txt looks like this: [foo.txt](https://github.com/metrumresearchgroup/mrgsolve/files/155850/foo.txt)

**Comment by kylebmetrum** [comment]
Output from my Windows AMI  .... let's start checking against this.

[foo.txt](https://github.com/metrumresearchgroup/mrgsolve/files/155872/foo.txt)

    > .libPaths("c:/lib")

    > library(mrgsolve)

    R shared object builder: 3.2.3 (r69752)


    Copyright (C) 2000-2013 The R Core Team.

    This is free software; see the GNU General Public License version 2

    or later for copying conditions.  There is NO warranty.

    > mrgsolve_example("pkpdExample")

    Copying pkpdExample.cpp to C:/Users/MetrumRG/Documents

    Use mread() to load and compile.

    > mod <- mread("pkpdExample")

    Compiling pkpdExample.cpp.cpp ... g++ -m64 -shared -s -static-libgcc -o 
    C:/Users/MetrumRG/AppData/Local/Temp/2/RtmpofqvMc/pkpdExample4fc22d3496b.dll tmp.def 
    C:/Users/MetrumRG/Documents/pkpdExample.cpp.o -Ld:/RCompile/r-compiling/local/local323/lib/x64 -Ld:/RCompile/r-compiling/local/local323/lib -LC:/PROGRA~1/R/R-32~1.3/bin/x64 -lR

    done.

    Loading: pkpdExample4fc22d3496b.dll

    > mod %>% mrgsim(capture="foo.txt")

    Model:  pkpdExample.cpp 

    Date:   Wed Mar 02 23:05:56 2016 

    Dim:    97 x 6 

    Time:   0 to 24 

    ID:     1 

         ID time GUT CENT RESP CP

    [1,]  1 0.00   0    0   50  0

    [2,]  1 0.25   0    0   50  0

    [3,]  1 0.50   0    0   50  0

    [4,]  1 0.75   0    0   50  0

    [5,]  1 1.00   0    0   50  0

    [showing 4 significant digits]

    > 

    > sessionInfo()

    R version 3.2.3 (2015-12-10)

    Platform: x86_64-w64-mingw32/x64 (64-bit)

    Running under: Windows Server 2008 R2 x64 (build 7601) Service Pack 1


    locale:

    [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   

    [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          

    [5] LC_TIME=English_United States.1252    


    attached base packages:

    [1] stats     graphics  grDevices utils     datasets  methods   base     


    other attached packages:

    [1] mrgsolve_0.5.008


    loaded via a namespace (and not attached):

    [1] lazyeval_0.1.10 magrittr_1.5    R6_2.1.2        assertthat_0.1  parallel_3.2.3 

    [6] DBI_0.3.1       tools_3.2.3     dpl

I can also see this when I run `getLoadedDLLs()`

`pkpdExample4fc22d3496b C:/Users/MetrumRG/AppData/Local/Temp/2/RtmpofqvMc/pkpdExample4fc22d3496b.dll`

Do you see something like this ?

**Comment by mct941** [comment]
This was also not compatible.

> mod %>% mrgsim(capture="foo.txt")
Error: not compatible with requested type

R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] BH_1.60.0-1               RcppArmadillo_0.6.500.4.0 Rcpp_0.12.3               gridExtra_2.2.1           readr_0.2.2              
 [6] lubridate_1.5.0           rdrop2_0.7.0              lazyeval_0.1.10           shinyBS_0.61              readxl_0.1.0             
[11] tidyr_0.4.1               stringr_1.0.0             GGally_1.0.1              dplyr_0.4.3               plyr_1.8.3               
[16] shiny_0.13.1              magrittr_1.5              gtools_3.5.0              ggplot2_2.1.0             mrgsolve_0.5.11          

loaded via a namespace (and not attached):
 [1] munsell_0.4.3    colorspace_1.2-6 xtable_1.8-2     R6_2.1.2         httr_1.1.0       tools_3.2.0      parallel_3.2.0   gtable_0.2.0    
 [9] DBI_0.3.1        htmltools_0.3    assertthat_0.1   digest_0.6.9     mime_0.4         stringi_1.0-1    scales_0.4.0     reshape_0.8.5   
[17] httpuv_1.3.3    
> 

The last DLL looks similar to yours.
> getLoadedDLLs()
                                                                                                   Filename Dynamic.Lookup
base                                                                                                   base          FALSE
utils                                   C:/Users/mtsai/Documents/R/R-3.2.0/library/utils/libs/x64/utils.dll          FALSE
methods                             C:/Users/mtsai/Documents/R/R-3.2.0/library/methods/libs/x64/methods.dll          FALSE
grDevices                       C:/Users/mtsai/Documents/R/R-3.2.0/library/grDevices/libs/x64/grDevices.dll          FALSE
graphics                          C:/Users/mtsai/Documents/R/R-3.2.0/library/graphics/libs/x64/graphics.dll          FALSE
stats                                   C:/Users/mtsai/Documents/R/R-3.2.0/library/stats/libs/x64/stats.dll          FALSE
tools                                   C:/Users/mtsai/Documents/R/R-3.2.0/library/tools/libs/x64/tools.dll          FALSE
internet                                        C:/Users/mtsai/DOCUME~1/R/R-32~1.0/modules/x64/internet.dll           TRUE
(embedding)                                                                                     (embedding)          FALSE
Rcpp                                      C:/Users/mtsai/Documents/R/R-3.2.0/library/Rcpp/libs/x64/Rcpp.dll           TRUE
parallel                          C:/Users/mtsai/Documents/R/R-3.2.0/library/parallel/libs/x64/parallel.dll          FALSE
dplyr                                   C:/Users/mtsai/Documents/R/R-3.2.0/library/dplyr/libs/x64/dplyr.dll           TRUE
lazyeval                          C:/Users/mtsai/Documents/R/R-3.2.0/library/lazyeval/libs/x64/lazyeval.dll           TRUE
mrgsolve                          C:/Users/mtsai/Documents/R/R-3.2.0/library/mrgsolve/libs/x64/mrgsolve.dll           TRUE
grid                                      C:/Users/mtsai/Documents/R/R-3.2.0/library/grid/libs/x64/grid.dll          FALSE
colorspace                    C:/Users/mtsai/Documents/R/R-3.2.0/library/colorspace/libs/x64/colorspace.dll           TRUE
plyr                                      C:/Users/mtsai/Documents/R/R-3.2.0/library/plyr/libs/x64/plyr.dll           TRUE
scales                                C:/Users/mtsai/Documents/R/R-3.2.0/library/scales/libs/x64/scales.dll           TRUE
gtools                                C:/Users/mtsai/Documents/R/R-3.2.0/library/gtools/libs/x64/gtools.dll           TRUE
digest                                C:/Users/mtsai/Documents/R/R-3.2.0/library/digest/libs/x64/digest.dll           TRUE
httpuv                                C:/Users/mtsai/Documents/R/R-3.2.0/library/httpuv/libs/x64/httpuv.dll           TRUE
mime                                      C:/Users/mtsai/Documents/R/R-3.2.0/library/mime/libs/x64/mime.dll           TRUE
stringi                             C:/Users/mtsai/Documents/R/R-3.2.0/library/stringi/libs/x64/stringi.dll           TRUE
tidyr                                   C:/Users/mtsai/Documents/R/R-3.2.0/library/tidyr/libs/x64/tidyr.dll           TRUE
readxl                                C:/Users/mtsai/Documents/R/R-3.2.0/library/readxl/libs/x64/readxl.dll           TRUE
lubridate                       C:/Users/mtsai/Documents/R/R-3.2.0/library/lubridate/libs/x64/lubridate.dll           TRUE
readr                                   C:/Users/mtsai/Documents/R/R-3.2.0/library/readr/libs/x64/readr.dll           TRUE
RcppArmadillo           C:/Users/mtsai/Documents/R/R-3.2.0/library/RcppArmadillo/libs/x64/RcppArmadillo.dll           TRUE
gallery119cc13113754                  C:/Users/mtsai/AppData/Local/Temp/RtmpqOPLjw/gallery119cc13113754.dll           TRUE
pkpdExample19cc7086433c            C:/Users/mtsai/AppData/Local/Temp/RtmpqOPLjw/pkpdExample19cc7086433c.dll           TRUE

**Comment by kylebmetrum** [comment]
I was expecting the same error.  Did `foo.txt` get generated?

I guess you'll get the same error with `init(mod)` or `mrgsolve:::touch_funs(mod)`?

What is the output of this:
````r
init(mod)
mod@init
mod@param
mrgsolve:::touch_funs(mod) ## might generate the error too
mrgsolve:::model_symbols(mod)

x <- mrgsolve:::model_symbols(mod)

x
is.loaded(as.character(x[1,1]), as.character(x[1,2]))
````

**Comment by kylebmetrum** [comment]
Two more requests:

1. Post the `pkpdExample.cpp` file that you were compiling
2. Restart your R session, load __only__ `mrgsolve`, and try compiling and running the model;  make **absolutely** sure that no other packages (except base packages) are loaded.

**Comment by mct941** [comment]
No foo.txt

Here is the output you requested.

Error: attempt to apply non-function
> mod@init
Error: attempt to apply non-function
> mod@param
Error: attempt to apply non-function
> mrgsolve:::touch_funs(mod) ## might generate the error too
$tnames
[1] "CP"

$init
 GUT CENT RESP 
   0    0   50 

$npar
[1] 6

$neq
[1] 3

> mrgsolve:::model_symbols(mod)
                      symbol                 PACKAGE
1  _model_pkpdExample_main__ pkpdExample19cc7086433c
2   _model_pkpdExample_ode__ pkpdExample19cc7086433c
3 _model_pkpdExample_table__ pkpdExample19cc7086433c
> 
> x <- mrgsolve:::model_symbols(mod)
> 
> x
                      symbol                 PACKAGE
1  _model_pkpdExample_main__ pkpdExample19cc7086433c
2   _model_pkpdExample_ode__ pkpdExample19cc7086433c
3 _model_pkpdExample_table__ pkpdExample19cc7086433c
> is.loaded(as.character(x[1,1]), as.character(x[1,2]))
[1] TRUE

**Comment by mct941** [comment]
Here is the pkpdExample.cpp

$PARAM
KA = 1.2, CL = 1, VC = 25
KIN = 100, KOUT = 2, EC50 = 4

$CMT GUT CENT RESP

$SET delta= 0.25

$MAIN
RESP_0 = KIN/KOUT;

$ODE
dxdt_GUT = -KA*GUT;
dxdt_CENT = KA*GUT - (CL/VC)*CENT;

double CP = CENT/VC;
double INH = CP/(EC50+CP);

dxdt_RESP = KIN*(1-INH) - RESP*KOUT;

$CAPTURE CP


Here is the new R session with only Rccp,RccpArmadillo,BH,dplyr packages loaded

**mrgsolve_example("pkpd",overwrite=T)**
Copying pkpdExample.cpp to C:/Users/mtsai/Documents
Use mread() to load and compile.
**mod <- mread("pkpdExample")**
Compiling pkpdExample.cpp.cpp ... g++ -m64 -shared -s -static-libgcc -o C:/Users/mtsai/AppData/Local/Temp/RtmpQ9I2xt/pkpdExample189811a33164.dll tmp.def C:/Users/mtsai/Documents/pkpdExample.cpp.o -Ld:/RCompile/r-compiling/local/local320/lib/x64 -Ld:/RCompile/r-compiling/local/local320/lib -LC:/Users/mtsai/DOCUME~1/R/R-32~1.0/bin/x64 -lR
done.
Loading: pkpdExample189811a33164.dll
**out <- mod %>% init(GUT=1000) %>% mrgsim(delta=0.1,end=168)**
Error: not compatible with requested type
**out**
Error: attempt to apply non-function

**Comment by kylebmetrum** [comment]
Thanks for your patience.  This is in way better shape than I was thinking:

1. The model compiles and loads; R can find the model functions
1.  Since foo.txt was not generated, that means the simulation never started (we never got to the bulk of the C++ code). 

Would you show me more:
````r
mod <- mread("pkpdExample")

str(mod)

mod@init@data

mod@param@data

init(mod) ## hopefully this fails

traceback() ## See what happened

mod@param ## fails?
traceback()

mod@init ## fails?
traceback()



````






Just curious if this `gallery1` model had the same problem?
`gallery119cc13113754 C:/Users/mtsai/AppData/Local/Temp/RtmpqOPLjw/gallery119cc13113754.dll TRUE`

**Comment by mct941** [comment]
Yes, same issue with gallery1 model.  Sorry, I can't do much to troubleshoot this on my own...hopefully in time.  

**mod <- mread("pkpdExample")**
Compiling pkpdExample.cpp.cpp ... g++ -m64 -shared -s -static-libgcc -o C:/Users/mtsai/AppData/Local/Temp/RtmpWKJnIH/pkpdExample1f4c4ef73ed4.dll tmp.def C:/Users/mtsai/Documents/pkpdExample.cpp.o -Ld:/RCompile/r-compiling/local/local320/lib/x64 -Ld:/RCompile/r-compiling/local/local320/lib -LC:/Users/mtsai/DOCUME~1/R/R-32~1.0/bin/x64 -lR
done.
Loading: pkpdExample1f4c4ef73ed4.dll
 
**str(mod)**
Formal class 'mrgmod' [package "mrgsolve"] with 34 slots
  ..@ model    : chr "pkpdExample"
  ..@ package  : chr "pkpdExample1f4c4ef73ed4"
  ..@ soloc    : chr "C:/Users/mtsai/AppData/Local/Temp/RtmpWKJnIH"
  ..@ project  : chr "C:/Users/mtsai/Documents"
  ..@ start    : num 0
  ..@ end      : num 24
  ..@ delta    : num 0.25
  ..@ add      : num(0) 
  ..@ tscale   : num 1
  ..@ digits   : num -1
  ..@ quiet    : logi FALSE
  ..@ verbose  : logi FALSE
  ..@ debug    : logi FALSE
  ..@ preclean : logi FALSE
  ..@ atol     : num 1e-08
  ..@ rtol     : num 1e-08
  ..@ maxsteps : num 2000
  ..@ hmin     : num 0
  ..@ hmax     : num 0
  ..@ ixpr     : num 0
  ..@ mxhnil   : num 0
  ..@ shlib    :List of 6
  .. ..$ date    : chr "03/02 23:19"
  .. ..$ compiled: logi TRUE
  .. ..$ cmt     : chr [1:3] "GUT" "CENT" "RESP"
  .. ..$ par     : chr [1:6] "KA" "CL" "VC" "KIN" ...
  .. ..$ npar    : int 6
  .. ..$ ncmt    : int 3
  ..@ func     : chr [1:2] "_model_pkpdExample_ode__" "pkpdExample1f4c4ef73ed4"
  ..@ init_fun : chr [1:2] "_model_pkpdExample_main__" "pkpdExample1f4c4ef73ed4"
  ..@ table_fun: chr [1:2] "_model_pkpdExample_table__" "pkpdExample1f4c4ef73ed4"
  ..@ omega    :Formal class 'omegalist' [package "mrgsolve"] with 2 slots
  .. .. ..@ data: Named list()
  .. .. ..@ n   : num 0
  ..@ sigma    :Formal class 'sigmalist' [package "mrgsolve"] with 2 slots
  .. .. ..@ data: Named list()
  .. .. ..@ n   : num 0
  ..@ events   :Formal class 'ev' [package "mrgsolve"] with 1 slot
  .. .. ..@ data:'data.frame':	0 obs. of  0 variables
Formal class 'data.frame' [package "methods"] with 4 slots
  .. .. .. .. ..@ .Data    : list()
  .. .. .. .. ..@ names    : chr(0) 
  .. .. .. .. ..@ row.names: int(0) 
  .. .. .. .. ..@ .S3Class : chr "data.frame"
  ..@ request  : chr "(all)"
  ..@ param    :Formal class 'parameter_list' [package "mrgsolve"] with 2 slots
  .. .. ..@ data   :List of 6
  .. .. .. ..$ KA  : num 1.2
  .. .. .. ..$ CL  : num 1
  .. .. .. ..$ VC  : num 25
  .. .. .. ..$ KIN : num 100
  .. .. .. ..$ KOUT: num 2
  .. .. .. ..$ EC50: num 4
  .. .. ..@ pattern: chr "*"
  ..@ init     :Formal class 'cmt_list' [package "mrgsolve"] with 2 slots
  .. .. ..@ data   :List of 3
  .. .. .. ..$ GUT : num 0
  .. .. .. ..$ CENT: num 0
  .. .. .. ..$ RESP: num 0
  .. .. ..@ pattern: chr "*"
  ..@ args     : list()
  ..@ fixed    : list()
  ..@ advan    : num 13
 
**mod@init@data**
$GUT
[1] 0

$CENT
[1] 0

$RESP
[1] 0


**mod@param@data**
$KA
[1] 1.2

$CL
[1] 1

$VC
[1] 25

$KIN
[1] 100

$KOUT
[1] 2

$EC50
[1] 4

 
**init(mod)** ## hopefully this fails
Error: attempt to apply non-function
 
**traceback()** ## See what happened
No traceback available 
 
**mod@param** ## fails?
Error: attempt to apply non-function
**traceback()**
No traceback available 
 
**mod@init** ## fails?
Error: attempt to apply non-function
**traceback()**
No traceback available

**Comment by kylebmetrum** [comment]
One more then done (for now):

````r
param(mod)
````

**Comment by mct941** [comment]
Same thing.
> param(mod)
Error: attempt to apply non-function

**Comment by kylebmetrum** [comment]
Thanks.  That last one was really helpful: there isn't (shouldn't be) anything controversial about `param(mod)`.  The model object (`mod`) seems to be well formed and the parameter list (`mod@param@data`) is fine.   `param(mod)` is pure `R` code calling an `S4` method.  `init(mod)` on the other hand was going into some of the `C++` code (it calls `touch_funs` ... which seemed to work fine).  That'll give us a place to focus this afternoon.

**Comment by kylebmetrum** [comment]
@mct941   @dpastoor


Here is a complete / fresh install of all dependencies on Windows system, including setting the path.

Notice that __only__ required directories are included in the path (chopping off everything else).

This example uses `Rtools32.exe` (with a check in there to make sure) and R-3.2.3 (see `sessionInfo` below).

The relevant output is included in a subsequent listing.

````r
.libPaths("c:/Rlibs")
Sys.setenv(R_LIBS="c:/Rlibs")
path <- "C:\\Program Files\\R\\R-3.2.3\\bin\\x64;c:\\Rtools32\\bin;c:\\Rtools32\\gcc-4.6.3\\bin;"
Sys.setenv(PATH=path)
Sys.getenv("PATH")

mrgs <- "https://github.com/metrumresearchgroup/mrgsolve/releases/download/v0.5.11/mrgsolve_0.5.11.tar.gz"



if(FALSE) {
  
  unlink("c:/Rlibs",recursive=TRUE)
  dir.create("c:/Rlibs")
  
  install.packages(c("dplyr", "Rcpp", "RcppArmadillo", "BH"),
                   type="source",
                   INSTALL_opts = "--no-multiarch")
  
  install.packages(mrgs, type="source", repos=NULL,
                   INSTALL_opts = "--no-multiarch")
                   
}

list.files("c:/Rtools32/")
readLines("c:/Rtools32/VERSION.txt")

library(mrgsolve)

mrgsolve_example("pkpd",overwrite=TRUE)

mod <- mread("pkpdExample")

mod %>% init(GUT=100) %>% mrgsim
````



Here is the complete output (not including the install piece

````r
Restarting R session...

> .libPaths("c:/Rlibs")
> Sys.setenv(R_LIBS="c:/Rlibs")
> path <- "C:\\Program Files\\R\\R-3.2.3\\bin\\x64;c:\\Rtools32\\bin;c:\\Rtools32\\gcc-4.6.3\\bin;"
> Sys.setenv(PATH=path)
> Sys.getenv("PATH")
[1] "C:\\Program Files\\R\\R-3.2.3\\bin\\x64;c:\\Rtools32\\bin;c:\\Rtools32\\gcc-4.6.3\\bin;"
> 
> mrgs <- "https://github.com/metrumresearchgroup/mrgsolve/releases/download/v0.5.11/mrgsolve_0.5.11.tar.gz"
> 
> 
> 
> if(FALSE) {
+   
+   unlink("c:/Rlibs",recursive=TRUE)
+   dir.create("c:/Rlibs")
+   
+   install.packages(c("dplyr", "Rcpp", "RcppArmadillo", "BH"),
+                    type="source",
+                    INSTALL_opts = "--no-multiarch")
+   
+   install.packages(mrgs, type="source", repos=NULL,
+                    INSTALL_opts = "--no-multiarch")
+                    
+ }
> 
> list.files("c:/Rtools32/")
[1] "bin"          "COPYING"     
[3] "gcc-4.6.3"    "README.txt"  
[5] "Rtools.txt"   "texinfo5"    
[7] "unins000.dat" "unins000.exe"
[9] "VERSION.txt" 
> readLines("c:/Rtools32/VERSION.txt")
[1] "Rtools version 3.2.0.1948"
> 
> library(mrgsolve)
R shared object builder: 3.2.3 (r69752)

Copyright (C) 2000-2013 The R Core Team.
This is free software; see the GNU General Public License version 2
or later for copying conditions.  There is NO warranty.
> 
> mrgsolve_example("pkpd",overwrite=TRUE)
Copying pkpdExample.cpp to C:/script
Use mread() to load and compile.
> 
> mod <- mread("pkpdExample")
Compiling pkpdExample.cpp.cpp ... g++ -m64 -I"C:/PROGRA~1/R/R-32~1.3/include" -DNDEBUG     -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -mtune=core2 -c C:/script/pkpdExample.cpp.cpp -o C:/script/pkpdExample.cpp.o
g++ -m64 -shared -s -static-libgcc -o C:/Users/MetrumRG/AppData/Local/Temp/2/Rtmp6LRj3h/pkpdExample8243b1421ec.dll tmp.def C:/script/pkpdExample.cpp.o -Ld:/RCompile/r-compiling/local/local323/lib/x64 -Ld:/RCompile/r-compiling/local/local323/lib -LC:/PROGRA~1/R/R-32~1.3/bin/x64 -lR
done.
Loading: pkpdExample8243b1421ec.dll
> 
> mod %>% init(GUT=100) %>% mrgsim
Model:  pkpdExample.cpp 
Date:   Fri Mar 04 04:20:14 2016 
Dim:    97 x 6 
Time:   0 to 24 
ID:     1 
     ID time    GUT  CENT  RESP    CP
[1,]  1 0.00 100.00  0.00 50.00 0.000
[2,]  1 0.25  74.08 25.78 47.56 1.031
[3,]  1 0.50  54.88 44.63 43.29 1.785
[4,]  1 0.75  40.66 58.33 39.17 2.333
[5,]  1 1.00  30.12 68.23 35.76 2.729
[showing 4 significant digits]
> 

````


`sessionInfo` output

````r
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2008 R2 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

other attached packages:
[1] mrgsolve_0.5.11

loaded via a namespace (and not attached):
[1] lazyeval_0.1.10 magrittr_1.5   
[3] R6_2.1.2        assertthat_0.1 
[5] parallel_3.2.3  DBI_0.3.1      
[7] tools_3.2.3     dplyr_0.4.3    
[9] Rcpp_0.12.3 
````

**Comment by kylebmetrum** [comment]
@mct941 

One more request to see output:

I'm getting this from the `save.RData` you sent today

````r
$deriv
<pointer: 0x0>
attr(,"class")
[1] "NativeSymbol"

$table
<pointer: 0x0>
attr(,"class")
[1] "NativeSymbol"

$init
<pointer: 0x0>
attr(,"class")
[1] "NativeSymbol"
````

I'm guessing these are saying `0x0` because you can't just pass that stuff around to different computers.  But could you check for me?

Here's how

````r
mod <- mread("pkpdExample")

mrgsolve:::init_function_pointer(mod)
mrgsolve:::ode_function_pointer(mod)
mrgsolve:::table_function_pointer(mod)

````
 Output should look like this:

````r
> mrgsolve:::init_function_pointer(mod)
<pointer: 0x1020fdf50>
attr(,"class")
[1] "NativeSymbol"
> mrgsolve:::ode_function_pointer(mod)
<pointer: 0x1020fdf80>
attr(,"class")
[1] "NativeSymbol"
> mrgsolve:::table_function_pointer(mod)
<pointer: 0x1020fdf90>
attr(,"class")
[1] "NativeSymbol"

````

**Comment by mct941** [comment]
Looks okay.

> mrgsolve:::init_function_pointer(mod)
<pointer: 0x000000006c5014c0>
attr(,"class")
[1] "NativeSymbol"
> mrgsolve:::ode_function_pointer(mod)
<pointer: 0x000000006c5014e0>
attr(,"class")
[1] "NativeSymbol"
> mrgsolve:::table_function_pointer(mod)
<pointer: 0x000000006c501580>
attr(,"class")
[1] "NativeSymbol"

**Comment by kylebmetrum** [comment]
Any news on this?

**Comment by mct941** [comment]
Hi Kyle,
Sorry for the delay.  My computer completely crashed.  IT provided me with a new one, but it appears to be less restricted.  RTools had no issues with installation, so the rest of the install was fine.

**Comment by kylebmetrum** [comment]
It was a sick computer.
