### ISSUE TITLE
Question about time-varying covariate on dosing parameter (like D1)

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#808]
Time-varying covariates on dosing items (like infusion duration); this appears to be in conflict with nonmem output. 

``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

code <- '

$PARAM D1I = 1, KA = 0.001, CL = 1, V = 10
$MAIN D_GUT = D1I;
$PKMODEL cmt = "GUT CENT", depot = TRUE
'

mod <- mcode("dur", code)
#> Building dur ...
#> done.

data <- expand.ev(time = 1, cmt = 1, rate = -2, amt = 100)
data <- expand_observations(data, times = seq(0, 4, 0.1), unique = TRUE)
data1 <- mutate(data, D1I = ifelse(time >= 1, 1, 2))
data2 <- mutate(data, D1I = ifelse(time > 1, 1, 2))
```

# One hour infusion

``` r
mrgsim(mod, data = data1) %>% plot(type = 'b')
```

![](https://i.imgur.com/dnh4Ycy.png)

``` r
filter(data1, time < 1.2, time > 0.8)
#>   ID time amt rate cmt evid D1I
#> 1  1  0.9   0    0   0    0   2
#> 2  1  1.0 100   -2   1    1   1
#> 3  1  1.1   0    0   0    0   1
```

# Two hour infusion

Should this be a one hour infusion or a 2 hour infusion?

``` r
mrgsim(mod, data = data2) %>% plot(type = 'b')
```

![](https://i.imgur.com/8Mu6bDR.png)

``` r
filter(data2, time < 1.2, time > 0.8)
#>   ID time amt rate cmt evid D1I
#> 1  1  0.9   0    0   0    0   2
#> 2  1  1.0 100   -2   1    1   2
#> 3  1  1.1   0    0   0    0   1
```

<sup>Created on 2021-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kylebaron** [comment]
This is something equivalent, but with bioavailability; we've had this set up so that the dose appears as 50 mg on the dosing record. 

``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
mod <- house()
data <- expand.ev(amt = 100, time = 2)
data <- expand_observations(data, times = seq(0,6,1), unique = TRUE)
data <- mutate(data, F1 = ifelse(time >= 2, 0.5, 1))
mrgsim(mod,data, delta = 1, recsort = 3)
#> Model:  housemodel 
#> Dim:    7 x 7 
#> Time:   0 to 6 
#> ID:     1 
#>     ID time     GUT  CENT  RESP    DV    CP
#> 1:   1    0  0.0000  0.00 50.00 0.000 0.000
#> 2:   1    1  0.0000  0.00 50.00 0.000 0.000
#> 3:   1    2 50.0000  0.00 50.00 0.000 0.000
#> 4:   1    3 15.0597 33.91 45.17 1.696 1.696
#> 5:   1    4  4.5359 42.48 42.07 2.124 2.124
#> 6:   1    5  1.3662 43.48 41.22 2.174 2.174
#> 7:   1    6  0.4115 42.29 41.19 2.114 2.114
```

<sup>Created on 2021-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by FelicienLL** [comment]
Hello Kyle, 
This is the kind of issue I'm really interested in so I took the initiative to run something with NONMEM on my own. However everything goes as expected from my experience, and I don't see what is the problem exactly. Maybe I'm missing something... I don't wanna interfere in your business here, but just to let you know I'd be glad to help if I can.
Thanks

``` r
setwd("C:/Users/le_louedec/Documents/REPREX/005/")

library(tidyverse)
library(sofa2)
library(mrgsolve)
#> 
#> Attachement du package : 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter

data <- expand.ev(time = 1, cmt = 1, rate = -2, amt = 100)
data <- expand_observations(data, times = seq(0, 4, 0.1), unique = TRUE)
data1 <- mutate(data, D1I = ifelse(time >= 1, 1, 2))
data2 <- mutate(data, D1I = ifelse(time > 1, 1, 2), ID = 2)

bind_rows(data1, data2) %>% 
  mutate(DV = NA_real_, mdv = 1) %>% 
  write_csv("data808.csv", na = ".")

read_lines("run808a.mod") %>% cat(sep = "\n")
#> $PROBLEM EX808
#> $INPUT ID TIME AMT RATE CMT EVID D1I DV MDV
#> $DATA data808.csv IGNORE=@
#> $SUBROUTINES ADVAN13 TOL=8
#> $MODEL COMP=(DEPOT) COMP=(CENTRAL) 
#> $PK
#> KA = 0.001
#> CL = 1
#> V = 10
#> D1 = D1I
#> Z = ETA(1); dummy
#> $DES
#> DADT(1) = - KA * A(1)
#> DADT(2) = KA * A(1) - (CL/V) * A(2)
#> $ERROR
#> GUT = A(1)
#> CENT = A(2)
#> $SIGMA 0 FIXED ; dummy
#> $OMEGA 0 FIXED ; dummy
#> $SIMULATION (123) SUBPROBLEMS = 1 ONLYSIM
#> $TABLE ID TIME AMT RATE CMT EVID D1I DV MDV GUT CENT NOPRINT NOAPPEND ONEHEADER FORMAT=s1PE16.8E3 FILE=predtab808a
run_nonmem("run808a.mod", path = "C:/Users/le_louedec/Documents/REPREX/005/")
#> 
#> ------ END -----
read_table("predtab808a", skip = 1) %>% 
 # print(n = Inf) %>% 
  ggplot(aes(TIME, GUT, group = ID, col = as.factor(ID)))+
  geom_line()+
  labs(title = "ADV 13 TOL8")

```

![](https://i.imgur.com/4YmwvBd.png)

``` r
run_nonmem("run808b.mod", path = "C:/Users/le_louedec/Documents/REPREX/005/")
#> 
#> ------ END -----
read_table("predtab808b", skip = 1) %>% 
#  print(n = Inf) %>% 
  ggplot(aes(TIME, GUT, group = ID, col = as.factor(ID)))+
  geom_line()+
  labs(title = "ADV 2 TRANS 2")

```

![](https://i.imgur.com/hVm1rBY.png)

<sup>Created on 2021-03-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by kylebaron** [comment]
@FelicienLL Thanks for doing this and you are always welcome to comment! I ran into this discrepancy with a clinical data set simulated with mrgsolve and NONMEM and trying to figure out where that was coming from.  I need to study this a bit and will be in touch!

Best Regards,
Kyle

**Comment by thinguyen94** [comment]
Dear @kylebaron,

Thanks for opening this issue. Do you have any updates for this?

I am currently working on a project of informing antibiotics dose in neonates using your mrgsolve package. We have time-varying covariates on dose (i.e., age, weight on dosing) and on PK parameters (i.e., age on clearance). Thus, I would like to ask if you have observed any conflict between mrgsolve and nonmem output in similar cases?

Thanks and regard,
Thi

**Comment by kylebaron** [comment]
Hi @thinguyen94 - 

I haven't really followed up on this or looked deeper since posting. The example that @FelicienLL posted seemed to suggest that the tools were functioning similarly.  I came up with this report when running through a colleague's code on a pretty complicated model / data set so I could have been an erroneous observation. I think the observation in this issue is really focused on dosing items which are determined _in the model_ (like having the **modeled** infusion duration vary as a function of a time-varying covariate). I think time-varying covariates on CL are handled similarly. 

If you could share some code / data we could look to see if there is a possibility for differences. 

Thanks,
Kyle

**Comment by thinguyen94** [comment]
Hi @kylebaron,

I have a pretty complex simulated data set of increasing postnatal age, which leads to time-varying dose interval and increasing of clearance by age/time. Neonates often have a quite complex dose regimens (both dose and dose interval), 
 just one day can result in changes in dosing interval and clearance. So, your report concerned me greatly. For the model, I don't  think it is complex as you can see attached. 

To better demonstration, I am sharing with you the model code, the examples of dosing dataset and concentration output. Thanks for thinking this through with me.

Kindly regards,
Thi
[AmikacinModel.docx](https://github.com/metrumresearchgroup/mrgsolve/files/7219051/AmikacinModel.docx)
[test.dose.xlsx](https://github.com/metrumresearchgroup/mrgsolve/files/7219055/test.dose.xlsx)
[test.data.xlsx](https://github.com/metrumresearchgroup/mrgsolve/files/7219058/test.data.xlsx)

**Comment by kylebaron** [comment]
Thanks; I don't see any dosing elements modeled here (like F or infusion duration or infusion rate ... written into the model; these look to be fixed in the data set) so to the best we can test right now, the time-varying covariates are handled the same.

**Comment by thinguyen94** [comment]
Thanks Kyle. I have simulated all the dataset including dosing elements and then used mrgsim_d function. I feel more comfortable due to the absence of them in the model, but I don't quite understand why dosing elements in the model make the difference compared with in the data set. Could you please explain a bit more?

**Comment by kylebaron** [comment]
@thinguyen94 I can try to explain briefly: when you write the dose and infusion rate into the data set, that's sort of fixed into the data; mrgsolve or the model code doesn't / can't mess around with it. It's locked in. But when you model, say, the infusion duration ([like this](https://github.com/mrgsolve/gallery/blob/master/infusion/model_rate_duration.md)), now the characteristics of that dose depend on the model (through what you enter for `R1`) or mrgsolve (when you have time-varying covariates, when in the simulation sequence those covariates are updated, etc). There's just a lot of behind the scenes stuff that is happening in terms of **order** that might matter for dosing. The only order issue that matters for other time-varying covariates is that we proceed with "next observation carried backward" approach which matches what NONMEM is doing.

**Comment by thinguyen94** [comment]
Thanks Kyle for your explanation! Though I don't fully understand, I have a feel of what is going on. THANKS again for all.

**Comment by kylebaron** [comment]
Going to close this issue with the understanding that mrgsolve is doing what we want it to do. May open again if that perspective changes.
