### ISSUE TITLE
duplicate names with carry_out and capture

### ISSUE THREAD

**Issue by FelicienLL** [metrumresearchgroup/mrgsolve#827]
Hello @kylebaron ,

I noticed that when the same variable was both "captured" and "carried_out", a table with duplicate names was unexpectedly returned, which is not supported by tidyverse functions. 

It is probably not big deal, because "base" R accepts data.frames with duplicate names. And also because the problem is (maybe?) more with the user, who shouldn't use `$CAPTURE` to recover values defined in `$PARAM`, or shouldn't use both capture and carry_out for the same variable...

Anyway, do you think duplicate names could be checked when "carried out" values are copied to the simulation output, in order to avoid this behaviour?

Thank you in advance

Félicien

``` r
library(tidyverse)
library(mrgsolve)
#> 
#> Attachement du package : 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter
code0 <- "
$PARAM TVCL = 1, V = 10,  BW = 70
$CMT CENT
$MAIN
double CL = TVCL * (BW / 70) ;
$PKMODEL ncmt = 1
$CAPTURE CL BW TVCL
"
mod0 <- mcode("mod0", code0)
#> Building mod0 ...
#> done.
sim <- mod0 %>%
  idata_set(expand.idata(BW = 80)) %>%
  mrgsim_df(carry_out = "BW")
head(sim)
#>   ID time BW CENT       CL BW TVCL
#> 1  1    0 80    0 1.142857 80    1
#> 2  1    1 80    0 1.142857 80    1
#> 3  1    2 80    0 1.142857 80    1
#> 4  1    3 80    0 1.142857 80    1
#> 5  1    4 80    0 1.142857 80    1
#> 6  1    5 80    0 1.142857 80    1
sim %>%
  mutate(FOO = 1)
#> Error: Can't transform a data frame with duplicate names.
```

<sup>Created on 2021-05-06 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by kylebaron** [comment]
Thanks; yeah it should be one or the other.

**Comment by kylebaron** [comment]
@timwaterhouse any preference on what the right thing to do here?  I'd like to either warn or error rather than try to fix the names.

**Comment by timwaterhouse** [comment]
When you say you'd prefer not to fix the names, do you mean rename one of the duplicates? How about dropping the one of the duplicate columns?  I guess I don't have a strong preference, but it would be more convenient to just drop the duplicates. If fixing names isn't an option, I think a warning would suffice. Could it be a bit more descriptive? Like ```column xyz is duplicated in output: did you $CAPTURE and carry_out the same variable?```

**Comment by kylebaron** [comment]
@timwaterhouse yes, we could drop.  Do you have an idea for re-naming?  Keep in mind that by the time we figure this out, it's hard to say for sure where the duplicates came from (there is just a lot of flexibility there, ability to re-name stuff etc).  Maybe we could add a suffix to the duplicates?  

I will list off the duplicates in the warning.   Hoping that makes the warning burden big enough to make people fix thing to make the warnings go away.

**Comment by timwaterhouse** [comment]
No ideas for renaming. Would that be of any help vs dropping since presumably the columns contain the same data? I guess they would have to contain the same data in the `capture`/`carry_out` duplicates, but maybe that's not always true? Probably just warning with a list of duplicates is the best option.

**Comment by kylebaron** [comment]
Yeah; that makes it sort of hard ... that the columns won't necessarily have the same data. This is starting to feel more like an error; but maybe we can list and warn / notify now; then eventually turn into an error.

**Comment by kylebaron** [comment]
There are so many reasonable things we could try to fix it for the user, but could easily do the wrong thing and I think we want to throw this back at the user and ask them to rename or don't ask for duplicates in the first place; maybe a little less convenient but would provide a real solution to the problem and no question about what was done.

**Comment by FelicienLL** [comment]
At first, I was suggesting to drop the duplicate column, but indeed this option may not be acceptable if data in both columns are not the same (for instance, if the user change the value of BW in the $MAIN, to keep our example). So renaming (with a warning) sounds good to me. No preference for how to rename, but maybe a suffix with the number of the column would offer the advantage to be neutral (wherever the duplication comes from) and consistent with how tidyverse function deal with duplicate name (see https://vctrs.r-lib.org/reference/vec_as_names.html)

Thus column names would be something like: 
`
#>   ID time BW...3 CENT CL BW...6 TVCL
`

**Comment by kylebaron** [comment]
@FelicienLL sounds reasonable.  I think we'll stick with the base version to generate the unique names (unless there is some tv functionality available in current dependency  ... eg. rlang or dplyr).

**Comment by kylebaron** [comment]
``` r
library(microbenchmark)
library(tidyverse)
#> Warning: package 'tidyverse' was built under R version 4.0.5
library(reprex)
library(tidyverse)
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter

code0 <- "
$PARAM TVCL = 1, V = 10,  BW = 70
$CMT CENT
$MAIN
double CL = TVCL * (BW / 70) ;
$PKMODEL ncmt = 1
$CAPTURE CL BW TVCL
"
mod0 <- mcode("mod0", code0)
#> Building mod0 ...
#> done.

sim <- mod0 %>%
  idata_set(expand.idata(BW = 80, CL = 1.2)) %>%
  mrgsim_df(carry_out = "BW,CL")
#> Warning: renaming duplicate output column: `CL`
#> Warning: renaming duplicate output column: `BW`
head(sim)
#>   ID time BW  CL CENT     CL.1 BW.1 TVCL
#> 1  1    0 80 1.2    0 1.142857   80    1
#> 2  1    1 80 1.2    0 1.142857   80    1
#> 3  1    2 80 1.2    0 1.142857   80    1
#> 4  1    3 80 1.2    0 1.142857   80    1
#> 5  1    4 80 1.2    0 1.142857   80    1
#> 6  1    5 80 1.2    0 1.142857   80    1
```

<sup>Created on 2021-05-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by kylebaron** [comment]
Closing for #828
