### ISSUE TITLE
pk2iv model

### ISSUE THREAD

**Issue by FelicienLL** [metrumresearchgroup/mrgsolve#831]
Hi Kyle, 

https://github.com/metrumresearchgroup/mrgsolve/blob/8e53a2fd6ad0d19e0c20f0440407d02548dd7f9b/inst/models/pk2iv.cpp#L12

shouldn't this be `CENT / V1` ?

Thanks in advance

Félicien

**Comment by kylebaron** [comment]
Thanks; that's right.  Closing this for #832 and #833.
