### ISSUE TITLE
Documentation suggestion:  Likely typo with as_cmat doc

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#856]
In the user guide for $OMEGA (https://mrgsolve.github.io/user_guide/model-specification.html#block-omega), it indicates "The matrix will be stored and used with these covariances, not the correlation."  (Thanks for documenting that as my initial question was going to be if it was stored as covariance or correlation with a flag.)

In my model building for the current model I'm working with, I have a correlation that I want to add to my existing model rather than at the time of model specification.  I found the documentation to as_cmat says "as_cmat to create a block matrix where diagonal elements are understood to be correlations rather than covariances".  I'm pretty sure that it should say "off-diagonal" rather than diagonal.

**Comment by billdenney** [comment]
Here is where it is in the code: https://github.com/metrumresearchgroup/mrgsolve/blob/37c581518eb591282c19314a9030df44fb908a04/R/matrix.R#L194-L196

**Comment by kylebaron** [comment]
Thanks for the report, @billdenney ; fixed now.
