### ISSUE TITLE
Issue with putting the location of Rtools "make utilities" on the PATH

### ISSUE THREAD

**Issue by stzhang77** [metrumresearchgroup/mrgsolve#884]
After installation Rtools40 in C: and wrote the following codes:

setwd("C:\\rtools40")
write('PATH="${RTOOLS40_HOME}\\usr\\bin;${PATH}"', file = "~/.Renviron", append = TRUE)

Received the following error message:
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'C:/.Renviron': Permission denied

Found that "make" in bin under user. After changing code "usr" to "user", the same error message was received.

**Comment by kylebaron** [comment]
It looks like the write command is attempting to send this to `C:/` but you don't have permission to write there. Is this 
 
```sh
cannot open file 'C:/.Renviron': Permission denied
```

What do you get from running this?

```
path.expand("~/.Renviron")
```

**Comment by stzhang77** [comment]
> path.expand("~/.Renviron")
[1] "C:/.Renviron"

**Comment by kylebaron** [comment]
Ok; then it is taking `C:/` as your `HOME` directory which is unusual given you don't have permission to write there. If that's really the case and you want to keep going with it, then you'd need to get access to `C:/`. But maybe some wire got crossed there and it should be something under `C:/Documents/...` or something like that. The important part is that this gets written to your `HOME` directory so the environment variable gets set properly when you start / restart R.
