### ISSUE TITLE
Change block structure (& feature request ?)

### ISSUE THREAD

**Issue by FelicienLL** [metrumresearchgroup/mrgsolve#894]
Hello, 
For a specific project, I would like to update $OMEGA with a full matrix, whatever the initial block structure.

``` r
library(mrgsolve)
#> 
#> Attachement du package : 'mrgsolve'
#> L'objet suivant est masqué depuis 'package:stats':
#> 
#>     filter
code0 <- "$OMEGA @annotated
ET1 : 1 : CL
$OMEGA 2
$CAPTURE ET1 ETA(2)"

mod0 <- mcode("mod0", code0)
#> Building mod0 ...
#> done.
str(mod0@omega)
#> Formal class 'omegalist' [package "mrgsolve"] with 3 slots
#>   ..@ data  :List of 2
#>   .. ..$ ...: num [1, 1] 1
#>   .. .. ..- attr(*, "dimnames")=List of 2
#>   .. .. .. ..$ : chr "1: "
#>   .. .. .. ..$ : NULL
#>   .. ..$ ...: num [1, 1] 2
#>   .. .. ..- attr(*, "dimnames")=List of 2
#>   .. .. .. ..$ : chr "1: "
#>   .. .. .. ..$ : NULL
#>   ..@ n     : int [1:2] 1 1
#>   ..@ labels:List of 2
#>   .. ..$ : chr "ET1"
#>   .. ..$ : chr "."
newmat <- matrix(c(0.1, 0.12, 0.12, 0.2), nrow = 2)
mod0 %>% omat(newmat)
#> Error: improper signature: omat
```

It fails because the block structure wouldn’t be the same anymore. So here is what I attempted below. 
``` r
stopifnot(sum(omat(mod0)@n) == dim(newmat)[1])
newmatlist <- omat(newmat)
newmatlist@labels <- list(`...` = unname(unlist(omat(mod0)@labels)))
mod0@omega <- newmatlist

# What does it say?

str(omat(mod0))
#> Formal class 'omegalist' [package "mrgsolve"] with 3 slots
#>   ..@ data  :List of 1
#>   .. ..$ ...: num [1:2, 1:2] 0.1 0.12 0.12 0.2
#>   ..@ n     : int 2
#>   ..@ labels:List of 1
#>   .. ..$ ...: chr [1:2] "ET1" "."
set.seed(12345)
sim0 <- mrgsim(mod0, end = 0, nid = 1000)
var(sim0$ET1)
#> [1] 0.0997181
var(sim0$ETA_2)
#> [1] 0.2002408
cov(sim0$ET1, sim0$ETA_2)
#> [1] 0.1190969
```
Probably not perfect but seems to do the job. Not sure if it is safe enough though: should I change something else than the `@omega` slot internally?

In the future, would it be possible to allow a less strict evaluation of block structure internally (in `update_matlist()`), so that we can do this update via `omat()` too? As long as the total number of eta is the same for instance?
Many thanks in advance
Felicien

<sup>Created on 2021-12-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kylebaron** [comment]
Hi @FelicienLL  - 

Yeah I could look at making that more flexible ... taking a single matrix and trying to reconcile how all that fits in with the existing block structure. 

For now, you can "collapse" the omega matrices into a single omega matrix so you can update it with a single matrix. This is irreversible and doesn't change any of the functionality, but you are committed to updating the whole omega matrix every time. 

``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter
code <- '
$SET collapse_omega = TRUE

$OMEGA
1

$OMEGA
2

'
mod <- mcode("collapse", code)
#> Building collapse ...
#> done.
omat(mod)
#> $...
#>     [,1] [,2]
#> 1:     1    0
#> 2:     0    2
mod <- omat(mod, bmat(0.1, 0.12, 0.2))
revar(mod)
#> $omega
#> $...
#>     [,1] [,2]
#> 1:  0.10 0.12
#> 2:  0.12 0.20
#> 
#> 
#> $sigma
#> No matrices found
```

<sup>Created on 2021-12-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by FelicienLL** [comment]
Thanks for your answer Kyle, 
Unfortunately, I was looking for something that would work without particular specifications in model code, and that does not need to re-compile the model.
I was not aware of this `collapse_omega` command... Maybe, could we simply have the possibility to call `collapse_omega` as an argument of `update` or `omat`? That would have two benefits:
- to be consistent with `delta`, `end` etc... that can be passed to both `$SET` or `update()`.
- to ignore my initial "request" (i.e. let `omat` being permissive about block structure) and keep the already existing strict evaluation of block structure, since a full matrix would be expected...

Just a few thoughts...
Thanks again !
Félicien

**Comment by kylebaron** [comment]
Hi @FelicienLL - 

Yeah; I think it would be great to handle this in a more-sophisticated way (e.g. update or omat). I think we can definitely head for that with some thought. 

For now, you can tap the un-exported function to do that

``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter

code0 <- "$OMEGA @annotated
ET1 : 1 : CL
$OMEGA 2
$CAPTURE ET1 ETA(2)
"


mod <- mcode("collapse", code0)
#> Building collapse ...
#> done.
omat(mod)
#> $...
#>       [,1]
#> ET1:     1
#> 
#> $...
#>     [,1]
#> 2:     2
try(mod <- omat(mod, bmat(0.1, 0.12, 0.2)))
#> Error : improper signature: omat
mod <- mrgsolve:::collapse_omega(mod)
mod <- omat(mod, bmat(0.1, 0.12, 0.2))
revar(mod)
#> $omega
#> $...
#>       [,1] [,2]
#> ET1:  0.10 0.12
#> .:    0.12 0.20
#> 
#> 
#> $sigma
#> No matrices found
```

<sup>Created on 2021-12-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I will document and export this function regardless of what direction we go with it. If you need to use this in you package, please go ahead and pull [the code](https://github.com/metrumresearchgroup/mrgsolve/blob/4c72461c65eeb315509d52c2734d5ecb0d6d66b3/R/matlist.R#L349-L362) or adapt according to your needs.

**Comment by FelicienLL** [comment]
Hi, 
This is exactly what I needed for now. Awesome.
Thank you very much
Félicien
