### ISSUE TITLE
Trouble installing on windows 

### ISSUE THREAD

**Issue by varungoelPMX** [metrumresearchgroup/mrgsolve#90]
I get this message working on corporate laptop. I have rtools 3.3 installed with the correct path and the required packages installed as per the instructions.
```
> install.packages("C:/Users/vgoel/Downloads/mrgsolve-0.7.1.tar.gz", repos = NULL, type = "source", lib="C:/Program Files/R/R-3.3.0/library")
'\\domain.internal\dfs\home\vgoel\My Documents'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
ERROR: cannot extract package from 'C:/Users/vgoel/Downloads/mrgsolve-0.7.1.tar.gz'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.0/bin/x64/R" CMD INSTALL -l "C:\Program Files\R\R-3.3.0\library" "C:/Users/vgoel/Downloads/mrgsolve-0.7.1.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/vgoel/Downloads/mrgsolve-0.7.1.tar.gz’ had non-zero exit status
```

**Comment by kylebmetrum** [comment]
@varungoelPMX @vjd

The `install.packages` call looks fine to me.  
```r
'\\domain.internal\dfs\home\vgoel\My Documents'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
```

I'm not totally sure what `mrgsolve` will do with a UNC path, but this error is getting issued by someone else.  R? Rstudio?  I'm not sure.

Seems like this is related to:
https://support.rstudio.com/hc/en-us/community/posts/202828346-Path-errors-on-start-up-in-Windows-7

**Comment by kylebmetrum** [comment]
Also, running anything `mrgsolve` related with UNC path or in any dropbox directory or anything other than a regular local directory isn't supported.  Just run it locally on your computer.  __Anything else__ is up to you to figure out.

**Comment by kylebmetrum** [comment]
http://stackoverflow.com/questions/5949775/windows-bat-file-error

**Comment by kylebmetrum** [comment]
Ah .... this isn't right.  Try installing the built package.

[mrgsolve_0.7.1.tar.gz](https://github.com/metrumresearchgroup/mrgsolve/files/382311/mrgsolve_0.7.1.tar.gz)

**Comment by varungoelPMX** [comment]
It worked with the built package

**Comment by kylebmetrum** [comment]
I should probably clarify this somehow on the release page.  The names `mrgsolve-0.7.1.tar.gz` and `mrgsolve_0.7.1.tar.gz` are too close.
