### ISSUE TITLE
[F] Add methods for interaction with data.table

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#94]
`data.table` is the only way to go for stuff like vpc.

**Comment by dpastoor** [comment]
Why do you say data.table is the only way to go? For performance reasons?

**Comment by kylebmetrum** [comment]
Yes; performance; I was surprised at the difference.  

I ended up using `data.table` for that first big data summary (by time,replicate, and 3 or 4 covariates for vpc) and then getting right back into `dplyr` stuff for the syntax.  

But after mulling this, I think all we could do is provide an `as.data.table` method for `mrgsims` objects.
