### ISSUE TITLE
Compiler issue

### ISSUE THREAD

**Issue by leehweeling** [metrumresearchgroup/mrgsolve#941]
Hi,

I'm new to mrgsolve. I was trying to follow the workshop online with this code:
library(tidyverse)
library(mrgsolve)

mod <- modlib("pk1")

I get an error message: 
Building pk1 ... error.

---:: stderr ::---------------------------------------------
Warning message:
In system(cmd) : 'make' not found
------------------------------------------------------------
Error: the model build step failed.

So then I followed the instructions to set the PATH environments using this code:
Sys.setenv(PATH=paste("C:\\R\\rtools40\\mingw64\\bin", Sys.getenv("PATH"), sep=";"))
Sys.setenv(BINPREF= "C:\\R\\rtools40\\mingw64\\bin")

I've also proceeded with testing the compiler using this code:
ccode <- 'extern "C" {void test() {double x=2.1; x = x+1;}}\n'
cat(file="R_Cpp_Test.cpp", ccode)
system("R CMD SHLIB R_Cpp_Test.cpp")

I get an error message:
Warning message:
In system(cmd) : 'make' not found
[1] 1

I've followed the instructions online as closely as possible, but I keep getting error message. Could someone please help?

Thanks.

Best regards,
Hweeling

**Comment by twa1970** [comment]
Hi @leehweeling 

I had similar issue - see discussion #888. 
Solution: Set Forced randomization for images (Mandatory ASLR) in Windows Security to "On by default" 

@twa1970

**Comment by leehweeling** [comment]
Hi @twa1970 ,

Thanks for your reply. What do you mean by this? Where can I find the windows security to set this? I was not able to find it in my settings.

Cheers,
Hweeling
