### ISSUE TITLE
make 1810 dofork: child -1 - forked process 1568 died unexpectedly

### ISSUE THREAD

**Issue by leehweeling** [metrumresearchgroup/mrgsolve#951]
Hi,

I've reinstalled rtools folder directly on C:\ and now it seems to work with the example.

However, when I tried to run 'mod <- modlib("pk1"), I get a different error message.

Building pk1 ... error.

---:: stderr ::---------------------------------------------
stderr could not be recovered after system4 call
------------------------------------------------------------
Error: the model build step failed.

Anyone experienced this and know how to solve this issue?

Cheers,
Hweeling

**Comment by kylebaron** [comment]
I forgot to write ... not being able to recover `stderr` indicates there was a problem compiling the model or finding the build toolchain; it is a symptom, not the problem we are trying to resolve. 

One more command I'd like you to run and post the result; you won't see the same details, but you should see some messages coming back. 

``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter

mod <- modlib("pk1", ignore.stdout = FALSE, preclean = TRUE)
#> ccache /usr/bin/clang++ -Wsign-compare -Wpedantic -Wall
#> -I"/Library/Frameworks/R.framework/Resources/include"
#> -DNDEBUG -I"/Users/kyleb/Rlibs-MPN/mrgsolve/base"
#> -I"/Users/kyleb/Rlibs-MPN/mrgsolve/models"
#> -I/usr/local/include -fPIC -Wall -g -O2 -c
#> pk1-mread-source.cpp -o pk1-mread-source.o
#> ccache /usr/bin/clang++ -dynamiclib
#> -Wl,-headerpad_max_install_names -undefined dynamic_lookup
#> -single_module -multiply_defined suppress
#> -L/Library/Frameworks/R.framework/Resources/lib
#> -L/usr/local/lib -o pk1-mread-source.so pk1-mread-source.o
#> -F/Library/Frameworks/R.framework/.. -framework R
#> -Wl,-framework -Wl,CoreFoundation
```

<sup>Created on 2022-03-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by leehweeling** [comment]
Dear Kyle,

Thank you for the prompt reply!

Here's what happened when I ran the commands:

>library(mrgsolve)

Attaching package: ‘mrgsolve’

The following object is masked from ‘package:stats’:

    filter

> sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mrgsolve_1.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8       fansi_1.0.2      assertthat_0.2.1 utf8_1.2.2       crayon_1.5.0     dplyr_1.0.8      R6_2.5.1         DBI_1.1.2        lifecycle_1.0.1 
[10] magrittr_2.0.2   pillar_1.7.0     rlang_1.0.2      cli_3.2.0        vctrs_0.3.8      generics_0.1.2   ellipsis_0.3.2   tools_4.1.3      glue_1.6.2      
[19] purrr_0.3.4      compiler_4.1.3   pkgconfig_2.0.3  tidyselect_1.1.2 tibble_3.1.6    
> Sys.getenv("PATH")
[1] "C:\\R\\R-4.1.3\\bin\\x64;C:\\Program Files (x86)\\Certara\\Phoenix\\application\\lib\\NLME\\Executables\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\rtools40\\usr\\bin\\;C:\\Users\\Hlee\\AppData\\Local\\Microsoft\\WindowsApps;"
> Sys.which("make")
                              make 
"C:\\rtools40\\usr\\bin\\make.exe" 
> pkgbuild::check_build_tools()
Your system is ready to build packages!
> mod <- modlib("pk1", ignore.stdout = FALSE, preclean = TRUE)

---:: stdout ::---------------------------------------------
"C:/rtools40/mingw64/bin/"g++ -std=gnu++11
-I"C:/R/R-41~1.3/include" -DNDEBUG
-I"C:/R/R-4.1.3/library/mrgsolve/base"
-I"C:/R/R-4.1.3/library/mrgsolve/models" -O2 -Wall
-mfpmath=sse -msse2 -mstackrealign -c pk1-mread-source.cpp
-o pk1-mread-source.o

---:: stderr ::---------------------------------------------
      0 [main] make 1810 dofork: child -1 - forked process 1568 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
make: *** [C:/R/R-41~1.3/etc/x64/Makeconf:245: pk1-mread-source.o] Error 127
------------------------------------------------------------
NOTE: 'Error 127' was detected in the above message.
 This possibly indicates that the build toolchain
 could not be found. Please check for proper compiler 
 installation ('Rtools.exe' on Windows).  Also consider
 trying 'pkgbuild::check_build_tools(debug=TRUE)' to
 assist in diagnosing this issue.
------------------------------------------------------------ 
Error: the model build step failed.

Cheers,
Hweeling

**Comment by leehweeling** [comment]
Hi @kylebaron @twa1970,

Thanks for your help. It finally solved the problem. @twa1970 your last message to me was to set "Force randomization for images (Mandatory ASLR) to "On by default", which did not work. Now, setting it to "Off by default" works perfectly.

Thanks again!

Cheers,
Hweeling

**Comment by kylebaron** [comment]
Thanks so much for your help, @twa1970.
