### ISSUE TITLE
Infusion should apply bio-availability after calculating infusion duration

### ISSUE THREAD

**Issue by rfaelens** [metrumresearchgroup/mrgsolve#954]
When calculating infusion duration based on `rate`, the bio-availability parameter is taken into account *before* calculating the infusion duration.

What I did:
```r
data <- expand.ev(ID=1:2,amt=100,rate=10,F1=c(1,0.1))
```

What I expected: Both ID's have an infusion of duration 10h, but ID 2 will receive only 10% of the amount.

What happened: Both ID's receive the same rate of infusion, but ID 2 stops infusing earlier.

``` r
library(tidyverse)
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter
code <- '
$PARAM CL=1, FORM=1,F1 = 0.1
$MAIN
F_CENT = 1;
if(FORM==2) F_CENT = F1;
$CMT CENT
$ODE dxdt_CENT = -(CL/10)*CENT;
$CAPTURE CL FORM  F1
'

mod <- mcode("bioav1",code) %>% carry_out(evid)
#> Building bioav1 ...
#> done.
data <- expand.ev(ID=1:2,amt=100,rate=10,FORM=c(1,2))
mod %>% data_set(data) %>%
  mrgsim() %>% plot()
```

![](https://i.imgur.com/zmmS6B6.png)

<sup>Created on 2022-03-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Reprex based on https://github.com/metrumresearchgroup/mrgsolve/blob/37c581518eb591282c19314a9030df44fb908a04/inst/maintenance/unit/test-bioav.R

**Comment by kylebaron** [comment]
Hi @rfaelens  - 

That's the expected behavior - changing bioavailability changes infusion _duration_.  

Kyle

**Comment by rfaelens** [comment]
OK, then I will need to double-check my validation step.
Thanks!

**Comment by smouksassi** [comment]
some history is here https://www.cognigen.com/nonmem/nm/98nov012001.html (see Stuart Beal comment).
Also you can look at NONMEM PREDPP guide and I think mrgsolve try to be consistent with the NONMEM zoo :).

**Comment by kylebaron** [comment]
Thanks for the reference, @smouksassi ; you indeed are a wise elephant.

**Comment by mattfidler** [comment]
@kylebaron do you have a fixed duration data item.  In `nlmixr`/`rxode` we have `dur`.  They have one in monolix as well (though I cannot remember what it is, but it wasn't `dur`).  If you don't it should not be too hard to add (and would make translation from `nlmixr` to `mrgsolve` a bit easier).

**Comment by kylebaron** [comment]
Thanks, @mattfidler ... I'll look into it.
