### ISSUE TITLE
Time-varying dose responses differ between  ODE and Analytical form

### ISSUE THREAD

**Issue by Maia-Iulia** [metrumresearchgroup/mrgsolve#982]
Dear Kyle,

I am using the mrgsolve package to simulate tumor size data from an ODE model. The model I use is the so-called Claret-Bruno model, published in the 2013 paper in JCO [Claret](https://ascopubs.org/doi/pdf/10.1200/JCO.2012.45.0973) .
The paper gives the ODE and the corresponding analytical formula. Unfortunately, the response (RESP) values from the simulation using an ODE do not match those of the analytical solution when I use a time-varying DOSE as a covariate (see code below).

I use DOSE as a time-varying covariate within subject (no event with amt for the dose).  

The simulations are the same when I use a fixed/flat DOSE for all subject observations ID=1:5 (i.e. DOSE=10 for all time points time=seq(0,1,0.1)) - see Design matrix in Section I.1 below. 

When I change the DOSE value at time t=0.4, the results no longer match - see Design matrix in Section I.2 below.

I have already examined the issues below, but I could not find a solution to my problem.
#741 
#754 
#382 
#49 
[MrgsolveGuide](https://mrgsolve.org/user_guide/topics.html#topics-time-varying
)
[Gallery](https://github.com/mrgsolve/gallery/blob/master/adaptive/adaptive_simple.md
)

Could you advise on the best way to introduce a time-varying dose as a covariate for the given models in ODE and Analytical form?

Here is my current implementation of the design matrix and model building:

pred<- '
$PARAM    TVKG =0.6, TVKS0=0.4, TVGAMMA=0.8, TVBASE =70 ,DOSE=10
$OMEGA  0.005 0.03 0.003 0.01
$PRED
double KG = TVKG * exp(ETA(1));
double KS0 = TVKS0 * exp(ETA(2));
double GAMMA = TVGAMMA * exp(ETA(3));
double BASE=TVBASE * exp(ETA(4));
double RESP_0=BASE;

double KS =  KS0*exp(-GAMMA * TIME);

double RESP = RESP_0*exp((KG*TIME)-(KS0*log(DOSE)/GAMMA)*(1-exp(-GAMMA*TIME)));

$CAPTURE    RESP RESP_0 BASE KS KS0 KG GAMMA 
'
`set.seed(123)`
`model_pred<-mcode("PRED",pred)
`

ode<-'
$PARAM  TVKG =0.6, TVKS0=0.4, TVGAMMA=0.8, TVBASE =70, DOSE=10

$OMEGA  0.005 0.03 0.003 0.01

$CMT RESP

$MAIN
double KG = TVKG * exp(ETA(1));
double KS0 = TVKS0 * exp(ETA(2));
double GAMMA = TVGAMMA * exp(ETA(3));
double BASE = TVBASE*exp(ETA(4));
RESP_0 = BASE;

$ODE
double KS=KS0 *exp( -GAMMA * SOLVERTIME);
dxdt_RESP = KG *RESP -   KS*log(DOSE)*RESP;
$CAPTURE 
 RESP_0 BASE KS KS0 KG GAMMA ETA(4)
'

`set.seed(123)
`
`model_ode<-mcode("ODE",ode)`

 **I. Construct the Design matrices**

   **1. Flat DOSE :**
flt<-
   ID tnum time DOSE
   1    0  0.0   10
    1    1  0.1   10
    1    2  0.2   10
   1    3  0.3   10
   1    4  0.4   10
    1    5  0.5   10
    1    6  0.6   10
    1    7  0.7   10
    1    8  0.8   10
    1    9  0.9   10
    1   10  1.0   10
    2    0  0.0   10
    2    1  0.1    10

 **2. Time-varying DOSE:**  for example I want to  change the DOSE amount at each time point  TIME==0.4 for all the subjects ( 5 patients). I tried different design matrices that correspond to this one as for example: adding columns in the dataset for  cmt= 1 and evid =0 or 1 or 2 for ODE and the same for analytical form  except that cmt=0 , but there  I  still have  differences in the response values . I also tried nocb=T and nocb=F in mrgsim(), but was not succeful.

tv<-
 ID tnum time DOSE
    1    0  0.0   10
    1    1  0.1   10
    1    2  0.2   10
    1    3  0.3   10
    1    4  0.4    5
    1    5  0.5   10
    1    6  0.6   10
    1    7  0.7   10
    1    8  0.8   10
    1    9  0.9   10
    1   10  1.0   10
    2    0  0.0   10
    2    1  0.1   10
    2    2  0.2   10
    2    3  0.3   10
    2    4  0.4    5
    2    5  0.5   10
    2    6  0.6   10

**II. Simulations:**
   **1.Flat DOSE**

`set.seed(123)`
```
snd.flt<-mrgsim_d(model_pred, as.data.frame(flt), carry.out="DOSE") %>% 
  as.data.frame()
```
`set.seed(123)`
```
ode.flt<-mrgsim_d(model_ode, as.data.frame(flt), carry.out="DOSE") %>% 
  as.data.frame()

```
As results I get:

 ID time DOSE RESP_PRED_flt RESP_ODE_flt
    1  0.0   10      83.90358     83.90358
    1  0.1   10      81.45628     81.45628
    1  0.2   10      79.63292     79.63292
    1  0.3   10      78.35387     78.35387
    1  0.4   10      77.55687     77.55687
    1  0.5   10      77.19337     77.19337
    1  0.6   10      77.22565     77.22565
    1  0.7   10      77.62476     77.62477
    1  0.8   10      78.36887     78.36887
    1  0.9   10      79.44200     79.44200
    1  1.0   10      80.83311     80.83311

 **2. Time varying DOSE**
`set.seed(123)`
```
snd.tv<-mrgsim_d(model_pred, as.data.frame(tv), carry.out="DOSE") %>% 
  as.data.frame()
```
`head(snd.tv,n=20)`

`set.seed(123)`
```
ode.tv<-mrgsim_d(model_ode, as.data.frame(tv), carry.out="DOSE") %>% 
  as.data.frame()
```
`head(ode.tv,n=20)`

   ID ,time, DOSE, RESP_PRED_tv ,   RESP_ODE_tv
      1 , 0.0 ,  10  ,   83.90358       ,            83.90358
     1 , 0.1 ,  10  ,   81.45628  ,                  81.45628
     1 , 0.2,   10    , 79.63292 ,                   79.63292
    1 , 0.3,   10,     78.35387,                   78.35387
    1 , 0.4 ,   5 ,          85.80719 ,                   79.31621
    1  ,0.5  , 10  ,   77.19337,                   78.94446
    1 , 0.6   ,10   ,  77.22565  ,                 78.97748
    1  ,0.7  , 10  ,   77.62476  ,                 79.38564
    1,  0.8,   10,     78.36887 ,                  80.14663
    1,  0.9,   10 ,    79.44200  ,                 81.24410
    1 , 1.0,   10  ,   80.83311   ,                82.66677

Thank you in advance.

**Comment by FelicienLL** [comment]
Hi @Maia-Iulia, 
> As we are not interested in exposure inferences, the TGI model can be simplified by assuming constant exposure over time. The differential equation can be solved as follows

Apparently the authors specified that the analytical form is valid for constant exposure over time only. That's probably why they wrote it _E0,i_ in the equation.

So if you want to test the influence of time-varying variables, I'd suggest to keep on with ODE model instead of analytical form. I hope I'm not mistaking, but $PRED only compute RESP at the "TIME" points you set in the data, independently of each other in some way... While ODE treat the variables continuously, thus enabling to study the influence of time-varying parameters like exposure (and this is why the nocb/locf settings matter here) 

Félicien

**Comment by kylebaron** [comment]
I think that's right; `$PRED` is just a vector calculation ... where the result is only a function of the data at that particular time.  If I'm understanding this correctly, I think you _could_ do this recursively ... advancing `RESP` in time and continually updating what `RESP_0` is; this is how the analytical solutions in `$PKMODEL` (1 and 2 compartment models) function. Not sure it's worth all that work if it is possible. 

Looking at the equations in the supplement, Exposure loses time dependence and I'm sure the solution would be different if that was retained.

**Comment by kylebaron** [comment]
Here's a nonmem test: https://github.com/mrgsolve/nmtests/blob/claret/claret/claret.md

I did this quick ... but confirmed that, when dose is constant, you get the same answer with ODE and PRED.

**Comment by Maia-Iulia** [comment]
Hi @FelicienLL ,Hi @kylebaron ,

Thank you for your quick replies. Your responses were very helpful . 
@kylebaron , thanks for sharing the code and results so quickly. 

Thus, when the dose is constant, both models do the same thing, but when the dose changes over time, ODE is able to see the influence of time on the dose, whereas PRED is not. PRED just calculates the result based on the data that corresponds to that particular time.

So in this case ,Is it the same if I use $TABLE instead of $PRED ?

Thank you in advance.

**Comment by Maia-Iulia** [comment]
Hi Kyle,

Thank you very much. It is very clear and helpful.

**Comment by kylebaron** [comment]
Thanks, @Maia-Iulia; let us know if we can help with anything else.
